### ISSUE TITLE
Support for BTC/EUR

### ISSUE THREAD

**Issue by MaxXor** [DeviaVir/zenbot#1]
First I want to say: Good work! :+1: I tested it and it's working pretty good so far.
I first backfilled the last 90 days, then started the recorder and then the learner. Is this the correct order?
But I can not trade for BTC/USD on Coinbase, could you please add support for BTC/EUR?

**Comment by hosiawak** [comment]
How did you backfill the last 90 days ? I couldn't figure out what to put after "--after" 

I was also looking at BTC-EUR, it's defined in `conf/constants.json` but I'm not sure if it's a good idea because BTC-EUR on GDAX is a much lower volume than BTC-USD. For EUR trading it would be a much better idea to use an exchange that trades mostly in EUR.

**Comment by MaxXor** [comment]
Just run `zenbot backfill` to fill the database with the latest trades. It will start at the current date and then goes back the trade history. You can stop after 90 days.

Hm, I'm not an US citizen and they require a lot of verification for BTC/USD trading...

**Comment by carlos8f** [comment]
> I first backfilled the last 90 days, then started the recorder and then the learner. Is this the correct order?

this is correct, the learner will use the backfilled trades and `zenbot run` will use the recorded trades.

> I couldn't figure out what to put after "--after"

If you start backfilling it will show the oldest sequence ID processed, i.e.

```
7/10/2016, 12:46:31 PM PDT backfilled "2016-07-10T18:29:10.000Z"  trades: SELL $649.09/3.000
7/10/2016, 12:46:31 PM PDT backfilled "2016-07-10T18:32:20.000Z"  trades:  BUY $649.24/12.969
7/10/2016, 12:46:31 PM PDT backfilled "2016-07-10T18:35:30.000Z"  trades: SELL $649.03/0.076
7/10/2016, 12:46:31 PM PDT backfilled "2016-07-10T18:36:20.000Z"  trades:  BUY $649.10/2.309
7/10/2016, 12:46:31 PM PDT backfilled "2016-07-10T18:44:50.000Z"  trades: SELL $649.28/0.154
7/10/2016, 12:46:31 PM PDT processed 400 trades. after = 10072557
```

Then use `zenbot backfill --after 10072557` to resume backfilling from there.

> For EUR trading it would be a much better idea to use an exchange that trades mostly in EUR.

Yes, GDAX is mostly for USD and I may add support for other exchanges if the demand is there. The catch is that each exchange needs to be machine-learned separately as they have different volume levels.

**Comment by carlos8f** [comment]
Zenbot 4 is out, so I'm cleaning up 3.x issues. Please use and test 4, thanks!
