### ISSUE TITLE
Spawning child processes in learner.js on Windows

### ISSUE THREAD

**Issue by xangma** [DeviaVir/zenbot#10]
Hi,

Great program, really enjoying using and learning about it. I found when using it on Windows, that it has trouble using the spawn command due to a well known bug (discussed [here](http://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js)). I had to install another node module 'node-cross-spawn'.

To get past this I had to add this line of code to learner.js:
`spawn = require('cross-spawn')`
I put it after line 10 and it worked. I have not tested this on any other OS though ...

**Comment by carlos8f** [comment]
Zenbot 4 is out, so I'm cleaning up 3.x issues. Please use and test 4, thanks!
