### ISSUE TITLE
Error when attempting to backfill

### ISSUE THREAD

**Issue by alternativesurfer** [DeviaVir/zenbot#100]
Hi!

I keep receiving this error when attempting to run a backfill....

I attempt to run a command like: ./zenbot launch map --backfill
and receive: TypeError: Cannot read property 'indexOf' of undefined

Paste of full log attached:
http://pastebin.com/LjMFKaw0

**Comment by alternativesurfer** [comment]
Anyone?

**Comment by robsteady** [comment]
I tried messing around with this today. I got a backfill to work by running a "full" instance, declaring which pair to use and everything. I just added the --backfill variable to the command in run.sh. Hopefully I'll be able to run some simulations once it gets done collecting the data.

**Comment by alternativesurfer** [comment]
And you are my savior.  @robsteady 
Don't know why I didn't think to try that, but thank you so much for replying.
My backfill is running now (off run.sh)

Any idea how far back it will go, or does it just backfill until I say stop?

**Comment by robsteady** [comment]
I believe I read somewhere that it will backfill 84 days. I'm going to let it go to at least 84 days and see if it keeps going or not. The only catch I was just thinking about with the last 84 days of history is that it will be next to impossible for it not to show a positive ROI. I'll probably have to go in to the fine details of whatever sim gets run and really look at the spread to see how well (or if) the current modified logic will work. Unless I find something blatantly screwed up (or I can't manage to make it work) I'll probably throw my sim results up for folks to look at.

**Comment by robsteady** [comment]
Correction, it does hit a point where it gives a message of "backfill complete". I remember seeing it yesterday when I was playing around with an ETH/USD pair.

**Comment by alternativesurfer** [comment]
84 days of history will only show Positive if you're running with all the default logic, correct.
I am attempting to tweak this to make many Same Day trades following the small little ups and downs that the value of BTC makes every day.

84 days should be fine enough for that, otherwise Ill figure out how to force it to pull further back.

**Comment by robsteady** [comment]
Yes, getting it to take advantage of more trades per day would be awesome. Even though it filled 84 days back it looks like the sims only run about 23 back.

**Comment by carlos8f** [comment]
Zenbot 4 is out, so I'm cleaning up 3.x issues. Please use and test 4, thanks!
