### ISSUE TITLE
darwin.js .csv output missing period data due to period -> periodLength conversion omission.

### ISSUE THREAD

**Issue by shr00mie** [DeviaVir/zenbot#1004]
i believe the commit which replaced all `period` with `periodLength` missed line 541 in darwin.js which is causing the "Period" column in .csv output to be empty. .json does not appear to be affected.

**Comment by DeviaVir** [comment]
This issue was moved to highvelocityspace/zenbot#10

**Comment by DeviaVir** [comment]
Is this fixed now due to your own PR?

**Comment by shr00mie** [comment]
yuuuuuuuuuuuuup
