### ISSUE TITLE
Simulation forces sale at the end

### ISSUE THREAD

**Issue by pursehouse** [DeviaVir/zenbot#1007]
When a sim runs, at the end of the test it sells your coins at whatever the last market price is. So the results data are useless because it could have been a great profit that only lost at the end because of this sale.
Can't it change to just not do that final sell and display the $ and coin holdings?

**Comment by DeviaVir** [comment]
This issue was moved to highvelocityspace/zenbot#5

**Comment by DeviaVir** [comment]
This issue was moved to highvelocityspace/zenbot#6

**Comment by DeviaVir** [comment]
This issue was moved to highvelocityspace/zenbot#7

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖

**Comment by ghost** [comment]
Has anybody answered pursehouse's question?! (Simulation forces sale at the end #1007)
Thanks for replying!

**Comment by LoneWolf345** [comment]
Might have to look and see if he reposted his question on reddit.

**Comment by pursehouse** [comment]
I didn't repost it... no idea why that reddit thing was created.. i'm abandoning zenbot so you can close this if you want

**Comment by LoneWolf345** [comment]
I believe the subreddit was created to help keep questions in a better location.  Unfortunately, since it was just created it has not seen wide adoption yet.  We wish you the best of luck.

**Comment by ghost** [comment]
I would really appreciate an answer... before closing the issue!

**Comment by DeviaVir** [comment]
Feel free to ask your question over at our Reddit, there's an elaborate explanation of why we choose this method when opening a new issue, thanks!
