### ISSUE TITLE
Multiple time frames for trading strategies

### ISSUE THREAD

**Issue by nlapham21** [DeviaVir/zenbot#1019]
Great project, its nice being able to simulate the trades with backfilled data then paper trade before moving to live trading.

I've been working on my strategies my question is, I would like to use multiple time frames in my strategies, is there a way to do this currently? I tried adding a second "period" variable in a strategy with a new name and only got errors.

For an example, I could use this in the srsi_macd stategy to have the macd trigger the positive buy signal at a larger period, say 5h, then have the srsi trigger the positive buy signal on a smaller period, say 5m (a buy signal would only occur when both of those criteria were in parody, for those not familiar with the strategy). That way I could use multiple time frames to see a bigger picture on when I would like to execute orders.

**Comment by zhoukeca** [comment]
I have the same question

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
