### ISSUE TITLE
multiple zenbot live instances 

### ISSUE THREAD

**Issue by psequeira** [DeviaVir/zenbot#1022]
Hello. 

Hello, I'm using zenbot for a week and for now it's been a really nice experience. For some reason that i'm missing i've been failled to launch multiple instances of zenbot it same strategy (speed), same currency but different assets. 

It don't show me any error but seems like the second instance receives multiple multiple periods for time:
In the attached images image 1 is first live bot running (BTC-SC) ok but in the second image you can see the problem happening live traiding BTC-STR.. It seems that it receives the period x5 times.

I'm a programmer. if you guide me i can make a pull request before the end of the year :)

Congratz and thanks for such great work
![btc-sc](https://user-images.githubusercontent.com/31435845/34456389-b064d962-ed8c-11e7-8cdc-922eef607e7f.PNG)
![btc-str](https://user-images.githubusercontent.com/31435845/34456415-661bca86-ed8d-11e7-8a55-070a655157ff.PNG)

**Comment by psequeira** [comment]
I'm still looking at this and i think is not related to have multiple instances.. but it's a stange bug. some one with same problem?

**Comment by defkev** [comment]
Strange indeed

I have multiple instances of zenbot on the same server working just fine.

How are you running zenbot? Local shell, over ssh, in screen/tmux?
Could just be a display problem of your terminal.

**Comment by psequeira** [comment]
I'm hosting on a ubuntu 16 in cloudbase. Runnig STR-BTC on Poloniex. it's running ok on SC-BTC.  This is happening to on a fresh zenbot install. I've not reinstalled mongodb but i deleted all db's before run. 
I will re-edit the post as soon as I have more test-cases.

**Comment by kernelsndrs** [comment]
I think this is related to the window size.  On every refresh of the CLI UI it attempts to display the overflow but cannot.  You can see the red 8% and green 2% overflow, and this issue can be replicated by resizing an ssh window like putty during trading.

**Comment by nlapham21** [comment]
^ I've seen odd issues like this if the terminal window size isn't large enough. Re-sizing always fixed it for me for future console displays.

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
