### ISSUE TITLE
Bot stopping unexpectedly when running in a AWS EC2 instance

### ISSUE THREAD

**Issue by acecilia** [DeviaVir/zenbot#1025]
Hello:

I am paper trading in a AWS EC2 instance for 5 days now. In order to see the output, I am using the screen command through ssh. Today I logged in to check the performance (did not logged in since some days ago, do not remember exactly when), and I realised that:
- The bot stopped trading some days ago (28th of December) without printing any error or indication.
- The bot started trading after I logged in, without me doing anything else.

Here you can see the last downloaded trade from 28th of December, and the first one form 31st:
![captura de pantalla 2017-12-31 a las 17 09 19](https://user-images.githubusercontent.com/7938671/34462940-7a6c859a-ee4e-11e7-97c8-dbf42a0ec89c.png)

Here you can see a network graph for the EC2 instance of the bot:
![captura de pantalla 2017-12-31 a las 17 09 44](https://user-images.githubusercontent.com/7938671/34462941-9b6f476e-ee4e-11e7-89ca-c411cd3c1842.png)

Here you can see how the graph jumps from 28th of December to 31st:
![captura de pantalla 2017-12-31 a las 17 22 48](https://user-images.githubusercontent.com/7938671/34462977-54149de6-ee4f-11e7-92f7-19fa569b0f71.png)

I know this may not be an issue with zenbot, it can also be a problem with the EC2 instance, or the screen command, or the OS, but:
- I checked, and seems the instance did not go to sleep at any point. 
- I do not see why the screen command would stop the execution.
- This being a newly created AWS EC2 instance, I expect the OS to run continuously, without any sleeping or hibernating configuration.

Did anybody experienced this before?
Thanks

### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Zenbot version**: 4 (checkout from master)
- **NodeJS version**: 8.9.3
- **Python version**: 2.7.12

**Comment by DeviaVir** [comment]
I don't think this is a zenbot specific question but I'll leave it open for now for others to chime in.

**Comment by kiancross** [comment]
I've also experienced the same thing.

![screen shot 2018-01-02 at 14 30 49](https://user-images.githubusercontent.com/11011464/34486892-d3ea4ac2-efc9-11e7-8fca-0f5f7aa7466e.png)

Not sure if those WebSocket disconnects are significant or now.

Can see the jump between 09:30 and 14:20 (when I reattached the screen session)

**Comment by defkev** [comment]
@acecilia 
Strange...looks almost like the instance hibernated.
Does syslog have a similar gap?

@kiancross 
> the jump between 09:30 and 14:20

Could just be low volume during this time.
Check the trade history on the exchange.

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
