### ISSUE TITLE
Run simulator in hosting environment

### ISSUE THREAD

**Issue by albertolive** [DeviaVir/zenbot#104]
Hi,

How can I view the simulator if the url given is for localhost. p.ex:

http://localhost:3013/?secret=ec9d27da7742327a

I also tried to add my hosting url instead of localhost but didn't work.

Thanks

**Comment by s-ftf** [comment]
@albertolive, it sounds like you are saying you have this hosted off of your local network and need to access it from your public ip.

Not sure if this will help, but here is the changes needed to have the terminal output display your LAN ip if it is on a locally networked device. This would be the same place that you could have it show the WAN instead.
https://github.com/mountaindrifter/zenbot/commit/ee03d0dd0b347f8b85d744d4add625694e0ab145?diff=split

The only trouble is, you should have been able to access it by manually entering your ip in place of localhost. I am thinking the port must not be opened or routed correctly on your host. Either that or maybe the secret key expired by then?

**Comment by albertolive** [comment]
Hi @mountaindrifter! Thank you for your response. I have tried but with no luck. With your code, it gived me a ip like this: http://172.17.28.138:3013/?secret=0562ade8c3b891b3. I'm hosting at heroku and maybe the port is closed. Now I know where I have to touch and I'll investigate more.

Thank you

**Comment by carlos8f** [comment]
Zenbot 4 is out, so I'm cleaning up 3.x issues. Please use and test 4, thanks!
