### ISSUE TITLE
not updating price and time (and therefore indicators) after Binance upgrade

### ISSUE THREAD

**Issue by 3BABY** [DeviaVir/zenbot#1041]
OS Ubuntu 16.04

Zenbot 4 was working great until Binance upgraded their systems today, after trading resumed the bot will not load the lastest price and therefore will not calculate indicators or percentages. i can place orders manually in manual mode.

any help would be much appreciated!

**Comment by bansalbhavin** [comment]
Same is with me. Have you found any solution?

**Comment by 3BABY** [comment]
No i havn'tfound a solution yet, hoping the Dev will be able to help ?

**Comment by bansalbhavin** [comment]
@DeviaVir 
Are you aware of this issue?

**Comment by bansalbhavin** [comment]
@3BABY start new instance with same details. It worked for me.

**Comment by DeviaVir** [comment]
Please re-open your ticket using the issue template.
