### ISSUE TITLE
Cant use neural strategy

### ISSUE THREAD

**Issue by Rutinguer** [DeviaVir/zenbot#1054]
Sorry for my english. Always when i use this strategy i got the same errors and cant work. I used neural recomended configuration, and i try with differents % sell / buy, and i have enough money ( 1ETH In this case ). Bot make a lot orders and cant work. When i tried on sim i have better results than the others strategies. Thanks for your help

```
```

> An error occurred { Error: binance POST https://api.binance.com/api/v3/order 400 Bad Request {"code":-2010,"msg":"Account has insufficient balance for requested action."} (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting)
>     at binance.defaultErrorHandler (/home/Xt/Documents/code/zenbot/node_modules/ccxt/js/base/Exchange.js:400:15)
>     at response.text.then.text (/home/X/Documents/code/zenbot/node_modules/ccxt/js/base/Exchange.js:413:25)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: ExchangeNotAvailable] }
```

```

> Binance API is down! unable to call buy, retrying in 20s
> [ { price: '0.008271',
>     size: '2.06935609',
>     orig_size: '2.04582361',
>     remaining_size: '2.04582361',
>     orig_price: '0.008270',
>     cancel_after: 'day',
>     product_id: 'KMD-ETH',
>     post_only: true,
>     type: 'limit',
>     side: 'buy' } ]
> An error occurred { Error: binance order cost = amount * price should be > 0.001 BTC {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}
>     at binance.handleErrors (/home/X/zenbotm/node_modules/ccxt/js/binance.js:627:19)
>     at response.text.then.text (/home/X/zenbotm/node_modules/ccxt/js/base/Exchange.js:412:18)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:`188:7) constructor: [Function: InvalidOrder] }`
```


```
> Binance API is down! unable to call cancelOrder, retrying in 20s
> { Error: binance cancelOrder() error: {"code":-2011,"msg":"UNKNOWN_ORDER"}
>     at binance.cancelOrder (/home/X/zenbotm/node_modules/ccxt/js/binance.js:531:23)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: OrderNotFound] }
> [ { order_id: '1956329', product_id: 'KMD-ETH' } ]
> An error occurred { Error: binance order cost = amount * price should be > 0.001 BTC {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}
>     at binance.handleErrors (/home/X/zenbotm/node_modules/ccxt/js/binance.js:627:19)
>     at response.text.then.text (/home/X/zenbotm/node_modules/ccxt/js/base/Exchange.js:412:18)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: InvalidOrder] }
```

`

**Comment by morenoh149** [comment]
it must be one of the issues listed `possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting)` please check these and report back.

**Comment by Rutinguer** [comment]
@ morenoh149 Says this problem , but zenbot make some orders. After that says no funds,  binance order cost = amount * price should be > 0.001 BTC etc

**Comment by Rutinguer** [comment]
Im trying again this morning , works fine ( at this moment ). I dont know why. I will let you know

Yesterday the bot make a lot orders / second , now looks more slow

**Comment by morenoh149** [comment]
zenbot can't be responsible for issues with the exchange. Make sure everything is okay on your side. Gdax has been known to stall out on people when there is a lot of traffic (panic in the markets).

**Comment by bbusche** [comment]
I have been getting this same error with neural when Zenbot gets a buy signal, but it has already bought. Seems like it is trying to use a very small amount of remaining funds to buy more, but that is below the exchange's minimum purchase size.  That may explain why this error appears to be intermittant.

**Comment by Rutinguer** [comment]
Still having the same problem. When the bot fails first time , always try to do the same and cant work

Says buying or selling but no making orders
@bbusche @morenoh149  @bbusche @DeviaVir 

EX:

Binance API is down! unable to call buy, retrying in 20s
[ { price: '0.00000904',
    size: '6364.70497995',
    orig_size: '6364.70497995',
    remaining_size: '6364.70497995',
    orig_price: '0.00000898',
    cancel_after: 'day',
    product_id: 'POE-BTC',
    post_only: true,
    order_id: '5026212',
    orig_time: 1516651873557,
    time: 1516651873557,
    local_time: 1516651873557,
    status: 'open',
    type: 'limit',
    side: 'buy' } ]

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
