### ISSUE TITLE
Question about checking from strategy if last signal's buy/sell order completed successfully

### ISSUE THREAD

**Issue by Orwi53** [DeviaVir/zenbot#1057]
Once I issue a "s.signal = ", how can I check if the corresponding order completed successfully? It would be useful, because my custom strategy often tries to sell before a corresponding buy order is completed, causing issues, especially in the cases where orders take 5+ minutes to complete. I would like to be able to check (from my strategy) if the s.signal command completed successfully before I issue another "s.signal = " command.

Can I do this?

**Comment by Orwi53** [comment]
After having a look at lib/engine.js, I found a (potentially unattractive) semi-solution:

    s.my_trades.length

can be used to get the number of completed trades. The increase of this number can be used as an indication for knowing if there was one or more completed orders after the last signal was issued.

If anyone has a better idea for this, they are welcome to post it, especially regarding the cases where a signal is accompanied by 2 buy (or sell) orders for that signal. Checking just against the increase of that number will tell you just if at least 1 order was completed (the second order might fail and still such indicator would tell you that your last s.signal's order/s were completed)

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
