### ISSUE TITLE
Duplicate 'dema' section in readme

### ISSUE THREAD

**Issue by tabbek** [DeviaVir/zenbot#1064]
dema section was duplicated in commit e8fc526 starting at line 318 of README.md

**Comment by DeviaVir** [comment]
That is actually `dema-lessnoise` but its name is `dema` hence the output.
https://github.com/DeviaVir/zenbot/blob/unstable/extensions/strategies/dema-lessnoise/strategy.js#L6
  
My suggested fix is to rename it there and rename it in the list-strategies README as well. We can remove it now but it is one of the strats so it'll be back as soon as we add another strategy and update the output.

**Comment by Shawn8901** [comment]
+1 for rename

**Comment by tabbek** [comment]
looking further, yes, leaving it there and renaming would be easiest, but ideally, this would be integrated with the existing strategy since it's basically the same thing just with the added option of a null signal.

**Comment by Shawn8901** [comment]
i have added a pr to merge both strategies.
