### ISSUE TITLE
Default Logic - Trade %

### ISSUE THREAD

**Issue by alternativesurfer** [DeviaVir/zenbot#107]
So in Default_logic.js:
rs.trade_pct = 0.98 // trade % of current balance

Any reason this isn't 100%?

**Comment by robsteady** [comment]
I'd assume to leave a balance in case two buys or two sells come in a row? Though if this were the case, it might have been better off at 75 or even 50 percent.

**Comment by alternativesurfer** [comment]
Yeah, I think I may play around with a lower percentage.
Dollar cost averaging, rather than lump sum investing...May help stave off losses from "crashes".

**Comment by DeviaVir** [comment]
Slippage seem to be the answer, and also an unhappy GDAX API.
