### ISSUE TITLE
Incorrect pinkie package dependency

### ISSUE THREAD

**Issue by tabbek** [DeviaVir/zenbot#1070]
```2661 verbose Linux 4.4.0-104-generic
2662 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
2663 verbose node v8.9.4
2664 verbose npm  v5.6.0
2665 error code E404
2666 error 404 Not Found: pinkie@https://registry.npmjs.org/pinkie/-/pinkie-2.0.5.tgz
```

https://github.com/floatdrop/pinkie/issues/18

https://github.com/npm/registry/issues/256#issuecomment-355785321

**Comment by danielkhalilov** [comment]
Just had this problem; I believe deleting the package-lock.json file and having it recreate itself fixed it for me (make a backup just in case)

**Comment by tabbek** [comment]
Deleting and re-'npm install'ing does regenerate the package-lock.json file with the proper 2.0.4 version of pinkie, just needs it committed so as to not fail after a fresh checkout.

**Comment by SlackerATX** [comment]
I got this as well

  npm ERR! code E404
npm ERR! 404 Not Found: pinkie@https://registry.npmjs.org/pinkie/-/pinkie-2.0.5.tgz

rm package-lock.jso fixed it as well
