### ISSUE TITLE
Bot not trading

### ISSUE THREAD

**Issue by albertolive** [DeviaVir/zenbot#109]
Hi,

It has been a week since I started to collect data needed for the bot starting to trade but nothing happened. Maybe I'm missing something so let's see if someone can help me.

I'm running the bot in heroku and saving to a mongodb of them.

I'm running this script to start the bot:

`./zenbot launch map --backfill reduce run server --config config_btc_eur.js --rs btc_eur`

**config_btc_eur.js**

    var c = module.exports = require('./config')

    c.assets = [
      "BTC"
    ]
    c.currencies = [
      "EUR",
      "BTC"
    ]

    // default selector for indicators, etc
    c.default_selector = "gdax.BTC-EUR"

**config.js**

    var c = module.exports = require('./config_defaults')()

    // mongo stuff
    c.mongo_url = "heroku mongodb" // change if your mongo server isn't local

    c.mongo_username = null // normally not needed
    c.mongo_password = null

    c.gdax_key = 'key' // TO ENABLE BOT TRADING: set this to GDAX api key,
    c.gdax_secret = 'secret' // set this to GDAX api secret,
    c.gdax_passphrase = 'pass' // set this to GDAX api passphrase.
    c.trade_log = true // log new trades as they come in.

    // watch these exchanges
    c.watch_exchanges = [
      //"bitfinex",
      "gdax",
      //"kraken",
      //"poloniex"
    ]

    // selector for indicators, trading, etc
    c.default_selector = "gdax.BTC-EUR"

    // add selectors in the format "{exchange-slug}.{asset}-{currency}" to graph them
    c.graph_selectors = [
      c.default_selector,
      "gdax.ETH-BTC",
      "gdax.ETH-EUR"
    ]

    // trade logic
    c.logic = require('./eur_logic')

**eur_logic**
Big file, I got it from another [post](https://github.com/carlos8f/zenbot/issues/25)

The logs are saying that n/a ROI:n/a:

![screen shot 2017-01-25 at 20 03 56](https://cloud.githubusercontent.com/assets/1182864/22304855/88ccab04-e339-11e6-9eac-9ee53b46aced.png)

If you see, I have placed 18€ just to try if it's working. Before that, I had all this money in BTC.

And, finally, my db data:

![screen shot 2017-01-25 at 20 07 30](https://cloud.githubusercontent.com/assets/1182864/22304960/0153654a-e33a-11e6-98e1-936cf72dc659.png)

Anyone can help me please?

**Comment by alternativesurfer** [comment]
Remove your Key/Secret/Passphrase from the config file and see if the Adviser mode bot runs/makes fake trades.

I would also check and confirm the API key you made in GDAX is for View and Trade.

**Comment by albertolive** [comment]
I have switched to default_logic and now I have ROI at 1.000. Let's see if finally it trades.

**Comment by carlos8f** [comment]
Cleaning up old 3.x issues
