### ISSUE TITLE
ZenBot Learning.js Param Errors

### ISSUE THREAD

**Issue by mesquka** [DeviaVir/zenbot#11]
Running Zenbot 2.6.0, while running ZenBot Learn I get errors at regular intervals, usually happening just before the 'simulating' progress bar hits 100%

Log file attached:
[log.txt](https://github.com/carlos8f/zenbot/files/405383/log.txt)

**Comment by carlos8f** [comment]
hi kieran,

those errors are actually just a part of the learning process, it validates that mutated params are within a good range and aborts the sim if not.

cheers,
Carlos

**Comment by carlos8f** [comment]
Zenbot 4 is out, so I'm cleaning up 3.x issues. Please use and test 4, thanks!
