### ISSUE TITLE
price update poll

### ISSUE THREAD

**Issue by trivalik** [DeviaVir/zenbot#1104]
How do I get regulary updated price, it doesn't look that there is a poll option. I use binance.

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
