### ISSUE TITLE
Project status.

### ISSUE THREAD

**Issue by edward81** [DeviaVir/zenbot#111]
After a long time i take a look at zenbot. Looks like that now is trading only from rsi value and some tricks on default_logic. Looks like all the learning thing present on 2.0 is gone now.

**Comment by postadelmaga** [comment]
https://github.com/carlos8f/zenbot/issues/128

**Comment by carlos8f** [comment]
Zenbot 4 is up and running! It uses an EMA-based approach now, and the strategy is more tweakable and nuanced. Do give it a try and let me know what you think.
