### ISSUE TITLE
Endless retry in cancelOrder Binance exchange action

### ISSUE THREAD

**Issue by Haehnchen** [DeviaVir/zenbot#1120]
Simular to #1096 _cancelOrder_ is in endless retry mode. We have missing error code extraction from response

```
    cancelOrder: function (opts, cb) {
      var func_args = [].slice.call(arguments)
      var client = authedClient()
      client.cancelOrder(opts.order_id, joinProduct(opts.product_id)).then(function (body) {
        if (body && (body.message === 'Order already done' || body.message === 'order not found')) return cb()
        cb(null)
      },function(err){
        if (err) return retry('cancelOrder', func_args, err)
        cb()
      })
    },
```

> Binance API is down! unable to call cancelOrder, retrying in 20s
> { Error: binance {"code":-2011,"msg":"UNKNOWN_ORDER"}
>     at binance.handleErrors (/root/zenbot/node_modules/ccxt/js/binance.js:805:27)
>     at response.text.then.text (/root/zenbot/node_modules/ccxt/js/base/Exchange.js:443:18)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: OrderNotFound] }
> [ { order_id: 'xxx', product_id: 'xxx-xxx' } ]

**Comment by didasy** [comment]
I still got this error on unstable branch.

```
Binance API is down! unable to call cancelOrder, retrying in 20s
{ Error: binance {"code":-2011,"msg":"UNKNOWN_ORDER"}
    at binance.handleErrors (/home/dida/zenbot-master/node_modules/ccxt/js/binance.js:847:27)
    at response.text.then.text (/home/dida/zenbot-master/node_modules/ccxt/js/base/Exchange.js:452:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: OrderNotFound] }
[ { order_id: '5925930', product_id: 'VEN-ETH' } ]

```
