### ISSUE TITLE
zenbot sim is broken

### ISSUE THREAD

**Issue by johanatan** [DeviaVir/zenbot#113]
Even though my bot has more than 84 days of historical data, I am getting the following errors when running `./zenbot sim --verbose`:

```
02/14/2017 06:34:55 PM PST [      trader] gdax.BTC-USD need more historical data, only have 0 of 26 5m ticks
02/14/2017 06:34:55 PM PST [      trader] gdax.BTC-USD need more historical data, only have 0 of 26 5m ticks
02/14/2017 06:34:55 PM PST [      trader] gdax.BTC-USD need more historical data, only have 0 of 26 5m ticks
02/14/2017 06:34:55 PM PST [      trader] gdax.BTC-USD need more historical data, only have 0 of 26 5m ticks
```

**Comment by nedievas** [comment]
There is a problem on your side. By default it is working like a clock. I tried to adapt it to bitfinex with no luck.

**Comment by johanatan** [comment]
I haven't made any modifications to the default configuration beyond entering my GDAX credentials.

Is there a way to just clear out the database and start from scratch? [or should I just re-clone into a fresh directory?]

**Comment by johanatan** [comment]
[or should i just re-clone into a different directory]?

**Comment by johanatan** [comment]
Oh, actually there is one deviation from the happy path I took. In step 4, I ran `config_eth_btc.js`. Do I need to also specify that when starting the sim? If so, how?

**Comment by tux-00** [comment]
I'm also curious to know if there is a way to clear the database ...

**Comment by nedievas** [comment]
$mongo
>use zenbrain
>db.dropDatabase()
>exit

**Comment by Leandrosson** [comment]
Sim is not working properly. Watch this

"id": "e130621fd907a16c",
  "ticks": 258559,
  "sim_end_timestamp": "02/16/2017 01:00:00 AM CET",
  "sim_start_bucket": "7d2447",
  "sim_start_time": 1479945600000,
  "sim_start_tick": "7d2447",
  "sim_start_timestamp": "11/24/2016 01:00:00 AM CET",
  "end_time": 1487203140000,
  "queue": [],
  "actions": [
    {
      "type": "buy",
      "asset": "BTC",
      "currency": "USD",
      "exchange": "gdax",
      "price": 730.02,
      "fee": 12.25,
      "market": true,
      "size": 6.712144872743213,
      "rsi": 18.607155791900013,
      "roi": 0.9910206575682383,
      "roi_delta": -0.001225,
      "performance": null,
      "waited": null,
      "balance": {
        "BTC": 13.455051335144768,
        "USD": 87.75
      },
      "end_balance": 9910.206575682383,
      "id": "0da88564322cfe68",
      "time": 1480154340000,
      "timestamp": "11/26/2016 10:59:00 AM CET"

If we start with 10.000 and maximum is 0.98 the rest is 200 not 87,75
If we buy 9800 minus 0.25% fee is 9.799,98 @ 730.02 is 13,4242 BTC not 13,4550
Final balance is got to be 9.999,98

So the whole sim calculation is wrong

**Comment by ghost** [comment]
I also encountered the same problem as OP with a completely default setup and had to drop the db and repopulate. One thing I was at the time doing all 3 default currency pairs, on the second try after dropping the db I only did btc_usd, so perhaps it will break again.

**Comment by carlosgb55** [comment]
Hi, I have a question. Do I have to setup a gdax account to config.js to be able to test live tranding and the simulation? When I run the simulation or the ./run.sh, zenbot shows a link to the chart, that chart shows "no data" for me. Any help appreciated.

**Comment by carlos8f** [comment]
Cleaning up 3.x issues
