### ISSUE TITLE
extensions/exchanges/binance/products.json broken

### ISSUE THREAD

**Issue by trivalik** [DeviaVir/zenbot#1137]
Please fix. i.e. by execute the update-product.sh

./zenbot.sh trade --conf ../conf.js
module.js:665
    throw err;
    ^

SyntaxError: /mnt/c/Users/y/Repos/zenbot/extensions/exchanges/binance/products.json: Unexpected token : in JSON at position 36618

**Comment by Shawn8901** [comment]
As quick fix add a '{' at the end of  line 1720

**Comment by thijsgelton** [comment]
And rename it to .js?

**Comment by Shawn8901** [comment]
no, why? its a json file.

**Comment by tienduccao** [comment]
> As quick fix add a '{' at the end of line 1720

It works, thanks :)
