### ISSUE TITLE
app.bundle.js returns 404 in the Web UI

### ISSUE THREAD

**Issue by GovanifY** [DeviaVir/zenbot#1142]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Gentoo Linux
- **Zenbot version**: Latest unstable
- **NodeJS version**: v9.3.0
- **Python version**: Python 3.5.4
- **Exact command to reproduce**: ./zenbot.sh trade

### Describe the problem
The web UI does not load the file "app.bundle.js". It returns 404.
The layout of the page also is way off: https://screenshots.firefox.com/WEIuKOO4qLsLaOeD/money.anarchist.pw
This file seems like it tried to be loaded as a CSS stylesheet too while keeping its js extension
![screenshot_20180115_181956](https://user-images.githubusercontent.com/6375438/34954419-b1eea006-fa20-11e7-94c5-d87895205ca0.png)

**Comment by defkev** [comment]
I suppose you are running npm as root?

Do this:
> npm install --unsafe-perm

**Comment by GovanifY** [comment]
I actually was not, I made a special user for the bot.
 I am under an SELinux setup, that might be the culprit. 
This command worked though *shrug*

**Comment by defkev** [comment]
> I made a special user for the bot

👍 

> I am under an SELinux setup

Also possible
