### ISSUE TITLE
No trades even with sim?

### ISSUE THREAD

**Issue by ivoras** [DeviaVir/zenbot#1144]
I'm running zenbot from git (just pulled it again and re-tested) on hitbtc, after applying the patch which solves backfilling trades for hitbtc (https://github.com/DeviaVir/zenbot/issues/773#issuecomment-356281073), and it's not making any trades even in sim.

I'm starting it as:

`./zenbot.sh sim --days 20  hitbtc.DOGE-USDT`

And the result is:

```
{
  "asset_capital": 100,
  "avg_slippage_pct": 0.045,
  "buy_pct": 99,
  "buy_stop_pct": 0,
  "currency_capital": 100,
  "days": 20,
  "markdown_buy_pct": 0,
  "markup_sell_pct": 0,
  "max_sell_loss_pct": 25,
  "max_slippage_pct": 5,
  "min_periods": 52,
  "mode": "sim",
  "neutral_rate": "auto",
  "order_adjust_time": 5000,
  "order_type": "maker",
  "oversold_rsi": 10,
  "oversold_rsi_periods": 14,
  "period": "2m",
  "period_length": "2m",
  "profit_stop_enable_pct": 0,
  "profit_stop_pct": 1,
  "rsi_periods": 14,
  "selector": {
    "exchange_id": "hitbtc",
    "product_id": "DOGE-USDT",
    "asset": "DOGE",
    "currency": "USDT",
    "normalized": "hitbtc.DOGE-USDT"
  },
  "sell_pct": 99,
  "sell_stop_pct": 0,
  "show_options": true,
  "start": 1514246400000,
  "stats": false,
  "strategy": "trend_ema",
  "trend_ema": 26,
  "verbose": false
}
end balance: 101.02540000 (0.15%)
buy hold: 118.75215086 (17.72%)
vs. buy hold: -14.93%
0 trades over 21 days (avg 0.00 trades/day)
wrote simulations/sim_result_hitbtc.DOGE-USDT_180115_195802_UTC.html
```

(this is a sim where the asset and currency capital are both set to 100).

While it's working I can see that it shows the "buy" and "sell" labels:

`2018-01-03 05:09:53   0.0090660 DOGE-USDT   +0.86%  119.89k   54 +       0.7333   0.3361      buy  100.00000000 DOGE  100.00000000 USDT   +0.03%   -3.90%`

only nothing happens - the balances (100 DOGE and 100 USDT) stay the same. I've tried changing the sim capital settings, different currency pairs, days simulated, and strategies - no success with any of those. But on the other hand the final output has "101.02540000", so it's like something is happening, only it's not shown during the process. Or am I misinterpreting the "100 DOGE, 100 USDT" part of the status line and the "0 trades" status of the sim?

Any ideas?

**Comment by ivoras** [comment]
I've later found out that this is most likely because HitBTC is not fully supported, so in a way this should be expected. I've tried with others and it works.

**Comment by ghost** [comment]
Since the binance hack I have moved over to hitbtc but now the trades are not working. Any ideas?
