### ISSUE TITLE
how do I get the lookback to populate?

### ISSUE THREAD

**Issue by BrannonKing** [DeviaVir/zenbot#1151]
I was attempting to write my own SRSI strategy using the code below. I don't understand how to get the lookback working as it's always an empty object for me. What am I doing wrong?

```js
module.exports = function container (get, set, clear) {
  return {
    name: 'brans_srsi',
    description: 'Brannon\'s Stochastic RSI Strategy',

    getOptions: function () {
      this.option('period', 'period length, same as --period_length', String, '5m')
      this.option('period_length', 'period length, same as --period', String, '5m')
      this.option('min_periods', 'min. number of history periods', Number, 20)
      this.option('rsi_periods', 'number of RSI periods', Number, 14)
      this.option('srsi_k', '%K line', Number, 2)
      this.option('srsi_d', '%D line', Number, 3)
      this.option('srsi_min_change', '', Number, 0.2)
    },

    calculate: function (s) {
      // compute Stochastic RSI
      get('lib.srsi')(s, 'srsi', s.options.rsi_periods, s.options.srsi_k, s.options.srsi_d)
    },

    onPeriod: function (s, cb) {
      if (s.in_preroll) return;

      var k = s.period.srsi_K;
      var k1 = s.lookback[0].srsi_K; // srsi_K is never defined!
      ...
```

**Comment by tiagosiebler** [comment]
The lookback populates over time, so if you need access to it you can follow what some of the libs are doing:
https://github.com/DeviaVir/zenbot/blob/unstable/lib/ema.js#L4

Keep checking if you have enough data, otherwise don't do your calculations yet. 

Edit: though I'm not sure whether custom items (such as your srsi_K) will be added to the lookback automatically over time.

**Comment by BrannonKing** [comment]
With min_periods set to 20 and an RSI period of 14, I should always have at least 6 items in the lookback, no? Or how do those numbers actually affect the calls to onPeriod?

For items not automatically added to the lookback, how do I do it manually?

**Comment by BrannonKing** [comment]
I added a check for `s.lookback.length < 2` to return at the top of `onPeriod`. That causes it to return from that method indefinitely. I also tried using the command line parameter keep_lookback_periods; it wasn't obvious what the default for that was (update: I guess that is for trade, not sim).

**Comment by BrannonKing** [comment]
I got it figured out; you have to execute the callback `cb` in any return scenario. Further than that, I discovered that syntax errors in onReport can cause the callback to fail without reporting the exact location.
