### ISSUE TITLE
Bug with latest version

### ISSUE THREAD

**Issue by ttrd06** [DeviaVir/zenbot#1160]
Morning,

I just git pulled the latest version of Zenbot (unstable) then i wanted to backfill some data from gdax.
Now i have this error from mongo db with the following cmd:

./zenbot.sh backfill gdax.BTC-EUR --days 1

`/zenbot/node_modules/sosa_mongo/mongo_backend.js:22
  var coll = db.collection(coll_path);
                ^

TypeError: db.collection is not a function
`

Someone has the same issue ?

**Comment by DeviaVir** [comment]
Please re-open your ticket using the issue template
