### ISSUE TITLE
Bittrex 'Error during syncing balance'

### ISSUE THREAD

**Issue by brucetus** [DeviaVir/zenbot#1164]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian 9
- **Zenbot version**: Latest 
- **NodeJS version**:  8.9.4
- **Python version**: ?
- **Exact command to reproduce**: ./zenbot.sh trade bittrex.ADA-BTC 

### Describe the problem
New error popping up multiple times related to syncing balances and API keys

### Source code / logs
I'm running multiple pairs in different screens. I've been getting this error recently which I haven't gotten before, so it may be related to recent changes. It seems to have something to do with my API key, but I've checked multiple times and it is correct in the conf.js and the permissions are correct. This is related to issue #1085 , which has been closed by the creator, but doesn't give a solid fix. Also he seemed to get the error instantly after starting up the bot while mine happens hours after. I think an easy fix would be to put in an line that prevents the bot from crashing if the API can't call the account balance, either around line 506 of the trade.js file or somewhere in Bittrex's exchange.js file. If anybody can think of a way to do this let me know. Thanks.

<img width="896" alt="screen shot 2018-01-17 at 10 47 55 am" src="https://user-images.githubusercontent.com/31704711/35061505-4dfb41f6-fb76-11e7-9337-ec61247769e0.png">

**Comment by station384** [comment]
Are you running all instances at 1 minute intervals? 
(Below is my findings,  I have found no official statements from bittrex)
I ask because if bittrex is polled to fast it gives odd errors, one of them I've noticed is this error.  
I don't know this for sure but from what I have noticed, there is a max polling interval for each IP address connected to the server,  so if your behind a NAT, the combined polling of all clients can result in bittrex sending out errors 500 or 504,  I've also gotten this when there site crashes.

**Comment by brucetus** [comment]
Im running with a 4h period_length and my polling options are all default. Eventually every instance I was running on Bittrex crashed with the same error :(

**Comment by brucetus** [comment]
Eventually every instance I was running on Bittrex crashed with the same error.

**Comment by tskazinski** [comment]
I'm also getting this error with Kraken:
error syncing balance / RequestError: Request timed out
Happens every couple mins, my period is 1m though.

**Comment by station384** [comment]
@brucetus, the fix for this has been merged into the unstable branch
