### ISSUE TITLE
Expose Docker GUI

### ISSUE THREAD

**Issue by clement-hollander** [DeviaVir/zenbot#1169]
When running zenbot trade within Docker, the GUI is not exposed outside the docker. Adding a port mapping and fixed port in config doesn’t work cause port is mapped on run and then already allocated

**Comment by elRadix** [comment]
how can this be achieved and set the fixed ip ?

**Comment by ghost** [comment]
In docker-compose.yaml set:

server:
  ....(old config lines)...
  ports;
    - "20060:20060"

Then in conf.js set a fixed port:
c.output.api.port = 20060

This will expose port 20060 through Docker, allowing you to access the GUI from anywhere in the local network. This does not work with random ports, but then how would you connect to it from the browser? I use a fixed port so I can set a bookmark.

**Comment by clement-hollander** [comment]
@sbisschops that's what I've done previously but keep getting port already allocated. I now understand why, the trade --paper is launched at the docker-compose up.

That can be closed, but would be useful to explain in the README

**Comment by DeviaVir** [comment]
@clement-hollander please feel free to add whatever you think is useful to the README in a PR.
