### ISSUE TITLE
questions on periods

### ISSUE THREAD

**Issue by BrannonKing** [DeviaVir/zenbot#1173]
If I choose 5m periods, does that imply a world-wide standard time? In other words, if I chose 5m periods does zenbot's 5m periods' start times align with the 5m periods' start times I see when logged in to GDAX? 5m periods start at 6:00am, 6:05am, 6:10am, etc, regardless of when I start zenbot running my trade script?

Is there an easy way to convert the period length into the same units as s.period.close_time? (microseconds)

Why do all the strategy scripts have both period and period_length in them?

I assume that onPeriod is called just before transitioning into a new period?

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
