### ISSUE TITLE
CB-ACCESS-PASSPHRASE header is required

### ISSUE THREAD

**Issue by Keitsu42** [DeviaVir/zenbot#118]
Hi Everyone,

I'm new to github as well as Zenbot. I can't use GDX as I am an Australian so I'm trying to use Bitfinix. I put my Bitfinix API key details into config.js but there was an empty space for passphrase. Not sure if anything goes there.

config.js
>var c = module.exports = require('./config_defaults')()
>
>// mongo stuff
>c.mongo_url = "mongodb://" + (process.env.MONGODB_PORT_27017_TCP_ADDR || "localhost") + >":27017/zenbrain" // change if your mongo server isn't local
>
>c.mongo_username = null // normally not needed
>c.mongo_password = 
>
>c.gdax_key = 'REMOVED FOR POST' // TO ENABLE BOT TRADING: set this to GDAX api key,
>c.gdax_secret = 'REMOVED FOR POST' // set this to GDAX api secret,
>c.gdax_passphrase = '' // set this to GDAX api passphrase.
>c.trade_log = true // log new trades as they come in.
>
>// watch these exchanges
>c.watch_exchanges = [
> "bitfinex",
>  //"gdax",
>  //"kraken",
>  //"poloniex"
>]
>
>// selector for indicators, trading, etc
>c.default_selector = "bitfinex.BTC-USD"
>
>// add selectors in the format "{exchange-slug}.{asset}-{currency}" to graph them
>c.graph_selectors = [
>  c.default_selector,
>  "bitfinex.ETH-BTC",
>  "bitfinex.ETH-USD"
>]
>
>// trade logic
>c.logic = require('./default_logic')

vHere is a sample of the logs when I try to run Zenbot.
`{ message: 'CB-ACCESS-PASSPHRASE header is required' }
02/22/2017 06:32:09 PM AEDT [ERROR] non-200 status from exchange: 400
02/22/2017 06:32:09 PM AEDT [    bitfinex]    m24795811       2 trades. 02/22/2017 06:31:04 PM AEDT SELL         0.095 at     $1,117.50 BTC/USD
02/22/2017 06:32:10 PM AEDT [      trader] gdax.BTC-USD need more historical data, only have 0 of 26 5m ticks
02/22/2017 06:32:10 PM AEDT [    reporter]    m24795811       1 trades.                      RSI:n/a gdax.BTC-USD BAL:         n/a ROI:n/a
02/22/2017 06:32:36 PM AEDT [    bitfinex]    m24795811       2 trades. 02/22/2017 06:31:04 PM AEDT SELL         0.095 at     $1,117.50 BTC/USD
02/22/2017 06:33:02 PM AEDT [    bitfinex]    m24795811       2 trades. 02/22/2017 06:31:04 PM AEDT SELL         0.095 at     $1,117.50 BTC/USD
02/22/2017 06:33:29 PM AEDT [    bitfinex]    m24795813       8 trades. 02/22/2017 06:33:05 PM AEDT SELL         5.585 at     $1,117.23 BTC/USD
`
When running the program it is also stuck on saying " gdax.BTC-USD need more historical data, only have 0 of 26 5m ticks" repeatedly.

**Comment by nedievas** [comment]
It will not work by default with Bitfinex.

**Comment by Keitsu42** [comment]
I understand that. Is there any way I can configure it to work with Bitfinix?

**Comment by carlos8f** [comment]
@nedievas has awesomely made a PR for Bitfinex for Zenbot 4 that I need to review :) I'm no longer supporting 3.x so I'm cleaning up issues relating to 3.x.
