### ISSUE TITLE
Problems with the NPM install

### ISSUE THREAD

**Issue by pablodelamora** [DeviaVir/zenbot#119]
After cloning the project I tried to use the npm install command but I encountered some errors because of zenbrain.

**Comment by nedievas** [comment]
Read older issues. You'll find a solution.

**Comment by carlosgb55** [comment]
Hello, 
I'm having an issue when trying to install zenbot, I search for the solution in older issues, but I couldn't find any. I attach a log file from the npm install attempt. 

gyp, shows an error message mentioning that it couldn't load "binding.gyp" and at the end it says something about the "failed at the microtime@2.1.1".

Any help would be appreciated, thanks! 

[npm-debug.log.txt](https://github.com/carlos8f/zenbot/files/916738/npm-debug.log.txt)

**Comment by carlosgb55** [comment]
Never mind, I just had to install node.js.

**Comment by carlos8f** [comment]
Cleaning up 3.x issues
