### ISSUE TITLE
Add buy/sell difference as percent in web ui

### ISSUE THREAD

**Issue by Haehnchen** [DeviaVir/zenbot#1192]
To compare buy/sell's i build a custom web ui. to get easy visible control over trades i added a diff column. see screenshot. this looks also helpful for the native web ui i think.

![webui](https://user-images.githubusercontent.com/1011712/35198003-8e10313c-fee8-11e7-97a0-e45ae89e648e.png)

**Comment by defkev** [comment]
You mean to get an idea what you max_sell_loss_pct should look like?

**Comment by defkev** [comment]
Might as well add a fee colum once #1193 is fixed.
Nice idea 👍

**Comment by Haehnchen** [comment]
meaning: just the difference between buy and sell. so the profit of each action
