### ISSUE TITLE
Bollinger High/Low Status

### ISSUE THREAD

**Issue by station384** [DeviaVir/zenbot#1195]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04 / macOS Current Version
- **Zenbot version**: unstable
- **NodeJS version**: current ubuntu release
- **Python version**: 
- **Exact command to reproduce**: ./zenbot sim gdax.bch-btc --strategy bollinger --days=3 

### Describe the problem
Bollinger High / Low status display only show whole numbers,  This results in confusing values when trading on values with a price less than 1.  i.e.  bch-btc,  1 bch is currently trading at 0.1XXXX this results in a High/Low value of 00 00  where it should display 00.1XXX 00.1XXX.
Looking thru the code there is room for 7 characters and one space for each high and low value so should not cause any issues. 

This effects Bollinger and Trend_Bollinger

**Comment by station384** [comment]
I'll make this change myself, if feedback is good.

**Comment by DeviaVir** [comment]
Sure, go for it @station384 :)
