### ISSUE TITLE
Trading more often

### ISSUE THREAD

**Issue by albertolive** [DeviaVir/zenbot#120]
Hi,

I was thinking why the bot does not trade more often? Why does it waits a lot of time from one buy to another buy? 

I think that then, we'll have more profits.

What do you think? Someone has try it?

Another thing, it has been 9 days without any buy. The bot sold all my assets when BTC was at 1070€ and then, it was not possible to buy again.

**Comment by nedievas** [comment]
Try to change RSI settings. I made it to trade each minute (needed to test).

**Comment by praeluceo** [comment]
If you want it to trade more often, you can change the wait times, for instance, I changed mine to trade every 30 minutes, this is the diff:

```
$ git diff
diff --git a/default_logic.js b/default_logic.js
index 649f76f..0f3ed82 100644
--- a/default_logic.js
+++ b/default_logic.js
@@ -73,8 +73,8 @@ module.exports = function container (get, set, clear) {
       if (!rs.product) return cb(new Error('no product for ' + c.default_selector))
       rs.min_trade = n(rs.product.min_size).multiply(1).value()
       rs.sim_start_balance = 10000
-      rs.min_double_wait = 86400000 * 1 // wait in ms after action before doing same action
-      rs.min_reversal_wait = 86400000 * 0.75 // wait in ms after action before doing opposite action
+      rs.min_double_wait = 1800000 * 1 // wait in ms after action before doing same action
+      rs.min_reversal_wait = 1800000 * 0.75 // wait in ms after action before doing opposite action
       rs.min_performance = -0.015 // abort trades with lower performance score
       if (first_run) {
         delete rs.real_trade_warning
```

Choose any time (in ms) that suits you and re-npm the bot.

**Comment by carlos8f** [comment]
Cleaning up 3.x issues
