### ISSUE TITLE
npm cannot write even as root with all perms

### ISSUE THREAD

**Issue by oxyopes** [DeviaVir/zenbot#1201]
i am trying to install  zenbot on ubuntu 16.04 just like the instructions on github.
It goes smoothly untill this line:

```
# npm install
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q git://github.com/mkmarek/forex.analytics.git /root/.npm/_cacache/tmp/git-clone-8cd5fb20
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-8cd5fb20': Permission denied
npm ERR! 


```
the cmd npm seems to see a permition problem to write on /root/.npm/_cacache/tmp/git-clone.....
Yet i am running it as root. I even gave full permitions (777) to all dirs under /root/.npm to be on the safe side. Yet it keeps seen perm problems. 

Can anyone give a hint?
THx

**Comment by JensvdHeydt** [comment]
Are you running npm install inside a docker container? In that case it could be a problem with the containers shared volumes.

**Comment by micheledicosmo** [comment]
The unclean way of `rm -rf /root/.npm` might solve it, if you are ok at reinstalling npm packages you have already installed.

**Comment by oxyopes** [comment]
hey guys, neither i am running zenbot from inside docker, nor deleting /root/.npm helped. I tried some variations of the latter as well. It must be a very silly problem, but i cant find it . Hope u have more tips!
Thx...

**Comment by trivalik** [comment]
Try not to run as root. Clean the node_modules folder and retry. It seems that running npm install twice is not working properly for all cases.

**Comment by oxyopes** [comment]
great!!!!!!!!!!!!!   Now it works....
Time to read the docs and get started!
Thx...
