### ISSUE TITLE
No data - BTC EUR

### ISSUE THREAD

**Issue by SimonVillage** [DeviaVir/zenbot#122]
Hi there,

I have set this in my config.js
`c.default_selector = "gdax.BTC-EUR"`

My runscript is the following:
`./zenbot launch map --backlog run --config config_btc_eur.js --rs btc_eur server`

config_btc_eur.js
```
var c = module.exports = require('./config')

c.assets = [
  "BTC"
]
c.currencies = [
  "EUR",
  "BTC"
]

// default selector for indicators, etc
c.default_selector = "gdax.BTC-EUR"
```

Out put after I run this script
```
03/09/2017 11:40:19 AM UTC [      server] open http://localhost:3013/?secret=1fa68024425d6021 to see a live graph.
03/09/2017 11:40:19 AM UTC [        gdax]    m24817659       2 trades. 03/09/2017 11:39:17 AM UTC  BUY         0.170 at    €1 107,00 BTC/EUR
03/09/2017 11:40:19 AM UTC [        gdax]    m24685637     100 trades. 12/07/2016 07:17:01 PM UTC  BUY        11.147 at      €716,38 BTC/EUR
03/09/2017 11:40:19 AM UTC [        gdax] BTC/EUR backfill complete
```

But server says still no data on gdax.BTC-EUR

Did I miss something?

**Comment by nedievas** [comment]
> My runscript is the following:
>./zenbot launch map --backlog run --config config_btc_eur.js --rs btc_eur server

Shouldn't it be like that: 
./zenbot launch map --backfill reduce run server --config config_btc_eur.js --rs btc_eur

**Comment by carlos8f** [comment]
Cleaning up old 3.x issues
