### ISSUE TITLE
Not enough funds to execute?

### ISSUE THREAD

**Issue by Octogafy** [DeviaVir/zenbot#123]
Hello,
Its driving me crazy..
The bot starts with "holding on to my but!" :)  and confirming the just balance right. 
When it wants to sell coin ("attempting to sell"), it cant,  saying "not enough funds" funds are 0.000, but actually are not. :(
Because Bitfinex and GDAX (modules) have the same issue, i suspect it is somewhere in the code.
It looks like it accurs after some time when the bot is running. At start it executes well.
Same issues as #112 (albertolive) but now with Bitfinex.
Any suggestions?
Thx!

**Comment by tperalta82** [comment]
In my case, it seems the bot makes some kind of calculation, for example:

04/18/2017 11:59:03 PM UTC [      action] m24875998 sell {
  "type": "sell",
  "asset": "ETH",
  "currency": "BTC",
  "exchange": "gdax",
  "price": 0.04157,
  "fee": 0.00016032939071584725,
  "market": true,
  "size": 1.5427413107129877,
  "rsi": 65.58469747008522,
  "roi": 0.99875,
  "roi_delta": -0.0012499999999999734,
  "performance": null,
  "waited": null,
  "balance": {
    "ETH": 1.5427413107129877,
    "BTC": 0.06397142689562306
  },
  "end_balance": 0.12810318318196195,
  "id": "d7afc48ba80daccd",
  "time": 1492559940000,
  "timestamp": "04/18/2017 11:59:00 PM UTC"
}

in my logic i have 50% trading, not the 98%

And I only have BTC, not ETH, and its balance is 0.12810318318196195 which is 3ETH
and the 50% make around-ish 1.5427413107129877 ETH it tries to sell.

So there is something wrong with the logic here

**Comment by nibzo1** [comment]
My bot is also configured to use 50% balance and it appears to be trying to sell amounts of coin I do not have. I have several trades which basically bounced as there was not enough funds.

Any solution to this, have you hacked about with the logic? Im going to have a dig about and see what I can see

**Comment by carlos8f** [comment]
Cleaning up 3.x issues, as I no longer support it. Try Zenbot 4!
