### ISSUE TITLE
Define products.json format

### ISSUE THREAD

**Issue by station384** [DeviaVir/zenbot#1232]
There is not a clear definition of what the values are in the products.json for the exchanges.
    "asset": "VIA",  --Con
    "currency": "BTC", --Market
    "min_size": "0.52410901", --Minimum  coin purchase purchase?
    "min_total": "0.52410901", --Minimum coin purchase purchase?
    "max_size": "1000000", --Maximum amount of coin you can buy at once.
    "increment": "0.52410901", --Increment size (this I'm really unsure of)
    "label": "BTC/VIA" -- label given to the coin/market pair.

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
