### ISSUE TITLE
sell_stop_pct does not work when updating live trading configuration 

### ISSUE THREAD

**Issue by ghost** [DeviaVir/zenbot#1239]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian 9.2
- **Zenbot version**: 4.0.5
- **NodeJS version**: 8.9.3-1nodesource1
- **Python version**: 2.7.13-2
- **Exact command to reproduce**: -

### Describe the problem
Hi,
I realized that when I change the configuration of zenbot in live trading (I do a ctrl + c and I restart zenbot command line with a new configuration in which I change the parameters, RSI, MACD, etc ...), the threshold defined with sell_stop_pct does not work.
I think the bought price is not recorded which explains this operation.
My question: Is this normal ? Is there a way to update the zenbot configuration and keep the sell_stop_pct active?
Regards,

**Comment by defkev** [comment]
> Is this normal ?

Yes, almost all of the metrics triggering possible stops (loss, slippage, profit, etc) are generated during runtime so the moment you quit and restart, the bot "forgot" everything.

One possible solution i was thinking about would be to store my_trades in mongo and reload it upon start to populate the necessary values if the selector/exchange is in my_trades.

A possible problem with this would be that we might don't want to do just that.

e.g. if you only intent to change a setting or update the bot and then restart it would be desirable to have our previous metrics retained but if the bot has been stopped for a couple of hours/days and the market moved considerably the bot might end up stuck in a dead end not being able to do anything.

Maybe something like a `--reset_metrics` switch...

**Comment by defkev** [comment]
Looks like we are already saving my_trades to mongo...let me cook something up as this would be indeed useful.

**Comment by ghost** [comment]
Thanks a lot for your answers.
I'm not a developer (my javascript is pretty bad!) But let me know if I can help.
I'm still going to take a look on my side.

**Comment by defkev** [comment]
I already got a PR ready, just testing it for a couple of hours to make sure i didn't break anything.

**Comment by defkev** [comment]
Done.

Note that this is an opt-in so you will have to explicitly enabled it either on the cmd or in conf.js

I try to avoid changing the default behavior as some might prefer it the way it is.

**Comment by ghost** [comment]
Very cool ! Thank you for your responsiveness !
I test it as soon as possible :-)
Thank you

**Comment by ghost** [comment]
Hi all,
Today I had proof that it does not work as expected.
I'm even wondering if my sell_stop_pct thresholds work even if I do not update the configuration.
I have verified that my trades are saved in the my_trades collection without apparent problems.
What are the things to check please?
Best regards,

**Comment by defkev** [comment]
> that it does not work as expected

What exactly "does not work"?
I am running this for a couple of weeks on multiple bots by now and haven't seen any oddities so far.

The change is fairly straight forward by simply loading previous trades in absence of a last trade to maintain a kind of persistence between session, it doesn't touch anything outside this scope.

**Comment by ghost** [comment]
The sell stop is not triggered when I update the configuration after the purchase.

I am testing actually if the sell stop works correctly when I do not update the configuration because I have a big doubt about it.

What should I check? The trades made are well written in the my_trades collection.
