### ISSUE TITLE
IFTTT  notifical

### ISSUE THREAD

**Issue by tontheonelove** [DeviaVir/zenbot#1244]
How to Config IFTTT Notifical for buy & sale   
 i  try it  is not send Notifical to my email 

Please give me you  Tutorial  

Thankyou..

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
