### ISSUE TITLE
Trade more frequent issue

### ISSUE THREAD

**Issue by shusunny** [DeviaVir/zenbot#125]
I tried to make the bot trading more frequent, but when I changed the default_logic.js here
`      rs.check_period = '1m' // speed to trigger actions at` 
I want to change 1m to 10s
Then the bot seems not calculate any more, its reporter gives same total amount and ROI with different trade price.

Can anyone give advices how to set the bot to make it check trigger every 10 sec and trade every minute.

Thx!

**Comment by alternativesurfer** [comment]
Check period and RSI can only be dropped to 1m.
You need to edit the min amount of time between trades.

**Comment by carlos8f** [comment]
Cleaning up 3.x issues
