### ISSUE TITLE
zenbot not triggering trades

### ISSUE THREAD

**Issue by leftoverramen** [DeviaVir/zenbot#1255]
The issue is that during live and paper trading the bot does not attempt to buy or sell. However, during simulations with the stddev strategy, a high rate of trading (1185 in 11 days) is predicted. Also, I am able to trigger successful limit sells and buys through the bot in live trading mode with (s) and (b). Thus, I am confident that the API credentials are functioning properly. Additionally, when I add the --debug flag no error or warning messages are outputted.

Is it normal for a large number of trades to occur in simulations, but very few using the same settings during paper and live trading?

The commands I've been using
./zenbot.sh trade --paper
./zenbot.sh trade

I thought this one would make some action but it did not.
./zenbot.sh trade --paper --stratagy rsi --oversold_rsi=45 --overbought_rsi=46

------------------------

### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX 10.13.2
- **Zenbot version**: 4
- **NodeJS version**:  8.9.4
- **Python version**: Not sure
- **Exact command to reproduce**:
./zenbot.sh trade --paper --stratagy rsi --oversold_rsi=45 --overbought_rsi=46

### Source code / logs
[paper.txt](https://github.com/DeviaVir/zenbot/files/1683760/paper.txt)

**Comment by laloch** [comment]
Hi, you have a typo in the `--strategy` parameter name. If you pass "--strat**a**gy", the parameter gets ignored and the default (trend_ema?) strategy is used instead.

**Comment by leftoverramen** [comment]
Thanks for catching that spelling error. So I recently had a few minutes to try the bot again, and now it doesn't work at all. When I have more time I'll try to get to the bottom of the recent problems and then update this post.

**Comment by leftoverramen** [comment]
Alright it seems to be working for now. I reinstalled mongodb and used docker. Oddly enough, I had to clone two separate copies of zenbot to get the first clone to work. However, now it seems to be trading as expected.
