### ISSUE TITLE
Error while running the docker image

### ISSUE THREAD

**Issue by nunoalc** [DeviaVir/zenbot#126]
Im running the default settings, and just changed the compose to use ETH-BTC, and also the config file looks like this:

// watch these exchanges
c.watch_exchanges = [
  //"bitfinex",
  "gdax",
  //"kraken",
  //"poloniex"
]

// selector for indicators, trading, etc
c.default_selector = "gdax.ETH-BTC"

// add selectors in the format "{exchange-slug}.{asset}-{currency}" to graph them
c.graph_selectors = [
  c.default_selector,
  "gdax.ETH-BTC",
  "gdax.ETH-USD"
]

// trade logic
c.logic = require('./default_logic')

the container still runs other commands and a bunch of logs are working, but in the middle, this error occurs several times:

mongodb_1       | 2017-03-17T14:05:10.663+0000 I NETWORK  [thread1] connection accepted from 172.17.0.4:46166 #113 (23 connections now open)
eth-btc_1       | { message: 'request timestamp expired' }
eth-btc_1       | 03/17/2017 02:06:03 PM UTC [ERROR] non-200 status from exchange: 400
eth-btc_1       | /app/node_modules/numbro/numbro.js:1111
eth-btc_1       |         var parts = x.toString().split('.');
eth-btc_1       |                      ^
eth-btc_1       | 
eth-btc_1       | TypeError: Cannot read property 'toString' of undefined
eth-btc_1       |     at multiplier (/app/node_modules/numbro/numbro.js:1111:22)
eth-btc_1       |     at /app/node_modules/numbro/numbro.js:1127:22
eth-btc_1       |     at Array.reduce (native)
eth-btc_1       |     at correctionFactor (/app/node_modules/numbro/numbro.js:1125:21)
eth-btc_1       |     at cback (/app/node_modules/numbro/numbro.js:1230:34)
eth-btc_1       |     at Array.reduce (native)
eth-btc_1       |     at Numbro.divide (/app/node_modules/numbro/numbro.js:1233:48)
eth-btc_1       |     at /app/default_logic.js:165:43
eth-btc_1       |     at Immediate.doNext (/app/node_modules/zenbrain/utils/apply_funcs.js:10:12)
eth-btc_1       |     at runCallback (timers.js:666:20)

PS: the ' ^ ' in the logs above is pointing at ' x. '

**Comment by boxofdeath** [comment]
I'm having the same issue as well. I am not using Docker.

**Comment by burnzzz** [comment]
same here inside docker

**Comment by adm-github** [comment]
you're using twice the same selector in c.graph_selectors:
```
c.graph_selectors = [
c.default_selector,
"gdax.ETH-BTC",
"gdax.ETH-USD"
]
```
since c.default_selector is already gdax.ETH-BTC. try remove the second item
```
c.graph_selectors = [
c.default_selector,
"gdax.ETH-USD"
]
```

**Comment by carlos8f** [comment]
Cleaning up 3.x issues
