### ISSUE TITLE
Could someone be amazing, adding BTC-e support!?

### ISSUE THREAD

**Issue by MrSiNiSt3R** [DeviaVir/zenbot#127]
Kudo's for the one!

**Comment by nedievas** [comment]
I could but have suspended account:(

**Comment by MrSiNiSt3R** [comment]
Hi man,

Register new one, on BTC-e you only need name and e-mail, easy peasy registration

oh and besides this might help:  https://github.com/voltsonic/btce-public-v3 <https://github.com/voltsonic/btce-public-v3>

**Comment by carlos8f** [comment]
I'd like to add BTC-e for Zenbot 4. Maybe for 4.1.
