### ISSUE TITLE
Backfill slow. 

### ISSUE THREAD

**Issue by station384** [DeviaVir/zenbot#1271]
Branch: unstable

Backfill passes in 1970 as the starting date on every call for retrieval of data.

Backfill is also taking up excessive memory during processing,  I observed spikes of 800megs, old version didn't exceed 120 megs during import. Seems there is a memory leak.

**Comment by xdien** [comment]
I am also experiencing the same problem. gdax, binance backfill is fast, hitbtc very slow. Binance has problems #1281 
`zenbot backfill binance.LTC-USDT --days 15`

> *************************
> Hitting up the exchange 'binance' for trades within the past 15 days.
> *************************
> Backfilling...
> 500 trades processed so far. The most recently processed trade happened 19 minutes ago.
> final trade id ==> [undefined]

**Comment by station384** [comment]
Backfill time has improved since this post.  Closing.
