### ISSUE TITLE
problem with large MA

### ISSUE THREAD

**Issue by masterlj01** [DeviaVir/zenbot#1282]
Hello
i'm using a self defined model, which operates on 1h periods. however the requires larger MAs of close prices as important references.  for instance,  the value of SMA(1 YEAR) is necessary and such larger average numbers are often used in many models .  It seems that,  if i use 1h period, the engine has to "lookback" by going through all detailed transaction data of the hole year in order to get this average number and it couldn't go though even with  my i7 + 16g memory, as the resources exhausted.  i think it muss be some other possibilities to calculate those larger average numbers in Runtime, because the details of transactions are in this case not useful.  i'd very appreciate , if somebody can help me at this point. Thanks a lot !
james

**Comment by abduegal** [comment]
you could probably change the sma indicator. in a way that it caches the previous value. An SMA is the average of the closes prices. So if this is the SMA code:
```
module.exports = function container (get, set, clear) {
  return function sma (s, key, length, source_key) {
    if (!source_key) source_key = 'close'
    if (s.lookback.length >= length) {
      let SMA = s.lookback
        .slice(0, length)
        .reduce((sum, cur) => {
          return sum + cur[source_key]
        }, 0)

      s.period[key] = SMA / length
    }
  }
}
```

you probably need to change it to something like: 
```
if (s.lookback[0] && !s.lookback[0].key) { 
  if (s.lookback.length >= length) {
      let SMA = s.lookback
        .slice(0, length)
        .reduce((sum, cur) => {
          return sum + cur[source_key]
        }, 0)

      s.period[key] = SMA / length
    }
} else {
      s.period[key] = (s.lookback[0] * (length - 1) + s.period.close) / length
}
```

I just printed my thought in here, so I'm not sure if it would work. but after some debugging it should probably work. This way you only need to add the latest close to the previous sma, which is waaay much faster. Only the first one will take a while though, but that is better than having this executed every trade zenbot receives.

**Comment by masterlj01** [comment]
thanks very much for the quick reply! I understand what you mean,  but i think the problem is not how fast the function SMA can work. no matter which way man choose to calculate, he needs to know the close value of EACH period. and the only way seems to me to fetch those data is to run backfill in a simulation, otherwise you always get 'undefined' return, because s.lookup dosen't have the data.  Now even if I do nothing in onPeriod function in a strategy but just simply give a return.  the Sim Engine just can not hold on for more than 150 days on period of 1h sim and gets gradually exhausted...  the engine saves all details of every Transaction.

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
