### ISSUE TITLE
Binance: error: getTrades() returned duplicate results

### ISSUE THREAD

**Issue by phatwila** [DeviaVir/zenbot#1287]
Getting the following while attempting a backfill on Binance. GDAX seems fine though. Running the latest unstable branch.

```
[root@cpaneldev zenbot]# ./zenbot.sh backfill binance.TRX-BTC --days 10
Fall back to sample-conf.js, Error: Cannot find module './conf'

skipping 170 hrs of previously collected data

binance.TRX-BTC saved 3507 trades 3 days left
.
error: getTrades() returned duplicate results
{ product_id: 'TRX-BTC', from: 1517601470855 }
{ product_id: 'TRX-BTC', from: 1517601470855 }
[root@cpaneldev zenbot]# ./zenbot.sh backfill binance.TRX-BTC --days 10
Fall back to sample-conf.js, Error: Cannot find module './conf'

skipping 170 hrs of previously collected data

binance.TRX-BTC saved 3504 trades 3 days left
.
error: getTrades() returned duplicate results
{ product_id: 'TRX-BTC', from: 1517601470855 }
{ product_id: 'TRX-BTC', from: 1517601470855 }
[root@cpaneldev zenbot]# ./zenbot.sh backfill binance.LTC-BTC --days 10
Fall back to sample-conf.js, Error: Cannot find module './conf'
..
error: getTrades() returned duplicate results
{ product_id: 'LTC-BTC', from: 1516986114209 }
{ product_id: 'LTC-BTC', from: 1516986114209 }
[root@cpaneldev zenbot]# ./zenbot.sh backfill gdax.LTC-BTC --days 10
Fall back to sample-conf.js, Error: Cannot find module './conf'

gdax.LTC-BTC saved 100 trades 10 days left
..................................................................................................

```

**Comment by fhassoun** [comment]
i just reinstalled ubuntu, udated all to latest versions, installed zenbot as described here. and still get same error for binance either when trading or backfilling:
backfilling:
./zenbot.sh backfill binance.icx-eth --days 1
.
error: getTrades() returned duplicate results
{ product_id: 'ICX-ETH', from: 1517910523704 }
{ product_id: 'ICX-ETH', from: 1517910523704 }

trading:
./zenbot.sh trade binance.icx-eth  
fetching pre-roll data:
.
error: getTrades() returned duplicate results
{ product_id: 'ICX-ETH', from: 1517910222297 }
{ product_id: 'ICX-ETH', from: 1517910222297 }


in trade if i keep it running it shows some trades but timestamps are about 2 hours back, it will initiate a buy/sell order and then just sits there untill canceled

**Comment by dakreepy1** [comment]
getting the same results here too on binance.  Thought it could be my database, so i dumped it and tried again, same results.

**Comment by djpirra** [comment]
Any news on this? Having the same issue with Binance.

**Comment by klahaeck** [comment]
Same issue here. Also dumped database, and same error.

**Comment by rummand** [comment]
Same issue here. Also dumped DB, and same error. I see the error on..:

- hitbtc
- poloniex
- binance

**Comment by xFFFFF** [comment]
And I too. Gdax working fine. Binance not.

**Comment by fhassoun** [comment]
still same problem with latest version.
