### ISSUE TITLE
No trades found for gdax after bakfilling

### ISSUE THREAD

**Issue by simclem77** [DeviaVir/zenbot#1292]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**:
No, vanilla

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04

- **Zenbot version**:
Zenbot4

- **NodeJS version**: 
8.9.4

- **Python version**:
2.7.12

- **Exact command to reproduce**:

> ./zenbot.sh backfill gdax.BTC-EUR --days 1
> ./zenbot.sh sim gdax.BTC-EUR --days 1 

### Describe the problem
After backfilling trades for one of gdax selectors, simulation doesn't work. It returns:

> no trades found! try running 'zenbot backfill gdax.BTC-EUR' first

**Comment by adamnmcc** [comment]
Having a similar issue. it will only find trade data from a live trade run.

**Comment by station384** [comment]
See #1290

**Comment by simclem77** [comment]
Thanks @station384 but I'm not sure the issue is the same. In my case the bakfilling works fine and I've tons of trades in mongo db (trades) but it's like simulation doesn't find them.

**Comment by station384** [comment]
Really it wasn’t the issue, it was my comments on the issue i was meaning to reference 

There was a merge that removed the simulation field on backfill inserts,  if your using that version the symptoms show up as backfill executes,  records get added to trade.db but you can’t select then using {selector:<exchange>.<asset-currency>},

**Comment by simclem77** [comment]
@station384 You're totally right. I've juste updated my zenbot to last unstable and backfilling and simulation works just fine now.

**Comment by krystophv** [comment]
Can this be closed?
