### ISSUE TITLE
Cex.io Buy don't buy on exchange

### ISSUE THREAD

**Issue by philinformatique** [DeviaVir/zenbot#1301]
Hi, when I place buy in live trading (not in paper.. :P ) its don't place a buy on exchange Cex.io, my API right are all on on Cex, and on zenbot 4.1.0 it say I'have bought but nothing :/

------------------------

### System information
- **OS Platform and Distribution: Ubuntu 16.04
- **Zenbot version**: 4.1

**Comment by philinformatique** [comment]
when I'm trying to do manual trade *

**Comment by juosma** [comment]
Hi,
Can You check settings buy_pct and sell_pct are it set on 99? If not try set and check again.

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
