### ISSUE TITLE
Error('invalid bucket size spec: ' + spec);

### ISSUE THREAD

**Issue by Dijkstra173** [DeviaVir/zenbot#1303]
Hello,

On docker container since the last upgrade I've this error : 

root@cloud:/home/docker/zenbot# docker-compose up
Starting zenbot_mongodb_1 ... done
Starting zenbot_server_1 ... done
Attaching to zenbot_mongodb_1, zenbot_server_1
server_1   | /app/node_modules/timebucket/lib/bucket-size.js:15
server_1   |   if (!match) throw new Error('invalid bucket size spec: ' + spec);
server_1   |               ^
server_1   |
server_1   | Error: invalid bucket size spec: undefined
server_1   |     at BucketSize.parse (/app/node_modules/timebucket/lib/bucket-size.js:15:21)
server_1   |     at new BucketSize (/app/node_modules/timebucket/lib/bucket-size.js:5:21)
server_1   |     at Bucket.resize (/app/node_modules/timebucket/lib/bucket.js:30:14)
server_1   |     at Command.<anonymous> (/app/commands/trade.js:361:30)
server_1   |     at Command.listener (/app/node_modules/commander/index.js:315:8)
server_1   |     at emitTwo (events.js:126:13)
server_1   |     at Command.emit (events.js:214:7)
server_1   |     at Command.parseArgs (/app/node_modules/commander/index.js:653:12)
server_1   |     at Command.parse (/app/node_modules/commander/index.js:475:21)
server_1   |     at /app/zenbot.js:53:13

**Comment by Shawn8901** [comment]
try to give a --period_length as param or specify it in your config. p.e --period_length=1h

**Comment by Dijkstra173** [comment]
It's work, Thank you
