### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by Netzarim** [DeviaVir/zenbot#1304]
Post Ubuntu updates 2 days ago:

/root/zenbot/node_modules/sosa_mongo/mongo_backend.js:33
      var tmp_obj = JSON.parse(JSON.stringify(obj))
                                    ^
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Object.save (/root/zenbot/node_modules/sosa_mongo/mongo_backend.js:33:37)
    at withHooks (/root/zenbot/node_modules/sosa/api.js:68:15)
    at Object.save (/root/zenbot/node_modules/sosa/api.js:65:12)
    at /root/zenbot/commands/trade.js:586:22
    at /root/zenbot/lib/engine.js:220:9
    at /root/zenbot/extensions/exchanges/gdax/exchange.js:281:11
    at Request._callback (/root/zenbot/node_modules/gdax/lib/clients/public.js:64:9)
    at Request.self.callback (/root/zenbot/node_modules/gdax/node_modules/request/request.js:188:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/root/zenbot/node_modules/gdax/node_modules/request/request.js:1171:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/root/zenbot/node_modules/gdax/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by Shawn8901** [comment]
confirming; this happens for me after a fresh unstable checkout.
It has to be somewhere between c31a6ae292edf4b66f803ec7455e1421b74c302e (was my last commit i running for my installation) and most recent commit.
the error is thrown right after the backfill and preroll is finished

edit: okay i dropped my old mongo database, and after refilling data everything was fine. So, somehow it smells like a breaking change.

**Comment by Netzarim** [comment]
I dropped the database and reran - it was not fine... same problem

**Comment by jasonchuanet** [comment]
I was getting the same error but I was able to get zenbot work by dropping the "--conf" argument. Zenbot seems to pick on my ./conf.js by default so specifying a conf file from the command line was a bit redundant.

**Comment by Netzarim** [comment]
yes, it appears to be an issue with the --conf argument... which is not good, because I have 4 of these running at the same time and use separate conf files to use different api keys on the same exchange.  So, without the --conf command, I will only be able to run one trading pair on an exchange at a time.

**Comment by defkev** [comment]
Just for clarification.

`conf.js` is parsed in place of `conf-sample.js`
`--conf` is used to override stuff in `conf.js/conf-sample.js`

So copying `conf-sample.js` to `conf.js` and parsing it using `--conf conf.js` is redundant.

@Netzarim dump the content of `obj `to get an idea what "circular structure" he's complaining about.

**Comment by krystophv** [comment]
Latest updates remove the `sosa-mongo` dependency and now use the mongodb driver directly. The issue you're having is in trying to save the `session`. I'd be interested in which property eventually has a reference to an internal property as well.

**Comment by narentin** [comment]
`sosa-mongo` dependency is not completly removed. I see it in db/createCollection.js. Anyway, I guess the property which has a reference to an internal property is: `obj.options.db`. This property is populated when `--conf` option is given on the command line.

**Comment by krystophv** [comment]
The latest `unstable` doesn't have a `db` directory - it was fully removed.

**Comment by narentin** [comment]
Right, I've updated my tree. `sosa-mongo` is now gone.

However, I still have the same kind of exception:
error saving session
Error: cyclic dependency detected

serializeObject (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:296)
serializeInto (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:776)
serializeObject (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:308)
serializeInto (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:776)
serializeObject (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:308)
serializeInto (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:776)
serializeObject (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:308)
serializeInto (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:776)
serializeObject (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:308)
serializeInto (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:776)
serializeObject (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:308)
serializeInto (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:776)
serializeObject (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:308)
serializeInto (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:776)
serializeObject (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:308)
serializeInto (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:776)
serializeObject (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:308)
serializeInto (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:776)
serializeObject (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:308)
serializeInto (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:776)
serializeObject (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:308)
serializeInto (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:776)
serializeObject (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:308)
serializeInto (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:776)
serializeObject (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:308)
serializeInto (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:776)
serializeObject (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:308)
serializeInto (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:618)
serializeObject (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:308)
serializeInto (c:\src\zenbot\node_modules\bson\lib\bson\parser\serializer.js:776)
serialize (c:\src\zenbot\node_modules\bson\lib\bson\bson.js:58)
Query.toBin (c:\src\zenbot\node_modules\mongodb-core\lib\connection\commands.js:141)
serializeCommands (c:\src\zenbot\node_modules\mongodb-core\lib\connection\pool.js:1050)
Pool.write (c:\src\zenbot\node_modules\mongodb-core\lib\connection\pool.js:1230)
executeWrite (c:\src\zenbot\node_modules\mongodb-core\lib\wireprotocol\3_2_support.js:80)
WireProtocol.update (c:\src\zenbot\node_modules\mongodb-core\lib\wireprotocol\3_2_support.js:95)
Server.update (c:\src\zenbot\node_modules\mongodb-core\lib\topologies\server.js:790)
update (c:\src\zenbot\node_modules\mongodb\lib\topologies\topology_base.js:318)
updateDocuments (c:\src\zenbot\node_modules\mongodb\lib\collection.js:1020)
save (c:\src\zenbot\node_modules\mongodb\lib\collection.js:1270)
executeOperation (c:\src\zenbot\node_modules\mongodb\lib\utils.js:408)
Collection.save (c:\src\zenbot\node_modules\mongodb\lib\collection.js:1261)
(anonymous function) (c:\src\zenbot\commands\trade.js:581)
syncBalance (c:\src\zenbot\lib\engine.js:207)
saveSession (c:\src\zenbot\commands\trade.js:527)
(anonymous function) (c:\src\zenbot\commands\trade.js:677)
end (c:\src\zenbot\node_modules\run-series\index.js:8)
done (c:\src\zenbot\node_modules\run-series\index.js:11)
each (c:\src\zenbot\node_modules\run-series\index.js:16)
runCallback (timers.js:789)
tryOnImmediate (timers.js:751)
processImmediate (timers.js:722)
[ Immediate ] (Unknown Source:undefined)
init (inspector_async_hook.js:22)
emitInitNative (async_hooks.js:472)
emitInitScript (async_hooks.js:388)
Immediate (timers.js:816)
createImmediate (timers.js:858)
setImmediate (timers.js:845)
withOnPeriod (c:\src\zenbot\lib\engine.js:922)

Certainly for the same reason, `db` property is added to `session.options` when `--conf` parameter is given. This property is not here when `--conf` is not given.

**Comment by krystophv** [comment]
With some help I was finally able to reproduce this locally. It turns out that `boot` was written in a way that you couldn't use the `--conf="someconf.js"` argument format (had to be `--conf someconf.js`). I'll try to get a working fix tomorrow.
