### ISSUE TITLE
getTrades() returned duplicate results not solved

### ISSUE THREAD

**Issue by glennfu** [DeviaVir/zenbot#1317]
@defkev I saw you put in: https://github.com/DeviaVir/zenbot/commit/439a024c05284e1a671019a4b4e55fd0f45fa2c0

But as of today, on `unstable`, running this: `./zenbot.sh backfill binance.EOS-BTC --days=1` results in:
```
skipping 23 hrs of previously collected data

binance.EOS-BTC saved 3478 trades 1 days left
.
error: getTrades() returned duplicate results
{ product_id: 'EOS-BTC', from: 1518290027202 }
{ product_id: 'EOS-BTC', from: 1518290027202 }
```

So it looks like it's still not solved.

**Comment by Shawn8901** [comment]
The issue for that is also still open! #1287 ....

**Comment by defkev** [comment]
Contrary to my initial assumption this isn't related to dupes but most likely exchange specific.
