### ISSUE TITLE
working version for Binance and Kraken both exhanges not working in live mode

### ISSUE THREAD

**Issue by juosma** [DeviaVir/zenbot#1320]
Hello friends,
posting first time sorry if in not right format.

I trying find working version from mine exchanges Kraken and Binance.
started one week ago, during these time get lot of experience, and spend probably more time than some developers till created these nice bot. 
have tried many versions of unstable, stable as I understand impossible to install at all.
launch more than 1000 simulations some of it very promising even with Forex_analytics strategy. 
as I understand bot mostly oriented  in to GDAX, bitrex and Poloniex, but there i can't get accounts ;(

### System information
- **OS Platform and Distribution   testing on Ununtu 16.04 machine.  
- **Zenbot version**:  -            v4.1.0  latest my tested build (by65zjhv7evagf9hvrhe2rb) bu there was many earlier - everywhere te same problem for (Kraken)  but the same on (greenkeeper/jasmine-3.0.0)
- **NodeJS version**:             v8.9.4
- **Python version**:                probably v2.7.12
- **Exact command to reproduce**:       Trade (for binance + backfill)
 
 ### Describe the problem
Issues what I have:
1. Kraken:
I live mode (.\zenbot.sh trade)
when I push "B" or "b" - nothing happens not buying and even not provide any error or log.
But when i push "S" or "s" - working well. And probably bot will not buy in automatic mode have let work for 6 hours - no one purchase, just sales.
one strange thing In --paper mode everything working well
have read documentation and do changes regarding timeout  in Kraken-api

2. Binance:

Probably known issue when not working backfill (duplicated record)

error log
error: getTrades() returned duplicate results
{ product_id: 'LTC-USDT', from: 1517149577130 }
{ product_id: 'LTC-USDT', from: 1517149577130 }

binance really interesting because theys fee are litle (0.1%) and after sytem upgra they sicounted 70% more for limited time till 24 february. ( we can make good profit ;) )

**Comment by Shawn8901** [comment]
see #1317, #1307   and #1287  for your report for binance

**Comment by juosma** [comment]
thanks,
already found for binance - backfill are working.
but looks like Manually buy also not working on binance also, but looks like once i had successes to buy, with market, but after no one time, but sell working well, just sell limit are problem but maybe reason that binance have changed fees talking something about order cost = ammount *shaould be > (.... "code, -1013, msg : filter failure MIN NOTIONAL. But market working and looks like in binance no differense  maker or taker.
