### ISSUE TITLE
Codemap off

### ISSUE THREAD

**Issue by 57ar7up** [DeviaVir/zenbot#1334]
Is there debug switch which will turn it off?
At least message spam in console

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
