### ISSUE TITLE
Question about config params

### ISSUE THREAD

**Issue by jerson** [DeviaVir/zenbot#1344]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu  17.10
- **Zenbot version**: unstable branch #7d773cc769bf8129a643f9e2defe9852474042ec
- **NodeJS version**:  9.4
- **Python version**: 2.7 - 3.6
- **Exact command to reproduce**:

just start zenbot in paper mode with binance IOTA-ETH

### Describe the problem
Hi, maybe it's a silly question, but I'd like your help please
what is the variable that allows me to sell in this situation:

1. start bot in paper mode or real mode
2. bot buy 1 eth
3. the value goes up 5%
4. the value drops 1% (bot should sell)
5. At that time bot should sell - but currently the bot expects to lower more to sell and generates less profit

### Source code / logs
just default config mode

```js
// Optional stop-order triggers:

// sell if price drops below this % of bought price (0 to disable)
c.sell_stop_pct = 0
// buy if price surges above this % of sold price (0 to disable)
c.buy_stop_pct = 0
// enable trailing sell stop when reaching this % profit (0 to disable)
c.profit_stop_enable_pct = 0
// maintain a trailing stop this % below the high-water mark of profit
c.profit_stop_pct = 1

// Order execution rules:

// avoid trading at a slippage above this pct
c.max_slippage_pct = 5
// buy with this % of currency balance (WARNING : sim won't work properly if you set this value to 100)
c.buy_pct = 99
// sell with this % of asset balance (WARNING : sim won't work properly if you set this value to 100)
c.sell_pct = 99
// ms to adjust non-filled order after
c.order_adjust_time = 5000
// avoid selling at a loss below this pct set to 0 to ensure selling at a higher price...
c.max_sell_loss_pct = 25
// ms to poll order status
c.order_poll_time = 5000
// ms to wait for settlement (after an order cancel)
c.wait_for_settlement = 5000
// % to mark down buy price for orders
c.markdown_buy_pct = 0
// % to mark up sell price for orders
c.markup_sell_pct = 0
// become a market taker (high fees) or a market maker (low fees)
c.order_type = 'maker'
// when supported by the exchange, use post only type orders.
c.post_only = true

```

**Comment by defkev** [comment]
> 3. the value goes up 5%
> 4. the value drops 1% (bot should sell)

Thats still a ~4% hold profit.

**Comment by jerson** [comment]
@defkev  you are right but that would be the ideal case, currently it is lower than 5%

**Comment by Shawn8901** [comment]
What you describe sounds like a strategy for me, on my opinion you can not get such behaviour without a strategy. The parameter you referring are handled outside strategy advises

**Comment by jerson** [comment]
@Shawn8901 exactly, but I'm not so expert in strategies, you know some strategy that allows me to do that in order to investigate about it. Thank you

**Comment by Shawn8901** [comment]
@jerson i dont know any strategy buildin zenbot which works like that, but it should be easy to achieve this with basic Scripting Knowledge

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
