### ISSUE TITLE
Poloniex Configuration

### ISSUE THREAD

**Issue by simonyipeter** [DeviaVir/zenbot#135]
Hi Everyone!

I'm newbie in automated trading.
I installed the zenbot working well only on GDAX.
But I tried to modify the configuration for poloniex trading and it was failed:
"No trader API key provided"
I used this topic:
https://github.com/carlos8f/zenbot/issues/110

I'm planning to reinstall the zenbot and then reconfigure.
Could you send me a step by step instructions for poloniex?

Thanks in advance
Peter

**Comment by DeviaVir** [comment]
You'll need to check the box that says "Enable trading":
![screenshot_2017-06-03_07-29-46](https://cloud.githubusercontent.com/assets/777823/26750951/73a49188-482e-11e7-8960-f1d806c0d817.png)

Will be closing this due to its age, but feel free to comment if this is still an issue for you.
