### ISSUE TITLE
Darwin simulation fail

### ISSUE THREAD

**Issue by gbarac** [DeviaVir/zenbot#1350]
Run from zenbot folder.
 ./scripts/genetic_backtester/darwin.js --selector=gdax.ETH-USD --days=1 --currency_capital=200 --use_strategies=trend_ema --population=1 --order_type=maker
generation 0 works
generation 1 hangs.
If I restart, generation 1 works, generation 2 hangs... and so on

here it is the complete log

--==Zenbot 4 Genetic Backtester v0.2.2==--
Thu, 15 Feb 2018 21:48:52 GMT

Backtesting strategy trend_ema ...

Creating population of 1 ...

=== Simulating generation 0 ===

Backfilling (might take some time) ...
./zenbot.sh backfill --days=1 gdax.ETH-USD

1: 92.7% ETA: 0m 0s
Done: 1, Active: 0, Remaining: 0, Completion: 100.0% Best Balance(1): 216.6642

Generation 0 completed at 2018-02-15 16:49:03, took 0m 6s, results saved to:
> Finished writing generation csv to simulations/backtest_201802151648/gen_0/results.csv
> Finished writing generation json to simulations/backtest_201802151648/gen_0/results.json

Generation's Best Results
(trend_ema) Result Fitness -0.019251103272757464, VS Buy and Hold: -1.0% BuyAndHold Balance: 218.770003  End Balance: 216.664221, Wins/Losses 1/0, ROI 0.000000.
./zenbot.sh sim gdax.ETH-USD --avg_slippage_pct=0.045 --backtester_generation=1 --buy_stop_pct=13 --help=false --markdown_buy_pct=-0.11962423193481575 --markup_sell_pct=1.4299431888060203 --max_sell_loss_pct=25 --max_slippage_pct=5 --min_periods=93 --neutral_rate=auto --order_type=maker --oversold_rsi=26 --oversold_rsi_periods=15 --period=39m --period_length=39m --profit_stop_enable_pct=4 --profit_stop_pct=15 --rsi_periods=15 --sell_stop_pct=31 --strategy=trend_ema --trend_ema=20 --version=false --start=201802131900 --asset_capital=undefined --currency_capital=200

=== Simulating generation 1 ===

Backfilling (might take some time) ...
./zenbot.sh backfill --days=1 gdax.ETH-USD

Generation 1 completed at 2018-02-15 16:49:04, took 0m 0s, results saved to:
Error: ENOENT: no such file or directory, open 'simulations/backtest_201802151648/gen_1/results.csv'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1291:33)
    at saveGenerationData (/root/zenbot/scripts/genetic_backtester/darwin.js:995:8)
    at parallel (/root/zenbot/scripts/genetic_backtester/darwin.js:1163:5)
    at end (/root/zenbot/node_modules/run-parallel-limit/index.js:17:15)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Resume this backtest later with:
./scripts/genetic_backtester/darwin.js --selector=gdax.ETH-USD --days=1 --currency_capital=200 --use_strategies=trend_ema --population=1 --order_type=maker --population_data=backtest_201802151648

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
