### ISSUE TITLE
Live doesn't update price the way that sim does on an existing order

### ISSUE THREAD

**Issue by glennfu** [DeviaVir/zenbot#1351]
In sim, if your signal is to buy, engine will call `executeSignal`, place an order, and then on every quote between periods it will keep calling `executeSignal`, `doOrder`, and `placeOrder`.

In live, engine will call `executeSignal`, place an order, and then on every quote between periods it will call `checkOrder`, but never `executeSignal`.

`executeSignal => syncBalance => getQuote` is where `price` gets set. In live, this isn't getting called, so the `order.price` can't update.

@krystophv @DeviaVir I could definitely use your help on this! I think this might be the source of why live/sim can get different results.

**Comment by krystophv** [comment]
`doOrder`'s callback to `placeOrder` takes a flag as the second argument that indicates that an order hasn't completed. If the order needs to be adjusted due to the price calculated in `checkOrder`, it will call `cancelOrder`, which returns to the callback with `null` or `false`, indicating that `placeOrder` should then call `executeSignal`.

**Comment by krystophv** [comment]
Here is where `checkOrder` is going to figure out if it needs to cancel the current order or not: https://github.com/DeviaVir/zenbot/blob/unstable/lib/engine.js#L358 if it never cancel's the order, then the condition is always false.

**Comment by glennfu** [comment]
OK I see. I had changed `marked_price = api_order.price` based on our conversation in Discord. So then I still don't know what to do here.

Reverting my change still leaves the problem of the fact the order gets canceled even if the price hasn't changed from the existing order.

**Comment by glennfu** [comment]
I'm going to re-open a new issue reflecting the original problem I was trying to solve.
