### ISSUE TITLE
/logs Internal Server Error

### ISSUE THREAD

**Issue by jeremyloe** [DeviaVir/zenbot#136]
Does anyone else get an Internal Server Error when trying to view the http://IPADDRESS:3013/logs page from another machine on the same network? The candlestick page loads and functions just fine remotely, but oddly not the logs page.

**Comment by tuxitor** [comment]
Copy the secret from the log and paste it to the end of the URL like this:
http://ipaddress:3013/logs?secret=blahblahblah

I It worked for me when I did that

**Comment by jeremyloe** [comment]
Yep, that works. Thanks!
