### ISSUE TITLE
Disable the need for secret when accessing trade bot / Change secret to known value

### ISSUE THREAD

**Issue by Krono5** [DeviaVir/zenbot#137]
Is there a way to permanantly disable the need for a secret when accessing the logs through the http://IP:3013?  My bot is running as a screen instance on a separate machine, and it is becoming tedious to constantly search for the secret.  Or if there is a way to set it to a fixed value seeing as my bot is on local network only.

**Comment by nedievas** [comment]
It's one time search if you don't remove db.

**Comment by Krono5** [comment]
I realize, but with frequent system restarts, and the service running in the backround, it would be convenient to always know what the secret would be.

**Comment by tuxitor** [comment]
It would be nice to have a link on the graph screen pointing to the log. Which brings another question. How is it possible to expose data from the trader to the web screen?

It could be useful to see some of trading parameters on the graph screen. Notably RSI up, RSI down values along with the actual RSI value. Even better if it's possible to adjust the values on the fly, and possibly stop and start active trading trom the graph screen. It could be placed above the graph along with the pulldown menues.

**Comment by Krono5** [comment]
I have found the setting that you can change the secret to one that you wish.  In directory file:
      /zenbot/plugins/server/action.js

By changing the line:
       var secret = get_id()

to something of your choice, an example being:
      var secret = "this_is_your_secret"

will allow you to enter that secret every time when accessing the server such as:
      http://localhost:3013/?secret=this_is_your_secret


I know carlos mentioned that they were looking to create a way to do this in future releases, this might provide an easy solution with a simple setter.

**Comment by DeviaVir** [comment]
This is now no longer supported by zenbot 4.
