### ISSUE TITLE
Error after building forex.analytics on windows subsystem or linux - ubuntu

### ISSUE THREAD

**Issue by archaistvolts** [DeviaVir/zenbot#1370]
------------------------
### System information
WIndows 10 w/ subsystem for linux - ubuntu
No custom code
Zenbot4 fresh install
node v8.9.4 (windows and ubuntu subsystem)
- **Exact command to reproduce**: zenbot train --help

### Describe the problem
I couldn't get forex.analytics to build on windows even though I have some build tools installed and have been able to build such applications in the past (do I need MS build tools 15?) .  Anyway, I followed the ubuntu installation directions in the subsystem and was able get npm install to run to completion w/out any errors. 

### Source code / logs
Here is the output: 

```bash
C:\Users\Travis\Documents\Code\zenbot>node zenbot.js train --help
module.js:672
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: \\?\C:\Users\Travis\Documents\Code\zenbot\node_modules\forex.analytics\build\Release\analytics.node is not a valid Win32 application\\?\C:\Users\Travis\Documents\Code\zenbot\node_modules\forex.analytics\build\Release\analytics.node
    at Object.Module._extensions..node (module.js:672:18)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Travis\Documents\Code\zenbot\node_modules\forex.analytics\index.js:1:79)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
```

Do I need to install msbuild tools 15 and run npm install from windows to get this working?

**Comment by Shawn8901** [comment]
You need to build this c code, so you need a compiler installed. See thus pr which wants to update the faq https://github.com/DeviaVir/zenbot/pull/1226

**Comment by archaistvolts** [comment]
I found a work around.  Just run the command from the ubuntu subsystem terminal window.

**Comment by archaistvolts** [comment]
I have a c compiler and have been able to build other projects with npm install.  If you follow to #420 it is discussed below that you need to be using Visual Studio 2015.  I thought maybe that was the issue.

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
