### ISSUE TITLE
[genetic_backtester] "Error: invalid bucket size spec: undefined" when run completed

### ISSUE THREAD

**Issue by timstoop** [DeviaVir/zenbot#1371]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: No.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: The upstream Docker image
- **Zenbot version**: unstable branch, commit 74ec688a1b492f953a86a38d2e1f21424e561241
- **NodeJS version**: v8.9.4
- **Python version**: 2.7.9
- **Exact command to reproduce**: `PARALLEL_LIMIT=6 scripts/genetic_backtester/darwin.js --selector=kraken.XETH-ZEUR --days 1 --population 100 --use_strategies bollinger,cci_srsi,crossover_vwap,dema,macd,momentum,rsi,sar,speed,srsi_macd,stddev,ta_ema,ta_macd,ta_macd_ext,ta_ppo,ta_trix,ta_ultosc,trend_bollinger,trend_ema,trendline,trust_distrust,wavetrend`

### Describe the problem

After 1300 sims with the above command, at 58.5% of the entire run, I get the following error:

```
Error: invalid bucket size spec: undefined
    at BucketSize.parse (/app/node_modules/timebucket/lib/bucket-size.js:15:21)
    at new BucketSize (/app/node_modules/timebucket/lib/bucket-size.js:5:21)
    at Bucket.resize (/app/node_modules/timebucket/lib/bucket.js:30:14)
    at Object.actualRange (/app/scripts/genetic_backtester/darwin.js:79:56)
    at buildCommand (/app/scripts/genetic_backtester/darwin.js:310:35)
    at Array.cb (/app/scripts/genetic_backtester/darwin.js:1126:19)
    at each (/app/scripts/genetic_backtester/node_modules/run-parallel-limit/index.js:38:19)
    at /app/scripts/genetic_backtester/node_modules/run-parallel-limit/index.js:38:45
    at ChildProcess.proc.on (/app/scripts/genetic_backtester/darwin.js:374:5)
    at emitTwo (events.js:126:13)
Resume this backtest later with:
./scripts/genetic_backtester/darwin.js --selector=kraken.XETH-ZEUR --days 1 --population 100 --use_strategies bollinger,cci_srsi,crossover_vwap,dema,macd,momentum,rsi,sar,speed,srsi_macd,stddev,ta_ema,ta_macd,ta_macd_ext,ta_ppo,ta_trix,ta_ultosc,trend_bollinger,trend_ema,trendline,trust_distrust,wavetrend --population_data=backtest_201802181228/
```
This triggers every time. It might be related to #938, but I'm not entirely sure about that, as that does not reference the genetic_backtester.

**Comment by timstoop** [comment]
Further testing seems to indicate the problem is with ta_macd_ext...

**Comment by juosma** [comment]
hello 
i have the same error i see when use strategies:
dema;
bollinger;
trendline;
ta_trix;
ta_ppo;
ta_macd_ext;
ta_ultosc;
momentum;


I guess it uses specific calculation or units or method and when it be fixed it will all at once, but i dont have experience in coding :(
help pleassse ;) 

abd one different error when use, but probably should be simple somewhere need add or remove")(":
noop
SyntaxError: missing ) after argument list

**Comment by dakreepy1** [comment]
just had this happen to me.  As far as i can tell it was with ta_macd_ext as well.

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖

**Comment by kenorb** [comment]
Related: #938, #994
