### ISSUE TITLE
Put monetary limits on usage?

### ISSUE THREAD

**Issue by jasdjensen** [DeviaVir/zenbot#1373]
I was thinking about all the requests to be able to do multiple coin trades at once, and with that comes a lot of complexity.  

Not knowing all the ins and outs, this may not work in every situation but I was wondering if zenbot could use a limit of how much money it plays with?   

For example give your GDAX account 200 bucks.  Run 4 instances of zenbot, each responsible for 50 bucks.   It would start trading on 50 bucks, but track gains or losses and adjust accordingly.

This would also be nice if you just wanted to play with some of your money.. and not risk all of it at once.  You wouldn't have to change any 99% settings, just change an overall limit of how much of the total funds zenbot would be able to access.  So in that same example you could run 3 instances of zenbots at 50 bucks and still leave 50 bucks in your account, untouched.

**Comment by defkev** [comment]
Sounds like #1216

**Comment by rouis** [comment]
This issues can really help to minimize losses !!
