### ISSUE TITLE
WebUI javascript assets missing

### ISSUE THREAD

**Issue by rcoenen** [DeviaVir/zenbot#1374]
Cannot GET /assets-wp/plotly.bundle.js

webui broken in unstable GIT cec00f8

**Comment by defkev** [comment]
#1240 removes plotly in favor of echarts

**Comment by Shawn8901** [comment]
Do you have the web ui running in a subfolder? If yes check this pr https://github.com/DeviaVir/zenbot/pull/1377

@defkev  as i see that your pr was merged. can you please remove the prefix / again? see #1377  for the reason.

**Comment by defkev** [comment]
Nothing to change

#1344 was merged after #1240 and thus took care of it

**Comment by Marekkon5** [comment]
/assets-wp/echarts.bundle.js
/assets-wp/app.bundle.js

Unable to load. Pls help.

**Comment by defkev** [comment]
Review the output of `npm install` especially everything after `bundling WebApp components`

Also @DeviaVir mind closing this as #1240 has been merged.

**Comment by Marekkon5** [comment]
Uhh I dont have the output anymore. Is it possible to rebuild only the WebApp component? @defkev 

I am doing this on SBC so npm install takes  long time

**Comment by DeviaVir** [comment]
@Marekkon5 try running `node post_install.js` (https://github.com/DeviaVir/zenbot/blob/unstable/post_install.js)

**Comment by Marekkon5** [comment]
``
bundling WebApp components
/bin/sh: 1: webpack: not found
``

@DeviaVir so I am missing webpack... Tried npm install webpack and same.

**Comment by DeviaVir** [comment]
@Marekkon5 what does `which webpack` say?
Also, I think you should install `webpack-cli` and not just `webpack`

**Comment by Marekkon5** [comment]
- which webpack outputs nothing
- After Installation of cli - same

@DeviaVir Should I try installing with --global?

**Comment by Marekkon5** [comment]
Both webpack installed ok, after starting zenbot got dependecy error (numbro). Installed everything started ok, expect the WebUI. 
https://user-images.githubusercontent.com/15169286/37330691-3023fb44-26a2-11e8-964f-568560febca8.png

Any ideas @DeviaVir 
? Thanks

**Comment by Marekkon5** [comment]
EDIT: Fixed

**Comment by tecmusti** [comment]
@Marekkon5 how did you fix it?

**Comment by Marekkon5** [comment]
Installed webpack globally.
