### ISSUE TITLE
How can I ensure I always end with the money as ethereum 

### ISSUE THREAD

**Issue by abelardojarab** [DeviaVir/zenbot#1381]
Hi
Thanks for all this work

A question

* can I make bot to finish always with the money as crypto?

* if I just remove the —paper and I add my poloniex api key will zenbot will be fast enough to do the sell and buy 

I have only used Coinbase to sell and buy so I don’t understand how a trader bot works

Please if someone can guide me a bit please

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
