### ISSUE TITLE
Error: Cannot find module './conf', falling back to conf-sample

### ISSUE THREAD

**Issue by rcoenen** [DeviaVir/zenbot#1386]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**:
No

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04

- **Zenbot version**:
8bcd969 

- **NodeJS version**: 
v8.9.4

- **Python version**:
Python 2.7.12

- **Exact command to reproduce**:
./zenbot.sh trade --conf conf-GDAX-EUR-BTC.js 

### Describe the problem
Error: Cannot find module './conf', falling back to conf-sample

### Source code / logs
Sorry no idea how to do this

**Comment by defkev** [comment]
Means you have no conf.js in your root dir (`cp conf-sample.js conf.js` per README)

The message is solely informational, your --conf will get loaded prior to conf/conf-sample

We do it like this to fill up whats missing to get a "complete" config.

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
