### ISSUE TITLE
configuration option makes Zenbot crashes when Web UI is used

### ISSUE THREAD

**Issue by rcoenen** [DeviaVir/zenbot#1387]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**:
No

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04

- **Zenbot version**:
8bcd969 

- **NodeJS version**: 
v8.9.4

- **Python version**:
Python 2.7.12

- **Exact command to reproduce**:
Run bot like this works fine, commandline and web ui: `./zenbot.sh trade --min_periods=60 --trend_ema=30 --neutral_rate=0.25 `

Running it this way will let the bot work fine until you access the web ui, then the bit crashes immediately
`./zenbot.sh trade --period=2h --min_periods=60 --trend_ema=30 --neutral_rate=0.25 `

### Describe the problem
I was trying to setup a bot as per @krilson suggestion (see https://github.com/DeviaVir/zenbot/issues/189#issuecomment-342462041 ) and noticed that the bt crashes as soon as I invoke the web ui.  Removing `--period=2h`  seems to fix it 

### Source code / logs
Sorry no idea how to do this

**Comment by defkev** [comment]
> Crash

No error?

**Comment by rcoenen** [comment]
Just something along the lines of process ID xxxx terminated

**Comment by defkev** [comment]
I am afraid thats not enough, as i don't even know where to look at.

The only possible problem coming to my mind is that the bot tries to bind to an already used interface (yielding a EADDRINUSE error) causing it to terminate.

**Comment by izk8** [comment]
Wow, I haven't had any problems running it and I only set it up yesterday.
I will say that it would be awesome to see some basic tutorials on
different strategies.

One quick question: on periods, for example on the ta_ema, an option is
'period length, same as --period_length (default: 10m)'. Is this 10 minute
or 10 month? How did you find this answer (just so I can figure out how to
increase to 10 months in the future if I felt like it, just an example
timeframe)?

Thanks for all your work making this awesome!

ᐧ

Sincerely,


Isaac Thompson, Ph.D.

Principal Data Scientist @ Shaker
LinkedIn <http://www.linkedin.com/in/thompsonisaac> & Company Website
<https://www.shakercg.com/>

**Comment by defkev** [comment]
Its the size (length) of a period, like a sample-rate, used by the underlying library.

`m` is in minutes so `10m` is 10 minutes.

See https://github.com/carlos8f/node-timebucket#granularity-identifiers for the different identifiers supported.

**Comment by mkuendig** [comment]
I get this too with latest unstable. This is the error message:

Press  l  to list available commands.
 events.js:183
       throw er; // Unhandled 'error' event
       ^
 
 Error: bind EADDRINUSE 0.0.0.0:80
     at Object._errnoException (util.js:1022:11)
     at _exceptionWithHostPort (util.js:1044:20)
     at listenOnMasterHandle (net.js:1411:16)
     at rr (internal/cluster/child.js:111:12)
     at Worker.send (internal/cluster/child.js:78:7)
     at process.onInternalMessage (internal/cluster/utils.js:42:8)
     at emitTwo (events.js:131:20)
     at process.emit (events.js:214:7)
     at emit (internal/child_process.js:772:12)
     at _combinedTickCallback (internal/process/next_tick.js:141:11)
     at process._tickCallback (internal/process/next_tick.js:180:9)


If I disable web/api it works just fine.

**Comment by rcoenen** [comment]
@mkuendig mmm... `EADDRINUSE` seems to indicate port 80 is already in use. 
Are you running another service at port 80? Or maybe you're running the bit twice?
Try changing in `conf.js` the value `c.output.api.port` and set it to 0?

**Comment by mkuendig** [comment]
Thanks,

This is a container. Nothing else running on that port. 

I also changed to another port (81). Same error just with the new port number 81. 

Haven‘t tried random yet.

**Comment by rcoenen** [comment]
@mkuendig just to be clear: so the but runs fine on command-line until you try to access the Web UI it crashes?

**Comment by mkuendig** [comment]
@rcoenen Actually it crashes already at start with that error. No access to the web-console needed. It crashes right away.

**Comment by rcoenen** [comment]
@mkuendig so then your problem unrelated to this ticket

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
