### ISSUE TITLE
Cant work with 100% or 99%

### ISSUE THREAD

**Issue by Rutinguer** [DeviaVir/zenbot#1392]
Try to buy for second time in a higher price and get this error

```
Account has insufficient balance for requested action."}
    at binance.handleErrors (/home/vorha/zenbot/node_modules/ccxt/js/binance.js:888:35)
    at response.text.then.responseBody (/home/vorha/zenbot/node_modules/ccxt/js/base/Exchange.js:477:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7) constructor: [Function: InsufficientFunds] }
```

After this , the bot dont try buy again

**Comment by defkev** [comment]
> Try to buy for second time

Is this on a re-order or a new order?

**Comment by Rutinguer** [comment]
@defkev re order i guess. WIth 96 % now i think is working well

Telegram messages: 
Buying BINANCE: placing buy order at 0.00000412 BTC, 0.00000002 BTC under best bid
Buying BINANCE: placing buy order at 0.00000413 BTC, 0.00000002 BTC under best bid
Buying BINANCE: placing buy order at 0.00000414 BTC, 0.00000002 BTC under best bid
Buying BINANCE: placing buy order at 0.00000415 BTC, 0.00000002 BTC under best bid
Buying BINANCE: placing buy order at 0.00000416 BTC, 0.00000002 BTC under best bid


Binance Orders
02-21 09:29:35 | TRX/BTC | Limit | Comprar | 0.00000416 | 0.00000416 | -- | 35,773 | -- | -- | Cancelado
02-21 09:28:38 | TRX/BTC | Limit | Comprar | 0.00000415 | 0.00000415 | -- | 35,773 | -- | -- | Cancelado
02-21 09:26:15 | TRX/BTC | Limit | Comprar | 0.00000414 | 0.00000414 | -- | 35,773 | -- | -- | Cancelado
02-21 09:21:05 | TRX/BTC | Limit | Comprar | 0.00000413 | 0.00000413 | -- | 35,773 | -- | -- | Cancelado
02-21 09:10:19 | TRX/BTC | Limit | Comprar | 0.00000412 | 0.00000412 | -- | 35,773 | -- | -- | Cancelado

**Comment by defkev** [comment]
> re order i guess

Thats a known bug, see e.g. #1315 

I am currently looking into this.

**Comment by Rutinguer** [comment]
@defkev 
Perfect , i will work with 96% until the problem will be fixed

**Comment by DeviaVir** [comment]
Closing this one in favor of #1315
