### ISSUE TITLE
Best Trading Strategy - Binance | BTC-USDT 

### ISSUE THREAD

**Issue by ghost** [DeviaVir/zenbot#1396]
Hey everyone im very new to doing all of this so want opinions on selling BTC to USDT on Binance. I saw this RSI strategy but after googling have seen that there are issues with it buying high selling low causing losses, these issues may still occur? I just would like your opinions on strategies for someone like me to use to create a steady profit. If this helps at all I will be using any profits from the BTCP fork next week to mainly help fund my account but for now only have around $80 to use.

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
