### ISSUE TITLE
Capturing redundant trades?

### ISSUE THREAD

**Issue by BarnumD** [DeviaVir/zenbot#14]
Hi.  I ran run.sh.  It began importing history.  I would exepect those entries (like 08/02/2016 07:31:09 PM) to have ~1000 trades as it goes back through history.  I don't understand though why it keeps pulling 1000 trades for what seems like the current time frame. (08/15/2016 02:18:01 AM UTC) (08/15/2016 02:18:32 AM UTC) (08/15/2016 02:19:02 AM UTC).  Shouldn't it only gather the latest trades?  Thanks.

`08/15/2016 02:18:39 AM UTC [     reducer] processing  28/ticks sec
08/15/2016 02:18:45 AM UTC [     reducer]    m24520458    1000 trades. 08/15/2016 02:18:01 AM UTC SELL       550.905 at       $564.91 BTC/USD
08/15/2016 02:18:57 AM UTC [     reducer]    m24502771    1000 trades. 08/02/2016 07:31:09 PM UTC  BUY       478.203 at       $578.46 BTC/USD
08/15/2016 02:19:00 AM UTC [    reporter]    m24520458       1 trades. 08/15/2016 02:18:00 AM UTC              0.211 CLOSE:   $569.79 USD
08/15/2016 02:19:09 AM UTC [     reducer]    m24520458    1000 trades. 08/15/2016 02:18:32 AM UTC SELL       678.611 at       $580.22 BTC/USD
08/15/2016 02:19:09 AM UTC [     reducer] processing  21/ticks sec
08/15/2016 02:19:21 AM UTC [     reducer]    m24502704    1000 trades. 08/02/2016 06:24:38 PM UTC SELL       563.896 at       $597.60 BTC/USD
08/15/2016 02:19:33 AM UTC [     reducer]    m24502652    1000 trades. 08/02/2016 05:32:31 PM UTC  BUY       419.043 at       $601.26 BTC/USD
08/15/2016 02:19:39 AM UTC [     reducer] processing  35/ticks sec
08/15/2016 02:19:45 AM UTC [     reducer]    m24520459    1000 trades. 08/15/2016 02:19:02 AM UTC SELL       226.849 at       $600.21 BTC/USD
08/15/2016 02:19:57 AM UTC [     reducer]    m24502501    1000 trades. 08/02/2016 03:01:20 PM UTC  BUY       335.306 at       $607.63 BTC/USD
08/15/2016 02:20:00 AM UTC [    reporter]    m24520459       1 trades. 08/15/2016 02:19:00 AM UTC              0.350 CLOSE:   $569.79 USD
08/15/2016 02:20:09 AM UTC [     reducer]    m24520459    1000 trades. 08/15/2016 02:19:31 AM UTC  BUY       238.721 at       $608.78 BTC/USD
08/15/2016 02:20:09 AM UTC [     reducer] processing  33/ticks sec
`

**Comment by BarnumD** [comment]
Also, I'm a little confused why it reported backfill complete but it's still going.

`08/15/2016 02:32:45 AM UTC [     reducer]    m24496846    1000 trades. 07/29/2016 04:46:32 PM UTC  BUY       178.919 at       $656.69 BTC/USD
08/15/2016 02:32:46 AM UTC [     reducer] processing  40/ticks sec
08/15/2016 02:33:00 AM UTC [    reporter]    m24520472       1 trades. 08/15/2016 02:32:00 AM UTC              0.080 CLOSE:   $571.33 USD
08/15/2016 02:33:08 AM UTC [     reducer]    m24520472    1000 trades. 08/15/2016 02:32:31 AM UTC  BUY       196.365 at       $657.18 BTC/USD
08/15/2016 02:33:11 AM UTC [        gdax] BTC/USD backfill complete
08/15/2016 02:33:17 AM UTC [     reducer] processing  19/ticks sec
08/15/2016 02:33:18 AM UTC [     reducer]    m24520473    1000 trades. 08/15/2016 02:33:01 AM UTC SELL       176.170 at       $656.26 BTC/USD
08/15/2016 02:33:42 AM UTC [     reducer]    m24496499    1000 trades. 07/29/2016 10:59:31 AM UTC SELL       146.672 at       $657.06 BTC/USD
08/15/2016 02:33:51 AM UTC [     reducer] processing  53/ticks sec
08/15/2016 02:33:52 AM UTC [     reducer]    m24496331    1000 trades. 07/29/2016 08:11:01 AM UTC SELL       141.446 at       $657.91 BTC/USD
08/15/2016 02:34:00 AM UTC [    reporter]    m24520473       2 trades. 08/15/2016 02:33:00 AM UTC              0.395 CLOSE:   $571.33 USD
08/15/2016 02:34:17 AM UTC [     reducer]    m24520473    1000 trades. 08/15/2016 02:33:31 AM UTC  BUY       180.887 at       $658.21 BTC/USD
08/15/2016 02:34:25 AM UTC [     reducer] processing  63/ticks sec
08/15/2016 02:34:27 AM UTC [     reducer]    m24520474    1000 trades. 08/15/2016 02:34:01 AM UTC SELL       201.413 at       $657.23 BTC/USD
08/15/2016 02:34:51 AM UTC [     reducer]    m24495996    1000 trades. 07/29/2016 02:36:03 AM UTC SELL       223.062 at       $657.02 BTC/USD
08/15/2016 02:34:59 AM UTC [     reducer] processing  35/ticks sec
08/15/2016 02:35:00 AM UTC [    reporter]    m24520474       1 trades. 08/15/2016 02:34:00 AM UTC              0.900 CLOSE:   $571.33 USD
08/15/2016 02:35:01 AM UTC [     reducer]    m24520474    1000 trades. 08/15/2016 02:34:31 AM UTC  BUY       258.225 at       $657.02 BTC/USD
08/15/2016 02:35:25 AM UTC [     reducer]    m24520475    1000 trades. 08/15/2016 02:35:01 AM UTC SELL       276.502 at       $656.68 BTC/USD
08/15/2016 02:35:34 AM UTC [     reducer] processing  65/ticks sec
08/15/2016 02:35:35 AM UTC [     reducer]    m24495541    1000 trades. 07/28/2016 07:01:51 PM UTC SELL       232.697 at       $657.48 BTC/USD
08/15/2016 02:36:00 AM UTC [     reducer]    m24495390    1000 trades. 07/28/2016 04:30:41 PM UTC SELL       164.608 at       $658.10 BTC/USD
08/15/2016 02:36:00 AM UTC [    reporter]    m24520475       2 trades. 08/15/2016 02:35:00 AM UTC              2.259 CLOSE:   $571.33 USD
08/15/2016 02:36:08 AM UTC [     reducer] processing  55/ticks sec
08/15/2016 02:36:10 AM UTC [     reducer]    m24520475    1000 trades. 08/15/2016 02:35:32 AM UTC  BUY       285.505 at       $658.66 BTC/USD
08/15/2016 02:36:34 AM UTC [     reducer]    m24520476    1000 trades. 08/15/2016 02:36:01 AM UTC  BUY       211.159 at       $656.53 BTC/USD
08/15/2016 02:36:38 AM UTC [     reducer] processing  41/ticks sec
08/15/2016 02:36:44 AM UTC [     reducer]    m24520476    1000 trades. 08/15/2016 02:36:09 AM UTC SELL       142.657 at       $656.37 BTC/USD
08/15/2016 02:37:00 AM UTC [    reporter]    m24520476       3 trades. 08/15/2016 02:36:00 AM UTC              1.000 CLOSE:   $571.48 USD
08/15/2016 02:37:04 AM UTC [     reducer]    m24520476    1000 trades. 08/15/2016 02:36:32 AM UTC SELL       140.871 at       $656.75 BTC/USD
08/15/2016 02:37:09 AM UTC [     reducer] processing  57/ticks sec
08/15/2016 02:37:27 AM UTC [     reducer]    m24520477    1000 trades. 08/15/2016 02:37:01 AM UTC SELL       164.314 at       $656.86 BTC/USD
08/15/2016 02:37:38 AM UTC [     reducer]    m24494573    1000 trades. 07/28/2016 02:53:01 AM UTC  BUY       138.974 at       $657.13 BTC/USD
08/15/2016 02:37:39 AM UTC [     reducer] processing  59/ticks sec
08/15/2016 02:38:00 AM UTC [    reporter]    m24520477       3 trades. 08/15/2016 02:37:00 AM UTC              0.736 CLOSE:   $571.46 USD
08/15/2016 02:38:01 AM UTC [     reducer]    m24494454    1000 trades. 07/28/2016 12:54:40 AM UTC  BUY       221.268 at       $656.75 BTC/USD
`

**Comment by xangma** [comment]
1st post - no idea why that's the case, it could just be printing how many trades it's currently dealing with (it will be reducing backfilled data in the background)

Regarding your second post, I'm thinking the backfill is done, but the reducing of the raw trades into ticks isn't yet.

Just guesses =]

**Comment by BarnumD** [comment]
It does seem to have settled down after leaving it overnight.

**Comment by carlos8f** [comment]
Lots of changes today, 3.1 released, config re-organized, trade strategy reprogrammed, please drop your zenbrain db, run ./update.sh, and ./run.sh again. Added update notes to the top of the README.

Cheers,
Carlos
