### ISSUE TITLE
Add GDAX Stop Order functionality?

### ISSUE THREAD

**Issue by l0rdh3lix** [DeviaVir/zenbot#140]
Stop orders still work through the API. Is there any way to add manual market actions (buy/sell market/limit/stop) to the CLI? That would be nice for those of us that use zenbot exclusively in advisor mode but still want to use the stop-loss function that GDAX took off their website.

**Comment by carlos8f** [comment]
3.x is no longer supported, we are moving on to 4, which does support stops, although still using a standard limit order. I don't plan to support actual stop orders.
