### ISSUE TITLE
"noop" strategy never stops fetching pre-fill

### ISSUE THREAD

**Issue by LoyLT** [DeviaVir/zenbot#1400]
### System information
- **Have I written custom code**: nope, plain vanilla
- **OS Platform and Distribution**: Kali Linux 2016.2 ("kali-rolling")
- **Zenbot version**: 4.1.0
- **NodeJS version**:  9.5.0
- **Python version**: 2.7.12+
- **Exact command to reproduce**:
./zenbot.sh trade --strategy=noop

### Describe the problem
for the noop strategy, it never stops fetching pre-fill info...
i've accumulated 700ish hours of gdax.ETH-USD already

### Source code / logs
give me commands to try or tell me what files you want...
i see no log directory or .log file in my zenbot directory

**Comment by blevok** [comment]
Try setting min_periods to some number. I know that was the fix at some point, and i'm still doing it. Haven't tried it without in a while, and haven't seen the problem since.

**Comment by LoyLT** [comment]
didn't occur to me to try that because --min_periods wasn't listed in the options for the noop strategy when I did a list-strategies  (that should probably get corrected as well)

okie, yep.... --min_periods=0 makes a decent workaround... still downloads 24 hours though... ideally, it probably shouldn't be downloading any history since noop strategy shouldn't need any for calculations, and min_periods=0 tells it not to display any history

any clue how many hours it would've downloaded had i left it alone for days?

**Comment by Shawn8901** [comment]
"same issue" like #1397 ?

**Comment by LoneWolf345** [comment]
If you consider your issue resolved. Please consider closing.
