### ISSUE TITLE
pls help me fix

### ISSUE THREAD

**Issue by vtnplus** [DeviaVir/zenbot#1401]
zenbot4 error
```
return s.exchange.getTime()
                        ^

TypeError: s.exchange.getTime is not a function
    at now (/root/zenbot/lib/engine.js:639:25)
```
I have change code is
```
function now () {
    if (so.mode === 'live')
      return new Date().getTime()
    else
	  return new Date().getTime()
      //return s.exchange.getTime()
  }
```

can work but i want fix it
pls help me fix it

**Comment by Shawn8901** [comment]
Can you please share you command line input?

**Comment by vtnplus** [comment]
zenbot trade --paper

**Comment by Shawn8901** [comment]
Which exchange and currency pair are you on?

**Comment by vtnplus** [comment]
ETH/BTC

**Comment by vtnplus** [comment]
Next bug. With HitBTC program not work ?

**Comment by Shawn8901** [comment]
To be honest, if you are not giving any input like startup parameters and config and no output, no one could even try to help you.
About the Original issue try #1405 
edit: check #1411

**Comment by LoneWolf345** [comment]
Did you resolve your issue?  If so please consider closing this.
