### ISSUE TITLE
Bitfinex  paper trade ERROR

### ISSUE THREAD

**Issue by tontheonelove** [DeviaVir/zenbot#1402]
Hello   i have problem when i run paper trade  on Bitfinex

i run this Command  >>>>>   ./zenbot.sh trade bitfinex.BTC-USD --paper

im compare between  Binance     The Binance  is work   >> ./zenbot.sh trade binance.BTC-USDT --paper

Please Help Me  about this issue   

This is out out  Error

------------------------------------------ INITIALIZE  OUTPUT ------------------------------------------
---------------------------------------- STARTING PAPER TRADING ----------------------------------------
!!! Paper mode enabled. No real trades are performed until you remove --paper from the startup command.
Press  l  to list available commands.
Web GUI running on http://0.0.0.0:20027/
/root/zenbot/extensions/exchanges/bitfinex/exchange.js:214
        throw new Error('please configure your Bitfinex credentials in ' + path.resolve(__dirname, 'conf.js'))
        ^

Error: please configure your Bitfinex credentials in /root/zenbot/extensions/exchanges/bitfinex/conf.js
    at wsClient (/root/zenbot/extensions/exchanges/bitfinex/exchange.js:214:15)
    at Object.getTrades (/root/zenbot/extensions/exchanges/bitfinex/exchange.js:314:27)
    at forwardScan (/root/zenbot/commands/trade.js:577:20)
    at Object.<anonymous> (/root/zenbot/commands/trade.js:431:21)
    at Immediate._onImmediate (/root/zenbot/node_modules/sosa/api.js:15:12)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

**Comment by Shawn8901** [comment]
did you fill in the credentials in you config file?

**Comment by tontheonelove** [comment]
You Mean  api  ?

**Comment by Shawn8901** [comment]
https://github.com/DeviaVir/zenbot/pull/1378 removed the code, which prevented a real sync to the exchange. so its a bug, that you have to fill in credentials for paper mode. also see #1403

**Comment by Shawn8901** [comment]
should be fixed with #1405

**Comment by tontheonelove** [comment]
Hello   I  successfull     


Thankyou for help me  ^_^
