### ISSUE TITLE
REAL trades being placed in --paper mode!

### ISSUE THREAD

**Issue by franzkruhm** [DeviaVir/zenbot#1403]
At first I thought it was a bit odd that paper mode suddenly required my API key etc...

I was "okay whatever, maybe they got in trouble with some exchanges for querying the API"...

Decided to test a strategy in --paper mode, paper mode was apparently active.

Suddenly my XMR get sold... I think, perhaps it is a simulated balance... Log into Kraken...
Sure enough my XMR had been sold...

./zenbot.sh trade kraken.XXMR-ZEUR --paper --order-type="taker"

is the command-line I used.

[proof](https://imgur.com/a/sIspM)

**Comment by pytel87** [comment]
Same thing happened to me on gdax.ETH-EUR

**Comment by JulesBern** [comment]
Confirmed on GDAX as well, performed actual trades.

**Comment by vtnplus** [comment]
help me.
why i set trade BTC-USDT ( BTC up bot buy, BTC down bot sell ) :(
what is set method ?

**Comment by Shawn8901** [comment]
in a short test on my side #1405 should fix the issue.
