### ISSUE TITLE
Trading LTC/BTC and LTC/USD

### ISSUE THREAD

**Issue by kopron** [DeviaVir/zenbot#141]
Has anyone used zenbot to trade LTC on GDAX?

I've created a config file with c.assets=["LTC"], c.currencies=["USD"] and c.default_selector="gdax.LTC-USD" but this results in a bot that launches and then does nothing. 

Any suggestions?

**Comment by papacasper** [comment]
Put this into the [exchange.json](https://github.com/carlos8f/zenbot/blob/5bfa82ac754d729602b00bcd32ea7d2839cbf403/plugins/gdax/exchange.json#L52) file and you should be good to go with the config file you have.

     {
      "id":"LTC-BTC",
      "asset":"LTC",
      "currency":"BTC",
      "min_size":0.01,
      "max_size":100000,
      "increment":0.00001,
      "label":"LTC/BTC" 
     },

    {
      "id":"LTC-USD",
      "asset":"LTC",
      "currency":"USD",
      "min_size":0.01,
      "max_size":100000,
      "increment":0.00001,
      "label":"LTC/USD"
     },

**Comment by tuxitor** [comment]
What are the recommended parameters for ETH-BTC and ETH-USD?
