### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by vtnplus** [DeviaVir/zenbot#1415]
After Update afew day.
bittrex not work
api can not execute
pls check
I run with 
./zenbot.sh trade --period_length=1m --profit_stop_enable_pct=10 --profit_stop_pct=4 --trend_ema=36 --sell_rate=-0.06 --paper

next error : 
with BTC-USDT can not work because
1. when BTC up we need sell
2. When BTC down we need buy

but now 
1. When BTC up bot buy
2. When BTC down bot sell :(

Not good

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
