### ISSUE TITLE
Strategy simulation in onPeriod do not take callback into account since latest refactoring

### ISSUE THREAD

**Issue by Haehnchen** [DeviaVir/zenbot#1416]
All talib strategies and indicators need a callback as calculations are async. therefore we moved all the calculation from `calculate` to `onPeriod` as this provides a callback. But onPeriod is not using the callback in simulations in the right way since the latests refactorings in engine code. 

If we run a simulation 14 days it stops already before. you can test this behavior with the following code. if you higher sleep time simulator stops more earlier. it looks like some code snippet is not waiting for the callback 

```javascript
    function sleep (time) {
      return new Promise((resolve) => setTimeout(resolve, time));
    }

onPeriod: function (s, cb) {
    Promise.all([sleep(500)]).then(function() {
      console.log("aaa")
      cb()
    })
}
```

**Comment by Haehnchen** [comment]
Looks like monodb data elements are now streamed and not collected. maybe @krystophv can help

https://github.com/DeviaVir/zenbot/commit/607a72c#diff-0b0ccd6820a6dc8b5de6b7c6868c126aR235

```
tradesCollection.find(opts.query).sort(opts.sort).limit(opts.limit).toArray(function (err, trades) {
```

```
        collectionCursor.on('data', function(trade){
          lastTrade = trade
          numTrades++
          if (so.symmetrical && reversing) {
            trade.orig_time = trade.time
            trade.time = reverse_point + (reverse_point - trade.time)
          }
          eventBus.emit('trade', trade)
        })
```

**Comment by krystophv** [comment]
Ah, yeah - I can look into this. It's not directly related to the code chunks you've pointed out, but I think it's an effect of that refactor. It's likely that the sim is exiting before the internal processing queue has finished emptying. I'll see about adjusting the exit functions to wait for an empty queue.
