### ISSUE TITLE
Too soon to buy after by

### ISSUE THREAD

**Issue by blakem17** [DeviaVir/zenbot#142]
trader] gdax.BTC-USD RSI:67 trend: null -> UP
     trader] gdax.BTC-USD too soon to buy after buy! waiting 23h 25m

What is calculating the time needed between purchases?

**Comment by ElliottLandsborough** [comment]
https://github.com/carlos8f/zenbot/blob/master/default_logic.js#L76+L77

**Comment by blakem17** [comment]
Thanks mate
