### ISSUE TITLE
Limited request and Delay to start trading

### ISSUE THREAD

**Issue by philinformatique** [DeviaVir/zenbot#1427]
Hi, I have 2 questions :
1, do the bot are limited to request only 1 request by second?  because on cex.io we are limited to 600 request by 10min, or do it have a  way to limit that.  

2, When I start the bot it make around 12 hours to it start make his first trade, do it have a way to change that?   

thanks

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
