### ISSUE TITLE
Update master

### ISSUE THREAD

**Issue by glennfu** [DeviaVir/zenbot#1430]
`master` branch is super out of date. I've been running what's on a recent unstable (accc62e605cba2d82853cd5a69f4b39c658b8122) commit, plus a couple of tweaks, in live mode for over 80 hours, profiting, and hitting no bugs/crashes, on a low memory Google compute instance. I feel like this is a great point to update master.

The commits since that point are mostly bug fixes as well so maybe even mark it after that.

**Comment by DeviaVir** [comment]
Yep, I'll try to bake a new release soon.

**Comment by imgrammy** [comment]
Thank you two for the effort of guiding to stable versions.

**Comment by DeviaVir** [comment]
https://github.com/DeviaVir/zenbot/releases/tag/v4.1.1
