### ISSUE TITLE
bug with darwin

### ISSUE THREAD

**Issue by ttrd06** [DeviaVir/zenbot#1447]
Morning !

An another bug with darwin if you want to use this amazing function:
with the last commits from unstable and if you run darwin, you have: "json2csv is not a function" and darwin crash.
i already know it is unstable but with latest commits, i hope bugs fixed.
same with fresh install...
if you clone from master branch and run npm install, you can't have a working version because of bugs during install.
please check the basics of the bot before to commit @DeviaVir , there is always something broken as the issues mentionned said

thank's for reply

**Comment by DeviaVir** [comment]
Please re-open your issue using the issue template, it's there for a reason.

Thank you!
