### ISSUE TITLE
Move Strat parameters out of darwin.js and into strategy.js

### ISSUE THREAD

**Issue by LoneWolf345** [DeviaVir/zenbot#1466]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04

### Describe the feature request
Feature Request: Move the strategy parameter ranges from within darwin.js to inside the strategy.js files for each strategy.

### Goal
I think it would be best to move the default ranges to the strategy files as I feel it would 1) clean up darwin.js 2) be a more natural place to find it for new users 3)easier to implement if you are creating a custom strat

**Comment by Shawn8901** [comment]
Looks similar to this pr #1433 ? Here are phenotypes are moved to the strategy-files.

**Comment by LoneWolf345** [comment]
Your right, I missed that one.
