### ISSUE TITLE
npm install fails at "forex.analytics"

### ISSUE THREAD

**Issue by jellicoe** [DeviaVir/zenbot#1468]
jj@zenbot:~/zenbot$ npm install
npm ERR! path /home/jj/zenbot/node_modules/forex.analytics
npm ERR! code EISGIT
npm ERR! git /home/jj/zenbot/node_modules/forex.analytics: Appears to be a git repo or submodule.
npm ERR! git     /home/jj/zenbot/node_modules/forex.analytics
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

package.jso has weird version name in it

**Comment by DeviaVir** [comment]
Please re-open your issue using the issue template, we added it for a reason. Thanks!

**Comment by jellicoe** [comment]
chnaged package.json to use "forex.analytics" : ^0.0.14

**Comment by vipul8907** [comment]
@jellicoe ...i am facing the same issue, could you please let me know what exactly did you do?

**Comment by jellicoe** [comment]
git clone

edit package.json

so line

"forex.analytics": "
github:mkmarek/forex.analytics#7bc278987700d4204e959af17de61495941d1a14",

looks like

"forex.analytics" : ^0.0.14
