### ISSUE TITLE
Sell on low RSI?

### ISSUE THREAD

**Issue by senoird** [DeviaVir/zenbot#147]
Just playing around with your bot today and while watching I noticed it was trying to sell at RSI of 30. Why would it try to sell on a down trend? I look in the config and :
      rs.rsi_up = 58 // upper RSI threshold
      rs.rsi_down = 35 // lower RSI threshold
is what I have it set at slightly tighter than the default was.

**Comment by alternativesurfer** [comment]
I only have email access but look for a bug I opened about this very thing
from a few months ago.
The logic is backwards, and I indicated the correct updated code to make it
behave correctly.

**Comment by senoird** [comment]
Thanks for the reply. Good to see its just not me thinking that was wrong. I found your code and replaced it in my config file. Going to give it a shot. Thanks again.

**Comment by DeviaVir** [comment]
Closing due to age, but do feel free to comment in case things still look off.
