### ISSUE TITLE
Zenbot hangs if trade volume is high

### ISSUE THREAD

**Issue by ghost** [DeviaVir/zenbot#1484]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Zenbot version** (commit ref, or version): 4.1.1
- **Zenbot branch**: unstable
- **NodeJS version**: 8.10.0
- **Python version (when using a python script)**:
- **Exact command to reproduce (include everything)**: ./zenbot.sh trade binance.BTC-USDT --paper
- **Did I make any changes to conf-sample.js?**: no

### Describe the problem
When volume is high (trades are coming at high rate) trading is impossibile. Zenbot hangs because all the setTimeout, setImmediate, .. instructions are not executed becuase NodeJS is always giving priority to EventEmitter and executes 'trade' events immediately at 1000/sec, so any other timeout waits indefinetly.

**Comment by ghost** [comment]
Upon further inspection i cannot paper-trade with any pair, it is not related to the high volume.
I printed some debug information and it seems that setImmediate function and setTimeout function are overridden by fake timeouts. "lolex" package seems to be responsible for this.

first call:
```
*** getNext ==> engine.update: before setImmediate
*** setImmediate is: function setImmediate(callback, arg1, arg2, arg3) {
  if (typeof callback !== 'function') {
    throw new TypeError('"callback" argument must be a function');
  }

  var i, args;

  switch (arguments.length) {
    // fast cases
    case 1:
      break;
    case 2:
      args = [arg1];
      break;
    case 3:
      args = [arg1, arg2];
      break;
    default:
      args = [arg1, arg2, arg3];
      for (i = 4; i < arguments.length; i++)
        // extend array dynamically, makes .apply run much faster in v6.0.0
        args[i - 1] = arguments[i];
      break;
  }
  return createImmediate(args, callback);
}
*** setImmediate return value Immediate {
  _idleNext: null,
  _idlePrev:
   Immediate {
     _idleNext: [Circular],
     _idlePrev: null,
     _callback: [Function],
     _argv: undefined,
     _onImmediate: [Function],
     _destroyed: false,
     domain: null,
     [Symbol(asyncId)]: 99,
     [Symbol(triggerAsyncId)]: 94 },
  _callback: [Function: getNext],
  _argv: undefined,
  _onImmediate: [Function: getNext],
  _destroyed: false,
  domain: null,
  [Symbol(asyncId)]: 102,
  [Symbol(triggerAsyncId)]: 94 }
```

second call (after this eveything hangs):
```
*** getNext ==> engine.update: before setImmediate
*** setImmediate is: function () {
            return clock[method].apply(clock, arguments);
        }
*** setImmediate return value { id: 1, ref: [Function: NOOP], unref: [Function: NOOP] }
```

the offending line seems to be

`engine.js:776`

if you comment that line everything works as expected.

**Comment by DeviaVir** [comment]
Should be fixed in latest unstable already.
