### ISSUE TITLE
About live trading and informations displayed thought api screen

### ISSUE THREAD

**Issue by ttrd06** [DeviaVir/zenbot#1493]
Good evening,

I only have a small question about live trading:

if i start with a fresh install  && an empty mongo db and then start with a live trade, the bot backfill 6 days before to begin ... ? Why ?
Then i use the api screen and it show 4 trades over 6 days but i just started the live trading since today !?
The right infos will be 4 trades over 1 day. Right ?

Before (2017)  it only backfill 1 day. Why ?

Thank's for reply

**Comment by theDiverDK** [comment]
Might i suggest, you go to https://discordapp.com/channels/316120967200112642/321961031620362240 and ask?

There are some really cleaver people there.

p.s. It's zenbot's discord developer channel

**Comment by vithonch** [comment]
Are you sure the link is correct?

**Comment by DeviaVir** [comment]
Please read the issue template before submitting your question.

**Comment by LoneWolf345** [comment]
https://discord.gg/6aAd2J5
