### ISSUE TITLE
trade 2 simultaneous cryptos

### ISSUE THREAD

**Issue by DrMabuse-2017** [DeviaVir/zenbot#1503]
### System information
- **OS Platform and Distribution (Linux Debian 9.3 amd64):
- **Zenbot version (version 4.1.0):
- **Zenbot branch *lattest*:
- **NodeJS version v8.10.0:
- **Python version (when using a python script) *no*:
- **Exact command to reproduce (include everything) *trade 2 simultaneous cryptos*:
- **Did I make any changes to conf-sample.js?**:

Hello guys...

I have a question
I want to trade 2 simultaneous cryptos. I assume that I have to open 2 consoles to start the 2 trade comands

Example: BCC-BTC (price is high) and TRX-BTC (price is low)
Each: --buy_pct = 50 --sell_pct = 50

zenbot now sells 1 BCC and my account balance (currency) gets higher.
Now comes the signal that the TRX-BTC should be purchased.
Is it the case that the 2 cryptos always share my account balance (currency) for each sell / buy?
Because I do not want that now the larger reserve for BCC is now taken for the trade for TRX.

Is there a way to get around that?

Sorry for my bad English

regards
Mario

**Comment by DeviaVir** [comment]
Hi Mario, some time ago we changed our policy to no longer allow questions in our GitHub Issues (as stated in the first line when you create a new issue), please post your question to our reddit instead:
https://www.reddit.com/r/zenbot/

**Comment by DrMabuse-2017** [comment]
Hi DeviaVir.

Sorry! Ok no Problem :-).

The new post is visible here:
https://www.reddit.com/r/zenbot/comments/84ew83/trade_2_simultaneous_cryptos/

Regards
Mario
