### ISSUE TITLE
Quick question on ./zenbot.sh sell cancelorder!

### ISSUE THREAD

**Issue by ghost** [DeviaVir/zenbot#1505]
------------------------
Remove everything above before creating your issue.
------------------------

### System information
Stock ubuntu 16.04.4 LTS

Custom script.

Zenbot Master Repository

Stock Zenbot Conf.js

### Describe the problem
Hello! I have been updating my cryptoping plugin for zenbot, and it's been awhile since I've dug into the code, but does zenbot support cancel_after on ./zenbot.sh sell command?

### Source code / Error logs
My script: https://github.com/juanzolo/Zenbot-CryptoPing/blob/master/polo.py

**Comment by DeviaVir** [comment]
Hi @juanzolo, some time ago we changed our policy to no longer allow questions in our GitHub Issues (as stated in the first line when you create a new issue), please post your question to our reddit instead:
https://www.reddit.com/r/zenbot/
