### ISSUE TITLE
Binance  - Timestamp for this request was 1000ms ahead of the server's time.

### ISSUE THREAD

**Issue by Leekyungun** [DeviaVir/zenbot#1506]
Hi, I was install zenbot and start it.  But it doesn't work.

Binance trade error.
I don't know this is error or work well. 

OS : windows 10
TimeZone : UTC/GMT +9
command : ./zenbot.sh trade
Error message.

> Binance API is down! unable to call getBalance, retrying in 20s
> [ { currency: 'USDT', asset: 'BTC' } ]
> An error occurred { Error: binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
>     at binance.handleErrors (C:\Users\dbsgn\Desktop\zenbot\node_modules\ccxt\js\binance.js:899:35)
>     at response.text.then.responseBody (C:\Users\dbsgn\Desktop\zenbot\node_modules\ccxt\js\base\Exchange.js:488:18)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: InvalidNonce] }

**Comment by RGAlexander216** [comment]
There is definitely an issue with the time difference as I'm having the same issue and no luck resolving it myself..

**Comment by DeviaVir** [comment]
Please re-open your issue using the issue template, and make sure your report is not a question.
