### ISSUE TITLE
Binance - Timestamp for this request was 1000ms ahead of the server's time.

### ISSUE THREAD

**Issue by Leekyungun** [DeviaVir/zenbot#1507]
## System information
Have I written custom code (as opposed to using zenbot vanilla):yes
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
Zenbot version (commit ref, or version): 6307098  
Zenbot branch: master
NodeJS version: v8.9.10
Exact command to reproduce (include everything): ./zenbot.js trade --selector=binance.BTC-USDT --use_strategies=speed
Did I make any changes to conf-sample.js?: no
TimeZone : UTC/GMT +9

##Describe the problem
zenbot doesn't work. Maybe different timezone.

## Source code / Error logs
```
Binance API is down! unable to call getBalance, retrying in 20s
[ { currency: 'USDT', asset: 'BTC' } ]
An error occurred { Error: binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
at binance.handleErrors (C:\Users\dbsgn\Desktop\zenbot\node_modules\ccxt\js\binance.js:899:35)
at response.text.then.responseBody (C:\Users\dbsgn\Desktop\zenbot\node_modules\ccxt\js\base\Exchange.js:488:18)
at 
at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: InvalidNonce] }
```

-------
console.log(date, new Date())   --> result 
![image](https://user-images.githubusercontent.com/12290390/37477407-fb12f534-28ba-11e8-999d-daf4789a4df1.png)

**Comment by Shawn8901** [comment]
Can you please check your local timestamp and sync it with a timeserver? Then re-test. This message is returned from binance if the timestamp your bot deliveres is too old. If you sync your clock (p.e. With ntp server) that should be fixed

**Comment by Leekyungun** [comment]
@Shawn8901  
I was check zenbot program date time. This is UTC/GMT +0.
But my window 10 OS date is UTC/GMT +9. 
 I don't know how to sync timestamp with a timeserver.

I found check serverTime.(https://api.binance.com/api/v1/time)
![image](https://user-images.githubusercontent.com/12290390/37479227-7c8af914-28bf-11e8-89ac-a0132c606629.png)
ServerTime : 1521133882239
localTime   : 1521133884780
diff time     : 2541

But I don't know How to fix it.

**Comment by Shawn8901** [comment]
syncing your clock with a timeserver, as i said... 
Really, i already told you the answer, and you have approved it by your analysis but you still dont now what to do?!
http://www.letmegooglethat.com/?q=windows+sync+clock+with+time+server

**Comment by Leekyungun** [comment]
@Shawn8901
Oh!! Really thank you 
And This URL is really funny. Thank you~
