### ISSUE TITLE
Accessing Web GUI from EC2 instance running on http://0.0.0.0:20075/

### ISSUE THREAD

**Issue by alexandrag2254** [DeviaVir/zenbot#1528]
Thanks for the great product! 

I am running zenbot on aws ec2 Ubuntu 16.04. When trading there is an ability to connect to a web available gui -- "Web GUI running on http://0.0.0.0:20015/"

Any hints or tips to access this Web GUI through ec2 instance? I tried using public_IP:20015 and adjusting security groups but haven't been able to get it to work. 

thanks in advance!

**Comment by DeviaVir** [comment]
Please post zenbot questions in our subreddit: https://www.reddit.com/r/zenbot/

The github issues is reserved for bugs and features.

Thanks!
