### ISSUE TITLE
Program will not work if activated over a day

### ISSUE THREAD

**Issue by Leekyungun** [DeviaVir/zenbot#1529]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**:yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: windows 10
- **Zenbot version (commit ref, or version)**: 6307098  
- **Zenbot branch**: master
- **NodeJS version**: v8.9.10
- **Exact command to reproduce (include everything)**: ./zenbot.js trade --selector=binance.BTC-USDT --use_strategies=speed
- **Did I make any changes to conf-sample.js?**: no
- **TimeZone**: UTC/GMT +9
- **Memory**: 2G

### Describe the problem
Program will not work if activated over a day
I think it's a symptom of a lack of memory.
What is the minimum specification?

### Source code / Error logs
![image](https://user-images.githubusercontent.com/12290390/37964785-a63dba20-31fd-11e8-9085-f14d319013e9.png)

**Comment by defkev** [comment]
-1021 indicates something is wrong with your system time, ENOTFOUND is a problem with your DNS

> I think it's a symptom of a lack of memory.

How so? As you are running Windows 10 i'd expect your box to pack a bigger punch.
Check the memory util of `node` as well as `mongo_stats`

> What is the minimum specification?

Honestly i have no idea, if anything the bot is fairly conservative when it comes to system requirements.
Unless you go crazy even the smallest VPS around will do just fine.

**Comment by Leekyungun** [comment]
Sorry. I use Ubuntu 14.04
Zenbot works well the first time it is used. 
However, after a certain time, errors appear.
![image](https://user-images.githubusercontent.com/12290390/38018020-b8156980-32ae-11e8-95ac-679a096f7ce7.png)

**Comment by LoneWolf345** [comment]
At the bottom of your conf.js, change 
`c.output.api.on = true`
to false.

**Comment by Shawn8901** [comment]
Tip from my side: don't run applications as root user. There a some quotas which could trigger on low memory condition, but as root user you are allowed to bypass this. As normal user a dns call (or time call) should not fail if you are a normal user on low memory condition...

If you have any other input feel free to add this, otherwise please consider closing the issue.

**Comment by Leekyungun** [comment]
Thanks
