### ISSUE TITLE
No trades found! Try running zenbot backfill...

### ISSUE THREAD

**Issue by ToX82** [DeviaVir/zenbot#153]
Is it too soon to try the 4.x branch?

I'd like to make a few tests on the 4.x branch, but I can't run a simulation on it:

    no trades found! try running `zenbot backfill gdax.BTC-EUR` first

If I do that, zenbot seems to correctly backfill all the needed data, but then I'm having that error again when I try to launch a simulation.

**Comment by leweohlsen** [comment]
Have you tried providing the zenbot sim command with date parameters?
`zenbot sim --days 7`
or
`zenbot sim --start <timestamp> --end <timestamp> ` 
where timestamp is in epoch time format.

**Comment by ToX82** [comment]
`zenbot sim --days 7` worked, thanks!

**Comment by mifau** [comment]
@ToX82 : So how does it perform? (like comparing to 3.x)

**Comment by ToX82** [comment]
Well that's an interesting question indeed. And I don't have an answer :)
Anyway, I have ran a simulation on the 4.x versions right now, and these are the results. 

I didn't test version 3.x too much honestly so I don't know if this is performing better, but I think that the 3.x version was more aggressive with the trading.

    { days: 7,
      strategy: 'trend_ema',
      sell_stop_pct: 0,
      buy_stop_pct: 0,
      profit_stop_enable_pct: 10,
      profit_stop_pct: 1,
      max_sell_loss_pct: 25,
      max_slippage_pct: 2,
      buy_pct: 99,
      sell_pct: 99,
      markup_pct: 0,
      currency_capital: 1000,
      asset_capital: 0,
      order_adjust_time: 30000,
      rsi_periods: 14,
      end: 1494979200000,
      start: 1494374400000,
      stats: false,
      selector: 'gdax.BTC-USD',
      mode: 'sim',
      period: '1h',
      min_periods: 36,
      trend_ema: 34,
      buy_rate: 0,
      sell_rate: 0,
      max_buy_duration: 1,
      max_sell_duration: 1 }
    end balance 1083.06 (8.31%)
    buy hold 1031.66 (3.17%)
    vs. buy hold 4.98%
    17 trades over 8 days (avg 2.13 trades/day)

**Comment by mifau** [comment]
I've tried...
I like the way how it works...
My results are:
{ strategy: 'trend_ema',
  sell_stop_pct: 0,
  buy_stop_pct: 0,
  profit_stop_enable_pct: 10,
  profit_stop_pct: 1,
  max_sell_loss_pct: 25,
  max_slippage_pct: 2,
  buy_pct: 99,
  sell_pct: 99,
  markup_pct: 0,
  days: 90,
  currency_capital: 1000,
  asset_capital: 0,
  order_adjust_time: 30000,
  rsi_periods: 14,
  end: 1494979200000,
  start: 1487203200000,
  stats: false,
  selector: 'gdax.BTC-EUR',
  mode: 'sim',
  period: '1h',
  min_periods: 36,
  trend_ema: 34,
  buy_rate: 0,
  sell_rate: 0,
  max_buy_duration: 1,
  max_sell_duration: 1,
  oversold_rsi_periods: 14,
  oversold_rsi: 0 }
end balance 1844.12 (84.41%)
buy hold 1643.07 (64.31%)
vs. buy hold 12.24%
178 trades over 89 days (avg 2.00 trades/day)

for 7 days I got 1,23% profit...which is lower (like few times) than just leave btc untouched.
With 3.x I made 4% just for last 2 days....(with modified rsi period to 1m, rsi filter=14, up=83 down=26 - simulation says it should be 1.53 roi for some period of time  - it was of course with reversed UP/DOWN logic). The problem with 3.x is that it should be permanently controlled by the user:)

**Comment by ToX82** [comment]
I was curious and did some more tests, for your same period (89 days), but using BTC-USD. The end balance seems to be ~40% more...

    end balance 2202.58 (120.26%)
    buy hold 1681.17 (68.12%)
    vs. buy hold 31.02%
    185 trades over 89 days (avg 2.08 trades/day)

Another test, with BTC-EUR

    end balance 1812.70 (81.27%)
    buy hold 1618.94 (61.89%)
    vs. buy hold 11.97%
    178 trades over 89 days (avg 2.00 trades/day)

**Comment by mifau** [comment]
That's a good reason to use BTC-USD pair;)

btw.... 
use this: 
c.order_adjust_time = 10000
Works better for me

**Comment by deadchannelsky** [comment]
Just as a data point I am trying to create a good ETH strategy code base from 4.x currently simulation is showing about +5% as opposed to about 84% buy and hold. Hehheh. ETH has been so volatile it might be inevitable.

**Comment by DeviaVir** [comment]
I'd suggest to continue this great stuff over at the discord:
https://discord.gg/ZdAd2gP
As there is no longer an issue here I'll be closing it for now.
