### ISSUE TITLE
Binance no longer trading during sims

### ISSUE THREAD

**Issue by phatwila** [DeviaVir/zenbot#1537]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: contos 7
- **Zenbot version** (commit ref, or version): latest
- **Zenbot branch**: unstable 
- **NodeJS version**: v9.6.1
- **Python version (when using a python script)**: Python 2.7.5
- **Exact command to reproduce (include everything)**:
- **Did I make any changes to conf-sample.js?**: no

### Describe the problem
There appears to be some issue with backtesting Binance, i've tried 3 or 4 different coin pairs and the genetic algo never does a trade. If I switch over to GDAX I am able to backtest and return trades. Any idea whats going on?

### Source code / Error logs
0 trades binance
![image](https://user-images.githubusercontent.com/33909492/38437442-77fee0a8-39a5-11e8-8249-928ab6428bec.png)
GDAX with trades
![image](https://user-images.githubusercontent.com/33909492/38437490-989a3fe2-39a5-11e8-9ec5-c794ecc78c22.png)

**Comment by DeviaVir** [comment]
I believe there was an issue with the Binance API around that time, do you still have a problem?

**Comment by phatwila** [comment]
@DeviaVir 
Yeah unfortunately it looks like its still having issues with sim trading. Any more information I can provide?
![image](https://user-images.githubusercontent.com/33909492/38509653-88722c54-3bf0-11e8-847c-6a75023d641b.png)

**Comment by LoneWolf345** [comment]
Have you tried other coin pairs? How about other strategies?  Try running it with a strategy like SAR because it will always make trades with any normal set of parameters.
As a note, I use Binance without those issues.
