### ISSUE TITLE
zenbot backfill gdax.BTC-EUR error

### ISSUE THREAD

**Issue by jianshengxing** [DeviaVir/zenbot#155]
when I run the  command in the title, at first it seems it runs okay, but after some time, error occurs:
gdax.BTC-EUR saved 100 trades 90 days left
..............................................................................................................
............................................................
gdax.BTC-EUR saved 6100 trades 13 days left
.......................................................................................
gdax.BTC-EUR saved 8800 trades 12 days left

the /home/zenbot4/commands/backfill.js:64
                if (err) throw err
                         ^
MongoError: insertDocument :: caused by :: 13636 file /var/lib/mongodb/zenbot4.3 open/create failed in createPrivateMap (look in log for more information)
    at Function.MongoError.create (/home/zenbot4/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/home/zenbot4/node_modules/mongodb/lib/utils.js:139:22)
    at /home/zenbot4/node_modules/mongodb/lib/collection.js:1060:67
    at /home/zenbot4/node_modules/mongodb-core/lib/connection/pool.js:461:18
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by DeviaVir** [comment]
Sounds like you ran out of disk space:
https://stackoverflow.com/questions/21246276/cant-initialise-replica-set-on-debian-open-create-failed-in-createprivatemap
