### ISSUE TITLE
Cannot build docker with genetic algorithms

### ISSUE THREAD

**Issue by avegrv** [DeviaVir/zenbot#1551]
Hi, I try to build docker in "scripts/genetic_algo"

And get error

Step 15/19 : ADD ../../ /app
ERROR: Service 'server' failed to build: ADD failed: Forbidden path outside the build context: ../../ ()

**Comment by DeviaVir** [comment]
Please re-open your bug report using the issue template, thanks!

**Comment by kenorb** [comment]
Related: [docker-compose build error when using parent dir & dockerfile for build](https://stackoverflow.com/q/37099008/55075).
