### ISSUE TITLE
Bittrex Trade API Error

### ISSUE THREAD

**Issue by pwalker0863** [DeviaVir/zenbot#1568]
------------------------

### System information
- **Have I written custom code : NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  CentOS Linux release 7.4.1708 (Core)
- **Zenbot version** (commit ref, or version): 4.1.0
- **Zenbot branch**: Master
- **NodeJS version**: v9.11.1
- **Python version (when using a python script)**:  Python 2.7.5
- **Exact command to reproduce (include everything)**:  ./zenbot.sh trade --avg_slippage_pct=0.046 --buy_stop_pct=0 --conf=/home/miner/zenbot/bitconf.js --markdown_buy_pct=5.6223196002001425 --markup_sell_pct=5.8259812587087167 --max_buy_loss_pct=25 --max_sell_loss_pct=-.1 --max_slippage_pct=5 --order_type=taker --overbought_rsi=97 --overbought_rsi_periods=15 --period=30m --period_length=1m --profit_stop_enable_pct=0 --profit_stop_pct=15 --rsi_periods=15 --sell_stop_pct=0 --signal=trend --strategy=ta_ultosc --timeperiod1=26 --timeperiod2=12 --timeperiod3=12 --selector=bittrex.ZEN-BTC --keep_prev_trades=no --buy_pct=30
- **Did I make any changes to conf-sample.js?**:  NO

### Describe the problem
Running command above, will not complete a bittrex trade.  Fails with error below

### Source code / Error logs
{ Error: order not found in cache
    at Object.getOrder (/home/miner/zenbot/extensions/exchanges/bittrex/exchange.js:371:25)
    at checkOrder (/home/miner/zenbot/lib/engine.js:833:16)
    at Timeout._onTimeout (/home/miner/zenbot/lib/engine.js:301:31)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5) desc: 'could not execute buy: error placing order' }

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by brucetus** [comment]
Hi I think Bittrex doesn't allow taker/market orders through their API (however the exchange file allows us to call for taker orders, which i dont think it should be able to do). Can you try again with
--order_type=maker and turn on the debug by adding --debug to your command or pressing shift L while trading? Then post the screenshots of what it says before you get the error.

**Comment by pwalker0863** [comment]
UGH!   Looks like you nailed it!! The '--order_type=taker' option was killing me.  Guess I need to read more into the finer points of Zenbot.  Appreciate the quick response!!  Consider this closed
