### ISSUE TITLE
Docker instances not coming up

### ISSUE THREAD

**Issue by felipecaldas** [DeviaVir/zenbot#158]
Hi guys,

Very  much followed the instructions:

git clone https://github.com/carlos8f/zenbot.git
cd zenbot
docker-compose build
docker-compose up (-d if you don't want to see the log)

And I end up with:

C:\Users\Felipe\zenbot>docker images
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
zenbot_btc-usd             latest              11c4e77122dd        22 minutes ago      750 MB
zenbot_reducer             latest              11c4e77122dd        22 minutes ago      750 MB
zenbot_server              latest              11c4e77122dd        22 minutes ago      750 MB

but when I run docker-compose up, this is what I get:

> C:\Users\Felipe\zenbot>docker-compose up
> Removing zenbot_reducer_1
> Removing zenbot_btc-usd_1
> Starting zenbot_mongodb-data_1
> Starting zenbot_mongodb_1
> Recreating 37c92cf401d9_37c92cf401d9_zenbot_reducer_1
> Recreating fd9cbb009996_fd9cbb009996_zenbot_btc-usd_1
> 
> ERROR: for reducer  Cannot start service reducer: Cannot link to a non running container: /zenbot_mongodb_1 AS /zenbot_reducer_1/mongodb
> 
> ERROR: for btc-usd  Cannot start service btc-usd: Cannot link to a non running container: /zenbot_mongodb_1 AS /zenbot_btc-usd_1/mongodb
> ERROR: Encountered errors while bringing up the project.

Should I be running the three images manually first before issuing the compose up command?

I tried:

C:\Users\Felipe\zenbot>docker run -it zenbot_server
>

But as you can see I end up with the Node command-line.

Any help much appreciated

Thanks,
Felipe

**Comment by enriquevago** [comment]
Hi Felipe,

Check a dock info file in git,i suppose it's a problem that mongodb is not running or its directory is not set corret.
Try running mongodb direct on dock
Sorry for my eng is google  translate !

**Comment by felipecaldas** [comment]
@enriquevago , se hablas espanol tu puedes me escribir aqui
If I understand you right, you're saying there is a docker info file in this Github repo that might help me. I will check it out Thanks

**Comment by egorbenko** [comment]
@felipecaldas 
@enriquevago is correct, mongodb doesn't seem to be running. check the error log why, possibly the port is already taken by something else

**Comment by DeviaVir** [comment]
Closing due to age, feel free to comment if you're still having problems.
