### ISSUE TITLE
Web GUI is broken

### ISSUE THREAD

**Issue by percenuage** [DeviaVir/zenbot#1581]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu server 16.04
- **Zenbot version** (commit ref, or version): 5a604de1cb5beb94157629e7a19e3c7bf3e80088
- **Zenbot branch**: unstable
- **NodeJS version**: 8.11.1
- **Python version (when using a python script)**: -
- **Exact command to reproduce (include everything)**: `npm i && ./zenbot.sh trade --paper`
- **Did I make any changes to conf-sample.js?**: No

### Describe the problem
I started to install Zenbot following the quick-start from the documentation. I have a web gui that seems broken on Chrome (version 66.0.3359.139) due to webpack bundle I think (see the screenshot).

### Source code / Error logs
Chrome console : 
> Refused to apply style from 'http://212.47.231.67:20027/assets-wp/app.bundle.js' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

![zenbot-webgui](https://user-images.githubusercontent.com/6691104/39571329-5f94d320-4ecb-11e8-897e-900de0343442.PNG)

**Comment by defkev** [comment]
Webpack bundles everything (JS & CSS) in one file, i was suspecting this to bite us in the butt at some point.

Usually the browser should just load it regardless of MIME but with "strict MIME-Type checking" enabled this of course doesn't work.
And as it seems there is no simple way to do just that in Chrome, without disabling "everything" at least - i am not using Chrome so never tested this to begin with.

Also refrain from running the bot on a public interface, as i can access your dashboard :wink:

**Comment by defkev** [comment]
Looks like this can be somewhat easily accomplished using ExtractTextWebpackPlugin

Let me prep a PR, brb

**Comment by defkev** [comment]
Ready at #1582

Give it a try and let me know.

**Comment by percenuage** [comment]
Hi thank you for your fix. Unfortunately the issue persists. See the
following screenshot :

![zenbot-error-1](https://user-images.githubusercontent.com/6691104/39597468-cd74a1c8-4f15-11e8-9d2e-13b3fb7719a9.PNG)

(it's not working on IE too).

**Comment by defkev** [comment]
Just tested and works for me in IE and Edge.

If the server is responding with a 404 the assets are missing all along, verify that the (now) three files are indeed present in `/zenbot/dist/` after `npm install` and `wepack -p` doesn't throw anything fancy during npm's postinstall at the `bundling WebApp components` step.

**Comment by percenuage** [comment]
Ok I understand now !!! In fact, I didn't notice that the `npm postinstall` wasn't run after `npm install`.
You can see the discret warning from npm : `npm WARN lifecycle zenbot4@4.1.0~postinstall: cannot run in wd %s %s (wd=%s) zenbot4@4.1.0 node post_install.js /root/zenbot`. And you have already respond about this issue [here](https://github.com/DeviaVir/zenbot/issues/1176) because I'm root user ...
After running the script manually (`npm start postinstall`) or using `npm install --unsafe-perm`, everything works! :)

So, maybe you're PR is no longer necessary ? Thanks a lot ^^

Last question, do you know how may I easily add the strategy name in the dashboard ? :)

**Comment by defkev** [comment]
Running the bot as root is not necessary and generally bad practice as it doesn't just pose a possible security risk (worst case some yet unknown backdoor in express which **could** grand a attacker remote access) but you will also miss out all the fancy stuff like memory management and what not, the system enforces on non-root users, which could cause the bot to crash/freeze on specific race conditions.

Considering the bot is handling (more or less) valuable assets i would refrain from doing so.

**Comment by percenuage** [comment]
I understand thank you 😃
