### ISSUE TITLE
Place order (market and limit) give zero price and infinite volume

### ISSUE THREAD

**Issue by njannink** [DeviaVir/zenbot#1592]
Hello I'm adding support for the lykke exchange (www.lykke.com) and when I make a trade I get a price of 0 and a volume of Infinite:

`{ price: '0.00',
  size: 'Infinity',
  fee: null,
  orig_size: 'Infinity',
  remaining_size: 'Infinity',
  orig_price: '0.00',
  order_type: 'maker',
  cancel_after: 'day',
  product_id: 'EOS-BTC',
  post_only: true }`

Even though I have a balance and quotes. Any idea what is going wrong?

2018-05-13 19:00:00  0.00185000 EOS-BTC   +0.00%        4     - 46.15    -1.2210   0.3815     sell  0.00000000 EOS  0.20753246 BTC   +0.00%  +18.43%

2018-05-14 15:32:26  0.00169900 EOS-BTC   -8.17%        2    -- 44.67    -1.6557   0.3836           0.00000000 EOS  0.20753246 BTC   +0.00%  +28.95%

**Comment by defkev** [comment]
> price: '0.00', size: 'Infinity'

Just a guess but you aren't dividing by zero?

**Comment by njannink** [comment]
no no deviding I just pass the values from the lykke exchange to zenbot. I saw that its working for BTC-USD so maybe it has something to do with the small prices behind zero in case of EOS-BTC?

**Comment by brucetus** [comment]
order size is calculated using your balance/deposit, which for many people recently has been incorrectly returning as 0 or null

**Comment by defkev** [comment]
Order size is calculated using buy/sell_pct, on a non-positive balance the bot will error out with insufficient funds will preparing a order.

If the balance doesn't get reported at all take a look at balance.js, as @illya13 did fix something? in #1573 only a couple of days ago this might also apply to engine.js

I have yet to see the error myself on any of my running bots though.
