### ISSUE TITLE
Backfill dont import all data

### ISSUE THREAD

**Issue by fgomezserna** [DeviaVir/zenbot#1602]
System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Zenbot version** (commit ref, or version): Last version
- **Zenbot branch**: Master
- **NodeJS version**: v8.11.2
- **Exact command to reproduce (include everything)**: ./zenbot.sh backfill binance.ADA-BNB --days 100
- **Did I make any changes to conf-sample.js?**: No

### Describe the problem
When i run backfill command zenbot return this error:
getTrades() returned no trades, retrying with smaller interval.

getTrades() returned no trades, retrying with smaller interval.

binance.ADA-BNB saved 276 trades 36 days left
.......................
binance.ADA-BNB saved 5829 trades 35 days left
.......................
binance.ADA-BNB saved 7807 trades 34 days left
.......................
binance.ADA-BNB saved 3344 trades 33 days left
........................
binance.ADA-BNB saved 4044 trades 32 days left
.......................
binance.ADA-BNB saved 4997 trades 31 days left
.......................
binance.ADA-BNB saved 6554 trades 30 days left
.......................
binance.ADA-BNB saved 4100 trades 29 days left
.............
skipping 681 hrs of previously collected data

binance.ADA-BNB saved 2046 trades 1 days left

Why dont import all data?

Ty very much

**Comment by defkev** [comment]
I am mildly confused, what do you mean with "all data"?

Its not up to us but the exchange to decide how far his backlog goes, e.g. if you want the last 100 days using `--days 100` but the exchange only provides the last 37 days, there isn't too much we can do about it.

**Comment by JohnnyVicious** [comment]
I have seen this also a few times, something gets corrupted sometimes and backfill just stops without any other reason, always on the same day for the same pair until you drop the table and start a backfill from the start. The next time it will go past that day, so something that makes the command error coz of a hickup, haven't seen it the past weeks but will do some debugging on it next time.

**Comment by JohnnyVicious** [comment]
Completely misread this issue, confused with something else and my apologies for that, the ADA-BNB pairing didn't exist before that time period I assume, it started april 17th.
Gonna assume this can be closed @DeviaVir
