### ISSUE TITLE
Issue while installing zenbot

### ISSUE THREAD

**Issue by vipul8907** [DeviaVir/zenbot#1603]
Hi
I am getting the following error while doing npm install in the console for installing zenbot.

### Source code / Error logs
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.8.3/win32-ia32-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.8.3/win32-ia32-64_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> talib@1.0.4 install C:\Users\Vipul Sharma\zenbot\node_modules\talib
> node ./src/lib/build.js && node-gyp configure && node-gyp build

building talib functions...
fs.js:143
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir 'C:/Program Files/Reference Assemblies/Microsoft/Framework/.NETFramework'
    at Object.fs.readdirSync (fs.js:893:3)
    at Object.<anonymous> (C:\Users\Vipul Sharma\zenbot\node_modules\talib\src\lib\build.js:22:30)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.0 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! talib@1.0.4 install: `node ./src/lib/build.js && node-gyp configure && node-gyp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the talib@1.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Vipul Sharma\AppData\Roaming\npm-cache\_logs\2018-05-29T23_09_29_263Z-debug.log

Could someone please help.

**Comment by liangchen815** [comment]
me too

**Comment by liangchen815** [comment]
Error: ENOENT: no such file or directory, scandir 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.<anonymous> (E:\zenbot\node_modules\talib\src\lib\build.js:22:30)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.0 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! talib@1.0.4 install: `node ./src/lib/build.js && node-gyp configure && node-gyp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the talib@1.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Leon\AppData\Roaming\npm-cache\_logs\2018-05-30T03_24_15_185Z-debug.log

E:\zenbot>npm install
npm ERR! path E:\zenbot\node_modules\forex.analytics
npm ERR! code EISGIT
npm ERR! git E:\zenbot\node_modules\forex.analytics: Appears to be a git repo or submodule.
npm ERR! git     E:\zenbot\node_modules\forex.analytics
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Leon\AppData\Roaming\npm-cache\_logs\2018-05-30T03_25_23_462Z-debug.log

E:\zenbot>npm install
npm ERR! path E:\zenbot\node_modules\forex.analytics
npm ERR! code EISGIT
npm ERR! git E:\zenbot\node_modules\forex.analytics: Appears to be a git repo or submodule.
npm ERR! git     E:\zenbot\node_modules\forex.analytics
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Leon\AppData\Roaming\npm-cache\_logs\2018-05-30T03_27_19_248Z-debug.log

**Comment by DeviaVir** [comment]
Please use the issue template.
