### ISSUE TITLE
Binance error

### ISSUE THREAD

**Issue by brucetus** [DeviaVir/zenbot#1613]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian 9
- **Zenbot version** (commit ref, or version): current unstable
- **Exact command to reproduce (include everything)**: ./zenbot.sh trade binance.BTC-USDT
- **Did I make any changes to conf-sample.js?**: no

### Describe the problem
Binance is giving me the "Way too many requests" error when backfilling and wants us to use the websocket instead 

### Source code / Error logs
<img width="897" alt="screen shot 2018-06-10 at 11 56 23 pm" src="https://user-images.githubusercontent.com/31704711/41216748-69b0be3e-6d0a-11e8-85c9-be1f9d856e56.png">

**Comment by JohnnyVicious** [comment]
I have about 150 dockers running to Binance and never get this ban, how many requests do you do to come to that point?? 
Just so I know, I did change the polling settings to 30s but still.

**Comment by brucetus** [comment]
Wow that's crazy, I was running like 20 instances. My polling rate was at 30s too. I think the problem may have been because I was trying to backfill multiple instances at the same time. Either way that ban was temporary.

**Comment by JohnnyVicious** [comment]
Oh yeah, I use a backfill script on one node that does it for each trading pair in serial, not concurrent, and slowly filled my central mongodb up every day by adding like 5 more days.
The issue you opened is a thing we gotta address nevertheless.

**Comment by brucetus** [comment]
Actually I just made a pull request that backfills data from Binance using candle data instead of raw trade data. It was merged today. It calls the API way less and backfills like 20x faster. This could completely solve the problem but we won't know for sure unless we get another error like above.
