### ISSUE TITLE
Balance command doesn't listen to selector input

### ISSUE THREAD

**Issue by brucetus** [DeviaVir/zenbot#1619]
When running ./zenbot.sh balance binance.BTC-USDT zenbot returns error that I haven't provided my GDAX credentials. Seems like it is ignoring the selector option and trying to get the balance for the default selector in conf.js, gdax.BTC-USD

<img width="739" alt="screen shot 2018-06-13 at 11 06 42 pm" src="https://user-images.githubusercontent.com/31704711/41394365-84285cf8-6f5e-11e8-9bb8-eeb13ff3a233.png">

**Comment by Tribic** [comment]
same here :( 
no idea what could be the reason.
