### ISSUE TITLE
GDAX API is down! unable to call getOrder, retrying in 10s

### ISSUE THREAD

**Issue by lurker02** [DeviaVir/zenbot#1637]
**System information**
**Have I written custom code (as opposed to using zenbot vanilla):** No
**OS Platform and Distribution (e.g., Linux Ubuntu 16.04):** Ubuntu 18.04 LTS 64 bit
**Zenbot version (commit ref, or version):** latest unstable
**Zenbot branch:** don't know
**NodeJS version:** 8.11.3
**Python version (when using a python script):** 2.7.15rc1
**Exact command to reproduce (include everything):**
./zenbot.sh trade --conf ./conf.js
**Did I make any changes to conf-sample.js?:** No

The process repeatedly generates the error message below. It was preceded by an unsuccessful buy order which eventually got canceled (marked Canceled on the gdax page). I also tried canceling it manually using the 'c' command but it didn't help - the bot was no longer "buying" yet kept throwing the exception.  

> 2018-06-23 06:00:07  6141.21 BTC-USD   +0.03%        2   71.83 +++     0.0549   0.0755   -0.06%  0.00003 BTC  1972.82 USD   -0.21%   -0.54%

> GDAX API is down! unable to call getOrder, retrying in 10s
{ Error: HTTP 404 Error: NotFound
    at Request._callback (/home/van/zenbot/node_modules/gdax/lib/clients/public.js:68:15)
    at Request.self.callback (/home/van/zenbot/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/van/zenbot/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/van/zenbot/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
  response: 
   IncomingMessage {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events: 
      { end: [Array],
        close: [Array],
        data: [Function],
        error: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     socket: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'api.gdax.com',
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'api.gdax.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 371,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 2814739,
        _destroyed: false,
        [Symbol(asyncId)]: 315657,
        [Symbol(bytesRead)]: 853,
        [Symbol(asyncId)]: 315668,
        [Symbol(triggerAsyncId)]: 315664 },
     connection: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'api.gdax.com',
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'api.gdax.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 371,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 2814739,
        _destroyed: false,
        [Symbol(asyncId)]: 315657,
        [Symbol(bytesRead)]: 853,
        [Symbol(asyncId)]: 315668,
        [Symbol(triggerAsyncId)]: 315664 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers: 
      { date: 'Sat, 23 Jun 2018 09:46:48 GMT',
        'content-type': 'application/json; charset=utf-8',
        'content-length': '22',
        connection: 'close',
        'set-cookie': [Array],
        'access-control-allow-headers': 'Content-Type, Accept, cb-session, cb-fp',
        'access-control-allow-methods': 'GET,POST,DELETE,PUT',
        'access-control-allow-origin': '*',
        'access-control-expose-headers': 'cb-before, cb-after, cb-gdpr',
        'access-control-max-age': '7200',
        etag: 'W/"16-osMlA0gxCAnmtiKBe1inhP+EK48"',
        'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
        'x-content-type-options': 'nosniff',
        'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
        server: 'cloudflare',
        'cf-ray': '42f607937d90574d-IAD' },
     rawHeaders: 
      [ 'Date',
        'Sat, 23 Jun 2018 09:46:48 GMT',
        'Content-Type',
        'application/json; charset=utf-8',
        'Content-Length',
        '22',
        'Connection',
        'close',
        'Set-Cookie',
        '__cfduid=ddae22e454a5e737ea0742910ee844a381529747208; expires=Sun, 23-Jun-19 09:46:48 GMT; path=/; domain=.gdax.com; HttpOnly',
        'Access-Control-Allow-Headers',
        'Content-Type, Accept, cb-session, cb-fp',
        'Access-Control-Allow-Methods',
        'GET,POST,DELETE,PUT',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'cb-before, cb-after, cb-gdpr',
        'Access-Control-Max-Age',
        '7200',
        'ETag',
        'W/"16-osMlA0gxCAnmtiKBe1inhP+EK48"',
        'Strict-Transport-Security',
        'max-age=31536000; includeSubDomains; preload',
        'X-Content-Type-Options',
        'nosniff',
        'Expect-CT',
        'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
        'Server',
        'cloudflare',
        'CF-RAY',
        '42f607937d90574d-IAD' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: '',
     method: null,
     statusCode: 404,
     statusMessage: 'Not Found',
     client: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'api.gdax.com',
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'api.gdax.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 371,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 2814739,
        _destroyed: false,
        [Symbol(asyncId)]: 315657,
        [Symbol(bytesRead)]: 853,
        [Symbol(asyncId)]: 315668,
        [Symbol(triggerAsyncId)]: 315664 },
     _consuming: true,
     _dumped: false,
     req: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /orders/32e62c18-8530-4f49-ba0c-5e7198df38e6 HTTP/1.1\r\nUser-Agent: gdax-node-client\r\nAccept: application/json\r\nContent-Type: application/json\r\nCB-ACCESS-KEY: a90c55dc3790f41d3bb7e4fa0441d155\r\nCB-ACCESS-SIGN: 3DdwRYeOcmmOclbDpNZdKJC9Bd8pUNuXZZD9gXyQQe0=\r\nCB-ACCESS-TIMESTAMP: 1529747207.302\r\nCB-ACCESS-PASSPHRASE: 1secii2rkwb\r\nhost: api.gdax.com\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/orders/32e62c18-8530-4f49-ba0c-5e7198df38e6',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: [Function: emitTimeout],
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(outHeadersKey)]: [Object] },
     request: 
      Request {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        headers: [Object],
        method: 'GET',
        uri: [Object],
        qsStringifyOptions: [Object],
        timeout: 10000,
        callback: [Function],
        readable: true,
        writable: true,
        explicitMethod: true,
        _qs: [Object],
        _auth: [Object],
        _oauth: [Object],
        _multipart: [Object],
        _redirect: [Object],
        _tunnel: [Object],
        setHeader: [Function],
        hasHeader: [Function],
        getHeader: [Function],
        removeHeader: [Function],
        localAddress: undefined,
        pool: {},
        dests: [],
        __isRequestRequest: true,
        _callback: [Function],
        proxy: null,
        tunnel: true,
        setHost: true,
        originalCookieHeader: undefined,
        _disableCookies: true,
        _jar: undefined,
        port: 443,
        host: 'api.gdax.com',
        path: '/orders/32e62c18-8530-4f49-ba0c-5e7198df38e6',
        httpModule: [Object],
        agentClass: [Object],
        agent: [Object],
        _started: true,
        href: 'https://api.gdax.com/orders/32e62c18-8530-4f49-ba0c-5e7198df38e6',
        req: [Object],
        ntick: true,
        timeoutTimer: null,
        response: [Circular],
        originalHost: 'api.gdax.com',
        originalHostHeaderName: 'host',
        responseContent: [Circular],
        _destdata: true,
        _ended: true,
        _callbackCalled: true },
     toJSON: [Function: responseToJSON],
     caseless: Caseless { dict: [Object] },
     read: [Function],
     body: '{"message":"NotFound"}' },
  data: { message: 'NotFound' } }
[ { order_id: '32e62c18-8530-4f49-ba0c-5e7198df38e6',
    product_id: 'BTC-USD' } ]

**Comment by sahaka** [comment]
This also happens to me if I leave zenbot on for extended periods of time or overnight. The api is still up yet zenbot thinks it is down. The only way I have fixed it is to restart the bot...

**Comment by mixisLv** [comment]
+1

**Comment by mrseeker** [comment]
cloudflare protection kicks in and kills the bot...

**Comment by mixisLv** [comment]
Run Zenbot with `--debug` and check is websocket connection working.

**Comment by nosekefik** [comment]
I have the same problem, when bot try to place an order, any solution for it?

**Comment by simonholmbring** [comment]
same here

**Comment by mrseeker** [comment]
I think I found the issue at play here:

https://github.com/DeviaVir/zenbot/blob/607fde5661292711ca6578d9a360c34c4d573d94/extensions/exchanges/gdax/exchange.js#L495-L504

The last lines should be put before the previous "if (err)" command, since that command will always be hit due to the 404, causing the bot to error out before it has a chance to cancel the order.

**Comment by dgallig** [comment]
Same error here!
