### ISSUE TITLE
move 3.x MongoDB to 4.x

### ISSUE THREAD

**Issue by nedievas** [DeviaVir/zenbot#165]
I have been running Bitfinex backfill for some time. Is it possible or useful to dump zenbot 3.x mongodb and restore it to zenbot 4.x mongodb?

**Comment by DeviaVir** [comment]
I think we would have to support bitfinex in 4.x first, and even then I'd advise just to run a new backfill instead of going through the problem of migrating..

**Comment by nedievas** [comment]
Obsolete as zenbot 3 data backfiller is offline. No need to migrate.
