### ISSUE TITLE
No Webpages on start

### ISSUE THREAD

**Issue by diveyez** [DeviaVir/zenbot#1654]
When started, as stated, there is no web page output mentioned.

**Comment by exp-cryp** [comment]
When you initialise a live trade command you should see "Web GUI running on http://10.8.151.211:200XX/" under starting live trading where XX will be different for each trading pair. Make sure to do the following to see the output for the bot:

1) Update the IP address ("10.8.151.211") to your IP address from which zenbot is running.

2) Make sure to keep the the port number as shown in the terminal.

3) After you have loaded the web GUI in your browser, scroll down and you should see the output (the data point are approximately half way down the page).

I hope this helps.

**Comment by diveyez** [comment]
STALE
