### ISSUE TITLE
Version control database dir?

### ISSUE THREAD

**Issue by jraviotta** [DeviaVir/zenbot#1657]
Should `database/*` be included in `.gitignore`? It seems like it should be. Happy to create a PR if that's helpful.

**Comment by DeviaVir** [comment]
you mean the dir generated by https://github.com/DeviaVir/zenbot/blob/unstable/docker-compose.yml#L25 ?

I suppose it doesn't hurt.

**Comment by jraviotta** [comment]
Submitted #1658
