### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by felipecaldas** [DeviaVir/zenbot#166]
Hi,

Running Zenbot on a docker container and get the error when running zenbot binary.

> root@261fc057e1db:/app# zenbot  backfill poloniex.BCN-BTC --days 2
> : No such file or directory
> root@261fc057e1db:/app# zenbot help
> : No such file or directory
> root@261fc057e1db:/app# zenbot list-strategies
> : No such file or directory
> root@261fc057e1db:/app# ls -ltr
> total 80
> -rwxr-xr-x   1 root root   745 May 20 19:51 zenbot.sh
> drwxr-xr-x   2 root root  4096 May 20 19:51 templates
> -rwxr-xr-x   1 root root   732 May 20 19:51 package.json
> drwxr-xr-x   2 root root  4096 May 20 19:51 lib
> -rwxr-xr-x   1 root root   635 May 20 19:51 index.js
> drwxr-xr-x   5 root root  4096 May 20 19:51 extensions
> -rwxr-xr-x   1 root root   359 May 20 19:51 docker-compose.yml
> drwxr-xr-x   2 root root  4096 May 20 19:51 db
> -rwxr-xr-x   1 root root  2289 May 20 19:51 conf-sample.js
> drwxr-xr-x   2 root root  4096 May 20 19:51 commands
> -rwxr-xr-x   1 root root  1601 May 20 19:51 boot.js
> drwxr-xr-x   2 root root  4096 May 20 19:51 assets
> -rwxr-xr-x   1 root root   221 May 20 19:51 _codemap.js
> -rwxr-xr-x   1 root root 13283 May 20 19:51 README.md
> -rwxr-xr-x   1 root root    65 May 20 19:51 Dockerfile
> -rw-r--r--   1 root root  2357 May 20 20:05 conf.js
> drwxr-xr-x 145 root root  4096 May 20 20:06 node_modules
> root@261fc057e1db:/app# zenbot trade --paper
> : No such file or directory
> root@261fc057e1db:/app#

Any idea what this might be?
Thanks

**Comment by stevepm** [comment]
try `./zenbot.sh trade --paper`

**Comment by felipecaldas** [comment]
@stevepm thanks, but unfortunately it didn't work:

root@261fc057e1db:/app# ./zenbot.sh trade --paper
: No such file or directory

I tried running on my Mac, no docker and worked fine... not sure exactly what this might be. Cheers

**Comment by nao0811ta** [comment]
you need to execute in directory includes zenbot.sh script.

**Comment by DeviaVir** [comment]
might need to `chmod +x zenbot.sh` after which you can use
`./zenbot.sh trade --paper`
That is definitely the way it should work. Note we do it the same way here:
https://github.com/carlos8f/zenbot#docker

Assuming you no longer have this problem, I'll close this ticket for now. If you do, feel free to comment.
