### ISSUE TITLE
StdDev Strategy not places orders

### ISSUE THREAD

**Issue by nosekefik** [DeviaVir/zenbot#1673]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS High Sierra 10.13.6
- **Zenbot version** (commit ref, or version):  #f6cf772 
- **Zenbot branch**: Unstable 
- **NodeJS version**:  v8.11.3
- **Python version (when using a python script)**: v3.6
- **Exact command to reproduce (include everything)**:  node zenbot trade --paper --period=100ms
- **Did I make any changes to conf-sample.js?**: Yes, only change strategy and set gdax.BTC-EUR

### Describe the problem
StdDev works well on simulation, but not places orders on trading (paper or live) apparently is working
I tested it for 2 days and on  poloniex.BTC-USDT, gdax.BTC-EUR, gdax.ETH-EUR

**Comment by Shawn8901** [comment]
Are you really trying to use a 100ms period?! Try please a higher period length (>1min)

**Comment by nosekefik** [comment]
Is the config on the documentation, I can test more
