### ISSUE TITLE
[Bug] forex.analytics: Appears to be a git repo or submodule.

### ISSUE THREAD

**Issue by sxiii** [DeviaVir/zenbot#1678]
The bot isn't working. Trouble on step "npm install". 

- I didn't touched anything in the code. I'm using zenbot vanilla (actually the instructions)
- Ubuntu 18.04 LTS (bionic)
- Current unstable version of zenbot
- NodeJS v8.11.3
- npm install
- I didn't make any changes.

### Source code / Error logs
```
s@mainframe:/media/s/ManjaroHome/zenbot$ npm install
npm ERR! path /media/s/ManjaroHome/zenbot/node_modules/forex.analytics
npm ERR! code EISGIT
npm ERR! git /media/s/ManjaroHome/zenbot/node_modules/forex.analytics: Appears to be a git repo or submodule.
npm ERR! git     /media/s/ManjaroHome/zenbot/node_modules/forex.analytics
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/s/.npm/_logs/2018-08-10T02_27_54_887Z-debug.log
```

[2018-08-10T02_27_54_887Z-debug.log](https://github.com/DeviaVir/zenbot/files/2276395/2018-08-10T02_27_54_887Z-debug.log)

**Comment by meU3** [comment]
me too! Trying to install zenbot, but have the same problem :(
may be pre-gyp does not work?

**Comment by meU3** [comment]
Failed on the tulind@0.8.10 install script

**Comment by Shawn8901** [comment]
Remove the forex.analytics folder once manually. There should be an after_install script which removes the git stuff, but that's only executed if there was no other error. 
You should afterwards also check the output of non install.

Edit if you read the logs careful, it's also written there that you should update this specific module manually or move the git stuff away

**Comment by biovolt** [comment]
I get the same error
