### ISSUE TITLE
Can't install the bot. 

### ISSUE THREAD

**Issue by meU3** [DeviaVir/zenbot#1680]
Can't install the bot. Trouble on step "npm install".

- I didn't touched anything in the code. I'm using zenbot vanilla (actually the instructions)
- Ubuntu 16.04 LTS (bionic)
- Current of zenbot
- NodeJS v8.11.3
- npm install
- I didn't make any changes.

```
node-pre-gyp ERR! Completion callback never invoked! 
node-pre-gyp ERR! System Linux 4.15.17-1-pve
node-pre-gyp ERR! command "/usr/bin/node" "/root/zenbot/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /root/zenbot/node_modules/tulind
node-pre-gyp ERR! node -v v8.11.3
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! This is a bug in node-pre-gyp.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.0 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! tulind@0.8.10 install: node-pre-gyp install --fallback-to-build
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the tulind@0.8.10 install 

```
starting with root@CT102:~/zenbot# ./zenbot.sh trade --paper

```
module.js:549
    throw err;
    ^

Error: Cannot find module './build/Release/analytics.node'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/zenbot/node_modules/forex.analytics/index.js:1:79)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

```

**Comment by barskuk** [comment]
you have to install not under root

**Comment by meU3** [comment]
Trying to install not under root
Nothing changed
`meu3@zen:~/zenbot$ npm install

> forex.analytics@0.0.14 preinstall /home/meu3/zenbot/node_modules/forex.analyti                                                                                                 cs
> node ./lib/ta-lib/build.js

building talib functions...

> tulind@0.8.10 install /home/meu3/zenbot/node_modules/tulind
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Completion callback never invoked!
node-pre-gyp ERR! System Linux 4.15.17-1-pve
node-pre-gyp ERR! command "/usr/bin/node" "/home/meu3/zenbot/node_modules/.bin/n                                                                                                 ode-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/meu3/zenbot/node_modules/tulind
node-pre-gyp ERR! node -v v8.11.4
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not he                                                                                                 lp:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed.                                                                                                  You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.0 (node_modules/fse                                                                                                 vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                                                                                 1.2.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}                                                                                                 )

npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! tulind@0.8.10 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 6
npm ERR!
npm ERR! Failed at the tulind@0.8.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                                 ging output above.

npm ERR! A complete log of this run can be found in:
`

**Comment by meU3** [comment]
I can solve my problem with
`npm audit fix`
it's resolve libraries and fixing some problems. But! You need to start this command twice or more times.
If your npm does not support "audit" command  - just update npm.

**Comment by yaotian** [comment]
npm audit fix can't work.
I am in Ubutun18 and get same problem.

**Comment by meU3** [comment]
You must update npm. I'm foget command, but when you enter npm audit fix, just read output. I find command here. ubuntu 16.04.

**Comment by yaotian** [comment]
yes. I did do the update the npm and selected the newest version. But still fail

**Comment by yaotian** [comment]
UPDATE: though the installation got failures, zenbot can run successfully.

**Comment by meU3** [comment]
:)   !

**Comment by RWiggers** [comment]
Try `npm install tulind --build-from-source`

**Comment by mroxso** [comment]
`npm install tulind --build-from-source` fixed my problem!

**Comment by rondijkstra** [comment]
> `npm install tulind --build-from-source` fixed my problem!

It didn't work out for me.. I'm still missing:

```
Error: Cannot find module './build/Release/analytics.node'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
```

Am on Mac btw.

**Comment by ZeroCool940711** [comment]
Is there any fix for this?
im having this exact same problem, tried on windows, ubuntu and even on WSL on windows and I get the exact same error no matter what I do.

**Comment by BAKFR** [comment]
@ZeroCool940711 Did you try with the last version ?
I've fixed an install bug with tulind two days ago.

If you still have an error, could you post the entire `npm install` output ?

**Comment by ZeroCool940711** [comment]
@BAKFR I downloaded the code today again after been away from zenbot for a while, I did everything according to the readme.md file and even searched a lot for issues about for this problem, Ive tried everything I could find, still not working.

**Comment by BAKFR** [comment]
@ZeroCool940711 please, gives us the exact error displayed on your screen. We can't help you without it.

**Comment by ZeroCool940711** [comment]
@BAKFR this is the error im getting, exactly the same as @meU3 
```module.js:549
    throw err;
    ^

Error: Cannot find module './build/Release/analytics.node'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/zerocool/zenbot/node_modules/forex.analytics/index.js:1:79)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)```

**Comment by seanpowell** [comment]
Try running `npm install forex.analytics`
It should force a (re)build of the analytics module.
