### ISSUE TITLE
[windows] npm install error:

### ISSUE THREAD

**Issue by shnmhrjn** [DeviaVir/zenbot#1699]
I am unable to install  zenbot in my windows 10 .

After cloing from repository , I did "npm install" which resulted in following issue.

> Error: ENOENT: no such file or directory, scandir 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework'

![error](https://user-images.githubusercontent.com/7370408/44944281-baf3d400-adf3-11e8-9c32-30f04a29b4f1.PNG)

How do i solve this?

Hoping for response soon.

Regards,

**Comment by AuPierrick** [comment]
I have the same error, what I can do?
