### ISSUE TITLE
Can't get zenbot sim to output ROI or list any simulated trades

### ISSUE THREAD

**Issue by xangma** [DeviaVir/zenbot#17]
The program makes actual trades fine when running with ./run.sh. All backfilled and reduced fine. Is the ROI output function still under development? The action array also returns empty after running sim. Hmmm.

**Comment by obsidian0001** [comment]
I'm having the same problem as well.

**Comment by xangma** [comment]
Ah in that case it's probably not developed yet. If that's the case, then there is no issue - sorry!

**Comment by obsidian0001** [comment]
Likely so. However, it was in previous versions. Perhaps it fell through the cracks. I'm sure it wouldn't be too difficult to add. Just a matter of analyzing the P/L of each trade.

**Comment by xangma** [comment]
3.1.2 has fixed this! Thanks!
