### ISSUE TITLE
Strange % values in balance \ profit columns in SSH GUI

### ISSUE THREAD

**Issue by donaldforest** [DeviaVir/zenbot#1711]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian 9
- **Zenbot version** (commit ref, or version): Commits on Sep 16, 2018
- **Zenbot branch**: master
- **NodeJS version**: v10.10.0
- **Python version (when using a python script)**: 2.7.13
- **Exact command to reproduce (include everything)**:
- **Did I make any changes to conf-sample.js?**: No

HitBTC exchange

### Describe the problem
![hitbtc](https://user-images.githubusercontent.com/33358791/45608906-0ba73600-ba5e-11e8-98a1-315f0643e725.PNG)

AND
![zen](https://user-images.githubusercontent.com/33358791/45655951-6d61b180-baeb-11e8-8106-df91a77a97d3.PNG)

**Comment by mrseeker** [comment]
As mentioned multiple times, this happens when a trade gets partially filled during an update request. It will cause the total amount to be different than it should. Resetting the bot fixes it, but needs a permanent solution.
