### ISSUE TITLE
Error starting zenbot_server in docker (Windows)

### ISSUE THREAD

**Issue by Kermel** [DeviaVir/zenbot#1717]
Hi, I have Windows 7, docker toolbox installed.

I did all the steps described for running zenbot in docker but I always end on failures with starting the server:

`o:\CryptoBots\Zenbot>docker-compose --file=docker-compose-windows.yml up
Starting zenbot_mongodb-data_1 ... done
Starting zenbot_mongodb_1      ... done
Starting zenbot_server_1       ... done
Attaching to zenbot_mongodb-data_1, zenbot_mongodb_1, zenbot_server_1
zenbot_mongodb-data_1 exited with code 0
server_1        | Error: Cannot find module './conf', falling back to conf-sample
server_1        | WARNING: MongoDB Connection Error:  { MongoNetworkError: failed to connect to server [172.17.0.3:27017] on first connect [MongoNetworkError: c
onnect ECONNREFUSED 172.17.0.3:27017]
server_1        |     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:505:11)
server_1        |     at emitOne (events.js:116:13)
server_1        |     at Pool.emit (events.js:211:7)
server_1        |     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:329:12)
server_1        |     at Object.onceWrapper (events.js:317:30)
server_1        |     at emitTwo (events.js:126:13)
server_1        |     at Connection.emit (events.js:214:7)
server_1        |     at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)
server_1        |     at Object.onceWrapper (events.js:315:30)
server_1        |     at emitOne (events.js:116:13)
server_1        |   name: 'MongoNetworkError',
server_1        |   message: 'failed to connect to server [172.17.0.3:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 172.17.0.3:27017]' }
server_1        | WARNING: without MongoDB some features (such as backfilling/simulation) may be disabled.
server_1        | Attempted authentication string: mongodb://172.17.0.3:27017/zenbot4?
server_1        | module.js:549
server_1        |     throw err;
server_1        |     ^
server_1        |
server_1        | Error: Cannot find module '/app/extensions/exchanges/sim/exchange'
server_1        |     at Function.Module._resolveFilename (module.js:547:15)
server_1        |     at Function.Module._load (module.js:474:25)
server_1        |     at Module.require (module.js:596:17)
server_1        |     at require (internal/module.js:11:18)
server_1        |     at module.exports (/app/lib/engine.js:29:20)
server_1        |     at Command.<anonymous> (/app/commands/trade.js:92:20)
server_1        |     at Command.listener (/app/node_modules/commander/index.js:315:8)
server_1        |     at emitTwo (events.js:126:13)
server_1        |     at Command.emit (events.js:214:7)
server_1        |     at Command.parseArgs (/app/node_modules/commander/index.js:651:12)
zenbot_server_1 exited with code 1`

(and this keeps repeating forever)

I even tried to change the conf-sample.js (comment out the entries c.mongo.host, port, username password and uncomment the c.mongo.connectionString providing the docker mongodb connection string but it didnt help)

The file conf.js also exists (just a copy of the conf-sample.js)

Plus that strange error with "Error: Cannot find module '/app/extensions/exchanges/sim/exchange'"
(of course the path /extensions/exchanges/sim/exchange) is there on my filesystem, "/app" is the docker stuff I guess...

Any ideas ?

**Comment by doedsjarl666** [comment]
I have the same issue. Windows 8.

**Comment by olexiyb** [comment]
Just FYI, I personally was able to run zenbot on windows without docker.  I only had some troubles to compile talib and had to install Visual Studio 2017 to build it

**Comment by Kermel** [comment]
Hi olexiyb. Could you please describe the way how you made it work - which modifications you made etc.? I have the Visual Studio so I would be able to build anything necessary but I think there were some config/build files updates as well maybe?

**Comment by olexiyb** [comment]
I have next installed
* Visual Studio Build Tools 2017
* Visual Studio Community 2017
* node.js 8.12, some package was not ready for latest node.js 10.

Run cmd with admin rights and install
`npm install --global windows-build-tools --vs2015`
You will get python and some staff installed for node.js
Run regular cmd
`npm config set msvs_version 2015`
`cd zenbot`
`npm install` or `yarn`

Hopefully you will get all required packages compiled for zenbot
