### ISSUE TITLE
Issue when running paper trading

### ISSUE THREAD

**Issue by urnotsam** [DeviaVir/zenbot#172]
I keep getting this error after a few hours of running zenbot.  

{ Error: getaddrinfo EAI_AGAIN api.gdax.com:443
    at Object.exports._errnoException (util.js:1050:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'EAI_AGAIN',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'api.gdax.com',
  host: 'api.gdax.com',
  port: 443 }

**Comment by antonanders** [comment]
I think it's a network problem. 
you could try to run a tool like "forever" to restart zenbot if it crashes. that's what i am doing currently.
simply run 
`sudo npm install -g forever`
`forever zenbot.sh trade`

**Comment by DeviaVir** [comment]
zenbot should still handle these kinds of things gracefully.

**Comment by carlos8f** [comment]
graceful retries are now a part of GDAX extension
