### ISSUE TITLE
System setup.

### ISSUE THREAD

**Issue by rondijkstra** [DeviaVir/zenbot#173]
Hi all gurus,

I have a hard time in setting this Zenbot system so, that it is doing some trading for me. 

I followed the guide as described on https://github.com/carlos8f/zenbot

1. git clone https://github.com/carlos8f/zenbot.git
2. I have copied conf-sample.js to conf.js and changed it to my polonium credentials.
3. Since I have docker installed (seemed a logical step to me; trusting the guide). I executed: 
cd zenbot
docker-compose build
docker-compose up
4. Then I should be able to get a list of selectors with the command zenbot list-selectors, but all I get at this step is: -bash: zenbot: command not found.

Pff what else is there to say.. I have a localhost-site running at localhost:27017. But that only shows me a text line with: "It looks like you are trying to access MongoDB over HTTP on the native driver port."

I was expecting that nice graphics etc.

Another point is what I don't get is that at some point I need to 'read' the history of the market; but I can't use the zenbot in a command box whatsoever.

As you can see; there are quite some open issues left to get it working. 

I can provide you with more info (if there's any) but I'm not aware of posting... lol

Many thanks if you find some time to help me out.

**Comment by felipecaldas** [comment]
There's a lot of things that you might want to consider studying and learning... Port 27017 is the mongo db port, so you should not be accessing it via the browser. 
Maybe start reading the mongodb manual, then follow to the nodejs manual. Then, maybe, come back to this project.

**Comment by rondijkstra** [comment]
Hehe, seems I have some homework to do. And all I was thinking that I was on the right way.
I made too many assumptions, like trusting that all would work well after going through the steps. 
I will check the documentation of the mentioned software.
Thanks!

**Comment by felipecaldas** [comment]
It's your best shot. Indeed, I also think the documentation needs the improve, but Carlos and his team and putting a lot of effort on getting bugs fixed and more features released (they released version 4, I believe).
The project is awesome and I am studying the code and the Docker/Composer configuration because it is also not working for me and, I would like to help exactly there if I can
Cheers and good luck.

Ps: I installed this on my MacOS yesterday (no Docker) and it's working just fine. If you're on Windows, Carlos said on his page for version 3 that he doesn't support that. Cheers.

**Comment by rondijkstra** [comment]
I am on a mac as well. The docker part just confused me a bit at the installation. Maybe working without docker is easier..
But to back you up; it looks like a nice project. I am doing similar work, though in another expertise. So I'm back to level n00b here. ;-)

**Comment by rondijkstra** [comment]
I found out that executing npm link gave an issue; zenbot wasn't placed into /usr/local/bin/ 
I can now finally use the zenbot 'command'..

**Comment by rondijkstra** [comment]
This is what I get now. It looks like a live stream from the coin, but nothing to be traded. 
<img width="697" alt="screen shot 2017-05-22 at 13 44 46" src="https://cloud.githubusercontent.com/assets/28846098/26307637/db751f54-3ef5-11e7-97bd-b7d2ddec40c1.png">

**Comment by DeviaVir** [comment]
Do you still have a specific issue here that you need help with, or did you resolve most of your problems?
