### ISSUE TITLE
Create a Helm-Chart for Zenbot

### ISSUE THREAD

**Issue by mkuendig** [DeviaVir/zenbot#180]
For the folks that use Kubernetes it would be fantastic to get native Helm support. 

https://github.com/kubernetes/helm

It is like apt-get install but a full container based environment is launched. Certainly much better than Docker Compose, particularly if you run it cloud based.

**Comment by adambarthelson** [comment]
Seems a little heavy duty for this app but I like it.  👍 👍 👍

**Comment by DeviaVir** [comment]
@adambarthelson not more heavy duty than the `docker-compose` included right now, me thinks.

**Comment by egorbenko** [comment]
@mkuendig i have no experience with Kubernetes, if you guys want to put it together and create a PR for it, you are more than welcome

**Comment by LoneWolf345** [comment]
This is getting pretty old.  Is anybody still looking into this?  Or should it be closed?

**Comment by DeviaVir** [comment]
I doubt it, it and if so a PR is always welcome.

**Comment by LarsAC** [comment]
Have started to work on a helm chart. A minimal setup is working locally, but does not support a lot of configuration items. Is there still interest in this ?

Lars
