### ISSUE TITLE
Unable to buy because funds on hold

### ISSUE THREAD

**Issue by lxwang** [DeviaVir/zenbot#181]
I'm using the zenbot buy function (by itself) on gdax, and it can't execute the buy even when there is plenty of money available

./zenbot.sh buy --size=10 --markup_pct=1 --order_adjust_time=60000 gdax.ETH-USD

buy delayed: +64.8% of funds (3236.50 USD USD) on hold

I have existing buy orders but that should not affect the zenbot function here.

**Comment by nedievas** [comment]
I also noticed this on Bitfinex. If I cancel existing orders, bot executes buy.

**Comment by DeviaVir** [comment]
This is by design, you cannot use the same funds for different orders.
