### ISSUE TITLE
GDAX is not offered in Germany. But Coinbase and Kraken.

### ISSUE THREAD

**Issue by fooness** [DeviaVir/zenbot#196]
Dear community,

unfortunately, GDAX is not offered to German traders. Maybe it would be possible to use Coinbase or Kraken instead. In the end, the user may decide which exchange to use, but please give us the ability.

also: https://github.com/carlos8f/zenbot/issues/177

**Comment by DeviaVir** [comment]
I think PR's adding support for more exchange are more than welcome, for a starting point see:
https://github.com/carlos8f/zenbot/tree/master/extensions

**Comment by fooness** [comment]
I think there already is a PR, which could be tested/reviewed.

https://github.com/Alexandre-io/zenbot/commit/586bb694016efc5115655bdf29bdf188caf1ca06

**Comment by natzar** [comment]
+1 to kraken or coinbase

**Comment by MCWiener101** [comment]
Since Coinbase is taking over GDAX, is GDAX still working, or Coinbase already working?

"GDAX transition: As part of the rebranding of Coinbase Exchange to GDAX, API endpoints have changed. The old *.exchange.coinbase.com endpoints have been discontinued as of Dec 6th, 2016." https://docs.gdax.com/#introduction

**Comment by micronax** [comment]
Gdax is working in Germany.

**Comment by DeviaVir** [comment]
And for Kraken, see:
https://github.com/carlos8f/zenbot/pull/207

**Comment by DeviaVir** [comment]
Actually, I'm opting to close this one:
- coinbase is not an exchange, please see GDAX
- kraken issue already exists over at https://github.com/carlos8f/zenbot/issues/177 (and now that there's a PR we don't need the extra visibility)

**Comment by decoye** [comment]
> Gdax is working in Germany.

it is, but its not officially supported says their faq here: https://support.gdax.com/customer/en/portal/articles/2425188-which-countries-and-states-can-access-gdax-
