### ISSUE TITLE
error: getTrades() returned duplicate results

### ISSUE THREAD

**Issue by kevupton** [DeviaVir/zenbot#199]
error: getTrades() returned duplicate results
{ product_id: 'BCN-BTC', to: 1494692503 }
{ product_id: 'BCN-BTC', to: 1494692503 }

Command:
./zenbot.sh backfill poloniex.BCN-BTC --days=40

Log:
poloniex.BCN-BTC saved 200 trades 40 days left
...........
poloniex.BCN-BTC saved 24801 trades 39 days left
...........
poloniex.BCN-BTC saved 30000 trades 38 days left
...........
poloniex.BCN-BTC saved 39493 trades 37 days left
...........
poloniex.BCN-BTC saved 36843 trades 36 days left
...........
poloniex.BCN-BTC saved 28543 trades 35 days left
...........
poloniex.BCN-BTC saved 41457 trades 34 days left
...........
poloniex.BCN-BTC saved 88369 trades 33 days left
...........
poloniex.BCN-BTC saved 47979 trades 32 days left
...........
poloniex.BCN-BTC saved 22899 trades 31 days left
...........
poloniex.BCN-BTC saved 46537 trades 30 days left
...........
poloniex.BCN-BTC saved 81210 trades 29 days left
...........
poloniex.BCN-BTC saved 34742 trades 28 days left
...........
poloniex.BCN-BTC saved 3032 trades 27 days left
............
poloniex.BCN-BTC saved 2826 trades 26 days left
..........
error: getTrades() returned duplicate results
{ product_id: 'BCN-BTC', to: 1494692503 }
{ product_id: 'BCN-BTC', to: 1494692503 }

**Comment by DeviaVir** [comment]
duplicates #188
