### ISSUE TITLE
Todo/backlong of tickets for zenbot

### ISSUE THREAD

**Issue by ch0wdan** [DeviaVir/zenbot#201]
Hey guys, 

I'm curious if there is any sort of backlog/todo tasks for future development of zenbot? 

Would like to help complete some tasks in my free time to make sure this thing doesn't just disappear and die off.

**Comment by DeviaVir** [comment]
I think this is already covered by:
https://github.com/carlos8f/zenbot#todo
and of course:
https://github.com/carlos8f/zenbot/issues
?
