### ISSUE TITLE
Add new GDAX selectors to the bot (ETH-EUR and LTC-EUR)

### ISSUE THREAD

**Issue by vitorego** [DeviaVir/zenbot#204]
Hi,
There is two new options on GDAX, ETH-EUR and LTC-EUR. Could be nice we you could add this two new selectors,

**Comment by vitorego** [comment]
I just modify the ETH/LTC-USD combinations to EUR inside products.json file and it seems to work.
Is only this file or there is anything else?

**Comment by micronax** [comment]
Try using `extensions/gdax/update-products.sh`

**Comment by vitorego** [comment]
I got this error:
update-products.sh: 2: update-products.sh: Syntax error: "(" unexpected

**Comment by DeviaVir** [comment]
@vitorego 
```
npm install
node extensions/gdax/update-products.sh
```

**Comment by vitorego** [comment]
it works now.
Thanks
