### ISSUE TITLE
"Reverse Trading"?

### ISSUE THREAD

**Issue by yonghan** [DeviaVir/zenbot#208]
I am trading on Poloniex with ETH/BTC. Zenbot's is trying to maximize BTC for me which is all good. I would like Zenbot to actually maximize ETH for me. How can I tweak the settings so maximizing ETH is possible?

Thanks!

**Comment by wbenny** [comment]
Isn't that the same thing, actually? If you maximize one side, the second side is per se maximized as well.

**Comment by yonghan** [comment]
Well never mind. I guess I am experiencing the "buy high, sell low" symptom that everybody else has.

**Comment by DeviaVir** [comment]
Yeah, that is exactly how that sounds like. This is covered in other issues (#189), so I'll be closing this one for now.
