### ISSUE TITLE
Unable to Trade GDAX.LTC-USD or GDAX.BTC-USD, not retrieving balance

### ISSUE THREAD

**Issue by nevernotrarekev** [DeviaVir/zenbot#210]
Live trading not recognizing currency balance or assets on GDAX.LTC-USD
With margin turned on or off.
When trying to manually trade, getting "not enough currency balance to buy!"

ETH/USD works fine.

**Comment by DeviaVir** [comment]
@nevernotkev did you by accident select the wrong API key profile? It should be `default`.
To verify, go to https://www.gdax.com/settings/api
- select "Default" profile
- create new key with "View" and "Trade" permissions checked
- update your conf.js

**Comment by DeviaVir** [comment]
Closing due to no response and feedback supplied. Feel free to leave a comment in case you are still having issues, and of course we will re-open if this is still a problem.

**Comment by nevernotrarekev** [comment]
I've tried your suggestion and still seeing issue. Even have margin turned on.

<img width="824" alt="screen shot 2017-06-09 at 2 49 01 am" src="https://user-images.githubusercontent.com/972100/26964144-3569a8f6-4cbe-11e7-8f46-74f9091e092a.png">
