### ISSUE TITLE
Add Market order (instead of limit)

### ISSUE THREAD

**Issue by Fjuxx** [DeviaVir/zenbot#220]
It would be great to have a market order function in the bot.

As it seems that limit orders rarley get filled, and if they get filled it is to late.
and at this moment only a few exchanges have free limit orders. most of them have a fee for all of them, so there is no real good reason to use limit orders on those exchanges.

i looked to update this myself. but i think it will quite a change as zenbot also checks if the limit order is filled or not. not sure how that will work with market orders.

**Comment by vitorego** [comment]
I think this could solve the low performance on real trading comparing with simulations. Since using short periods the orders sometimes take several minutes and we lose the profit window.

**Comment by DeviaVir** [comment]
Thinking perhaps short-term this could be a user-configurable setting. Long term we will want to have the bot decide what is smart.
