### ISSUE TITLE
Add currency capital to live trading

### ISSUE THREAD

**Issue by yodathegrey** [DeviaVir/zenbot#221]
It would be good to add the currency_capital switch to live trading to allow for mixed currency trading over the same account without incurring race conditions for funds.

**Comment by DeviaVir** [comment]
I'm not sure what you mean, do you mean we should be able to tell the bot with how much he is allowed to trade? (#174)

**Comment by yodathegrey** [comment]
yes, just like the paper trading capability with currency_capital but for live trading. that way if running different instances there won't be a race condition for funds.

**Comment by DeviaVir** [comment]
Okay, so this duplicates https://github.com/carlos8f/zenbot/issues/174, closing this ticket in favor of that one.
