### ISSUE TITLE
Manual interactive trade option

### ISSUE THREAD

**Issue by grleblanc** [DeviaVir/zenbot#224]
Hi, I've been following this project and using it for a few weeks and one thing I think Zenbot is missing, is the ability to manually interact with the bot.

ie: You're watching the console output and you just see on BCT/Twitter that something has happened to a token and you want to get out, and watch the the exchange rate for a few days. You simply press "s" in the console and it will automatically sell your current shares at the current market price. Or, "b" to buy, etc.

Example output could be (at the bottom of the console):
`[b] buy shares [s] sell shares `

I think even those two options at first would be helpful.

**Comment by deadchannelsky** [comment]
You can do the same basic thing with "zenbot sell --pct 100" and reversing
it with the zenbot @buy@ command. This is the primary way I use zenbot at
the moment as the live trading seems broken.

**Comment by grleblanc** [comment]
You're right and agreed. However, it might be cool to be able to do it right in the bot interface, without having to spawn Zenbot again, etc.

**Comment by carlos8f** [comment]
We now have support for this! also a `--manual` flag where the interactive controls control all of the trade decisions.

**Comment by Rinat056** [comment]
Hey. Help me, please, with advice.
How can I sell coins manually at the price of a bid, and not ask?
