### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by DeviaVir** [DeviaVir/zenbot#229]
As the amount of PR's grows, it would be great if we had unit tests for certain edge cases, so we can resolve once and retain forever :)

**Comment by carlos8f** [comment]
hmm, unit tests for what cases? Unit tests have to be deterministic, and the app behaves non-deterministically in trading and sim.

**Comment by DeviaVir** [comment]
@carlos8f I was thinking we could have unit tests for extensions and for engine. It would make it easier when reviewing PR's to make sure that different parts of zenbot that rely on different things still work as they should. It could prevent things like https://github.com/carlos8f/zenbot/issues/240

**Comment by Crim** [comment]
A test could use a deterministic mock/test extension to validate engine behavior in certain ways under various conditions

**Comment by tuxitor** [comment]
A lot of the errors I see comes from returning undefined (empty) values or wrong data type from the exchange.js files. It is a fackt of life the the different exchanges return different names and data types for the sam variables. The exchanges. js file is therefore the natural place to do the conversion and not leave the dirty work to the core functions, IMO

The errors manifests by bailing out and showing pointing to engine.js or even higher up in the execution stack. 

Most of these errors would usually be easy to fix if we had the data types defined in an easy to find place. And we have. The developers.md file (https://github.com/carlos8f/zenbot/blob/master/docs/developers.md) is the natural place where we already have some documentation for the API interfacing. Every variable exposed to the exchange.js file should have been here.

The same goes for the error handlig. most of it should be done on the inteface layer, but the codes returned to the core functions should be clearly defined and described.

If so, it would have been a lot easier to locate the errors.

I hope for devs who are familiar with the core code to look into this.  @carlos8f?
