### ISSUE TITLE
docker-compose up fails with server_1        `| Error: Cannot find module 'bitfinex-api-node'`

### ISSUE THREAD

**Issue by arphen** [DeviaVir/zenbot#248]
![image](https://user-images.githubusercontent.com/1078042/26971248-b2b065cc-4d0c-11e7-8a3c-a22c169c6d60.png)
on latest master

**Comment by nedievas** [comment]
npm update or install

**Comment by DeviaVir** [comment]
@arpheno

```
docker rmi zenbot_server
docker-compose build
docker-compose up -d
```

**Comment by arphen** [comment]
Not sure what's happening. 
`Dockerfile` has the `npm install`

I added `npm update` to `Dockerfile`, still same error:

![image](https://user-images.githubusercontent.com/1078042/26971616-2b80cb94-4d0e-11e7-84e9-03af5b308954.png)

**Comment by arphen** [comment]
`docker rmi -f zenbot_server`
`docker-compose rm server`
`docker-compose up --build`

Worked. Still super weird. My friend is building it from a clean system and it didn't work for him

**Comment by DeviaVir** [comment]
I think it is caused by outdated package-lock.json, but not sure yet.
https://github.com/carlos8f/zenbot/blob/master/package-lock.json

I ran into it a few times, and cleaning the image allowed me to truck on, so didn't look into it more.

**Comment by egorbenko** [comment]
`docker exec -it server_1 bash`
`rm package-lock.json`
`rm -f node_modules`
`npm install`

**Comment by carlos8f** [comment]
Had to update package-lock.json again with d9ac27adb3f89a838090a5770f15d1a5ffe20478 to fix 'pinkie-promise not found' error
