### ISSUE TITLE
Enhancement request. "getProducts()" function call

### ISSUE THREAD

**Issue by tuxitor** [DeviaVir/zenbot#260]
This request is a really too small for a PR.
For proper (early) initiatiation of the websocket functions we need one single parameter passed as an option to the
**getProducts** function on line 22 of the **lib/engine.js** file, The parameter is **s.product_id**

```js
    s.product_id = selector_parts[1]
    s.asset = s.product_id.split('-')[0]
    s.currency = s.product_id.split('-')[1]
    var products = s.exchange.getProducts(s.product_id)
    products.forEach(function (product) {
      if (product.asset === s.asset && product.currency === s.currency) {
        s.product = product
      }
    })
```

In the future it may prove useful to change the name to **exchangeInit(params)** and make it a callback for exchange spesific information such as API capabilities. Just a thought.

This change is desparately needed for further work on websockets implementation.
(Even the whole **s** object could have been passed. In that case it probably wold have been the smallest change ever. LOL)

**Comment by DeviaVir** [comment]
@eigilb I don't understand why this is "too small for a PR", nothing is too small for a PR. Could you send in a PR showcasing what you exactly need? I think that code is easier to reason about than words.

**Comment by tuxitor** [comment]
Never mind. The change is not necessary. Instead the needed information (product_id) is now generated from the command line params in "argv".
