### ISSUE TITLE
Bittrex: orders are not being placed

### ISSUE THREAD

**Issue by MCrypto** [DeviaVir/zenbot#261]
im running the bot on bittrex and i keep getting the following on zenbot (also using --debug):

`

> 2017-06-10 22:26:00  2802.51060162 USDT-BTC   +0.0%        1      +       0.0268   0.0600           22.68 USDT  0.00000 BTC    -0.5%   +0.0%
> 2017-06-10 22:27:00  2802.51060162 USDT-BTC   +0.0%        0      +       0.0242   0.0600           22.68 USDT  0.00000 BTC    -0.5%   +0.0%
> 
> 2017-06-11 00:28:03 - placing sell order...
> 2017-06-10 22:27:15  2805.00000000 USDT-BTC   +0.1%        0      +       0.0304   0.0600  selling  22.68 USDT  0.00000 BTC    -0.5%   +0.0%
> 2017-06-11 00:28:03 - placing sell order...
> 
> 2017-06-11 00:28:03 - placing sell order...
> 2017-06-10 22:28:00  2805.00000000 USDT-BTC   +0.1%        3      +       0.0304   0.0600  selling  22.68 USDT  0.00000 BTC    -0.5%   +0.0%
> 2017-06-10 22:33:00  2790.00000000 USDT-BTC   -0.5%        1     -       -0.0236   0.0600  selling  22.68 USDT  0.00000 BTC    -1.0%   +0.0%
> 2017-06-10 22:35:00  2802.51100000 USDT-BTC   +0.4%        0      +       0.0213   0.0600  selling  22.68 USDT  0.00000 BTC    -0.5%   +0.0%
> 2017-06-10 22:35:34  2818.94400000 USDT-BTC   +0.6%        8      ++      0.0752   0.0600  selling  22.68 USDT  0.00000 BTC    +0.0%    0.0%
> 

`
but nothing happens on bittrex ... no orders are being placed.

this is my conf.js file:

`

> var c = module.exports = {}
> 
> // mongo configuration
> c.mongo = {}
> c.mongo.host = process.env.MONGODB_PORT_27017_TCP_ADDR || 'localhost'
> c.mongo.port = 27017
> c.mongo.db = 'zenbot4'
> c.mongo.username = null
> c.mongo.password = null
> // when using mongodb replication, i.e. when running a mongodb cluster, you can define your replication set here; when you are not using replication (most of the users), just set it to `null` (default).
> c.mongo.replicaSet = null
> 
> // default selector. only used if omitting [selector] argument from a command.
> c.selector = 'bittrex.USDT-BTC'
> // name of default trade strategy
> c.strategy = 'trend_ema'
> 
> // Exchange API keys:
> 
> // to enable Bittrex trading, enter your API credentials:
> c.bittrex = {}
> c.bittrex.key = 'myAPI_Key'
> c.bittrex.secret = 'myAPI_Pass'
> // make sure to give your API key access to only: "Trade Limit" and "Read Info",
> // please note that this might change in the future.
> // please note that bittrex API is limited, you cannot use backfills or sims (paper/live trading only)
> 
> // Optional stop-order triggers:
> 
> // sell if price drops below this % of bought price (0 to disable)
> c.sell_stop_pct = 0
> // buy if price surges above this % of sold price (0 to disable)
> c.buy_stop_pct = 0
> // enable trailing sell stop when reaching this % profit (0 to disable)
> c.profit_stop_enable_pct = 3
> // maintain a trailing stop this % below the high-water mark of profit
> c.profit_stop_pct = 1
> 
> // Order execution rules:
> 
> // avoid trading at a slippage above this pct
> c.max_slippage_pct = 5
> // buy with this % of currency balance
> c.buy_pct = 99
> // sell with this % of asset balance
> c.sell_pct = 99
> // ms to adjust non-filled order after
> c.order_adjust_time = 30000
> // avoid selling at a loss below this pct
> c.max_sell_loss_pct = 25
> // ms to poll order status
> c.order_poll_time = 5000
> // ms to wait for settlement (after an order cancel)
> c.wait_for_settlement = 5000
> // % to mark up or down price for orders
> c.markup_pct = 0
> // become a market taker (high fees) or a market maker (low fees)
> c.order_type = 'maker'
> 
> // Misc options:
> 
> // default # days for backfill and sim commands
> c.days = 14
> // ms to poll new trades at
> c.poll_trades = 30000
> // amount of currency to start simulations with
> c.currency_capital = 1000
> // amount of asset to start simulations with
> c.asset_capital = 0
> // for sim, reverse time at the end of the graph, normalizing buy/hold to 0
> c.symmetrical = false
> // number of periods to calculate RSI at
> c.rsi_periods = 14
> // period to record balances for stats
> c.balance_snapshot_period = '15m'
> // avg. amount of slippage to apply to sim trades
> c.avg_slippage_pct = 0.045
> 

`

and this is my run command:

> zenbot trade --period=1m --reset_profit --debug

@DeviaVir ... what am i missing?

**Comment by spiffyfitz** [comment]
Could this have to do with the Bittrex order limit?

More details here:
https://bittrex.zendesk.com/hc/en-us/articles/202673194-The-taming-of-the-Bots-Part-II

**Comment by DeviaVir** [comment]
I think this fixes it: https://github.com/carlos8f/zenbot/pull/269

@megacrypto could you verify?

**Comment by MCrypto** [comment]
to upgrade this is what i use

> git pull
> npm install
> npm link

is that correct?


now after doing this, this is what i noticed first, the values are mixed up in the console, im looking at USDT to BTC, and i have 163USDT but they are showing as BTC ?

> 2017-06-12 10:20:00  2792.00000000 USDT-BTC                1              0.0000   0.0600           0.00 USDT  163.29135 BTC    +0.0%   -1.1%
> 2017-06-12 10:21:00  2785.00000000 USDT-BTC   -0.3%        3              0.0000   0.0600           0.00 USDT  163.29135 BTC    +0.0%   -0.9%
> 2017-06-12 10:22:00  2771.07500000 USDT-BTC   -0.5%        2              0.0000   0.0600           0.00 USDT  163.29135 BTC    +0.0%   -0.4%

**Comment by MCrypto** [comment]
orders are now being placed ... aside from the mixup of coins show up in opposite side ... it seems to be working now ... thanks @DeviaVir :))
