### ISSUE TITLE
opts.order_type is undefined when Bitfinex API is down! unable to call buy, retrying in 10s

### ISSUE THREAD

**Issue by nao0811ta** [DeviaVir/zenbot#262]
Code
```
108     buy: function (opts, cb) {
109       var func_args = [].slice.call(arguments)
110       var client = authedClient()
111       if (c.bitfinex.wallet === 'exchange' && typeof opts.order_type === 'maker') {
112         opts.type = 'exchange limit'
113       }
114       else if (c.bitfinex.wallet === 'exchange' && typeof opts.order_type === 'taker') {
115         opts.type = 'exchange market'
116       }
117       if (typeof opts.post_only === 'undefined') {
118          opts.post_only = true
129        }
......
128       var params = {
129         symbol,
130         amount,
131         price,
132         exchange,
133         side,
134         type,
135         is_hidden,
136         is_postonly
137       }
138 console.error(params)

```

Result of 
```
[ec2-user@ip-10-166-11-188 zen4-bit-2]$ ./zenbot.sh buy
{ symbol: 'ETCUSD',
  amount: '7.55683975',
  price: '19.6040',
  exchange: 'bitfinex',
  side: 'buy',
  type: undefined,
  is_hidden: false,
  is_postonly: true }

Bitfinex API is down! unable to call buy, retrying in 10s
placing order...
```

**Comment by DeviaVir** [comment]
@nedievas any chance you can take a look into this?

**Comment by nao0811ta** [comment]
@nedievas 
Thank you
I have a question
err.toString('') have to be err.toString().match('')?

FYI, I testing bitfinex backfill with v2 api. it seems well.
After testing , I will upload.

**Comment by nedievas** [comment]
@nao0811ta [string.match(regexp)](https://www.w3schools.com/jsref/jsref_match.asp).

Good. I'm thinking of websockets also.

**Comment by nao0811ta** [comment]
Your new code is  err.toString(regex)

**Comment by nao0811ta** [comment]
still can't buy

Bitfinex API is down! unable to call buy, retryin
g in 10s                                         
placing order...                                 
placing order...                                 
placing order...

**Comment by nao0811ta** [comment]
typeof opts.order_type === 'maker'
to be
c.order_type === 'maker'

**Comment by nedievas** [comment]
Still it is not fixed. I will give a fix in a few seconds.

**Comment by nao0811ta** [comment]
c.bitfinex.wallet === 'exchange' && c.order_type === 'maker'

err && err.match && err.match(/Error: Invalid order: not enough exchange balance$/)

**Comment by nedievas** [comment]
pull
