### ISSUE TITLE
Poloniex trading error

### ISSUE THREAD

**Issue by MCrypto** [DeviaVir/zenbot#267]
im getting the following error on poloiex:

> 2017-06-11 22:11:00  2925.74510538 BTC-USDT   +0.3%        9      +       0.0038   0.0600
> 2017-06-11 22:12:00  2925.42303357 BTC-USDT    0.0%       10      +       0.0024   0.0600
> 2017-06-11 22:13:00  2924.83948777 BTC-USDT    0.0%        1      +       0.0003   0.0600
> ---------------------------- STARTING LIVE TRADING ----------------------------
> ggetBalance error:
> { error: 'Nonce must be greater than 1475845520851281. You provided 149721198840200.' }
> 
> Poloniex API is down! unable to call getBalance, retrying in 10s
> ggetBalance error:
> { error: 'Nonce must be greater than 1475845520851281. You provided 149721200713600.' }
> 
> Poloniex API is down! unable to call getBalance, retrying in 10s
> ggetBalance error:
> { error: 'Nonce must be greater than 1475845520851281. You provided 149721201745100.' }
> 
> Poloniex API is down! unable to call getBalance, retrying in 10s
> ggetBalance error:
> { error: 'Nonce must be greater than 1475845520851281. You provided 149721202784300.' }
> 
> Poloniex API is down! unable to call getBalance, retrying in 10s
> ggetBalance error:
> { error: 'Nonce must be greater than 1475845520851281. You provided 149721203867100.' }
>

**Comment by wfafsvawetgww3tfw32rfa** [comment]
I encountered this when trying to run on amazon's lightsail.

**Comment by nao0811ta** [comment]
Try new api key 
And avoid to use multiple agent with same key.

**Comment by FreshLondon** [comment]
no improvement yet, any further ideas? 😃

**Comment by egorbenko** [comment]
duplicate of #193, please do a search before creating new issues
