### ISSUE TITLE
[Offtopic] Where to learn NodeJs/Javascript?

### ISSUE THREAD

**Issue by ghostnegotiator** [DeviaVir/zenbot#27]
Heya,

I have been searching all over the place where to learn to code in NodeJS. And considered it better asking to more experienced people.

Generally the question:
Where would it be possible to learn NodeJS? 
And is there a kind of mentoring program for it (online)?

Yours Faithfully,
RDash

**Comment by grigio** [comment]
I suggest starting with JavaScript ES2015+ and then NodeJS
https://developer.mozilla.org/docs/Web/JavaScript
https://nodejs.org/dist/latest-v6.x/docs/api/

**Comment by ghostnegotiator** [comment]
Awesome! Thanks for the refference :)

Yours Faithfully,
RDash

**Comment by carlos8f** [comment]
use this flowchart :)
1. what kind of code do you want to write?
2. come up with topics
3. search npmjs.org for topics
4. click on repository link for module(s) found
5. read through code
6. clone repo or copy-paste stuff into your own code
7. write tests (I use mocha) for what your code should do
8. make the code do it, gradually, until the tests pass
