### ISSUE TITLE
Order not found in cache

### ISSUE THREAD

**Issue by MCrypto** [DeviaVir/zenbot#280]
when bot crashes and i restart it, i awlays get this msg:

> { Error: order not found in cache
>     at Object.getOrder (/home/mylin/Downloads/zenbot/extensions/exchanges/bittrex/exchange.js:263:29)
>     at Timeout.checkOrder [as _onTimeout] (/home/mylin/Downloads/zenbot/lib/engine.js:273:24)
>     at ontimeout (timers.js:386:14)
>     at tryOnTimeout (timers.js:250:5)
>     at Timer.listOnTimeout (timers.js:214:5) desc: 'could not execute sell: error placing order' }
> 
> 
> undefined
> UUID_INVALID
> undefined
> UUID_INVALID
> undefined
> UUID_INVALID
> undefined
> UUID_INVALID
> undefined
> UUID_INVALID
>

**Comment by DeviaVir** [comment]
what is the command you start your bot with?

**Comment by MCrypto** [comment]
i start it with:

> zenbot trade --period=1m --reset_profit

**Comment by MCrypto** [comment]
this is the msg that i keep getting:

> 2017-06-13 20:10:07  0.00 BTC-ZCL   +0.0%      112   ---         2.07%  selling  0.07596 BTC  0.00 ZCL    -2.5%   +1.9%DUST_TRADE_DISALLOWED_MIN_VALUE_50K_SAT
> 
> 
> { Error: order not found in cache
>     at Object.getOrder (/home/mylin/Downloads/zenbot/extensions/exchanges/bittrex/exchange.js:263:29)
>     at Timeout.checkOrder [as _onTimeout] (/home/mylin/Downloads/zenbot/lib/engine.js:273:24)
>     at ontimeout (timers.js:386:14)
>     at tryOnTimeout (timers.js:250:5)
>     at Timer.listOnTimeout (timers.js:214:5) desc: 'could not execute sell: error placing order' }
>

**Comment by FreshLondon** [comment]
i'd suggest using another exchange for now until;
- bittrex balance issue is fixed.
- poloniex api delalys are fixed.

for now thats all i can suggest, unfortunately 😞

**Comment by DeviaVir** [comment]
duplicate of #277 in that case
