### ISSUE TITLE
--buy_pct <pct> not working

### ISSUE THREAD

**Issue by marco4444** [DeviaVir/zenbot#283]
Like the option --buy_pct <pct> to use one currency for two assets trading but when I do this one asset eats complete amount of the currency. E.g. if I set --buy_pct=50 with start 100$ in first round 50$ is used to trade, in next round 50% of the remaining 50$ is used, so together already 75% ... and so on.
Bottom line one asset usually wins the race.
Didn't find a way to use a fix amount of currency, e.g. 50$ for asset1 and rest for asset2.
any idea how to do it now already or could this be an option for future release?

Thanks.

**Comment by DeviaVir** [comment]
duplicates https://github.com/carlos8f/zenbot/issues/174
