### ISSUE TITLE
Telegram bot for notifications?

### ISSUE THREAD

**Issue by DeviaVir** [DeviaVir/zenbot#284]
Idea:

*telegram bot*

in conf.js set your telegram id
the bot will tell you when buying and selling
the bot will tell you (per period) (optionally) what the current value of your balance is
in a future version, you might interact with the telegram bot to directly tell zenbot to buy or sell

**Comment by DeF3c** [comment]
Maybe the bot tells you how much profit what the bought price is etc.

**Comment by jclancy93** [comment]
I think we could make it more generic to allow for either Telegram or Slack, the code would be very similar since they both use webhooks. That way user could choose their preference. I would be willing to take a shot at this over the weekend

**Comment by tuxitor** [comment]
@jclancy93 has a good point. I want to add that the software and protocol should be open source in compliance with zenbot, at last on the client side. It should also have ready made clients for all platforms. And it should support solid and easy to use node libraries.

Other factors to consider, should it be based on:
- p2p or central server
- end to end encryption or client to server encryption
- support one or many protocols
- slim or feature rich
- and what else?

For those interested, Wikipedia has a comparition of all sorts of IM systems here:
https://en.wikipedia.org/wiki/Comparison_of_instant_messaging_clients

**Comment by jclancy93** [comment]
I'm thinking something simple but flexible. A new variable in the conf.js file WEBHOOK_URL and you would enter whatever incoming webhook your messaging service provides. It would output at a frequency you choose (maybe a new var in conf.js for that too). The output would be the same as  verbose mode or real trading mode outputs by default (currency price, rsi changes, p/l, etc.)

I think it would have the most utility for the most users this way. Encryption is an interesting thing I hadn't thought of for this. @eigilb Will definitely let you my thoughts on this as I work through this task.

**Comment by hmronline** [comment]
This would help: https://github.com/yagop/node-telegram-bot-api

**Comment by Want100Cookies** [comment]
I implemented the telegram side here #920

**Comment by LoneWolf345** [comment]
Telegram is now implemented.  consider closing this.
