### ISSUE TITLE
Wording in conf.js

### ISSUE THREAD

**Issue by FreshLondon** [DeviaVir/zenbot#290]
_// avoid selling at a loss **below** this pct_
**c.max_sell_loss_pct = 0**

Pretty sure this should say **'above'** 😃

**Comment by Robbes** [comment]
Yes, it should state 'above'. This is what it seems to do:
![image](https://user-images.githubusercontent.com/1299321/30103594-66f3a8c4-92f3-11e7-822e-a84c14e01874.png)

**Comment by DeviaVir** [comment]
Please create a PR for this, closing this for now due to inactivity.
