### ISSUE TITLE
How to specific selector with docker?

### ISSUE THREAD

**Issue by chriscrutt** [DeviaVir/zenbot#293]
When i run docker, it runs the gdax.BTC-USD selector.

is there a way to specify a different selector, each time I run zenbot through docker, this way i could have multiple instances running different bots, without changing the default selector in the cong.js file

**Comment by DeviaVir** [comment]
Yep. Simply update the command here: https://github.com/carlos8f/zenbot/blob/master/docker-compose.yml#L8
