### ISSUE TITLE
sim and trade differ

### ISSUE THREAD

**Issue by chriscrutt** [DeviaVir/zenbot#296]
I ran sim using:
```
docker run --rm --link zenbot_mongodb_1:mongodb -it zenbot_server ./zenbot.sh sim --enable_profit_stop_pct=10 --profit_stop_pct=4 --trend_ema=36 --sell_rate=-0.006 poloniex.ETH-BTC
```
I ran trade using:

```
docker run --rm --link zenbot_mongodb_1:mongodb -it zenbot_server ./zenbot.sh trade --enable_profit_stop_pct=10 --profit_stop_pct=4 --trend_ema=36 --sell_rate=-0.006 poloniex.ETH-BTC
```

The only difference is i replaced sim with trade.

what ends up happening is it does what i specify for sim, but in trade it uses the defaults

**Comment by chriscrutt** [comment]
it seems to be fixed after i rebuild it and etc

**Comment by arphen** [comment]
Most likely due to slippage. The real slippage is often much higher than what the sims assume
