### ISSUE TITLE
Bitfinex asset sell fail

### ISSUE THREAD

**Issue by louisswart** [DeviaVir/zenbot#300]
Using the command line: zenbot sell bitfinex.BTC-USD --pct=10
The Bitfinex website shows: "Invalid order price precision (5 sig figures limit)"

**Comment by nedievas** [comment]
I suppose it is sell.js problem to send values with figures over the limit. `.format('0.00000000')`

it should look for products.json returned limits and format according to that.

**Comment by louisswart** [comment]
I'm not skilled enough to jump into the java, I tried a few changes as suggested, but with no good result.
Running the command line "zenbot sell bitfinex.BTC-USD --pct=10" a few times gives one of the following results:

1) "Submitting exchange limit sell order for 0.04467526 BTC." immediately followed by "Exchange limit sell order of 0.04467526 BTC has been canceled." resulting in no order execution.

2) "Submitting exchange limit sell order for 0.04467526 BTC." that ends in a successful order execution.

3) "Invalid order price precision (5 sig figures limit)" resulting in no order being placed.

These results seem to be random.

**Comment by nedievas** [comment]
It's Bitfinex side error. It is not common. Their API should truncate price with precision >5. More info: [Bitfinex API](https://docs.bitfinex.com/v1/docs/readme)

**Comment by Robbes** [comment]
This still is a problem with Bitfinex. Current solution has all products/pairs with precision of 0.0001 in product.json, but this makes the bot 'useless' for pairs like IOT/ETH and that act in the range of 0.0020389. The page referenced by @nedievas tells that 0.0020389 has a precision of 5 significant digits (20389) and is valid to place as sell price. A work around is setting the IOT/ETH pair at 0.0000001, but all pairs then need to be checked and changed.

**Comment by DeviaVir** [comment]
Closing this on our side for now.
