### ISSUE TITLE
MACD Strategy does not perform any trades in 4.0.5

### ISSUE THREAD

**Issue by brasky** [DeviaVir/zenbot#309]
I just updated to 4.0.5 and macd with default settings does not perform any trades. I've tried in production as well as 15 and 30 day sims in ltc/btc/eth on gdax. I tried replacing zenbot/extensions/strategies/macd/strategy.js with an older version with no impact. Other strategies are still working properly. 

Any help with this would be appreciated, thanks!

@DeviaVir it finally let me tag you.

**Comment by vikasprogrammer** [comment]
I am having the same issue.

**Comment by phips28** [comment]
same here, reverted to an earlier version.

**Comment by vikasprogrammer** [comment]
Me too.
