### ISSUE TITLE
Manual trades while in trade mode

### ISSUE THREAD

**Issue by infatrus** [DeviaVir/zenbot#315]
Maybe it would be useful to implement "command line" for zenbot in trade mode, accepting following commands with (yes/no) acceptance:
```
b - for immediate buy
s - for "panic sell"
x - for exit and showing up a report similar to the one known from sim mode
```
Maybe more, for example starting other strategy or something else...

**Comment by DeviaVir** [comment]
duplicates https://github.com/carlos8f/zenbot/issues/224
