### ISSUE TITLE
Poloniex API is seriously broken on the exchange side

### ISSUE THREAD

**Issue by tuxitor** [DeviaVir/zenbot#320]
This issue is probably not fixable by the Zenbot project, but is reported as an issue anyway to make it visible for both Poloniex and users of Zenbot. In short: Complaints should go to Poloniex

It proves that Poloniex is seriously broken. In attempt to reduce the nonce problems, I have done some experiments to use websockets for the API calls with support for it.

Websockets on Poloniex needs a lot of time to start. Therefore it is neccessary to use the REST API while waiting for WS (websockets) to get ready. As seen here, what Zenbot asks for (trade_cursor) it gets from REST call to Poloniex (restTrades / 1000)

```
2017-06-21 08:40:53  0.00010805 XRP-BTC  +0.0%  140.26k ---  -0.1074  0.0150  sold  7.98 XRP  886.29394 BTC  -11.4%  -5.3%
trade_cursor -->  1498027253 ('2017-06-21 06:40:53')
restTrades ---->  1498027253000
restTrades / 1000 ---------> ('2017-06-21 06:40:53')
```

About 30 seconds later the rest API starts to stream trade data. As seen here, the time difference is quite substantial. The difference is an odd number of hours, minutes and seconds that cannot be expained as a time zone difference. This also means that the WS API is totally unsuitable for bot trading. 
The human readable dates are for UTC timezone, BTW.
```
2017-06-21 08:41:24  0.00010799 XRP-BTC  -0.1%  228.74k ---  -0.1147  0.0151  sold  7.98 XRP  886.29394 BTC  -11.4%  -5.3%
wsReady:  true
trade_cursor ==>  1498027284 ('2017-06-21 06:41:24')
wsTrades ======>  1498014871000
wsTrades / 1000 ===========> ('2017-06-21 03:14:31') 
```

**Comment by Boscop** [comment]
Any updates on this?
Does poloniex's websocket API still lag?
