### ISSUE TITLE
Gemini exchange

### ISSUE THREAD

**Issue by tycho** [DeviaVir/zenbot#322]
Please add support for the Gemini exchange. Here's a relevant Node module for it:

https://github.com/mjesuele/gemini-api-node

**Comment by DeviaVir** [comment]
not sure how interesting for bots with 0.15% fee, but it's definitely one of the better ones out there.

**Comment by tycho** [comment]
Agree that the fees are high, but depending on the strategy used, you may
only have a few trades per day. So if the profit is high enough, the fee
may not matter.

**Comment by cmroche** [comment]
Push request https://github.com/carlos8f/zenbot/pull/445
