### ISSUE TITLE
value for currency and asset is mixed up at bittrex

### ISSUE THREAD

**Issue by marco4444** [DeviaVir/zenbot#327]
When I trade bittrex.BTC-BTS the values for asset and currency are interchanged. Zenbot shows for example 0 BTC  and 0.04 BTS but correct would be 0.04 BTC and 0 BTS.

**Comment by ghost** [comment]
Same for me too...

But it looks like it is on purpose: https://github.com/carlos8f/zenbot/blob/master/extensions/exchanges/bittrex/exchange.js#L122

**Comment by marco4444** [comment]
Ok I see. However one point is how to exchange the date with bittrex and the other is how to display it. Would prefer this would be like for the other exchanges.

**Comment by DeviaVir** [comment]
duplicate https://github.com/carlos8f/zenbot/issues/277
