### ISSUE TITLE
Sugestion for RPi Mongo users

### ISSUE THREAD

**Issue by talvasconcelos** [DeviaVir/zenbot#330]
Is it possible to integrate Firebase or mlab for the bot database?

i use an Raspbery Pi for the bot and mongo is not very Pi friendly. I understand that a cloud db can slow down but maybe it would eliminate the connection errors from using mongo on the pi. the implementation seems pretty straightforward:

```
// Set the configuration for your app
  // TODO: Replace with your project's config object
  var config = {
    apiKey: "apiKey",
    authDomain: "projectId.firebaseapp.com",
    databaseURL: "https://databaseName.firebaseio.com",
    storageBucket: "bucket.appspot.com"
  };
  firebase.initializeApp(config);

  // Get a reference to the database service
  var database = firebase.database();
```
for mlab they provide the mongodb:// URI to connect, it's even simpler, just some minor changes in boot.js... one more if?!

**Comment by DeviaVir** [comment]
this duplicates #234 somewhat
