### ISSUE TITLE
asset numbers and currency numbers are mixed up

### ISSUE THREAD

**Issue by brisklad** [DeviaVir/zenbot#343]
I'm running latest version of Zenbot, and the issue is that asset shows currency amounts and vice-averse 0.02303 ETH is actually BTC and 2.27229 BTC is actually ETH. It's a trade running on Bittrex. How to fix that?

<img width="1101" alt="screenshot 2017-06-30 10 18 01" src="https://user-images.githubusercontent.com/29792602/27725270-39ef5076-5d7e-11e7-986f-71578080031c.png">
<img width="1393" alt="screenshot 2017-06-30 10 23 24" src="https://user-images.githubusercontent.com/29792602/27725271-3a18f2dc-5d7e-11e7-9f5c-f2656c637f3a.png">

**Comment by DeviaVir** [comment]
duplicates #277
