### ISSUE TITLE
Chart access when hosted on remote server?

### ISSUE THREAD

**Issue by shanehull** [DeviaVir/zenbot#345]
Hi,

Should I be able to access the html chart if Zenbot is hosted on a DigitalOcean server?

I'm getting nothing using the url it outputs after a sim.

I've searched around but can only find issues related to 3.x.

**Comment by shanehull** [comment]
Worked it out! It's just outputted to the folder - no web server!

Ps. it would be sweet to get some documentation on setting up nginx with ssl to the simulations directory for anyone running remotely. I'm in the process of getting my head around it. Can share once I do.

**Comment by nedievas** [comment]
I have simple solution:
Install [ws](https://www.npmjs.com/package/local-web-server)
start from zenbot folder: `ws -p 8080 -d simulations/`
on your browser write `http://<external IP>:8080` of your zenbot server.

**Comment by shanehull** [comment]
Thanks @nedievas .
I ended up setting up nginx over ssl with authentication after all. It works a treat.

I created a cert with certbot using ```certbot certonly --standalone -d subdomain.example.com```.

[Installed nginx ](https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-ubuntu-16-04).
Created a htpasswd using: ```printf "username:`openssl passwd -apr1`\n" >> /etc/nginx/.htpasswd```

Then, edited the ```/etc/nginx/sites-enabled/default``` file to contain of the following:

```server {
   listen 80;
   listen [::]:80;
   server_name subdomain.mydomain.me;
   return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    root /root/zenbot/simulations;

    ssl_certificate                 /etc/letsencrypt/live/subdomain.mydomain.me/fullchain.pem;
    ssl_certificate_key             /etc/letsencrypt/live/subdomain.mydomain.me/privkey.pem;
    add_header                      Strict-Transport-Security "max-age=31536000";

            autoindex on;
            auth_basic "Restricted Content";
            auth_basic_user_file /etc/nginx/.htpasswd;
}
```

Run `systemctl restart nginx.service` and that's it!

Result:
![screen shot 2017-07-01 at 11 27 08 am](https://user-images.githubusercontent.com/20835304/27758101-4221f960-5e50-11e7-82a9-bdec020c939e.png)
