### ISSUE TITLE
RSI Backfiller Error

### ISSUE THREAD

**Issue by JFD3D** [DeviaVir/zenbot#35]
I am getting the following error with the latest update while trying to use the new config_eth.js with config_defaults.js

```
/home/zero/zenbot/zenbot/core/indicators/rsi/backfiller.js:36
        if (err) throw err
                 ^
MongoError: $in needs an array
    at Function.MongoError.create (/home/zero/zenbot/zenbot/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/home/zero/zenbot/zenbot/node_modules/mongodb-core/lib/cursor.js:197:36)
    at /home/zero/zenbot/zenbot/node_modules/mongodb-core/lib/connection/pool.js:428:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

Any idea what is causing this?

**Comment by carlos8f** [comment]
that would mean your `c.rsi_sizes` is undefined, but I released a ton of changes today to config so you'll need to update to `v3.5.2` to get the updated config layout. `c.rsi_sizes` is defined in `config_defaults.js` going forward.

**Comment by JFD3D** [comment]
You fixed it literally five minutes after I figured it out last night :laughing:

BTW I'm having trouble getting zenbot to trade so I can test the Poloniex logic, do the following vars (in default_logic.js) tell zenbot to only trade after (originally half a day?) a day and a half? Are these first run parameters or between each trade action?

```
      rs.min_buy_wait = 43200000 // wait half a day after action before selling
      rs.min_sell_wait = 43200000 // wait half a day after action before selling

```

```
      rs.min_buy_wait = 43200000 * 3 // wait in ms after action before buying
      rs.min_sell_wait = 43200000 * 3 // wait in ms after action before selling

```

I have been trying dropping mongo db's with nearly every update as well as importing db's to no avail. I'm just trying to test the trades, any suggestions on how to get zenbot to trade more frequently? 

Thanks

**Comment by carlos8f** [comment]
between each trade action it waits 1.5 days by default. this is to keep the number of trades down, and reduce fees. set to 0 to disable, or to whatever ms you want, check the results with sim command.

**Comment by JFD3D** [comment]
Does this feature still use the "maximum 6% loss" to protect funds or do the default settings make it so zenbot only every trades every 1.5 days no matter what?

**Comment by carlos8f** [comment]
zenbot only trades when a trend is detected (rsi <= 30 or >= 70). min wait is an additional check, so it throttles the trade signals, and the min_performance is an additional check to ensure the trade "makes sense" (buy after price drops, sell after price gains)

**Comment by JFD3D** [comment]
Ah I misunderstood the 0.06 value. I tinkered around with the values and I got it to work the way I intended, Thanks!
