### ISSUE TITLE
Kraken - Unable to trade against EOS currency pair's

### ISSUE THREAD

**Issue by nibzo1** [DeviaVir/zenbot#352]
Ive been trying to get Zenbot running against Kraken API with the EOS-ETH currency pair. 

I have ran the Kraken Update products script which has correctly loaded the new currency pairs, although exceptions occur when trying to run the sim or trade. 

Strangle backfill works correctly...

I had the same issue in the past with GNO in the past if i recall? Anyone know if this is a Kraken thing or a Zenbot thing?
```
:~/zbot$ zenbot sim kraken.EOS-ETH
error: could not find product "EOS-ETH"
:~/zbot$ zenbot sim kraken.XEOS-XETH
error: could not find product "XEOS-XETH"
```

**Comment by nibzo1** [comment]
im not sure this fixes the issue, i had previously updated the EOS-ETH currency pair in the `products.json`

backfill worked but trade and sim do not. It may be a kraken issue??

**Comment by DeviaVir** [comment]
@nibzo1 what is the error you are running in to?

**Comment by nibzo1** [comment]
@DeviaVir  been at work all day and only getting to reply now

so I get when i run
```
zenbot backfill kraken.EOS-ETH

skipping 75 hrs of previously collected data

kraken.EOS-ETH saved 1000 trades 1 days left
.....
kraken.EOS-ETH saved 5107 trades 0 days left

download complete!
```

when I run (also same for trade)

```
zenbot sim kraken.EOS-ETH
error: could not find product "EOS-ETH"
```
