### ISSUE TITLE
3.5.0 Config not found

### ISSUE THREAD

**Issue by BarnumD** [DeviaVir/zenbot#36]
I'm trying to use --config in 3.5.0.  When I do I get config_btc_usd.js is not in the same folder.
# zenbot launch map --backfill run --config /data/config_btc_usd.js --rs btc_usd

/usr/src/zenbot/node_modules/zenbrain/core/launcher/launcher.js:22
            throw new Error('No config found. Please copy config_sample.js to ' + options.parent.config + ', edit, and re-try.')
            ^

Error: No config found. Please copy config_sample.js to /data/config_btc_usd.js, edit, and re-try.
    at Command.<anonymous> (/usr/src/zenbot/node_modules/zenbrain/core/launcher/launcher.js:22:19)
    at Command.listener (/usr/src/zenbot/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/usr/src/zenbot/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/src/zenbot/node_modules/commander/index.js:458:21)
    at Object.cli (/usr/src/zenbot/node_modules/zenbrain/zenbrain.js:71:15)
    at Object.<anonymous> (/usr/src/zenbot/zenbot:10:7)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)

**Comment by carlos8f** [comment]
ok I think currently it doesn't handle an absolute path correctly, i'll try to fix it

**Comment by carlos8f** [comment]
just published `3.5.3` with an update to Zenbrain to fix this issue.

**Comment by BarnumD** [comment]
I'm running with version 3.5.7 now.  Still getting similar errors.  However I think i'm making assumptions about what --config is expecting.

I have no config.js in the zenbot folder.  I was assuming that config.js was a default, and that config_btc_usd.js was overriding those settings.  But I was also assuming that if I combined the two files into one, and only specified `--config config_btc_usd.js` (a file that has all the options in it) while leaving config.js absent it would work. 

I think what's going on is that the program is looking for config.js regardless of if I pass --config.  I haven't looked at the code to verify that.  Just a hunch.

If I put config.js in place than I can get everything working.

**Comment by carlos8f** [comment]
The idea is that `config.js` requires `config_defaults.js` at the top, and `config_btc_usd.js` requires `config.js` at the top. They cascade in that order:

config_btc_usd > config > config_defaults

config_btc_usd = pair specific config
config = non-pair specific config
config_defaults = all possible config vars

**Comment by grigio** [comment]
I understood this :) but I find it complicated, isn't plain json simpler?

```
> a = {key:'prova', secret:'123'}
{ key: 'prova', secret: '123' }
> b = Object.assign({}, a, {secret:'wow'})
{ key: 'prova', secret: 'wow' }
> b
{ key: 'prova', secret: 'wow' }
```

I think it is also easier to override and debug
