### ISSUE TITLE
Question about a custom strategy. I can't seem to configure

### ISSUE THREAD

**Issue by twalf** [DeviaVir/zenbot#371]
Hey there! Zenbot 4 looks really cool! But I have some problems with configuring my "strategy"(maybe it is not possible yet). What I want to do is to run a certain order on kraken once a certain cryptocurrency hits a certain price. For example. Lets say I bought Ether at 200 euros a piece. I want to run a trailing stop (limit) order of 5% if the price hits 250 euros. This way I make sure that I will sell the ether at at least 237.5 (250 * 0.95). Another possibility is that if the price gets higher to 300 euros and then goes down. The sell order will happen at 285. This way I make sure I will at least follow the trend if it hits at least a threshold. What would I need to do to make this happen? Thanks in advance for the help!

p.s. I had one more question. If the above is possible, could I also add like a maximum price point. For example this price hits 300 euros. I want to sell those ether immediately for that price and override the trailing stop order (so cancel that one out).

Keep up the good work! And sorry for my bad English

**Comment by DeviaVir** [comment]
Hi @wouterrobot, you would have to create your own custom strategy with custom variables to use fixed/absolute points. Here's an example of a strategy I worked on before: https://github.com/DeviaVir/zenbot/blob/9790c3227c94ede6ba403577e1c580443eb48be8/extensions/strategies/trust_distrust/strategy.js
Good luck!
