### ISSUE TITLE
Feature Idea.

### ISSUE THREAD

**Issue by ghost** [DeviaVir/zenbot#382]
Hey guys, been doing a lot of work on running simulations with the simulations auto backtester.

I was wondering, if you guys were interested, trying to output the estimated coin rise/fall percentage for the next 24 hours. in one script (however that's done.) then using my script that alternates periods for trend_ema and your backtesting script that alternates the RSI. I think you guys would be very interested in implementing this into your backtesting script that alternates RSI, as, you'll be able to lower the processing time. You would also be able to alternate the period in the second half of the backtesting script where RSI is alternated since this will be a lot quicker.

How can I code something that will tell me this using zenbot? :)

This will give us the best coin option every day.

**Comment by ghost** [comment]
Can I do this by setting period to 24hrs?

**Comment by talvasconcelos** [comment]
you could make a call to an api to get that data.
