### ISSUE TITLE
Server: 404 on trades.csv

### ISSUE THREAD

**Issue by InfoAddict** [DeviaVir/zenbot#39]
Fresh install (using a raspberry pi) - everything is working except I get a 404 on the URL below when hitting the web server. The page renders and everything else is found but I get the spinny image and that's it.

http://192.168.1.101:3013/trades.csv?sim_id=&selector=gdax.ETH-BTC&period=1h&limit=200

**Comment by carlos8f** [comment]
hmm, i'm not sure why this would be a 404. I don't have experience with raspberry pi either so I'm afraid I'm not of much help.

**Comment by egorbenko** [comment]
same issue here on desktop

`main.js:381 Uncaught TypeError: Cannot read property 'map' of undefined`

**Comment by BarnumD** [comment]
I started getting the same issue around 3.5.11 (not exact sorry) .  I'm
seeing it with a config using btc/usd but not with a separate instance I
have using eth/usd

**Comment by egorbenko** [comment]
At first I thought something was up with my docker setup. But I get the same issue everywhere including separate instance.

**Comment by carlos8f** [comment]
ahh, found a simple error on my part. patch incoming...

**Comment by carlos8f** [comment]
please run `./update.sh` and let me know if the issue still persists.

**Comment by BarnumD** [comment]
Seems better for me.
