### ISSUE TITLE
Bot sometimes fails to buy

### ISSUE THREAD

**Issue by tslater2006** [DeviaVir/zenbot#394]
I am running default settings and sometimes this happens:

![image](https://user-images.githubusercontent.com/1731714/28501049-01b73d72-6f99-11e7-8ebf-2679dbfc5b9c.png)

You can see at 10:52 it says "buy" but gdax doesn't show any buy orders being placed. I've had buys/sells work earlier but occasionally I'll see a "buy" or "sell" that doesn't actually do anything.

In this case it seems zenbot sold at 228.81 because it saw a drop from ~230, but then the price started going back up so it wanted to buy again and it didn't :(

**Comment by crubb** [comment]
Run with `--debug`, so you will see more about the bot's decisions. The signal seems to have switched from "buy" to "neutral", as the numbers in the 7th column are grey.

**Comment by tslater2006** [comment]
![image](https://user-images.githubusercontent.com/1731714/28521519-b204837e-7039-11e7-811a-8acfe9c921e6.png)

Claims to not have enough balance to buy, even though it clearly does.

**Comment by tslater2006** [comment]
Any ideas on this? I really enjoyed the software and it was making me reasonable gains so I would love to use it again.

**Comment by DeviaVir** [comment]
@tslater2006 what permissions did you give your API key?

**Comment by tslater2006** [comment]
the API key has the fullest access you are able to give one. The bot has bought and sold successfully in the past using this API key so I can't imagine that being the issue. Its also able to grab my balances properly per the screenshots.

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
