### ISSUE TITLE
Bittrex : Reversed currencies output ?

### ISSUE THREAD

**Issue by suparub** [DeviaVir/zenbot#399]
Here is what I got running the bot on bittrex :

`2017-07-24 22:37:00  0.00 BTC-UBQ   +0.7%       14     -       -0.0301   0.1500    +0.6%   0.30000 BTC  0.02 UBQ    -0.2%   +0.4%`

Shouldn't it be 

`2017-07-24 22:37:00  0.00 BTC-UBQ   +0.7%       14     -       -0.0301   0.1500    +0.6%   0.30000 UBQ  0.02 BTC    -0.2%   +0.4% ? `

Thanks for the amazing work so far ^^

**Comment by DeviaVir** [comment]
duplicates https://github.com/carlos8f/zenbot/issues/277
