### ISSUE TITLE
Coin and BTC units flipped in Bittrex

### ISSUE THREAD

**Issue by asterismo** [DeviaVir/zenbot#419]
Zenbot is showing i have 2.66 BTC and 0.00 ANS when actually Bittrex balances are 0.00 BTC and 2.66 ANS, is this a bug? Maybe the bittrex API changed?

**Comment by benpdavison** [comment]
well in the code there is this comment:
`// yes, currency and asset are turned around on purpose, their API is weird`
so maybe they have since updated their API?

**Comment by asterismo** [comment]
I also commented here --> https://github.com/carlos8f/zenbot/issues/277 because it seems that the bot its buying high and selling low... maybe the bittrex plugin is broken for the moment

**Comment by DeviaVir** [comment]
Dup of https://github.com/carlos8f/zenbot/issues/277

**Comment by asterismo** [comment]
Does it work with node 6? i managed to run without problems in ubuntu 16.04 and node 8, but i'm interested in running it in debian 8 with node 6 LTS
