### ISSUE TITLE
Question related new altcoin Bitcoin cash

### ISSUE THREAD

**Issue by marco4444** [DeviaVir/zenbot#429]
Hi,
in order to deal with the new Bitcoin cash https://www.bitcoincash.org/ is it enough to add a few lines to the products.json file or anything else to do?

A bit off topic I have another concern. Having the private key for bitcoins I can use it as well to get same amount of bitcoin cash. How to make sure that a bitcoin cash wallet is not taking my private key and use it for stealing my bitcoins? Would it be safe (in case the wallet is scam) to do it this way? 

1.  Generate new private bitcoin key and move all the bitcoins there
2.  Import the old bitcoin private key into the new bitcoin cash wallet

If I'm right then the old key has in bitcoin only the power about 0 but in bitcoin cash still power about the full value. So in case the bitcoin cash wallet is a scam they can steal my bitcoin cash but not the bitcoin.

Comments appreciated  if I oversee something or how you guys handle this topic.
Thanks.

**Comment by smartbrain** [comment]
For Bittrex simply running updateproducts.sh works and you will see the new selector available when you run list-selectors. I have been reliably trading BTC-BCC (they call call it BCC there, not BCH) since they enabled trading yesterday.

For Kraken, the updateproducts.sh script is broken - https://github.com/carlos8f/zenbot/issues/427

**Comment by marco4444** [comment]
Thanks! Both kraken and bittrex don't allow currently to deposit bcc funds so I assume you had it already there. So I'll wait a bit until I can move my bcc there. However on kraken I changed some euros into bcc so I can manually handle for the time beeing.

Any comments about bcc wallets with trust and why trusting ... welcome
