### ISSUE TITLE
Bittrex has inverted values

### ISSUE THREAD

**Issue by VincentDatrier** [DeviaVir/zenbot#444]
Hi, 

I'm having an issue on Bittrex. I have about 0.2 LTC in my balance, but this shows:

```
fetching pre-roll data:
please note: do not be alarmed if you see an error "returned duplicate results"
please note: the bittrex api does not support backfilling (trade/paper only).
please note: make sure to set the --period=1m to make sure data for trade/paper is fetched.

bittrex.BTC-LTC saved 200 trades 1 days left

               DATE            PRICE     DIFF            VOL         RSI                         ACTIONS                      BAL                PROFIT
2017-08-05 14:51:00  0.0142335 BTC-LTC              380
---------------------------- STARTING LIVE TRADING ----------------------------
please note: do not be alarmed if you see an error "returned duplicate results"
please note: the bittrex api does not support backfilling (trade/paper only).
please note: make sure to set the --period=1m to make sure data for trade/paper is fetched.
2017-08-05 15:10:00  0.0142500 BTC-LTC   +0.1%    19878                               0.19779 BTC  0.00 LTC    -0.2%   +0.0%
```

It should be 0.19779 LTC, not BTC.

**Comment by azrulhaifan** [comment]
I got the error too, i use BTC-ETH. and my BTC balance was inverted with my ETH.

**Comment by VincentDatrier** [comment]
I dug into the code but I'm not much of a Javascript guy... Could it be that Bittrex finally "fixed" their API? I read in the bittrex exchange file that they swap the asset and the currency.

**Comment by azrulhaifan** [comment]
@Gobelet The balances that show on output was inverted. But, bot is working as well. I think it just the output. 
BTW just want to know, what strategy that you use ? i use the trend ema strategy with --period=1m and default value for other. But get loss for about 2.5%. Very sad for now.

**Comment by DeviaVir** [comment]
Duplicate of https://github.com/carlos8f/zenbot/issues/277

Please search the issues before creating a new one :)
