### ISSUE TITLE
Is 'trade --buy_pct X' doing what it's supposed to do?

### ISSUE THREAD

**Issue by timstoop** [DeviaVir/zenbot#450]
Hi,

I'm trading with the option `--buy_pct 50`. I was expecting that this would use 50% of the balance in my account to buy cryptocurrency. Apparantly, it's still using 100%. Am I doing something wrong or did I misunderstand this option (or could it be a bug)? Thanks in advance!

**Comment by DeviaVir** [comment]
This is discussed in https://github.com/carlos8f/zenbot/issues/174

The current implementation uses 50% (from your example) *per trade*.
