### ISSUE TITLE
Error running under WebStorm

### ISSUE THREAD

**Issue by kentenzer** [DeviaVir/zenbot#456]
Hi All, 

First of all congratulation for this great project! 
I would really like to participate and thus I am experimenting with it even though I am old school backend developer, so please forgive my ignorance here. 

I have run the zenbot from command line, and it worked excellent, beside I didn't find the simulation html file once it was finished.

I then wanted to get my hands on, and have spent quite good time trying to make docker work with WebStore GUI. 
At this point, I have a "Docker for Mac" project, I am using the docker-compose.yml for deployment.
When I run it, I get the following error:
```
Deploying 'Compose:  docker-compose.yml'...
Removing old containers...
Stopping zenbot_server_1 ... 
Stopping zenbot_mongodb_1 ... 
Removing zenbot_server_1 ... 
Removing zenbot_mongodb_1 ... 
Removing zenbot_mongodb-data_1 ... 
(Re)building services...
mongodb-data uses an image, skipping
mongodb uses an image, skipping
Building server
Step 1/7 : FROM node:boron
 ---> 5a767079e3df
Step 2/7 : RUN mkdir -p /app
 ---> Using cache
 ---> 277ce69f522d
Step 3/7 : WORKDIR /app
 ---> Using cache
 ---> d948c2be38ca
Step 4/7 : COPY package.json /app/
 ---> Using cache
 ---> 58ad2acf84ef
Step 5/7 : RUN npm install -g node-gyp && npm install --unsafe-perm
 ---> Using cache
 ---> 6460aaf73226
Step 6/7 : COPY . /app
 ---> d34e254e5037
Removing intermediate container b71ea8162554
Step 7/7 : CMD ./zenbot.sh trade --paper
 ---> Running in ac582e582db0
 ---> 6d51d9c793be
Removing intermediate container ac582e582db0
Successfully built 6d51d9c793be
Successfully tagged zenbot_server:latest
Starting...
Creating zenbot_mongodb-data_1 ... 
Creating zenbot_mongodb-data_1
Creating zenbot_mongodb-data_1 ... doneCreating zenbot_mongodb_1 ... 
Creating zenbot_mongodb_1
Creating zenbot_mongodb_1 ... doneCreating zenbot_server_1 ... 
Creating zenbot_server_1
Creating zenbot_server_1 ... doneContainer [Name:/zenbot_mongodb-data_1; ID:df7cca29cefc0f74fe4a44538e6bd73b64022fc8ed789c64849ace96ccc3267b]: is not started
Failed to deploy 'Compose:  docker-compose.yml': Some services/containers not started
```
My newby question is :), do you know why zenbot_mongodb-data_1 is not started?

Is someone else using WebStorm here?

Really appreciate your help! 
Cheers,

**Comment by nodevar** [comment]
I know why you cant access the html files. 

https://github.com/carlos8f/zenbot/issues/295

With the given information i cant point out why this is not starting.

**Comment by kentenzer** [comment]
Hi, 

Thanks for your reply! It is good that you are already aware of the html file issue. 

Regarding the deploy issue, I am sure this is something related to my environment but I didn't found what the problem is yet. 

I attach my Docker.xml configuration file (renamed to txt), I took it from $/.idea/runConfigurations/. 
[Docker.txt](https://github.com/carlos8f/zenbot/files/1220020/Docker.txt)

Also screenshots from the configuration:
<img width="1132" alt="screen shot 2017-08-12 at 16 53 22" src="https://user-images.githubusercontent.com/11169160/29243824-0b7487e8-7f7f-11e7-9fd8-9138141a86e8.png">

<img width="1117" alt="screen shot 2017-08-12 at 16 53 37" src="https://user-images.githubusercontent.com/11169160/29243825-119284f4-7f7f-11e7-81a0-0dce6372c23e.png">

I believe this is the information you may need, but feel free to ask more information. 

Thanks in advance!
