### ISSUE TITLE
Live trading appears to be broken after this commit.

### ISSUE THREAD

**Issue by davidandrewcope** [DeviaVir/zenbot#466]
Live trading appears to be broken after commit af971ef3. I get to ---STARTING LIVE TRADING--- then nothing... Strangely, I can still toggle Manual mode, but nothing else. Rolling back to the previous commit locally takes care of the issue.

**Comment by gasperzupancic** [comment]
i can confirm this situation. Thanks @davidandrewcope for pointing this out. it was making me crazy when i was trying to figure it out yesterday and over night:S

**Comment by cmroche** [comment]
It won't show anything until it receives valid trade data, if you have short periods on a low volume exchange there is no data until the first live trade is reported by the exchange.

Previous behaviour is that it would fail pre_roll, and then fallback to loading an entire day worth of data during the live update stage potentially signalling bad trade orders on the exchange while it effectively caught up.

@davidandrewcope @gasperzupancic 

As an example, kraken.XETH-ZCAD has period of an hour with no volume. I've found that it can take 10-20 minutes often to receive the first sample, then you will begin to see data including 0 volume periods reporting.

Can you please confirm that this is the case you are seeing.

While it may be possible to inject 0 volume periods on the exchange once live trading is started, it isn't a trivial change and will have to wait until I have some time to tackle the problem.

**Comment by cmroche** [comment]
After thinking about the problem a bit, I could probably add a check to detect that we don't gave enough data to start the reports and throw out a warning to the console in stead. I'll look at this in the short term.

**Comment by cmroche** [comment]
https://github.com/carlos8f/zenbot/pull/470

**Comment by dymex0** [comment]
same here, 1h later and my live trading on gdax is still empty

**Comment by cmroche** [comment]
@dymex0 I'll investigate, GDAX uses a reverse history scan, it could be related. But for now can you please tell me the following.

1) Can you reproduce the problem with paper trading?
2) Which currency pairs specifically are you using on GDAX.
3) What parameters are you using for trading (basically strategy, and configuration options for it)

Thanks

**Comment by cmroche** [comment]
I've found the problem, it effects any exchange platform that doesn't use timestamps for filtering/pagination. I'll have a fix in the next 24 hours.

**Comment by cmroche** [comment]
Fixed in pull request #470
