### ISSUE TITLE
No update-products.sh for Bitstamp 

### ISSUE THREAD

**Issue by procmail** [DeviaVir/zenbot#486]
Hi,

Bitstamp just started trading ETH pairs and there's no transaction cost this month, so I was hoping to get on the action. 

How do I get the bot to add the selectors for this?

**Comment by cmroche** [comment]
https://www.bitstamp.net/api/

Has no API function to retrieve asset pairs. If you need a currency pair added, edit productlist.json manually

**Comment by tuxitor** [comment]
@procmail, @cmroche
I think nedievas created a PR for this yesterday

**Comment by cmroche** [comment]
Yes you are right, ETH trading pairs added on https://github.com/carlos8f/zenbot/pull/485
