### ISSUE TITLE
Using 100 for buy_pct and sell_pct results in negative balance

### ISSUE THREAD

**Issue by procmail** [DeviaVir/zenbot#487]
Hi,

I have --buy_pct=100 --sell_pct=100 set and am seeing things like:

`2017-08-17 15:20:00  305.000 ETH-USDT   -0.2%        1     - 47    -0.0124   0.0450   bought  10.03 ETH    -1.37967 USDT    -0.7%   +0.2%
2017-08-17 15:20:55  307.380 ETH-USDT   +0.8%       20   58 ++     -0.0778   0.1561  selling  10.03 ETH    -1.37967 USDT    +0.1%   +0.2%
`

and a bit later:

`2017-08-17 15:25:00  304.800 ETH-USDT   +0.0%        7     - 47    -0.0236  -0.0326   bought  10.05 ETH    -1.38225 USDT    -0.5%   +0.5%
2017-08-17 15:25:11  305.000 ETH-USDT   +0.1%        1     - 48    -0.1041  -0.0565  selling  10.05 ETH    -1.38225 USDT    -0.5%   +0.5%
`

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
