### ISSUE TITLE
running zenbot sim --paper bitfinex.bch-btc  gives me an error error: could not find product "BTC-LTC"

### ISSUE THREAD

**Issue by abclution** [DeviaVir/zenbot#490]
something broken.
➜  zenbot git:(master) ✗ zenbot sim --paper bitfinex.bch-btc
error: could not find product "BTC-LTC"
➜  zenbot git:(master) ✗ zenbot trade --paper bitfinex.bch-btc
fetching pre-roll data:

running it as a trade or paper starts the bot properly with the correct pairs

**Comment by abclution** [comment]
I think HEAD is now at 4b42380 Update all products.json (#482)
screwed everything

**Comment by DeviaVir** [comment]
Is this still an active issue? Did you run the product update script?
