### ISSUE TITLE
Is there any config variable to setup the fees in paper mode?

### ISSUE THREAD

**Issue by cbelizon** [DeviaVir/zenbot#496]
When we are trading in paper mode it would be useful to let the bot know which kind of fee is being applied in each transaction, is there any place to set this up?

If not this would be a really good improvement for paper mode.

**Comment by DeviaVir** [comment]
This is set per exchange, see for an example:
https://github.com/carlos8f/zenbot/blob/master/extensions/exchanges/bitstamp/exchange.js#L193

You do not need to set the fee yourself.
