### ISSUE TITLE
Question about adding of assets/currency while bot is running

### ISSUE THREAD

**Issue by procmail** [DeviaVir/zenbot#497]
During live trading mode, as the bot is running, will the bot detect new capital/asset and use them if i send more funds/coins to the exchange?

**Comment by cmroche** [comment]
Yes, the bot synchronizes the balance on a regular basis and will and use new assets in the currency/asset pair that you've selected. However what the bot cannot do is compensate for this in the profitability calculations. Adding either will cause the bot to report high profitability, and removing them would cause the bot to report reduced profitability. Next time you launch the bot you can reset this with the `--reset_profit` option
