### ISSUE TITLE
 buy order timed out, adjusting price

### ISSUE THREAD

**Issue by crack00r** [DeviaVir/zenbot#500]
Isnt it possible to set c.markup_pct = -2 ?

When i set a - infront, i just get this
2017-08-19 19:48:42 - placing buy order...

2017-08-19 19:48:43 - buy order timed out, adjusting price
order status: rejected, bid: 0.00023689, -0.00000464 below best bid, 0.0% filled
order status: rejected, bid: 0.00023689, -0.00000464 below best bid, 0.0% filled

2017-08-19 19:48:46 - placing buy order...

2017-08-19 19:48:47 - buy order timed out, adjusting price

**Comment by sniper7kills** [comment]
markup_pct is the % to mark up or down ask/bid price.

I'm not sure why you would want a negative number as it automatically adjusts down 2% for buys and up 2% for sells, if you just set it to 2.

----

If I'm not mistaken, the error is saying that you are trying to place a buy order 0.00000464 ABOVE the lowest sell order and the exchange is rejecting it because you have mode set to taker.

**Comment by crack00r** [comment]
it didnt care if maker ore taker
with: c.markup_pct = 2
i allways get
```
2017-08-20 05:07:00 - buy order placed at 0.00069095 BTC
order status: open, bid: 0.00069095, 0.00001410 below best bid, 0.0% filled

2017-08-20 05:07:11 - 0.00141014 vs our 0.00069095
```
but i want a 100% buy... so i want to give more money then the price is right now...

**Comment by crack00r** [comment]
same problem here
https://github.com/carlos8f/zenbot/issues/360

how to buy 100 into a coin... maker/taker didnt help... it always want .15%...

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
