### ISSUE TITLE
npm install fails on talib@1.0.3

### ISSUE THREAD

**Issue by dannystommen** [DeviaVir/zenbot#503]
trying to run npm install:

$ npm install
npm WARN zenbot4@4.0.5 No repository field.
npm WARN zenbot4@4.0.5 No license field.

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for talib@1.0.3: wanted {"os":"darwin,linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin,linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DannyStommen\AppData\Roaming\npm-cache\_logs\2017-08-20T09_19_19_478Z-debug.log

Relevant output from the debug log file:
556 verbose stack Error: Unsupported platform for talib@1.0.3: wanted {"author":{"name":"Mustafa Oransel"},"contributors":[{"name":"Alfred Omega"},{"name":"Vedran Opacic"},{"name":"Kelvin Foo"}],"name":"talib","description":"Technical Analysis Library","version":"1.0.3","homepage":"https://github.com/oransel/node-talib","repository":{"type":"git","url":"git+https://github.com/oransel/node-talib.git"},"os":["darwin","linux"],"scripts":{"install":"node ./src/lib/build.js && node-gyp configure && node-gyp build","clean":"rm -rf ./build && rm -rf ./node_modules && node ./src/lib/clean.js"},"main":"build/Release/talib.node","engines":{"node":">=4.1.1"},"dependencies":{"nan":"^2.5.0"},"devDependencies":{},"optionalDependencies":{},"keywords":["talib","stocks","stock market"],"licenses":[{"type":"LGPL License","url":"http://www.gnu.org/licenses/lgpl.html"}],"bugs":{"url":"https://github.com/oransel/node-talib/issues"},"_id":"talib@1.0.3","_resolved":"https://registry.npmjs.org/talib/-/talib-1.0.3.tgz","_requested":{"type":"version","registry":true,"raw":"talib@1.0.3","name":"talib","escapedName":"talib","rawSpec":"1.0.3","saveSpec":null,"fetchSpec":"1.0.3"},"_integrity":"sha1-6wp+P1MBsyOwrwL7M41DHSubc1o=","_from":"talib@1.0.3","_spec":"1.0.3","_where":"C:\\Projects\\zenbot","_args":[["talib@1.0.3","C:\\Projects\\zenbot"]]} (current: {"os":"win32","cpu":"x64"})
556 verbose stack     at checkPlatform (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-install-checks\index.js:45:14)
556 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
556 verbose stack     at ret (eval at makeNodePromisifiedEval (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:13:39)
556 verbose stack     at readJson.then.catch.then (C:\Program Files\nodejs\node_modules\npm\lib\install\action\refresh-package-json.js:31:12)
556 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
556 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
556 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
556 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
556 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
556 verbose stack     at Promise._fulfill (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:638:18)
556 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:582:21)
556 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
556 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
556 verbose stack     at Promise._fulfill (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:638:18)
556 verbose stack     at Promise._resolveCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:432:57)
556 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:524:17)
557 verbose pkgid talib@1.0.3
558 verbose cwd C:\Projects\zenbot
559 verbose Windows_NT 10.0.15063
560 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
561 verbose node v8.4.0
562 verbose npm  v5.3.0
563 error code EBADPLATFORM
564 error notsup Unsupported platform for talib@1.0.3: wanted {"os":"darwin,linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
565 error notsup Valid OS:    darwin,linux
565 error notsup Valid Arch:  any
565 error notsup Actual OS:   win32
565 error notsup Actual Arch: x64
566 verbose exit [ 1, true ]

Seems like talib is not supported for Windows, but would be kind of strange,,, Am I doing something wrong?

Thanks,
Danny

**Comment by pharrisee** [comment]
Seeing the same here.

Windows 10 x64

**Comment by cmroche** [comment]
At the top of the output, it says that it is only supported on linux and OS X.

You will need to use docker to run this in a windows environment, or you will need to use OSX or Linux.

As another potential option, it does seem to install if you install Bash for Windows as part of the Windows 10 linux subsystem feature and compile through that. I have not thoroughly tested that this works. If you do, let us know how it goes.

**Comment by xxKryptonite** [comment]
I think I am having the same issue, trying it on ubuntu right now:

```
npm WARN zenbot4@4.0.5 No repository field.
npm WARN zenbot4@4.0.5 No license field.
npm ERR! Linux 4.10.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! talib@1.0.3 install: `node ./src/lib/build.js && node-gyp configure && node-gyp build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the talib@1.0.3 install script 'node ./src/lib/build.js && node-gyp configure && node-gyp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the talib package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./src/lib/build.js && node-gyp configure && node-gyp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs talib
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls talib
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/zenbot/npm-debug.log
```

**Comment by nikkadim** [comment]
same Centos 6
```
[root@bla zenbot]# npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!

> talib@1.0.3 install /root/zenbot/node_modules/talib
> node ./src/lib/build.js && node-gyp configure && node-gyp build

building talib functions...
sh: /usr/local/lib/node_modules/npm/bin/node-gyp-bin/node-gyp: Permission denied
npm WARN zenbot4@4.0.5 No repository field.
npm WARN zenbot4@4.0.5 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! talib@1.0.3 install: `node ./src/lib/build.js && node-gyp configure && node-gyp build`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the talib@1.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-24T21_10_43_353Z-debug.log
[root@bla zenbot]# 
```

**Comment by cmroche** [comment]
Hi, the error message says

`sh: /usr/local/lib/node_modules/npm/bin/node-gyp-bin/node-gyp: Permission denied`

Which means you probably installed npm packages using sudo at some point. This has broken your npm installation, it is not a defect with zenbot. It is also not the same error as the original one posted.

**Comment by dannystommen** [comment]
Sorry for my late response on this.

Just tried to run it using docker.


ERROR: for zenbot_server_1  Cannot create container for service server: An error occured while sharing drive

ERROR: for server  Cannot create container for service server: An error occured while sharing drive
ERROR: Encountered errors while bringing up the project.

Not sure why, but seems it can not access my C drive. Also seems to be quite a common Docker issue when I google this, but still haven't found any solution. 

Any idea how to solve this? Or would you recommend running Linux?

**Comment by cmroche** [comment]
`ERROR: for zenbot_server_1 Cannot create container for service server: An error occured while sharing drive`

Probably should be a new issue in case other people have the same question. But you need to setup drive sharing, check your docker for windows settings after launching the application, there is a whole section for configuring this in there.

**Comment by thejewce** [comment]
You might try running virtual box or some other vm solution.

**Comment by jack5432109** [comment]
I successfully installed zenbot via bash subsystem for windows 10.
Im facing the issues while installing on aws-ubuntu instance (building talib)

**Comment by campbellgoe** [comment]
I fixed a ta-lib issue with [npm install --global windows-build-tools](https://www.npmjs.com/package/windows-build-tools)

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖

**Comment by Ruud-cb** [comment]
Hi @DeviaVir 

I believe you should look into this, I think 100% of windows users encounter this issue. I tested on my system which has already visual studio, npm, git, python installed and on a laptop which still had to download all tools and encountered the same error.

I know this is a issue of `forex.analytics` project that requires talib to compile scripts. I would recommend looking for an alternative  or remove it all together because this is just time consuming trial and error searching and searching with no results. Seriously spend 3 hours trying to find a solution and ended up deleting it from the project.json in hope it is not used that much...

The solutions provided here did not work for me (installing windows build tools). Also tried to specify a python version for npm and node but without success.

Any more solutions are welcome but if found I would recommend adding the solution to your readme for windows users.
 
```
PS C:\Users\Ruud\Documents\git\zenbotbooyah\zenbot> npm i

> talib@1.0.5 install C:\Users\Ruud\Documents\git\zenbotbooyah\zenbot\node_modules\talib
> node ./src/lib/build.js && node-gyp configure && node-gyp build

building talib functions...
 The system cannot find the path specified.


C:\Users\Ruud\Documents\git\zenbotbooyah\zenbot\node_modules\talib>if not defined npm_config_node_gyp (node "C:\Users\Ruud\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure )  else (node "C:\Users\Ruud\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure )

C:\Users\Ruud\Documents\git\zenbotbooyah\zenbot\node_modules\talib>if not defined npm_config_node_gyp (node "C:\Users\Ruud\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build )  else (node "C:\Users\Ruud\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" build )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  talib.cpp
  win_delay_load_hook.cc
c:\users\ruud\documents\git\zenbotbooyah\zenbot\node_modules\talib\src\talib.cpp(85): warning C4996: 'Nan::Callback::Ca
ll': was declared deprecated [C:\Users\Ruud\Documents\git\zenbotbooyah\zenbot\node_modules\talib\build\talib.vcxproj]
  c:\users\ruud\documents\git\zenbotbooyah\zenbot\node_modules\nan\nan.h(1618): note: see declaration of 'Nan::Callback
  ::Call'
c:\users\ruud\documents\git\zenbotbooyah\zenbot\node_modules\talib\src\talib.cpp(95): warning C4996: 'Nan::Callback::Ca
ll': was declared deprecated [C:\Users\Ruud\Documents\git\zenbotbooyah\zenbot\node_modules\talib\build\talib.vcxproj]
  c:\users\ruud\documents\git\zenbotbooyah\zenbot\node_modules\nan\nan.h(1618): note: see declaration of 'Nan::Callback
  ::Call'
c:\users\ruud\documents\git\zenbotbooyah\zenbot\node_modules\talib\src\talib.cpp(543): warning C4996: 'Nan::Callback::C
all': was declared deprecated [C:\Users\Ruud\Documents\git\zenbotbooyah\zenbot\node_modules\talib\build\talib.vcxproj]
  c:\users\ruud\documents\git\zenbotbooyah\zenbot\node_modules\nan\nan.h(1618): note: see declaration of 'Nan::Callback
  ::Call'
c:\users\ruud\documents\git\zenbotbooyah\zenbot\node_modules\talib\src\talib.cpp(917): warning C4244: '=': conversion f
rom 'int64_t' to 'int', possible loss of data [C:\Users\Ruud\Documents\git\zenbotbooyah\zenbot\node_modules\talib\build
\talib.vcxproj]
c:\users\ruud\documents\git\zenbotbooyah\zenbot\node_modules\talib\src\talib.cpp(981): warning C4244: '=': conversion f
rom 'int64_t' to 'int', possible loss of data [C:\Users\Ruud\Documents\git\zenbotbooyah\zenbot\node_modules\talib\build
\talib.vcxproj]
LINK : fatal error LNK1181: cannot open input file '..\src\lib\lib\ta_libc_csr.lib' [C:\Users\Ruud\Documents\git\zenbot
booyah\zenbot\node_modules\talib\build\talib.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Ruud\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ruud\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd C:\Users\Ruud\Documents\git\zenbotbooyah\zenbot\node_modules\talib
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! talib@1.0.5 install: `node ./src/lib/build.js && node-gyp configure && node-gyp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the talib@1.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ruud\AppData\Roaming\npm-cache\_logs\2018-10-30T20_22_18_922Z-debug.log
```
