### ISSUE TITLE
Kraken API returned error: API:Invalid nonce

### ISSUE THREAD

**Issue by jeroenpeeters** [DeviaVir/zenbot#507]
I get a lot of 

`Kraken API warning - unable to call trade (Error: Kraken API returned error: API:Invalid nonce), retrying in 0.15s`

and

`Kraken API warning - unable to call getBalance (Error: Kraken API returned error: API:Invalid nonce), retrying in 0.15s`

I have the feeling that because of this error the bot is not always doing what it intended to do, or is that not the case? In other words, does this error negatively impact the bot's operation?

The Kraken api key is only used once. I've widened the Nonce Window on Kraken to '15', whatever that means.

Please advice.

**Comment by cmroche** [comment]
This more likely relates to performance issues on the kraken exchange, honestly. They've been having a lot of reliability issues that can cause re-ordering of requests and cause the nonce issue. Additionally internet time synchronization can cause minute changes in local time on your PC and also impact this.

The kraken-api uses milliseconds CPU time for the nonce it generates so a nonce window of '15' is going to do very little for you. Try setting it to something between 3000 and 15000 (as is recommended by the Kraken API) https://www.kraken.com/help/api

**Comment by sfdu** [comment]
In which file do we have to change it?

**Comment by cmroche** [comment]
@sfdu It's an API setting on Kraken, you'll need to login to your account and configure it there.
