### ISSUE TITLE
Initial buy or sell price too far from mid market

### ISSUE THREAD

**Issue by rockcat** [DeviaVir/zenbot#508]
There is a big delay in buying or selling - sometimes as much as 30 mins which seems to be due to the initial price being so far from mid market that it cannot be achieved. The adjustment algorithm kicks in nicely but doesn't move the price sufficiently and often the bot is left chasing the market up or down - generally losing money in the process.

This code in engine.js

`          if (signal === 'buy') {`
`            price = n(quote.bid).subtract(n(quote.bid).multiply(so.markup_pct / 100)).format(s.product.increment, Math.floor)`

(and the same for selling) seems to use the current bid (or ask for selling) price when placing an order which is then too slow to fill. Is there any way to use a less aggressive price?

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
