### ISSUE TITLE
Calculate periods based on volume instead of time

### ISSUE THREAD

**Issue by kmarhold** [DeviaVir/zenbot#511]
Is there any way to have periods based on trade volume instead of time? For instance, I would like to tell the bot to open a new period each time the trade volume has reached 5. Can this be achieved somehow?

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
