### ISSUE TITLE
Binance Exchange support

### ISSUE THREAD

**Issue by silentrob** [DeviaVir/zenbot#513]
They have the lowest fees in the market right now.
https://binance.zendesk.com/hc/en-us/articles/115000429332
Trading: .1%

**Comment by cirrusdex** [comment]
agree binance is a great up and coming exchange and pro tip, buy $50 worth of BNB and select use BNB for trading fees, you get a 50% discount

**Comment by milaas** [comment]
hi there somebody working on binance support?_

**Comment by ramene** [comment]
This was discussed in discord #development channel and confirmed working by atleast one other 

`docker-compose exec server zenbot backfill binance.XRP-ETH start="20171228110000" end="201712281110000"`

`docker-compose exec server zenbot trade --paper --days=1 --asset_capital=1000.000000 --currency_capital=0.1000000 binance.XRP-BTC`

#### Error

```
An error occurred { Error: binance {"code":-1127,"msg":"More than 1 hours between startTime and endTime."}
    at binance.handleErrors (/app/node_modules/ccxt/js/binance.js:751:23)
    at response.text.then.text (/app/node_modules/ccxt/js/base/Exchange.js:433:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: ExchangeError] }
```
_Please note the ambiguity between  `--startTime=`, `--start=` and `start=` and the error as it currently reads_

#### Fix
Change the getTrades function  in:  `extensions/exchanges/binance/exchange.js` to add/subtract 1 hour versus 12 

```
getTrades: function (opts, cb) {
      var func_args = [].slice.call(arguments)

      var args = {};
      if (opts.from) {
        args.startTime = opts.from
      }
      if (opts.to) {
        args.endTime = opts.to
      }
      if (args.startTime && !args.endTime) {
        // add 1 hour instead of 12
        args.endTime = args.startTime + 3600000
      }
      else if (args.endTime && !args.startTime) {
        // subtract only 1 hour instead of 12
        args.startTime = args.endTime - 3600000
      }
      ....
```

**Comment by wilderuncat** [comment]
Just wanted to note that this worked for me.

**Comment by DeviaVir** [comment]
I think this has been resolved by a recently merged PR, could you please update zenbot and try again?

**Comment by DeviaVir** [comment]
https://github.com/DeviaVir/zenbot/pull/1027
