### ISSUE TITLE
Sell as a Taker after a X% (configurable) slippage

### ISSUE THREAD

**Issue by mariotsi** [DeviaVir/zenbot#515]
Hi,
could be useful, mainly in sell, to sell as a taker when the price is getting down very fast and the bot continue to add new order with adjusted price. It can be configurable with % respect the original price or also "Sell as taker after X try as maker"

**Comment by DeviaVir** [comment]
I mark this as `invalid` because I think this ticket is a dup, but I need to find the ticket that it duplicates before I close this.

**Comment by vitorego** [comment]
maybe this one: https://github.com/carlos8f/zenbot/issues/268

**Comment by DeviaVir** [comment]
thanks @vitorego, that's the one.
