### ISSUE TITLE
Bitfinex buy problem

### ISSUE THREAD

**Issue by voltz67** [DeviaVir/zenbot#516]
Hello, I'm trying to use Zenbot on Bitfinex.OMG-BTC. I have added the API key in config.js, authentification is OK but Zenbot didn't buy whereas it detect that it's time to buy (screenshot).

Have you a solution to this problem ?
Thank you :)

![capture du 2017-09-02 16-08-19](https://user-images.githubusercontent.com/31568474/29996125-07520066-8ff9-11e7-840b-1961af512381.png)

**Comment by nedievas** [comment]
What messages do you see at that moment on the Bitfinex web platform?

**Comment by crubb** [comment]
Hey, a single "buy" signal might not mean, that zenbot will start buying. The signal might for example have changed within the period. zenbot will only start buying if you see "buying". Please run with `--debug`, that'll give you more information.

**Comment by benjamincburns** [comment]
I've been digging into this just now. Relevant info over [here](https://github.com/DeviaVir/zenbot/issues/868#issuecomment-354963455) on #868.

**Comment by benjamincburns** [comment]
> Hey, a single "buy" signal might not mean, that zenbot will start buying. The signal might for example have changed within the period.

The signal changing on the next `onPeriod` is reason for _canceling_ an open order. However, if there's a `buy` or a `sell` signal, provided there is currency or asset available, I'd expect an order to be placed during the same period.

> zenbot will only start buying if you see "buying"
This is printed when there is an open buy order at the start of a period, not when the order itself is opened.

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
