### ISSUE TITLE
Db.prototype.authenticate method will no longer be available in the next major release 3.x

### ISSUE THREAD

**Issue by berendt** [DeviaVir/zenbot#521]
When working with ``master`` I got the following warning message after calling ``zenbot.sh``:

```
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
```

Used the following Mongo service:

```
# mongod --version
db version v3.4.7
git version: cf38c1b8a0a8dca4a11737581beafef4fe120bcd
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
allocator: tcmalloc
modules: none
build environment:
    distmod: debian81
    distarch: x86_64
    target_arch: x86_64
```

**Comment by vaisov** [comment]
Same here.

**Comment by pgnjidic** [comment]
Same here...

> #mongod --version
db version v3.6.0
git version: a57d8e71e6998a2d0afde7edc11bd23e5661c915
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1604
    distarch: x86_64
    target_arch: x86_64

>

**Comment by pgnjidic** [comment]
@vaisov @berendt Did you succeed to solve this problem?

**Comment by kingsolo50** [comment]
I update mongoose to version 5.0.15 and that seemed to fix the warning
