### ISSUE TITLE
zenbot sell profit_stop_enable_pct

### ISSUE THREAD

**Issue by crack00r** [DeviaVir/zenbot#523]
how is it possible to get this working
./zenbot.sh sell --profit_stop_enable_pct=1 --profit_stop_pct=0.25 --order_adjust_time=100 --sell_pct=100  poloniex.btc_eth

**Comment by crack00r** [comment]
this dont work... right now

![image](https://user-images.githubusercontent.com/6163329/30082524-646d3150-928b-11e7-86b9-7ef13cf67fb8.png)

**Comment by crack00r** [comment]
it just sells... but dont add a trailing stop

**Comment by ether-btc** [comment]
the syntax of the command is limited to:

> zenbot sell <selector> [--size=<size>] [--pct=<pct>]

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
