### ISSUE TITLE
Send keys on command line

### ISSUE THREAD

**Issue by davidlondono** [DeviaVir/zenbot#524]
It would be nice to send the keys of the exchanges on the BUY SELL commands.
So to some one use diferent accounts on the same code

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
