### ISSUE TITLE
mongo error

### ISSUE THREAD

**Issue by grrminator** [DeviaVir/zenbot#547]
`fetching pre-roll data:
(node:2259) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: not authorized on zenbot4 to execute command { listIndexes: "trades", cursor: {} }
(node:2259) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2259) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): MongoError: not authorized on zenbot4 to execute command { listIndexes: "resume_markers", cursor: {} }
(node:2270) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: not authorized on zenbot4 to execute command { listIndexes: "trades", cursor: {} }
(node:2270) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2270) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): MongoError: not authorized on zenbot4 to execute command { listIndexes: "resume_markers", cursor: {} }

/home/john/zenbot/commands/backfill.js:52
          if (err) throw err
                   ^
MongoError: not authorized on zenbot4 to execute command { find: "resume_markers", filter: { selector: "gdax.BTC-USD" } }
    at Function.MongoError.create (/home/john/zenbot/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/home/john/zenbot/node_modules/mongodb-core/lib/cursor.js:212:36)
    at /home/john/zenbot/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)` 
can anyone help me?

**Comment by Froelund** [comment]
It looks like missing permissions on your mongo connection.

**Comment by grrminator** [comment]
Ok. How do i fix that? i followed a mondo tutorial and added an admin user. i also added a database user but neither of those work with zenbot.

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
