### ISSUE TITLE
How to run on Raspberry Pi w/ Raspbian

### ISSUE THREAD

**Issue by brucetus** [DeviaVir/zenbot#553]
(I'm running it on a Raspberry Pi 3 with Raspbian Stretch)

**1. Install nodejs.** 
http://thisdavej.com/beginners-guide-to-installing-node-js-on-a-raspberry-pi/

**2. Install docker and docker-compose.**
Docker:
https://blog.alexellis.io/getting-started-with-docker-on-raspberry-pi/
Docker-compose instructions at the end of this page:
https://pixelchrome.org/blog/quickstart-guide-how-to-install-docker-a-raspberry-pi/

**3. Install this or another mongodb dockerfile made for the rapsberry pi.**
https://hub.docker.com/r/nonoroazoro/rpi-mongo/

**4.Rename the mongodb dockerfile to "mongo"** so that the conf.js from zenbot works with it.
In my case:
`docker tag nonoroazoro/rpi-mongo:latest mongo:latest`

**5.Run the mongo dockerfile.**
`docker run mongo`
(You can control-c or command-c to close the dialogue after it stays at "waiting for connections on port 27017") 
`docker ps`
to make sure mongo is running

**6. Run zenbot.**
`cd zenbot`
`docker-compose build`
`docker-compose up -d`

Commands are the same
`docker run --rm --link zenbot_mongodb_1:mongodb -it zenbot_server ./zenbot.sh [command]`

There ya go

**Comment by nedievas** [comment]
Let's move that to DOCS.md or README.md?

**Comment by brucetus** [comment]
I submitted a pull request. This is my first time doing so, so if I messed anything up let me know.

**Comment by Jope31** [comment]
Hi bmorovati,
I've been trying to install Zenbot on my RPI 3 for a while now, and this is the closest I've got. With your instuctions I'm getting an error on step 5/9, please see below:

> mongodb-data uses an image, skipping
mongodb uses an image, skipping
Building server
Step 1/9 : FROM node:boron
 ---> 9c50a941c838
Step 2/9 : RUN mkdir -p /app
 ---> Using cache
 ---> 60e07b4fe08f
Step 3/9 : WORKDIR /app
 ---> Using cache
 ---> d6c33d4717c8
Step 4/9 : COPY package.json /app/
 ---> adb45d416bbe
Removing intermediate container 69240bbd5d64
Step 5/9 : RUN npm install -g node-gyp && npm install --unsafe-perm
 ---> Running in 965c86161d1e
Illegal instruction (core dumped)
ERROR: Service 'server' failed to build: The command '/bin/sh -c npm install -g node-gyp && npm install --unsafe-perm' returned a non-zero code: 132

I'm still learning as I go with Docker, npm and the rest and Google returns no useful results. Can you tell what I'm doing wrong?
