### ISSUE TITLE
trailing stop

### ISSUE THREAD

**Issue by ALaPlaceO** [DeviaVir/zenbot#554]
hi, 

is there an ambition to implement a strategy that is only doing a normal trailing stop in the near future? 
(following the trend and reset "highest price" if new highest price is given and then when falling x% sell signal takes effect) 
would be great if this could be implemented

**Comment by nedievas** [comment]
Don't we have it with these now?

> --profit_stop_enable_pct <pct>  enable trailing sell stop when reaching this % profit
> --profit_stop_pct <pct>         maintain a trailing stop this % below the high-water mark of profit

**Comment by ALaPlaceO** [comment]
is this a question or do you know that it is possible? like I understand it, the used strategy (one of the implemented in zenbot) then must be set up with values that the strategy doesnt work, because otherwise it would get in the way of the set trailing (if this is the real trailing like I mentioned).. or am I wrong? if you know how to set it up would be great if you could help out/ or someone else who knows how to configure it..thank you

**Comment by nedievas** [comment]
I suppose it is what you are seeking. It works with` zenbot trade` (uses strategy), but does not work with` zenbot buy` or `sell`

**Comment by ALaPlaceO** [comment]
I think you mean the same thing like me in the text above. so zenbot only works with a strategy when you say "zenbot trade" , except the manual trading when you say "zenbot buy or sell" which hasnt any functions, is this correct? so then the strategy musnt work to not interupt the set trailing syntax above? is this correct? if yes could you tell me a possible setting I would need, because Im totally noob in zenbot strategys and the syntax? would be great thank you.. 

ps: are you sure that the zenbot trailing really works like the trailing I was talking in the first text? so in the first line I would write like 1% then when price is rising 1% the trailing starts? and in the secon line the "high-water mark" is always replaced if a new "highest price" is reached?

**Comment by nedievas** [comment]
That really works in sims and in live trading:
`--profit_stop_enable_pct 10 --profit_stop_pct 1`

**Comment by ALaPlaceO** [comment]
ok sounds great. so when you say live trading, there always is a strategy from zenbot behind working isnt it? or does the trailing also work with --manual trading? 

if not the strategy has to be turned off to not interupt the trailing or am I wrong?

**Comment by nedievas** [comment]
Yes. There is a strategy behind. In manual trading this should not work like you wish, while pressing 's'ell or 'b'uy will execute order immediately,
