### ISSUE TITLE
Debian installation

### ISSUE THREAD

**Issue by bart886** [DeviaVir/zenbot#563]
I want install zenbot4 on Debian. 
debug.log
https://pastebin.com/fpeh0qz3

**Comment by grigio** [comment]
probably you miss some packages to build some zenbot dependecies.. 
```
sudo apt install build-essential 
```
do you have it or something similar?

**Comment by bart886** [comment]
g++: error: ../lib/ta-lib/lib/libta_abstract_csr.a
g++: error: ../lib/ta-lib/lib/libta_func_csr.a
g++: error: ../lib/ta-lib/lib/libta_common_csr.a
g++: error: ../lib/ta-lib/lib/libta_libc_csr.a

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
