### ISSUE TITLE
Bitstamp constant "buying/selling" issue

### ISSUE THREAD

**Issue by mercatorTU** [DeviaVir/zenbot#575]
Whenever I (or zenbot) trigger a buy or sell order at Bitstamp, I constantly get the "buying" output on the console. It does not stop to output "buying" although the asset has already been bought. The same happens for selling. If I sell manually on the exchange directly, the bot buys the asset immediately again because it is still in buying mode.
Here are a few lines console output as an example
#### 
2017-09-30 15:16:00  301.350 ETH-USD   +0.35%     1880   61 ++        067     044   buying 
2017-09-30 15:18:09  300.920 ETH-USD   +0.21%     1985   59 ++        059     022   buying 
2017-09-30 15:20:01  301.390 ETH-USD   +0.16%       11   61 ++        080     100   buying 
2017-09-30 15:21:56  301.290 ETH-USD   +0.12%       17   61 ++        075     100   buying 

In this example the asset has been bought over 1 hour ago.

I usually issue "maker" orders on Bitstamp, which means they are usually immediately fulfilled. 
Zenbot does not seem to get confirmation that the order has ever been fulfilled. 

Could you please look into it and fix it.

Thanks a lot for your excellent work!

**Comment by evseevnn-zz** [comment]
Same problem on Bitfinex

**Comment by crubb** [comment]
Please post a log with `--debug` enabled.

**Comment by mercatorTU** [comment]
Hi, I used the --debug switch but the console output is exactly the same as without --debug.
I do not know why the behavior changed but in the recent version zenbot writes "buy" and immediately in the next line "buying", as I would expect, but does not buy the asset. It never gets bought.
Very strange behavior on bitstamp and no assets get bought at all even though the buying gets triggered.
Do you want me to pipe the console output into a textfile? --debug doesn't do anything

**Comment by JohnnyJai** [comment]
I have the same issue, but I am using gdax.

<img width="960" alt="screen shot 2017-10-30 at 22 02 03" src="https://user-images.githubusercontent.com/612351/32195587-ff8de974-bdbd-11e7-8dc9-8adb04d5f89f.png">

**Comment by LoneWolf345** [comment]
It has been quite awhile since the last comment.  Do you feel your issue is resolved?  Please consider closing it.

**Comment by DeviaVir** [comment]
Closing, it's cheap to re-open.
