### ISSUE TITLE
Windows/Linux/Docker??

### ISSUE THREAD

**Issue by jasurakk** [DeviaVir/zenbot#601]
Hi all!

I'm interested on this Zenbot, but before downloading & installing it I just wanted to ask your opinion for the most suitable platform for it. My both PC's have Windows 10, so I don't have any Linux machines available, and no any other need for Linux either. Naturally I could run some Linux distro on VM, if it gives any benefit over running it directly in Windows. I'm surely not a Linux expert in ways, but I'm think that with loooots of Googling I could manage it.

Docker is totally new for me, just checked from Wikipedia what it even is ;=)

So, what's your opinion on this, should this newbie use Win10, Win10 + (some? )Linux VM, or Win10 + Docker??

**Comment by zemelax** [comment]
Docker probably, but to be honest, I generally do not understand anything, especially where to insert api keys, how to properly start the docker, I'm new, too. Here if on youtube someone has hung a installation visually or on screens would be abruptly

**Comment by jasurakk** [comment]
Ok, thanks, but why? I would like to understand pros/cons of all these options, if there really is any real life difference between them.

And, if it makes any difference regarding the choice, my final goal would be to have 5-10 bots running for different pairs per exhange, on a few largest exchanges.

**Comment by jasurakk** [comment]
Now that I think, maybe it would be best to use Linux anyway. I'm surely going for some cloud platform, and Linux seems to be the cheapest option by far. Digital Ocean for example offers a Linux VM's starting from 5$/month!  Ok, maybe a desktop usage would require that 10$ version with 1MB of memory, but it's still quite cheap.

But does it matter at all which distro I choose? Does it make any difference from Zenbot point of view if I use Ubuntu, CentOS, Fedora or Debian?

**Comment by mluis** [comment]
@jasurakk you don't need to choose a specific OS. If you use Docker you can keep your favourite one since the options remain in x86 and ARM.

It lacks documentation and I'm completing it but you only need to 'volume' your conf.js file. It will be updated on my docker hub @mluis 

Enjoy :)

**Comment by jasurakk** [comment]
Ok, thanks mluis! :=)
