### ISSUE TITLE
Trading Strategies?

### ISSUE THREAD

**Issue by rudehn** [DeviaVir/zenbot#604]
Hi All. I was just curious as to what trading strategies people are going with. I'm still new to this community, but from my take on it the following would seem like a good approach:

1. Find a trading pair and market with good liquidity.
2. Run a bunch of simulations to determine good trading strategies and parameter settings.
3. See how the strategy holds during paper trading.
4. Go to live trading.

This is a lot of steps to run through for each trading pair/market you would like to trade (since your fine tuned strategy may not apply to each market / trading pair). Potential automation?

I was wondering if there were other approaches people were using and wouldn't mind sharing?

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
