### ISSUE TITLE
Can I run zenbot trade in the background ?

### ISSUE THREAD

**Issue by ituhin** [DeviaVir/zenbot#611]
I was thinking about leaving it running in the background in aws ec2 for a day

eg: nohup zenbot trade bitfinex.BTC-USD --paper --strategy rsi > /tmp/t.out &

but its not working. within a minute its saying stopped, though the process is running in the background. then i am able to do a fg and issue X for exit. 

i used nohup so that i can do a logout from ec2 console, which gets disconnected anyway if i leave it open for too long. and i didnt wanna leave it running from my home as network is not that stable.

is there any way to make it work ?

**Comment by typicalaimster** [comment]
I installed screen on my EC2 instance run zenbot inside a screen. The nice thing is the ability to attach/detach and :split the window. So you can run multiple bots in a split window. Just search for GNU screen cheat sheet to get the ctrl+a commands to do things.. Also I'd suggest naming your sessions.. Eg 'screen -R trading' or 'screen -R paper'. So you can later attach by doing a 'screen -x trading'. 

![capture](https://user-images.githubusercontent.com/5075528/31472085-558d5fc0-aea1-11e7-8b8b-3cfaf5a7c4b6.PNG)

**Comment by JensvdHeydt** [comment]
I think part of this information should be included in the doc

**Comment by DeviaVir** [comment]
I disagree, this is out of scope for zenbot. Running apps in the background with either Docker or screen/tmux is too common to have to be documented in the apps themselves.
