### ISSUE TITLE
help a newbe please

### ISSUE THREAD

**Issue by zemelax** [DeviaVir/zenbot#613]
container_linux.go:265: starting container process caused "process_linux.go:368: container init caused \"rootfs_linux.go:57: mounting \\\"/c/zenbot1/conf.js\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/aufs/mnt/0814ca175a9117a3e92362196d35f7d4741a96c6dfde164bda8204db67e57b53\\\" at \\\"/mnt/sda1/var/lib/docker/aufs/mnt/0814ca175a9117a3e92362196d35f7d4741a96c6dfde164bda8204db67e57b53/app/conf.js\\\" caused \\\"not a directory\\\"\""

whats problem? 

and else
conf-simle.js to conf.js    im must rename file and add api and api key in the conf.js, I understand correctly,?

**Comment by zemelax** [comment]
docker run -v /zenbot/conf.js:/app/conf.js mongo:latest  after this command im have this thrable


waiting for connections on port 27017

**Comment by zemelax** [comment]
If someone reads my bullshit and does not want to explain, but thinks that I'm going in the right direction, just put + 

"I found out that executing npm link gave an issue; zenbot wasn't placed into /usr/local/bin/
I can now finally use the zenbot 'command'.."  


I fight with this robot for 5 days already, and I have not even launched it yet .... but I want to win ..

P.S. just hard when the manual is not, and you also know the English badly. ((

**Comment by zemelax** [comment]
Creating zenbot_mongodb-data_1 ...
Creating zenbot_mongodb-data_1 ... done
Creating zenbot_mongodb_1 ...
Creating zenbot_mongodb_1 ... done
Creating zenbot_server_1 ...
Creating zenbot_server_1 ... error

ERROR: for zenbot_server_1  Cannot start service server: oci runtime error: cont
ainer_linux.go:265: starting container process caused "process_linux.go:368: con
tainer init caused \"rootfs_linux.go:57: mounting \\\"/c/zenbot/conf.js\\\" to r
ootfs \\\"/mnt/sda1/var/lib/docker/aufs/mnt/e0a4298c4da2cdabc5dab9ac511fa85af806
4b1b96268e844c0dff3b8c16a505\\\" at \\\"/mnt/sda1/var/lib/docker/aufs/mnt/e0a429
8c4da2cdabc5dab9ac511fa85af8064b1b96268e844c0dff3b8c16a505/app/conf.js\\\" cause
d \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the
specified host path exists and is the expected type

ERROR: for server  Cannot start service server: oci runtime error: container_lin
ux.go:265: starting container process caused "process_linux.go:368: container in
it caused \"rootfs_linux.go:57: mounting \\\"/c/zenbot/conf.js\\\" to rootfs \\\
"/mnt/sda1/var/lib/docker/aufs/mnt/e0a4298c4da2cdabc5dab9ac511fa85af8064b1b96268
e844c0dff3b8c16a505\\\" at \\\"/mnt/sda1/var/lib/docker/aufs/mnt/e0a4298c4da2cda
bc5dab9ac511fa85af8064b1b96268e844c0dff3b8c16a505/app/conf.js\\\" caused \\\"not
 a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the
specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.



again and again and again

**Comment by JensvdHeydt** [comment]
Don't get me wrong but I think the problem is not exactly a somewhat lacking documentation but you are missing basic npm / node and maybe linux knowledge here. I know that docker can be quite hard to understand and use in the beginning. That's why you can always use zenbot on a native system, native in normal Linux with a MongoDb installed. 

Regarding the problem at hand: The docker-compose file configures several "volumes" to be mounted inside the docker images. One of those is "conf.js" with it's target pointing at "/app/conf.js" in the zenbot_server docker image. Your docker installation seems to fail there. I don't know why because it's perfectly working for many other users. Maybe it's a very old version of docker you are using?

**Comment by zemelax** [comment]
node -v 8.7.0
npm -v 5.4.2
MongoDB in the service, works and connect to 127.0.0.1 ok
im douwnload zenbot in github
I read like I need to share the disk, but I do not have Docker a DockerTollbox and I do not know where the disk settings are. Going 7 days my install zenbot......

**Comment by zemelax** [comment]
what file should I open in MongoDB:  conf.js or zenbot.js ?

**Comment by zemelax** [comment]
$ docker version
Client:
 Version:      17.07.0-ce
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   8784753
 Built:        Tue Aug 29 17:41:05 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by zemelax** [comment]
$ docker info
Containers: 7
 Running: 2
 Paused: 0
 Stopped: 5
Images: 10
Server Version: 17.09.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 37
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.89-boot2docker
Operating System: Boot2Docker 17.09.0-ce (TCL 7.2); HEAD : 06d5c35 - Wed Sep 27
23:22:43 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8MiB
Name: default
ID: MBC4:V75F:KP5Q:TIC3:MH65:GXPO:4RY7:3RWU:355J:VR54:V365:JBLD
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 30
 Goroutines: 40
 System Time: 2017-10-13T20:10:22.76759278Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by sniper7kills** [comment]
My 2 cents;
Get an account with AWS; launch a nano ubuntu instance; (~20 a month after the free tier expires)

sudo apt-get update
sudo apt-get upgrade
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs

git clone https://github.com/carlos8f/zenbot.git
cd zenbot
npm install

cp conf-sample.js conf.js
vi conf.js
./zenbot.sh trade

**Comment by zemelax** [comment]
It seems to me easier, because the day before yesterday I somehow managed to do something after docker-compose up -d was
Creating zenbot_mongodb-data_1 ...
Creating zenbot_mongodb-data_1 ... done
Creating zenbot_mongodb_1 ...
Creating zenbot_mongodb_1 ... done
Creating zenbot_server_1 ...
Creating zenbot_server_1 ... done

but then another error with the module got out, and while I was trying to make it all fly away and I did not remember how I managed it (in my opinion whether the settings of the VB server are somewhere else, in short, I did not remember)

**Comment by zemelax** [comment]
Hope is no more. (

**Comment by zemelax** [comment]
ivan@i3:~/zenbot$ docker run --rm --link zenbot_mongodb_1:mongodb -it zenbot_server list-selectors
module.js:529
    throw err;
    ^

Error: Cannot find module './conf-sample'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at module.exports (/app/boot.js:12:18)
    at Object.<anonymous> (/app/zenbot.js:20:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)


a new problem.

**Comment by zemelax** [comment]
How can I change the configuration of strategies?

**Comment by zemelax** [comment]
Close the question, sort of figured out, it took time, but learned something new. Although how to properly change the tincture of the strategy has not yet understood, but I think I will deal with it. Thanks to all.
