### ISSUE TITLE
Two questions from a noob?

### ISSUE THREAD

**Issue by jasurakk** [DeviaVir/zenbot#619]
1) If the Zenbot for some reason gets killed after it has opened some trades, is it able to get "back in business" with those previously opened trades after it has been restarted? I.e. can it close those trades as planned?

2) Zenbot does not seem to have a "take profit" setting for closing the trade after wanted postive % change. But could the dynamic stoploss- setting be used for that, by setting the same value for both parameters?

**Comment by jasurakk** [comment]
Can anyone help with these questions, all information is highly appreciated! :-)

**Comment by mikeh21** [comment]
1. it will trade with what asset and currency is available on the exchange. starting a bot with asset it will trigger a sell order when conditions are met and it will sell the asset. however i understand it will not have some previously recorded info (asset bought price) so max_sell_loss_pct will not work.

2. see --greed in trust_distrust strategy, or use profit-stop-enable and profit_stop_pct

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
