### ISSUE TITLE
Simulation inconsistent results

### ISSUE THREAD

**Issue by ruimgoncalves** [DeviaVir/zenbot#62]
Hi
I've been playing around with Zenbot on windows for a week now, although I know you don't support it the only 2 things that doesn't work are the server, because of path problems, and the launch option, which can be averted by launching zenbot in separate processes.
I decided to go this way because the reducer is way faster than using it inside docker, so I decided to ditch the server for now since I can live without it.
On my first try I restored the database that you provide and backfilled the rest, runned the reducer and the simulations where consistent with your results.
The second time I decided to start from scratch and backfill all the data, for BTC in EUR and USD, it took +-1 day to backfill and reduce. 
I ran the simulations but this time they do not yield the same results, I've got BTC/USD = 1.297 ROI and BTC/EUR = 0.797774 ROI
The main thing I'm, confused is why the results where identical when I restored the database and why are they so off now. I also noticed that the bot only traded 4 times in BTC/EUR but traded 44 times in BTC/USD so something strange is happening here. 
I'm a newbie in trading so there must be something I'm doing wrong, but cant figure out what.

Here are my configs
- BTC/USD

``` javascript
var c = module.exports = require('./config')

c.assets = [
  "BTC"
]
c.currencies = [
  "USD",
  "EUR",
  "BTC"
]

// default selector for indicators, etc
c.default_selector = "gdax.BTC-USD"
//c.logic = require('./logic_2');
```
- BTC/EUR

``` javascript
var c = module.exports = require('./config')

c.assets = [
  "BTC"
]
c.currencies = [
  "EUR",
  "USD",
  "BTC"
]

// default selector for indicators, etc
c.default_selector = "gdax.BTC-EUR"
//c.logic = require('./logic_2')
```

Here is my latest sim data.

[BTCUSDsim.txt](https://github.com/carlos8f/zenbot/files/462076/BTCUSDsim.txt)
[BTCEURsim.txt](https://github.com/carlos8f/zenbot/files/462077/BTCEURsim.txt)

**Comment by ruimgoncalves** [comment]
Hummm
In the sim log for BTC/EUR I am getting  
`gdax.BTC-EUR missing RSI tick: 06/15/2016 11:40:00 PM WEST`

and then a lot of
`gdax.BTC-EUR aborting sell due to low perf. = -0.048`

How can I fix this without backfilling all again?

Here are the [logs](https://gist.github.com/ruimgoncalves/d5f6cf921ddb4de8e68198e751b61d8c)

**Comment by carlos8f** [comment]
Zenbot 4 is out, so I'm cleaning up 3.x issues. Please use and test 4, thanks!
