### ISSUE TITLE
GDAX - Good Till Time - expire_time required

### ISSUE THREAD

**Issue by sniper7kills** [DeviaVir/zenbot#628]
#596 appears to not include an expire_time variable in the request.

![Error](https://i.imgur.com/mjLTjYV.png)

**Comment by DeviaVir** [comment]
Please add this option to your `conf.js`:
https://github.com/carlos8f/zenbot/blob/master/conf-sample.js#L151
I will PR a default value.

**Comment by sniper7kills** [comment]
I've still got the issue.

And I've pulled the the latest merge as well.

**Comment by DeviaVir** [comment]
Okay, I have no clue. GDAX API (https://docs.gdax.com/) has no mention of `expire_time`, neither has `gdax` (npm) (https://github.com/coinbase/gdax-node/search?utf8=%E2%9C%93&q=expire_time&type=) ever heard of it.

**Comment by sniper7kills** [comment]
OK, I agree with you that there is no expire_time variable. It must just be the error message that is thrown by GDAX.

It looks like the cancel_after just isn't being put into the order request. All I have is:

```
[ { price: '5687.00',
    size: '0.01758560',
    orig_size: '0.01758560',
    remaining_size: '0.01758560',
    orig_price: '5687.00',
    product_id: 'BTC-USD',
    post_only: true,
    time_in_force: 'GTT',
    side: 'buy' } ]
```

**Comment by sniper7kills** [comment]
On a side note; doesn't cancel_after also need to be added at: https://github.com/carlos8f/zenbot/blob/master/lib/engine.js#L614 ?

**Comment by sniper7kills** [comment]
Doing some troubleshooting, and I think I've found the issue, not that I know how to fix it.

I've modified /extensions/exchanges/gdax/exchange.js
![GDAX Exchange.js](https://i.imgur.com/R0oeZqL.png)

Which Returns
![GDAX OPTIONS](https://i.imgur.com/ikeQnMh.png)

So it looks like the cancel_after option isn't getting to gdax/exchannge.js

**Comment by nedievas** [comment]
I think that `cancel_after: so.cancel_after || 'day'` should be in here: https://github.com/carlos8f/zenbot/blob/c97377889f8f8a5d142de597d8b839c92abe3275/lib/engine.js#L495

**Comment by sniper7kills** [comment]
@nedievas Added that, but it still doesn't make it to gdax/exchange.js

**Comment by sniper7kills** [comment]
@nedievas I added after https://github.com/carlos8f/zenbot/blob/master/lib/engine.js#L204
and it appears to have worked; as I didn't get an error this time but it also didn't place an order on gdax that I can see

**Comment by sniper7kills** [comment]
Disregard that would be the fix. Needs to be added after line 204.

I have verified an order placed on GDAX.

**Comment by DeviaVir** [comment]
@sniper7kills thanks for the investigative and testing work on this one. Can you verify it's fixed now?

**Comment by sniper7kills** [comment]
@DeviaVir no worries; and yes, testing now.

**Comment by sniper7kills** [comment]
Buy and Sell orders are working as expected.
