### ISSUE TITLE
Auto change trade pair

### ISSUE THREAD

**Issue by thitganuong** [DeviaVir/zenbot#634]
I want to develop a new strategy but I have a problem in trade.js source code.
Could zenbot can auto switch product pair?
EX: BTC - USDT then auto switch to BTC - NEO?

**Comment by mikeh21** [comment]
Following....

Very interested if this can be implemented on gdax.

**Comment by talvasconcelos** [comment]
Following  this one

**Comment by tibbon** [comment]
following

**Comment by DeviaVir** [comment]
Not at this time.
