### ISSUE TITLE
ETC-XBT Trade at Kraken

### ISSUE THREAD

**Issue by hlboys** [DeviaVir/zenbot#64]
I have Question

September 10th, 2016 1:00 KST
Referring to https://github.com/carlos8f/zenbot/issues/9 Zenbot3 Had installed

and Run to RealTrading Mod

Now is 13:00 KST

![001](https://cloud.githubusercontent.com/assets/22008188/18407978/ddd06028-775a-11e6-8c05-f39fd2d227ab.png)

**Comment by JFD3D** [comment]
You can change `.format(d3.format(',.2fs'))` to  `.format(d3.format(',.8fs'))` on line 88 in zenbot/plugins/server/public/main.js to fix the current close price for `var closeAnnotation = techan.plot.axisannotation()` and optionally doing a 'replace all' ,.2fs to ,.8fs in your favorite text editor will change all plotted values to 8 decimals thereby fixing this issue. I'm not sure if it's best to do this for volumes as well as it may have an effect on performance so I will let @carlos8f decide how to commit those changes.

I'm not sure why there is no trade action on the 5min RSI, I think either it's a `rs.min_double_wait/rs.min_reversal_wait` issue or there wasn't enough look-back data to calculate RSI. It's also possible that zenbot missed the signal if it lasted less than 1 minute. Does anyone else have any input on this issue?
