### ISSUE TITLE
cannot get hitbtc trading working

### ISSUE THREAD

**Issue by ljankok** [DeviaVir/zenbot#649]
please delete, issue is on my side.

**Comment by brucetus** [comment]
@ljankok 

Were you having the "getTrades() returned no trades, --start may be too remotely in the past." issue? If so can you tell me what you did to fix it? I'm trying to update the hitbtc API to V2 and I'm having this problem so if you could tell me what you did that would help a lot. Thanks.

**Comment by ljankok** [comment]
I added this to my strategy

this.option('min_periods', 'min. number of history periods', Number, 52);
