### ISSUE TITLE
Which exchanges are supported by zenbot? (full supported, also trading)

### ISSUE THREAD

**Issue by michaldev** [DeviaVir/zenbot#65]
Which exchanges are supported by zenbot? (full supported, also trading)

**Comment by itsMichael** [comment]
@refresh

**Comment by egorbenko** [comment]
Zenbot only supports GDAX trading at the moment @carlos8f correct me if I'm wrong.

**Comment by JFD3D** [comment]
@egorbenko this is correct, it's in the README.md documentation under features. "Default support for other exchanges is ongoing"
