### ISSUE TITLE
ubuntu 16.04 install video

### ISSUE THREAD

**Issue by ahmethakandd** [DeviaVir/zenbot#650]
Hello to everyone. I am using ubuntu 16.04LTS (from aws). I want to build Zenbot, every time I'm doing wrong because I'm not pro user

Is there anyone who wants to take video about the installation on ubuntu 16.04? For installation video, I will share the vps server information and he can share this video on your own YouTube channel ...

email for communication: aliminik12345678@gmail.com

As soon as I wait for the return. Best regards..  (sorry bad english, just google translate :)

**Comment by ahmethakandd** [comment]
It can also be an automated script for installation. :)

**Comment by sniper7kills** [comment]
See #645

**Comment by ahmethakandd** [comment]
I followed those steps but I did not succeed to the line. As I said I am not a pro user :(

**Comment by sniper7kills** [comment]
those steps are line for line what is required on a new aws ubuntu 16.04 instance. You must have skipped something.

**Comment by ahmethakandd** [comment]
in fact I do not know how to use ubuntu, especially the command line. I would like to use the ZenBot web interface as it is. I need the installation videos for windows or ubuntu (it does not matter). Could you take a video at a time when you are free?

**Comment by sniper7kills** [comment]
There is no web interface.

**Comment by ahmethakandd** [comment]
:( ok. For ubuntu command line, using video? Because there is no video on the internet

**Comment by ahmethakandd** [comment]
please need it...:(

**Comment by sniper7kills** [comment]
imho, if you are already having this much trouble typing commands into the command line that I linked to you, you probably want to look for something else because zenbot is entirely command line based.

https://youtu.be/BEhU55W9pBI

**Comment by metin02oktay** [comment]
Thank you so much, I needed it too. Must have web interface...

**Comment by ahmethakandd** [comment]
thank you @sniper7kills :) :smile:

**Comment by sniper7kills** [comment]
@ahmethakandd if that solved it for you, you should close this issue

**Comment by ahmethakandd** [comment]
I need to learn zenbot commands urgently :smile: 

I do not know how to close issue

**Comment by ahmethakandd** [comment]
Is there a "command line generator"? or do you intend to do it?

**Comment by ahmethakandd** [comment]
Making the web interface may be difficult, but at least such this can be done

**Comment by sniper7kills** [comment]
@ahmethakandd "I need to learn zenbot commands urgently" You'll want to read though the Read Me. It has all of the commands documented.

Good luck, I won't be able to assist any further.

**Comment by ahmethakandd** [comment]
one last question:

for example, the bot started and putty shutdown. What happens when I reconnect the putty's screen? that is, it will continue again? Is there a command to see the state of the bot?

really respectful

**Comment by metin02oktay** [comment]
@ahmethakandd I wanted to ask those questions. thank you. I'm waiting for the answer. :smile:

**Comment by halvors** [comment]
You could use the "screen -S zenbot nodejs zenbot.js whateverzenbotcommand" for the process to persist different login sessions.

**Comment by halvors** [comment]
And to attach to the process later use "screen -rx"

**Comment by bbusche** [comment]
@halvors Thanks for the tip. I have been looking for this.  So this would work if say I wanted to run paper trading, close the terminal session, and log back on later? Would it be something like:
`screen -S zenbot nodejs zenbot.js trade --paper`
and in a later session...
`screen -rx`
Do I have that right?

**Comment by bdfoster** [comment]
This issue isn't really about the project but more about how to Linux. There's plenty of tutorials out there to follow...
