### ISSUE TITLE
Setting time period for simulation?

### ISSUE THREAD

**Issue by jasurakk** [DeviaVir/zenbot#654]
How exactly do I tell the time period for the wanted simulation strategy?? I if a take a look for what "zenbot sim --help" returns, it gives me these options:
    --conf <path>                   path to optional conf overrides file
    --strategy <name>               strategy to use
    --order_type <type>             order type to use (maker/taker)
    --filename <filename>           filename for the result output (ex: result.html). "none" to disable
    --start <timestamp>             start at timestamp
    --end <timestamp>               end at timestamp
    --days <days>                   set duration by day count
    --currency_capital <amount>     amount of start capital in currency
    --asset_capital <amount>        amount of start capital in asset
    --avg_slippage_pct <pct>        avg. amount of slippage to apply to trades
    --buy_pct <pct>                 buy with this % of currency balance
    --sell_pct <pct>                sell with this % of asset balance
    --markup_pct <pct>              % to mark up or down ask/bid price
    --order_adjust_time <ms>        adjust bid/ask on this interval to keep orders competitive
    --sell_stop_pct <pct>           sell if price drops below this % of bought price
    --buy_stop_pct <pct>            buy if price surges above this % of sold price
    --profit_stop_enable_pct <pct>  enable trailing sell stop when reaching this % profit
    --profit_stop_pct <pct>         maintain a trailing stop this % below the high-water mark of profit
    --max_sell_loss_pct <pct>       avoid selling at a loss pct under this float
    --max_slippage_pct <pct>        avoid selling at a slippage pct above this float
    --symmetrical                   reverse time at the end of the graph, normalizing buy/hold to 0
    --rsi_periods <periods>         number of periods to calculate RSI at
    --disable_options               disable printing of options
    --enable_stats                  enable printing order stats
    --verbose                       print status lines on every period
    -h, --help                      output usage information

There is this "strategy"- setting, but no "time period" to be used for that strategy anywhere? Could someone provide a basic config file for simulation, just to get started?? Thank you!

**Comment by mikeh21** [comment]
answer is in your question;

--start start at timestamp
--end end at timestamp

eg: zenbot sim --start '2017-06-10' --end '2017-06-17' gdax.eth-usd --strategy=trend_ema

**Comment by jasurakk** [comment]
Thank you mikeh21 for your answer, and sorry for my vague question; what I actually tried to ask for was how to set period such as M15, H2 or D1, meaning the period for the used strategy? There doesn't seem to be any setting for that?

**Comment by mikeh21** [comment]
ok sorry for confusion.

you can set period in strategy settings

eg:
zenbot sim --strategy=trend_ema --period=1h

zenbot list-strategies - will list the settings and configuration available for each strategy

**Comment by jasurakk** [comment]
Aaaa OK, so that "zenbot sim --help" does not actually list ALL possible settings for the simulation! So I could basically create one _simulation_conf.js-_ file that contains all settings listed by "zenbot sim --help" and "zenbot list-strategies", right?

**Comment by mikeh21** [comment]
--period is a setting for the chosen strategy. not a simulation setting.

each strategy has its own individual settings.you can see this from "zenbot list-strategies"

**Comment by jasurakk** [comment]
Ok, but do I need a different conf- file for both strategy- and simulation settings? Or can they both be on the same file, which is then used with --conf- parameter?

**Comment by mikeh21** [comment]
no, and the command line settings will overide anything set in conf.js anyway

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
