### ISSUE TITLE
MongoError: connection 1 to localhost:27017 timed out

### ISSUE THREAD

**Issue by jasurakk** [DeviaVir/zenbot#658]
Now that I got my Zenbot running and simulation working (thanks to you all :=), I ran on the next problem; when I try to backfill the data for the simulation, I always get the following error:

_:~/zenbot$ ./zenbot.sh backfill poloniex.LTC-BTC --days 370
.....
poloniex.LTC-BTC saved 19054 trades 360 days left
.
poloniex.LTC-BTC saved 21814 trades 359 days left
.{ MongoError: connection 1 to localhost:27017 timed out
    at Function.MongoError.create (/home/xxxx/zenbot/node_modules/mongodb-core/lib/error.js:29:11)
    at Socket.<anonymous> (/home/xxxx/zenbot/node_modules/mongodb-core/lib/connection/connection.js:198:20)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at Socket.emit (events.js:207:7)
    at Socket._onTimeout (net.js:400:8)
    at ontimeout (timers.js:471:11)
    at tryOnTimeout (timers.js:306:5)
    at Timer.listOnTimeout (timers.js:266:5)
  name: 'MongoError',
  message: 'connection 1 to localhost:27017 timed out',
  saved: false,
  obj:
   { trade_id: 11393742,
     time: 1507873929000,
     size: 13.56835582,
     price: 0.01011636,
     side: 'sell',
     id: 'poloniex.LTC-BTC-11393742',
     selector: 'poloniex.LTC-BTC' } }
retrying..._

Few other users in this forum have also had this same problem, but I could not find any valid solutions for this. What could I do to make the simulation work??

**Comment by jasurakk** [comment]
Actually, could it be so that Zenbot needs more than 1GB of memory even in Linux for the backfill & simulation? If so, how much??

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
