### ISSUE TITLE
How long until first trade?

### ISSUE THREAD

**Issue by Beyondem** [DeviaVir/zenbot#66]
I have the bot configured on GDAX to trade BTC-ETH

It has been running for 3 days, the only thing in the logs are other trades being performed, but none are mine.

How long typically until it does its first trade? Or am I doing something wrong somewhere? I have configured the config with my api keys and everything, and ensured they are correctly configured for the asset/currency pairs.

Thanks!

**Comment by egorbenko** [comment]
@Beyondem are you sure trades are not being made or you just don't see their logs?

make sure logs are enabled in config_defaults.js

c.trade_log
c.trade_reducer_log

**Comment by Beyondem** [comment]
Yep, logging is all enabled. Looking through my gdax account I still have all the same balances and no trade history. It definitely is not trading!

**Comment by JFD3D** [comment]
@Beyondem How are you starting zenbot? Feel free to paste your config.js (Without your API key of course).

**Comment by TimBroddin** [comment]
Mine has been running for 2 weeks (BTC/EUR) and has logged about 4 buys/sells so far. Patience is key!

**Comment by Beyondem** [comment]
My run command:
`./zenbot launch map --backfill run server --config config.js --rs eth_btc`

My config.js:

```
var c = module.exports = require('./config_defaults')()

// mongo stuff
c.mongo_url = "mongodb://" + (process.env.MONGODB_PORT_27017_TCP_ADDR || "localhost") + ":27017/zenbrain" // change if your mongo server isn't local

c.mongo_username = null // normally not needed
c.mongo_password = null

c.gdax_key = 'REMOVED' // TO ENABLE BOT TRADING: set this to GDAX api key,
c.gdax_secret = 'REMOVED' // set this to GDAX api secret,
c.gdax_passphrase = 'REMOVED' // set this to GDAX api passphrase.
c.trade_log = true // log new trades as they come in.

// watch these exchanges
c.watch_exchanges = [
  //"bitfinex",
  "gdax",
  //"kraken",
  //"poloniex"
]

// selector for indicators, trading, etc
c.default_selector = "gdax.ETH-BTC"

// add selectors in the format "{exchange-slug}.{asset}-{currency}" to graph them
c.graph_selectors = [
  c.default_selector,
  "gdax.ETH-BTC",
  "gdax.ETH-USD"
]


c.assets = [
  "ETH"
]
c.currencies = [
  "BTC"
]

// trade logic
c.logic = require('./default_logic')
```

Everything look normal here?

**Comment by egorbenko** [comment]
lol...
try ./zenbot launch map --backfill reduce run server --config config_eth_btc.js

**Comment by egorbenko** [comment]
./zenbot launch map --backfill run server --config config.js --rs eth_btc only start a server, you can still do this but then you need to start reducer and trader individually

**Comment by JFD3D** [comment]
@egorbenko's solution should fix your issue @TimBroddin. Can you confirm this?

**Comment by TimBroddin** [comment]
I didn't have any problems :) @Beyondem ?

**Comment by Beyondem** [comment]
So, I have allowed it to run all week.

Upon first starting, it sold all my BTC for ETC.

Since then there has been no trades, but numerous errors in the logs:

> 09/23/2016 03:03:02 PM EDT [ERROR] non-200 status from exchange: 400

No matter how many times I restart the bot, I still get the same errors and no additional trades.

**Comment by ShawnHarte** [comment]
@Beyondem
If you have 2fa set for a certain trade volume, and the bot exceeded that volume it will give that error unless the api key allows for bypassing 2fa.  I had exactly the same thing happen to me.

  Hope that helps a bit.

**Comment by carlos8f** [comment]
Zenbot 4 is out, so I'm cleaning up 3.x issues. Please use and test 4, thanks!
