### ISSUE TITLE
Custom config file settings not set in poloniex/exchange.js

### ISSUE THREAD

**Issue by Corstiaan84** [DeviaVir/zenbot#665]
When I specify a custom `--conf` js file, those settings are not picked up by zenbot. Well, they are, but only partially. This issue pops up for me when I want to set different api keys for different pairs on Poloniex. It then fails with the `please set your keys` error.

When I open up `trade.js` and dig around a bit I see that the conf is loaded initially using some sort of DI container on line 15 using `var c = get('conf')`. When I print out `c` with `console.log(c)` I get the default conf values, e.g.: `poloniex: { key: 'YOUR-API-KEY', secret: 'YOUR-SECRET' }`.

A bit further down in `trade.js` starting on line 60, the custom `--conf` param is checked and used to override any settings. When I do a print out, now I get `poloniex: { key: 'may-actual-key', secret: 'my-actual-secret-key' } }`.

So far so good but when running `trade` I still get the message that my api keys are not set.

So, then I look in `poloniex/exchange.js`. On line 8 it gets the conf from the Di container using `var c = get('conf')`, just like in `trade.js`. However, when printing this conf out I get the default values again: `poloniex: { key: 'YOUR-API-KEY', secret: 'YOUR-SECRET' }`.

So, it seems `trade.js` opens the default conf using the container and then overrides with the keys from the custom `--conf`, which is what you would expect. `poloniex/exchange.js` on the other hand seems the ONLY be using the conf from the container, which are never updated with the values from the custom `--conf`, thus trying to connect to Poloniex with `poloniex: { key: 'YOUR-API-KEY', secret: 'YOUR-SECRET' }`, causing the `please set your keys` error.

The container needs to update it's conf after any custom `--conf` has been loaded. I would like to help out but can't find where `var c = get('conf')` is set using something like `set('conf', value)`. Please point me in the right direction.

Thanks again!

(the reason I want to use different api keys for different pairs is [this](https://github.com/carlos8f/zenbot/issues/193))

**Comment by Corstiaan84** [comment]
@DeviaVir I am eager to help you (and myself :-)) with this. Just need a few pointers on de where the conf/container is set to get started. Let me know 👍

**Comment by Corstiaan84** [comment]
[see](https://github.com/carlos8f/zenbot/pull/671)

**Comment by haxwell** [comment]
I added a PR which may address this problem.. https://github.com/carlos8f/zenbot/pull/912
