### ISSUE TITLE
./scripts/genetic_backtester/darwin.js --selector="poloniex.ETH-BTC"

### ISSUE THREAD

**Issue by AidasK** [DeviaVir/zenbot#673]
`./scripts/genetic_backtester/darwin.js --selector="poloniex.ETH-BTC" --strategy=macd`
Hi, I have tried running this command, but it runs for ages. 
it starts with `=== Simulating generation 1 ===` and goes on to `=== Simulating generation 999999 ===` without stopping. Why it is so?

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖

**Comment by Netzarim** [comment]
Try adding --runGenerations=# of generations you want
