### ISSUE TITLE
Trade --paper missing logging to html file similar to sim function

### ISSUE THREAD

**Issue by tomeh100** [DeviaVir/zenbot#677]
Trade function with --paper flag is missing logging to html file similar to sim function

**Comment by mikeh21** [comment]
use --filename option to save stats

eg:

--filename=/path/to/stats/paperstats.html

**Comment by tomeh100** [comment]
this is not working for trade --paper function
the command I used
./zenbot.sh trade --paper --filename=/stats/paperstats.html
so I can write file to /zenbot/stats/paperstats.html

**Comment by mikeh21** [comment]
it works ok for me. check your path is correct. I dont know your dir structure but you may need to use --filename=./stats/paperstats.html

notice ./

On exit you should see: 

_wrote /home/xxxxx/zenbot/sim/todaytrade.html_

**Comment by tomeh100** [comment]
what do you mean by "on exit"?

**Comment by tomeh100** [comment]
Are you sure? I thought this option is only available for sim not trade


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: mikeh21 <notifications@github.com> Date: 11/5/17  10:56 AM  (GMT-06:00) To: carlos8f/zenbot <zenbot@noreply.github.com> Cc: tomeh100 <tomeh100@gmail.com>, Author <author@noreply.github.com> Subject: Re: [carlos8f/zenbot] Trade --paper missing logging to html file similar to sim function (#677) 
it works ok for me. check your path is correct. I dont know your dir structure but you may need to use --filename=./stats/paperstats.html
notice ./
On exit you should see:
wrote /home/xxxxx/zenbot/sim/todaytrade.html

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/carlos8f/zenbot","title":"carlos8f/zenbot","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/carlos8f/zenbot"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mikeh21 in #677: it works ok for me. check your path is correct. I dont know your dir structure but you may need to use --filename=./stats/paperstats.html\r\n\r\nnotice ./\r\n\r\nOn exit you should see: \r\n\r\n_wrote /home/xxxxx/zenbot/sim/todaytrade.html_\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/carlos8f/zenbot/issues/677#issuecomment-341987692"}}}

**Comment by mikeh21** [comment]
on exit stats html output it written. stats are only produced on exit and not live.

im sure enough that I use it every day in live trade.

**Comment by tomeh100** [comment]
How do you exit? I do Ctrl + c to exit the process Am I doing something wrong?


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: mikeh21 <notifications@github.com> Date: 11/5/17  1:12 PM  (GMT-06:00) To: carlos8f/zenbot <zenbot@noreply.github.com> Cc: tomeh100 <tomeh100@gmail.com>, Author <author@noreply.github.com> Subject: Re: [carlos8f/zenbot] Trade --paper missing logging to html file similar to sim function (#677) 
on exit stats html output it written. stats are only produced on exit and not live.
im sure enough that I use it every day in live trade.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/carlos8f/zenbot","title":"carlos8f/zenbot","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/carlos8f/zenbot"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mikeh21 in #677: on exit stats html output it written. stats are only produced on exit and not live.\r\n\r\nim sure enough that I use it every day in live trade.\r\n"}],"action":{"name":"View Issue","url":"https://github.com/carlos8f/zenbot/issues/677#issuecomment-341997122"}}}

**Comment by mikeh21** [comment]
I would strongly urge you to read the documentation in full and learn the program as much as you can before using it for live trade.

Available command keys:
 b - limit BUY
 B - market BUY
 s - limit SELL
 S - market SELL
 c - cancel order
 m - toggle MANUAL trade in LIVE mode ON / OFF
 T - switch to 'Taker' order type
 M - switch to 'Maker' order type
 o - show current trade options
 O - show current trade options in a dirty view (full list)
 P - print statistical output
 **X - exit program with statistical output**
