### ISSUE TITLE
Failed installation

### ISSUE THREAD

**Issue by ChizzDeus** [DeviaVir/zenbot#678]
Hey,
I tried to install this on a fresh Ubuntu 16.04 server, and ran into an error. Then I found ticket 643, and tried that (after reinstalling server), however I still get the same error.

![image](https://user-images.githubusercontent.com/32727469/32355538-93d3c694-c02f-11e7-9bd3-6c67538bde0e.png)

Ticket 643 indicates to copy + paste the code into the server, but I can not copy paste, nor did googling give me the answer. (I open my server through console on a windows 10 pc). However, I doubt that I made any typing mistakes, and have not misused sudo, and I exactly typed over what it said.

Any idea what could be wrong here, or please explain me how to copy paste from ticket 643 into the console.. :)

Thanks in advance

**Comment by interbiznw** [comment]
Gonna need more info..

What command was ran to output this error, what version of node & npm are installed..

**Comment by ChizzDeus** [comment]
@interbiznw 
The command run that produced this error was: "npm install" (when in "cd zenbot")

The versions of node and npm can't tell for certain, I've used the exact steps listed below on a fresh server. A part from below commands, nothing else has been installed. So I suppose node version 8. something (as this is what the command says) and npm no clue. Are there specific versions required? The readme just shows the below lines and that's what I've used.

> sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install build-essential mongodb

>curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs

>git clone https://github.com/carlos8f/zenbot.git
cd zenbot
npm install

**Comment by sniper7kills** [comment]
@ChizzDeus Where are you installing it on? Those instructions work for AWS servers; did you install from a CD?

"Import Error: No Module named compiler.ast" would be your issue; leading me to believe you are missing something related to python.

**Comment by ChizzDeus** [comment]
@sniper7kills I'm installing it on a fresh Vultr ubuntu 16.04 server.

Should I install python separately? if so, what version?

**Comment by sniper7kills** [comment]
Run `python -V` and check what version you have, try using 2.7

**Comment by ChizzDeus** [comment]
It's version 2.7.12. Should I downgrade to 2.7 instead?

**Comment by sniper7kills** [comment]
Nope, that's the same version on my server...

**Comment by ChizzDeus** [comment]
Did you run any other command on your server other than the ones that you recommended?

**Comment by sniper7kills** [comment]
Nope those were the only commands I used on a fresh instance in AWS. Your issue is the missing compiler.ast, but I don't have any idea for a resolve for you unfortunately.

**Comment by ChizzDeus** [comment]
Maybe switch to AWS then.. :) Thanks for your help anyway

**Comment by ChizzDeus** [comment]
@sniper7kills this seems to have fixed the issue.. :)
