### ISSUE TITLE
How should look config for the exchange Bitfinex?

### ISSUE THREAD

**Issue by michaldev** [DeviaVir/zenbot#68]

**Comment by postadelmaga** [comment]
I also need to use bitfinex ... apparently GDAX is only available in USA.

I made the following changes at the config.js files:
I just installed the program, s0 I'm not sure if anything else is required ... but I get some logs about transactions and data from bitfinex and so far it looks working

in `config.js` put your api key/secret into the  fileds:

```
c.gdax_key = 'YOUR_BITFINEX KEY' 
c.gdax_secret = 'YOUR_BITFINEX SECRET' 
c.gdax_passphrase = '' // leave empty for bitfinex
c.trade_log = true // log new trades as they come in.

// watch these exchanges
c.watch_exchanges = [
  "bitfinex",
  //"gdax",
  //"kraken",
  //"poloniex"
]
```

**Comment by postadelmaga** [comment]
is the above configuration correct ? if somebody can confirm, it will be helpful for others

**Comment by nullprobe** [comment]
That config looks OK, but I have issues with the trading logic config that seems to only work with GDAX. Anyone else have that problem?

**Comment by JFD3D** [comment]
@nullprobe, Support for other exchanges is ongoing. What exchange are you trying to use?

**Comment by nullprobe** [comment]
@JFD3D , I'm trying to use it for Bitfinex, like OP.

**Comment by szempo** [comment]
Added bitfinex key,secret...

tarding log monitoring SELL only 

btc-usd_1      | 01/13/2017 11:20:35 AM UTC [    bitfinex]    m24738220      20 trades. 01/13/2017 07:40:33 AM UTC SELL        39.750 at       $777.40 BTC/USD
btc-usd_1      | 01/13/2017 11:20:56 AM UTC [    bitfinex]    m24738220      18 trades. 01/13/2017 07:40:56 AM UTC SELL        11.894 at       $777.13 BTC/USD
btc-usd_1      | 01/13/2017 11:21:16 AM UTC [    bitfinex]    m24738221       4 trades. 01/13/2017 07:41:07 AM UTC SELL         2.182 at       $777.26 BTC/USD
btc-usd_1      | 01/13/2017 11:21:36 AM UTC [    bitfinex]    m24738221       5 trades. 01/13/2017 07:41:35 AM UTC SELL         6.275 at       $777.29 BTC/USD
btc-usd_1      | 01/13/2017 11:21:56 AM UTC [    bitfinex]    m24738221      14 trades. 01/13/2017 07:41:55 AM UTC SELL        18.373 at       $777.19 BTC/USD

**Comment by schessa75** [comment]
hi to all. I'm new of this website. I've just configured zenbot to trade with bitfinex. someone have correct settings of conf.js to trade on bitfinex? 
what I need are all the setting to buy, sell, etc etc... strategy...
thank you
Stefano
