### ISSUE TITLE
Save to MongoDb in sim mode?

### ISSUE THREAD

**Issue by JensvdHeydt** [DeviaVir/zenbot#685]
I need a little help: I'm currently developing a web api and web ui for zenbot and would like to view sim results in this web ui. So I'm extending sim.js with the following code but it actually never saves to mongodb. Is there any hidden flag that disables the db or am I missing something? 

// Save the SIM Session
          var sessions = get('db.sessions')
          let session = {
            id: crypto.randomBytes(4).toString('hex'),
            selector: so.selector,
            started: new Date().getTime(),
            mode: so.mode,
            options: so
          }
          console.log(session)

          sessions.save(session, function (err) {
            if (err) {
              console.error('\n' + moment().format('YYYY-MM-DD HH:mm:ss') + ' - error saving session')
              console.error(err)
            }
            if (s.period) {
              engine.writeReport(true)
            }
          })

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
