### ISSUE TITLE
Pusher error with bitstamp

### ISSUE THREAD

**Issue by flexy1994** [DeviaVir/zenbot#686]
I added my api key and secret to the conf.js and executed this:

> zenbot trade --paper  bitstamp.XRP-EUR

This shows the following error:

> Pusher : You should always specify a cluster when connecting. See: https://pusher.com/docs/javascript_quick_start
Pusher : You should always specify a cluster when connecting. See: https://pusher.com/docs/javascript_quick_start
fetching pre-roll data:
Pusher : You should always specify a cluster when connecting. See: https://pusher.com/docs/javascript_quick_start
Pusher : You should always specify a cluster when connecting. See: https://pusher.com/docs/javascript_quick_start
cannot backfill bitstamp.BTC-EUR: exchange does not offer historical data

**Comment by JensvdHeydt** [comment]
It looks like you are using a configuration for the notification feature that is missing a property "app_cluster". Also: The exchange you are using does not support historical data as it seems.

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
