### ISSUE TITLE
Srsi wrong values

### ISSUE THREAD

**Issue by matz9x** [DeviaVir/zenbot#694]
Srsi indicator gives, to me, wrong results, with oscillations greater than the maximum srsi range (typically 0-100% or 0-1). If this issue is confirmed the validity of both macd-srsi and cci-srsi strategies is compromised. I think that is needed a fix on the srsi.js file inside lib folder. Unfortunately I'm not an expert in javascript language and I can give support only on the technical analysis part.
Further information on srsi: https://www.tradingview.com/wiki/Stochastic_RSI_(STOCH_RSI)

The cyan column gives the value of srsi
![2017-11-09](https://user-images.githubusercontent.com/32924751/32602295-e9cfd770-c545-11e7-8189-a6fa12f750f7.png)

Thank you for the support

**Comment by matz9x** [comment]
Someone else noticed this issue?

**Comment by Lucidarme** [comment]
I don't notice this issue but I notice something really strange with strategies which use srsi. No one of theses use the "srsi_periods" params, whereas it's something important. Even in the lib/srsi.js it's not used. Someone know why this param is not considered? Perhaps this issue join the yours.

**Comment by Lucidarme** [comment]
This issue come from the lib/srsi.js file. In this file, there is theses lines:

> var highestRSI = Math.max(...RSI)
> var lowestRSI = Math.min(...RSI)
> var stochK = 0
> stochK = ((s.period.rsi - lowestRSI) / (highestRSI - lowestRSI)) * 100

So it seems to be right. But sometime, s.period.rsi is lower than lowestRSI ... And it gives negatives values! And sometime s.period.rsi is higher than highestRSI... And it gives values higher than 100.

So now the question is:
What we should set to stochK when s.period.rsi is lower than lowestRSI or higher than highestRSI??

**Comment by matz9x** [comment]
Thank you for your analysis! However, I think that this is not the real issue because the lowest RSI is computed among a set of values, including the actual RSI value. It means that, in a worst case scenario s.period.rsi - lowestRSI is equal to zero.
e.g.1
RSI = [10 15 40 80 65 20 5]
For this set of data the lowest RSI is 5 it means that:
stochk = (5 - 5) / (80 - 5) > 0
e.g.2
even if there is 0 on the last position stochk is still equal to 0
RSI = [0 15 40 80 65 20 0]
stochk = (0 - 0)/(80 - 0) = 0
So the equation is well implemented but the computation is wrong and I don't know what's the reason, mainly because I don't understand JS language.

My suspects however are focused on this part of the code:
```
    if (typeof s.period.rsi !== 'undefined')
      s.lookback.slice(0, k).forEach(function (period) {
        if (period.rsi)
          RSI.push(period.rsi)
      })
```
I would appreciate your feedback on his purpose inside the code, in particular RSI.push(period.rsi)

**Comment by Lucidarme** [comment]
That is the problem, in this code, current RSI is not push. I added 

> RSI.push(s.period.rsi)

just after the lines you wrote, and now I have reals values. However, these value are not the same that tradingview.com SRSI indicator...

If you want some explaination about the code you wrote:

> s.lookback.slice(0, k).forEach(function (period) {}

this line will separate all periods between the current period-1 and the current period-k-1, and each period will be accessible via "period". It's like a "for" in some ways.

and then,

> RSI.push(period.rsi)

is used to push each rsi of each period inside RSI array.

**Comment by aquamanjl** [comment]
This should now be fixed by https://github.com/DeviaVir/zenbot/pull/1196
