### ISSUE TITLE
Fine tuning model parameters

### ISSUE THREAD

**Issue by vea45** [DeviaVir/zenbot#696]
The actual genetic fine-tuner would be great if it could improve the already trained models. So the idea is to use the models as an start point.

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
