### ISSUE TITLE
conf for maker/taker fees?

### ISSUE THREAD

**Issue by deamonkai** [DeviaVir/zenbot#698]
Looking through I don't see where it allows you to specify maker/taker fees.  I note the Gemini exchange where it it lists them as 0.1/0.1, which for low-vol traders is wrong, it's .25bps.  

Is there a way to specify the maker/taker fee or pull the current fee schedule from the exchanges?

**Comment by deamonkai** [comment]
zenbot/extensions/exchanges/gemini/exchange.js

  var exchange = {
    name: 'gemini',
    historyScan: 'forward',
    makerFee: 0.10,
    takerFee: 0.10,

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
