### ISSUE TITLE
Errors with npm install on 4.05 update after git pull

### ISSUE THREAD

**Issue by bbusche** [DeviaVir/zenbot#700]
On my Ubuntu instance I did a git pull for the latest 4.05 code.  I ran npm install and got his error:

```
npm ERR! path /home/ubuntu/zenbot/node_modules/forex.analytics
npm ERR! code EISGIT
npm ERR! git /home/ubuntu/zenbot/node_modules/forex.analytics: Appears to be a git repo or submodule.
npm ERR! git     /home/ubuntu/zenbot/node_modules/forex.analytics
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2017-11-12T15_59_48_930Z-debug.log
```

**Comment by scarecr0w12** [comment]
This is normal, remove the forex.analytics and run it again. it will rebuild that module

**Comment by democodex** [comment]
@bbusche i had same problem and still didn't work with your recs above @scarecr0w12 
i removed all node modules and installed essentials. worked

rm -rf node_modules
apt install build-essential

**Comment by democodex** [comment]
rm -rf node_modules 
npm install (if on mac)

**Comment by sniper7kills** [comment]
you will have to run npm install regardless of what platform you are on if you remove node_modules.

**Comment by JensvdHeydt** [comment]
This is no error / issue at all. Close?
