### ISSUE TITLE
Difference between c.sell_stop_pct and c.max_sell_loss_pct

### ISSUE THREAD

**Issue by bbusche** [DeviaVir/zenbot#702]
I'm confused about these two parameters.  Using c.sell_stop_pct = 1, I can get the bot to sell when the price dips beyond a 1% loss on the trade. In this case, wouldn't c.max_sell_loss_pct = 1 be redundant? Or does it serve a different purpose?

**Comment by brucetus** [comment]
Yeah i thought c.sell_stop_pct x would sell when the trade is down x pct but it doesnt seem to do that.

**Comment by bbusche** [comment]
@brucetus It works for me, but I think it depends on the period value. If the period is set too high, you could miss the value by a lot.  For example, a --period=10m can leave you exposed for 10 minutes while the loss grows bigger than the c.sell_stop_pct.  I think it would only kick in at the next period. At least thats my assumptions from watching it trade.  Using c.max_sell_loss_pct does not behave as expected for my however.

**Comment by brucetus** [comment]
@bbusche Ahh i think you're right. I was using 4h period and it eventually sold.

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
