### ISSUE TITLE
Bitfinex paper mode error

### ISSUE THREAD

**Issue by albabosh** [DeviaVir/zenbot#704]
/home/tradeops/zenbot/extensions/exchanges/bitfinex/exchange.js:201
        throw new Error('please configure your Bitfinex credentials in ' + path.resolve(__dirname, 'conf.js'))

**Comment by DeviaVir** [comment]
You should probably do as the error tells you and fill in your bitfinex credentials in the conf.js file.

**Comment by albabosh** [comment]
Other exchanges do not require credentials in paper mode
