### ISSUE TITLE
Initial trade price setting?

### ISSUE THREAD

**Issue by rountrey** [DeviaVir/zenbot#705]
Is there a way to set the initial trade price on a strategy? I've been testing about 6 configurations at a time for a couple of weeks and I have found that I can start making a profit sooner if I start the bot on a downswing or on a low price. So I was wondering if there was a way to set the initial buy price at $XX.

Like if I started a bot and the current price was $100, but it won't buy until the price drops to $75.

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
