### ISSUE TITLE
Bittrex and Insufficient Funds

### ISSUE THREAD

**Issue by KryptoNova** [DeviaVir/zenbot#708]
I'm trying to place a manual trade in a live trading environment and am getting the error below.  I have the buy_pct and sell_pct values set to 100 so that the entire balance is bought and sold each time.  I am thinking it has something to do with rounding and it is one Sat more than what is in the account.  I'm not exactly sure where this calculation takes place, but I guess it is in engine.js somewhere.  Could someone point me to where this calculation takes place so I can handle rounding errors so the 100% purchase of asset works?  Thanks!

```
manual limit BUY command executed
INSUFFICIENT_FUNDS


{ Error: order not found in cache
    at Object.getOrder (/root/nodeJS/zenbot/extensions/exchanges/bittrex/exchange.js:263:29)
    at Timeout.checkOrder [as _onTimeout] (/root/nodeJS/zenbot/lib/engine.js:283:24)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5) desc: 'could not execute buy: error placing order' }

```

**Comment by ether-btc** [comment]
with bittrex "99.5"% works. With Gdax I found, "99.6"% works.
`buy_pct=99.5 and buy_pct=99.6` respectively.
`sell_pct=100` works fine both on bittrex and gdax.

Is it the bot that fails to being able to buy 100% or is it the exchanges fault I wonder. Never got to find out who is the culprit.

**Comment by KryptoNova** [comment]
To answer @ether-btc it is both.  The bot wasn't taking a fee into account when determining the amount of asset to buy to leave enough BTC in the account to cover the fee.  I think that Bittrex needs a way to handle a 1 sat rounding problem.

Closing for now as I do believe that #711 has addressed this for 100% buys.
