### ISSUE TITLE
How to Purge History of Trading Pair

### ISSUE THREAD

**Issue by KryptoNova** [DeviaVir/zenbot#712]
I have a few breaks in trade history due to Bittrex choking and when I run sims on it Zenbot does not account for the gaps and thinks that it is just passing from one period to the next.  The problem with Bittrex is that it cannot fetch history via backfill and only can pull the 200 most recent trades.

I would like to purge out the history from mongodb, but I do not see a way to do this via the command line.  Is there some way of doing this that is not documented anywhere or a shell script that purges out pairs from mongodb?

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
