### ISSUE TITLE
Placing STOP LOSS orders for trailing stop instead of limit sell orders

### ISSUE THREAD

**Issue by mikeh21** [DeviaVir/zenbot#721]
Feature request.

HI just wanted to know if there is a reason why the bot doesnt use the STOP LOSS order function when using trailing stop? this would make it much easier for the bot to sell the top rather than chasing it up with the limit sell orders it is currently using?... can this be easily changed in the exchange scripts?

    --profit_stop_enable_pct <pct>  enable trailing sell stop when reaching this % profit
    --profit_stop_pct <pct>         maintain a trailing stop this % below the high-water mark of profit

**Comment by mikeh21** [comment]
PS Im referring to GDAX exchange I do not have experience of other exchange but expect the same is possible and would also benefit from this feature

**Comment by nedievas** [comment]
STOP orders usually have taker fees. It this OK?

**Comment by mikeh21** [comment]
Hi, I know on GDAX can place Stop Loss W/ Limit order which is no fees and can be placed below market price to prevent loss. could this be implemented in zenbot to use trailing stop loss to lock in profit in trending market?

**Comment by manuelpaulo** [comment]
Same request! Thanks.

**Comment by skeebuzz** [comment]
Unfortunately, the API doesn't currently support stop-limit. You can put in a stop order, but it turns into a market order when triggered.

**Comment by shri046** [comment]
@skeebuzz I am interested in this feature as well and based on the [discussion here](https://github.com/coinbase/gdax-node/issues/164) it looks it is possible to place such an order, it is just not documented. I have not tested this myself.


```
authenticatedClient.sell( {
  type: "limit",
  product_id: "BTC-USD",
  size: "0.005",
  price: "10100",      // the limit price
  stop: "entry",       // currently undocumented
  stop_price: "10000", // currently undocumented
});
```

**Comment by skeebuzz** [comment]
@shri046 Oooowwww... thanks for that! Good to know!!

**Comment by skeebuzz** [comment]
Gdax now officially supports them: https://docs.gdax.com/#place-a-new-order

**Comment by obinnaokechukwu** [comment]
@shri046 That's not quite right. For sell side it should be stop: "loss" not "entry". For buy side, it's "entry".

**Comment by yang2lalang** [comment]
This looks a very interesting feature that should solve the slippage problem in live trading where order execution is a big mess and you see limit orders filled after 11 minutes

stop limit order should help trigger  price points for strategy.js to act on

**Comment by kilo42L** [comment]
Correct me if won't please but I thought on gdax if you place a stop loss order for say $50 and then under advanced a limit of $45 then if the market crashes fast and gdax cannot fill as a market order between $45-$50 then it won't sell at all. This avoids leaving you at the very bottom before popping up again.  I use to think it execute at a limit order saving you money but I believe that is just an extra precautionary.
Please inform me if I'm incorrect.

Either way it would be extremely useful for me if I could enter process to sell and buy irregardless of if it's above or below the current price
