### ISSUE TITLE
Discord receive trading messages from other bots

### ISSUE THREAD

**Issue by coolfarmer** [DeviaVir/zenbot#723]
So I have activated the Discord Notifier with my app ID and my token, booted the container and started to reveive some messages. WTF? I didn't start the trading command, just booted the container and I received those messages.

How is this possible? I run locally the script and nobody have my webhook info.

**Comment by scarecr0w12** [comment]
Lol, how, i can't even get the discord to work

**Comment by coolfarmer** [comment]
Ok I just found the problem, when the container is launched, he run automatically a paper trading command.

@scarecr0w12 , you just have to put your APP ID and TOKEN into your config file, and set to true the param « c.notifiers.discord.on » .

**Comment by scarecr0w12** [comment]
Well the labeling it uses is confusing as it says Webhook, not App ID and token

@carlos8f Should correct that.

**Comment by DeviaVir** [comment]
https://support.discordapp.com/hc/en-us/articles/228383668-Intro-to-Webhooks
Gives me a sense that WEBHOOK is a better name for it. But since it's an opensource project I'll await your improvement @scarecr0w12, thanks!
