### ISSUE TITLE
When the container is booted, he launch automatically the bot in paper trading mode, but why?

### ISSUE THREAD

**Issue by coolfarmer** [DeviaVir/zenbot#726]
Current workflow: 
 - Container booted
 - Bot started in paper mode (with your conf.js)
 - You start your instance the command "zenbot trade poloniex.ETH-USDT --params ..."
 - If you have a discord channel setted up, you will receive the notification for these 2 instances

Actually this is bad, I just want to run MY command line, I don't want Docker to start an instance with default settings in paper trading.

At the end you will find the process that docker launched when the container is built:
![2017-11-17_03-33-10](https://user-images.githubusercontent.com/4965519/32938071-f5496d06-cb48-11e7-97bf-e0ba812021e8.png)

I don't want that, any solution? If I remove some lines from DockerFile, I have as result that the container reboot in loop.

Please help!

**Comment by DeviaVir** [comment]
Change the command here:
https://github.com/carlos8f/zenbot/blob/master/docker-compose.yml#L9

**Comment by coolfarmer** [comment]
I have already removed that line and rebuilt the container, this does nothing.
If you remove the same line (#15) in the DockerFile, the container will reboot indefinitely (and logs are showing like if you type "zenbot" command.

![2017-11-17_12-42-05](https://user-images.githubusercontent.com/4965519/32960962-ca9c4bb8-cb94-11e7-8a02-b7a74dffb298.png)

**Comment by DeviaVir** [comment]
@coolfarmer I did not say "remove"; change! If you have no command, it does nothing but return the help page.

You can also log into your container using `docker exec -it zendev_server_1 bash` and run a command there, after you removed the command.

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
