### ISSUE TITLE
Trade frequency

### ISSUE THREAD

**Issue by blastbeng** [DeviaVir/zenbot#727]
Hello, i have seen that in the description the trade frequency is:

"Flexible sampling period and trade frequency - averages 1-2 trades/day with 1h period, 15-50/day with 5m period"

how to increase this frequency? i want like 20 or 30 trades/day

thanks

**Comment by JensvdHeydt** [comment]
Most strategies have a default time period that they are working on. In your example it's one hour. The higher this period the less trades the bot will make. So maybe try to lower it with

-- period=30m
or
--period=5m

**Comment by blastbeng** [comment]
and what about --min_periods? what does it mean ?

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
