### ISSUE TITLE
s8f.org down

### ISSUE THREAD

**Issue by samvrlewis** [DeviaVir/zenbot#73]
Seems as though s8f.org is currently down, does anyone know where I can find a mirror of the historical data (https://s8f.org/dl/zenbrain.tar.gz)? 

Thanks!

**Comment by JFD3D** [comment]
I have no idea why s8f.org is down, @carlos8f has been inactive as of late. You can always run a backfill yourself by running `./zenbot launch map --backfill`

**Comment by TimBroddin** [comment]
Where is @carlos8f ? His Twitter account seems to have vanished. Please come back!

**Comment by ghostnegotiator** [comment]
He's still here but away for a short period of time. He has invited me as a
collaborator today so he's still there.

**Comment by enriquevago** [comment]
@samvrlewis git this https://github.com/carlos8f/zenbrain.git

**Comment by denniswong34** [comment]
could anyone update the zenbrain.tar.gz file? I can't download the historial data too.

**Comment by carlos8f** [comment]
i am back. i was sent to jail for 5 days and a mental hospital for 2 weeks, on a petty trespassing charge. bail was $25,000, more than i could afford. I forsaw the arrest and shut down my shit accordingly. I added the cream of the crop as collaborators.

RE: S8f, it's dead now. of course, s8f.org was hosted with jekyll and the source is still available at https://github.com/carlos8f/s8f.org and archives at https://web.archive.org/web/*/http://s8f.org

i have new websites popping up now. will update if any go public. I am actively involved in hactivism now for charity.

I am now known as _Morpheus_ , s8f.org is dead. long live s8f.org

I will be per

**Comment by carlos8f** [comment]
@JFD3D @RDash21 @egorbenko ;)

[![music pictures](https://cloud.githubusercontent.com/assets/106763/19345855/4ebd6d22-90f5-11e6-8cfd-2e2eeca1ff55.jpg)](https://soundcloud.com/carlos8f/sets/music-pictures)

**Comment by grigio** [comment]
😨  Welcome back online

**Comment by ghostnegotiator** [comment]
Welcome back to the real world @carlos8f :)

**Comment by karolismatul** [comment]
Welcome back @carlos8f :rocket:
