### ISSUE TITLE
SRSI formule don't use "srsi_periods" params

### ISSUE THREAD

**Issue by Lucidarme** [DeviaVir/zenbot#738]
I notice something really strange with strategies which use SRSI. No one of theses use the "srsi_periods" params, whereas it's something important. Even in the lib/srsi.js it's not used. Someone know why this param is not considered?

We should think about how to deal with this problem because SRSI is a very efficient indicator, and it's already use in srsi_macd and srsi_cci strategies.

For those who want to know more about this SRSI, and find out why the srsi_periods parameter is important, I advise you to go for some test on tradingview.

**Comment by JensvdHeydt** [comment]
Hi @Lucidarme,

I checked some of the strats and they all seam to use the parameter "rsi_periods" and not "srsi_periods".

**Comment by Lucidarme** [comment]
Hi @JensvdHeydt,

Yes the strats use the "rsi_periods" but "srsi_periods" is another parameter.

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
