### ISSUE TITLE
last_sell_price not updated when changing currency

### ISSUE THREAD

**Issue by ghost** [DeviaVir/zenbot#74]
I first tried the bot without real trading using the default BTC/USD config.

After that (3 days) I changed to BTC/EUR and filled the GDAX api info, in an accocunt with just Bitcoins. Looking at the logs I noticed that three sells failed due to low performance. It made no sense and looked a the code, and discovered that last_sell_price was the USD price, which was higher than the euro, and thus the low score.

I run dropped the entire run_states collection and that solved it,  but this could be really misleading for people without coding knowledge.

I hope this helps, thanks for the amazing work!

**Comment by egorbenko** [comment]
Every pair should be treated separately, you can't simply test your config on one pair and run it on the other, it will not be as effective/profitable. You should always run simulation of the pair you are going to trade prior to bringing it live to make sure your config is good.

**Comment by ghost** [comment]
Thank you egorbenko, maybe I did not explain propely, but what I was trying to say is that if somebody tries zenbot in one currency, and then on the other, that variable takes the value of the first one until a buy AND a sell is done, which can make the bot not take any action. Unless I am missing something else that I should have changed in the EUR config file.
