### ISSUE TITLE
Trading mode

### ISSUE THREAD

**Issue by kazdimenator** [DeviaVir/zenbot#742]
Why in a trade regime it is impossible to specify quantity of means which will be spent for the order?

**Comment by KryptoNova** [comment]
You can set this in the conf.js file.  There are two parameters that are used to handle the quantities.
// buy with this % of currency balance (WARNING : sim won't work properly if you set this value to 100)
c.buy_pct = 99
// sell with this % of asset balance (WARNING : sim won't work properly if you set this value to 100)
c.sell_pct = 99

This will use the balances or either the asset or currency, depending on the type.  While there isn't a way to explicitly specify a quantity, this will allow you to only invest a portion of your available balance.
The only thing I have found is that if you use a strategy that sends multiple buy or sell signals in succession, it will keep on buying or selling while a viable balance remains.

**Comment by code4passion** [comment]
It would be great we can specify absolute percentages. For example i use to trade on GDAX-BTC manually and i use the bot on GDAX-ETH . I just want to try bot on GDAX-ETX with X USD.

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
