### ISSUE TITLE
Live trading on poloniex works but on Bitfinex doesn't.

### ISSUE THREAD

**Issue by via-marketing** [DeviaVir/zenbot#743]
Hi Guys,

I've ran the bot live on Bitfinex using slightly modified trend_ema for over 3 days and it didn't make any trades whatsoever. When running sim, it makes 1.09 trades per day. Trading live on Poloniex with the same setup works perfectly fine.

When running --debug every so often it shows: WebSockets Error: Connection closed. Retrying every 10 seconds. and We are now fully connected and authenticated,

Any suggestions? 

Thanks
![bitfinex](https://user-images.githubusercontent.com/33762520/33187289-aa141c94-d045-11e7-9ae9-57a14d2b7978.png)
![bitfinex2](https://user-images.githubusercontent.com/33762520/33187483-c7131b8c-d046-11e7-809a-ed41804f48af.png)

**Comment by nedievas** [comment]
Duplicate #695
