### ISSUE TITLE
Bittrex list-selectors

### ISSUE THREAD

**Issue by kazdimenator** [DeviaVir/zenbot#749]
./zenbot.sh trade bittrex.OMG-USDT  --paper
error: could not find product "OMG-USDT"

**Comment by KryptoNova** [comment]
Hello @kazdimenator,
You will need to run the update-products.sh in the zenbot/extensions/exchanges/bittrex folder.  That will update the necessary pairs based on what is currently offered on the site.  After that, you will should be able to see the OMG-USDT market on bittrex.
NOTE:  If you are running this on linux, you may need to chmod the update-products.sh file to allow it to have execution privileges.

Hope this helps.
