### ISSUE TITLE
Bitstamp problem

### ISSUE THREAD

**Issue by Dosix** [DeviaVir/zenbot#758]
Hi, I got an error when I try to trade with Bitstamp (paper or live),

I know there isn't backfill but the date is wrong, I get "NaN%" and nothing happen :/

Gdax work very well no problem!

Thanks for your anwsers

> cannot backfill bitstamp.XRP-EUR: exchange does not offer historical data
>                DATE            PRICE     DIFF            VOL         RSI                         ACTIONS                      BAL                PROFIT
> ---------------------------- STARTING PAPER TRADING ----------------------------
> !!! Paper mode enabled. No real trades are performed until you remove --paper from the startup command.
> Press  l  to list available commands.
> 1970-01-01 01:00:01  0.00000000 XRP-EUR                0                               0.00000000 XRP  208.97 EUR   +0.00%    NaN%

**Comment by Dosix** [comment]
Nobody have this problem ? :(

**Comment by tiagosiebler** [comment]
@Dosix I saw this too, the bitstamp setup wasn't clear. For testing safely I made a subaccount in bitstamp with very little credit. 

Is it reading your balance for you? I realised eventually that it wasn't authenticating with bitstamp correctly, since the clientID is your customerID not your account number. Changing the clientID for bitstamp to my customerID eventually got it running properly. Hope this helps!

**Comment by Dosix** [comment]
Thanks for your reply

So I tried with this command in my main account and not with a subaccount 

>  ./zenbot.sh trade bitstamp.XRP-EUR --paper

And it worked but when I try without bitstamp.XRP-EUR, it doesn't work

Also I must wait few minutes (10/20min) with period=5m for get correctly the data

I don't know it running properly :/

**Comment by alessionobile** [comment]
same problem here

**Comment by tiagosiebler** [comment]
@Dosix I'm finding it harder to use this with bitstamp. Other exchanges allow you to fetch history of that selector. As far as I understand it, it means the bot usually has the data it needs to start trading immediately. Bitstamp doesn't seem to support that in their API, so the bot has to watch and wait until it has enough data to reliably start trading. I'm wondering if that's what causing you to wait 10/20 mins with a 5min period before you start seeing the data you expect?

**Comment by Dosix** [comment]
@tiagosiebler Yeah you have totally right

I executed the bot all night and I think that's good now because I hav enough data to reliable start trading.

PS : I'm developing a web interface for run or create bots and show statistics. I think that I will put the code in open source later. 

Thanks for your anwsers guys
