### ISSUE TITLE
slack/client is not in npm registry

### ISSUE THREAD

**Issue by skazichris** [DeviaVir/zenbot#768]
Hello,

while installing manually on debian server, I got stuck at:

root@svr_name:/opt/zenbot# npm install
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'slack/client' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'zenbot4'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.10.77
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /opt/zenbot
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/zenbot/npm-debug.log
npm ERR! not ok code 0

**Comment by DeviaVir** [comment]
`npm install @slack/client` does not work for you?
https://www.npmjs.com/package/@slack/client seems to still be correct.

You may want to update your node version though, at least to LTS.

**Comment by skazichris** [comment]
Nope. It does not.
I have installed nodejs using standard repos available in the system.

/opt/zenbot# npm install @slack/client
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'slack/client' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'zenbot4'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.10.77
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "@slack/client"
npm ERR! cwd /opt/zenbot
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code E404

**Comment by haxwell** [comment]
I have not found this to be an issue when installing on my Linux Mint 18 box.. I agree with DeviaVir, that the version of node reported in this error should be upgraded. The version in standard repos is often behind the curve.

https://nodejs.org/en/blog/release/v0.10.29/ was released June of 2014! That's approx 3.2k years ago in Javascript time.

**Comment by mrlake** [comment]
Hi I am having problems installing as well  via npm on rasbian stretch.

~/.node-red $ npm install @slack/client
npm WARN package.json node-red-project@0.0.1 No repository field.
npm WARN package.json node-red-project@0.0.1 No README data
npm WARN package.json node-red-project@0.0.1 No license field.
npm ERR! git clone git@github.com:slack/client undefined
npm ERR! git clone git@github.com:slack/client undefined
npm ERR! addLocal Could not install slack/client
npm ERR! Error: ENOENT: no such file or directory, stat 'slack/client'
npm ERR!     at Error (native)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.9.59-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "@slack/client"
npm ERR! cwd /home/pi/.node-red
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! path slack/client
npm ERR! syscall stat
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/.node-red/npm-debug.log
npm ERR! not ok code 0

Any pointers appreciated :)

Sam

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
