### ISSUE TITLE
Custom config file not overwritte  mongo.db param ?

### ISSUE THREAD

**Issue by TheRealBobi** [DeviaVir/zenbot#769]
I give a custom_conf.js in command line  like : 

`sim --conf JDJiJDEyJDEvSHd3SnJVMmNuWno5a1RxbUZ0WU9yVTlQZWVjTW1pU2NCUC53RkhVNy5QRkQzZnI1VHU2_conf.js  gdax.LTC-EUR    --srsi_macd   --order_type maker   --reset_profit yes`

Have set mongodb params in this custom file but zenbot using default db params in conf.js. 

How can i fix it ?

**Comment by haxwell** [comment]
This should no longer be an issue with PR #912.
