### ISSUE TITLE
HW requirements and hosting environment

### ISSUE THREAD

**Issue by freshpatze** [DeviaVir/zenbot#77]
Where do u guys usually run the bot? I noticed that the memory requirement in terms of RAM is pretty high, right? On AWS micro (1 GB) or on my NAS the bot did not run smoothly and lacked to operate for hours... in fact it was hardly operating at all.
Can u give a general estimation of how much computing power is adequate? Everything above 2 GB of RAM and a decent CPU?

**Comment by TimBroddin** [comment]
I run on a $5 Digital Ocean droplet, works fine. I backfilled on my Macbook and imported the mongo dump.
