### ISSUE TITLE
Bars Data collection

### ISSUE THREAD

**Issue by parliament718** [DeviaVir/zenbot#772]
I'm trying to use zenbot to collect bar data from exchanges. I noticed that the timestamp on each generated bar seems to be dependent on when the bot was started.

For example, when selecting 1M as the period and starting the bot at 4:30:23 PM, the bot will generate its first bar with a timestamp some time around 4:31:23 PM (plus/minus a few seconds).

For bigger timeframe this might not matter as much but for lower timeframes a bar in the middle of the period does not reflect the price accurately.

Is there an easy fix to make bars generate at exact points in time ie 4:30:00, 4:31:00, 4:32:00 (for 1M). Simply rounding is not sufficient

Thanks for this awesome software.

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
