### ISSUE TITLE
Not trading?

### ISSUE THREAD

**Issue by kasperrt** [DeviaVir/zenbot#776]
Is there something I haven't enabled in the configs, when this ![image](https://puu.sh/yxgic/7440699bd5.png) happens? When it says buy, does it mean it is supposed to perform a buy? I have added api-credentials from GDAX in conf.js, and changed it to work with gdax.BTC-EUR, but nothing more.

Anything I'm missing?

**Comment by hquan212** [comment]
Try updating your time on you machine. You can check using the date command in terminal
