### ISSUE TITLE
No trades in advisor mode?

### ISSUE THREAD

**Issue by cschritt** [DeviaVir/zenbot#78]
I am testing zenbot on my personal server using the docker image. Because I don't have a GDAX account yet, I left the configuration untouched. Because of that zenbot starts in advisor mode:

```
btc-usd_1       | 10/13/2016 02:35:04 PM UTC [      trader] gdax.BTC-USD No trader API key provided. Starting in advisor mode. --Zen
```

I notices that there are no trades shown in the live graph. Is this an error or are there no trades to report in advisor mode?

**Comment by egorbenko** [comment]
Make sure in config_defaults.js line 35 and 37 are set to true

**Comment by cschritt** [comment]
Hi egorbenko,

thanks for your reply.

I set both values to true and I can see lines like:

```
10/13/2016 03:21:00 PM UTC [    reporter] 10/13/2016 03:20:00 PM UTC    m24606200       1 trades.           ++         RSI: 60 CLOSE:      $638.29 USD gdax.BTC-USD BAL:   $10,011.35 ROI:1.001 [link]
```

in the log, but still nothing to see in the live graph.

**Comment by egorbenko** [comment]
you need to give zenbot some time. trades don't happen right away

**Comment by cschritt** [comment]
It's been running for nearly a day now. Don't these lines in the log mean that a trade would have been made?

```
10/14/2016 11:06:02 AM UTC [ reporter] 10/14/2016 11:05:00 AM UTC m24607385 13 trades. - RSI: 43 CLOSE: $632.90 USD gdax.BTC-USD BAL: $9,927.55 ROI:0.993
```

**Comment by JFD3D** [comment]
This is just the reporter showing the current RSI, balance and ROI. Are you referring to the ROI being lower than 1?

**Comment by carlos8f** [comment]
Zenbot 4 is out, so I'm cleaning up 3.x issues. Please use and test 4, thanks!
