### ISSUE TITLE
HitBTC: does not place orders (buy/sell)

### ISSUE THREAD

**Issue by tieunguu** [DeviaVir/zenbot#786]
I run zenbot on hitbtc. unfortunately zenbot does not place any orders (buy/sell) on manual or auto trading. while zenbot can get the balance of account.
please help me to fix this issues. thank so much.

![20171203_150609](https://user-images.githubusercontent.com/34205726/33523500-accee5ce-d83b-11e7-8694-48b57319cdc8.jpg)

**Comment by tieunguu** [comment]
any body help me?

**Comment by vtnplus** [comment]
ong phai cap nhap lai API 2.0 chi hitbtc. o version nay no dang sai API 1.0 nen ko chay duoc

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
