### ISSUE TITLE
TheRock: backfill doesn't working

### ISSUE THREAD

**Issue by alemazz** [DeviaVir/zenbot#788]
Hi,
I just pulled the repo and followed the Ubuntu setup, tried to get some trades from TheRock, i got this output:

./zenbot.sh backfill therock.LTC-EUR
(node:15833) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'page' of null
(node:15833) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

the node doesn't exit, it stay up forever

ps: backfills from other exchanges works well 👍

**Comment by ghost** [comment]
I started getting these too, they are about to roll out node 10

**Comment by LoneWolf345** [comment]
It has been quite awhile since the last comment.  Do you feel your issue is resolved?  Please consider closing it.
