### ISSUE TITLE
api.kraken.com | 525: SSL handshake failed

### ISSUE THREAD

**Issue by sfdu** [DeviaVir/zenbot#789]
How to solve this?

Error: Could not understand response from server: <!DOCTYPE html>

 <html class="no-js" lang="en-US"> 
<head>
<meta http-equiv="set-cookie" content="cf_use_ob=0; expires=Sun, 03-Dec-17 09:44:56 GMT; path=/">
<title>api.kraken.com | 525: SSL handshake failed</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />

<style type="text/css">body{margin:0;padding:0}</style>

<script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script>
<script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script>

**Comment by DeviaVir** [comment]
I think this is not something zenbot *can* fix, how often does it happen?

**Comment by sfdu** [comment]
Agree 
I have the same issue on zenbot and on kraken.com. 
The error is more on Kraken.com IT side.
