### ISSUE TITLE
Running version 3

### ISSUE THREAD

**Issue by BarnumD** [DeviaVir/zenbot#8]
Hi Carlos,

I know you're not done with v3 yet..  I noticed that you split zenbot and zenbrain, at least, that's what it appears like.  I'm a little lost as to how to run zenbot now.  Do I have to clone both of these and npm install them?

Thanks

**Comment by carlos8f** [comment]
i'm just getting zenbot 3 running for the first time now. will update with directions when i push the code.

**Comment by BarnumD** [comment]
Thanks!

**Comment by carlos8f** [comment]
ok, @BarnumD here's how to get it running:

``` bash
curl --silent https://raw.githubusercontent.com/carlos8f/zenbot/3.x/install.sh | /bin/bash
```

right now all that works are:
- gdax backfiller/recorder
- bitfinex recorder
- trade reducer (creates ticks in various sizes with map/reduce results)

**Comment by BarnumD** [comment]
Hi again.  I'm working on getting 3.x running in a docker container.  I used what you put in install.sh on the 3.x repo.  I'm having an error getting it to run however.  I should say.. I'm using a database that is carried over from the previous version.

zenbot launch map reduce
`/usr/src/zenbrain/node_modules/mongodb/lib/mongo_client.js:210
          throw err
          ^
ReferenceError: cb is not defined
    at /usr/src/zenbrain/zenbrain.js:84:18`

Any ideas why i'm getting this error?
You can reproduce the error by running the container with docker (change config.js to point to 'mongodb' as your database):
`docker run -d -v /path/to/zenbot/config.js:/usr/src/zenbot/config.js:ro --link mongodb:mongodb --name zenbot barnumd/zenbot:3.0`

**Comment by BarnumD** [comment]
You can see how I built the docker container here: https://github.com/BarnumD/docker-zenbot

**Comment by carlos8f** [comment]
3.x is very unstable right now, just did a bunch of breaking changes yesterday

**Comment by BarnumD** [comment]
K.  Glad to know it's not just me.  I can wait more if that's what it is.

**Comment by BarnumD** [comment]
I realized the mongo cb is not defined error was due to the fact that it couldn't contact it's database.  (I had the wrong entry in the config.js)
