### ISSUE TITLE
Can sell but cannot buy?

### ISSUE THREAD

**Issue by hquan212** [DeviaVir/zenbot#802]
Hi, I am relatively new at using zenbot, but I left the script running over night and I did notice that the default strategy does sell my coins on Gdax but will not buy. I find this strange since when I run the simulator, it will buy and sell at the correct time. 

I have already confirmed that the date on my machine is correct.

One last thing, yesterday, Gdax updated their minimum purchase and sell limit to 0.0001 BTC. I went into the extensions/exchanged/gdax and updated the products.json . I switched the min_size to 0.0001 and increment to 0.0001 . 

Could this be the reason why trend_ema , rsi, neural, etc. are not buying when they are supposed to?
I would appreciate any help

EDIT: also, when I manually trade in LIVE move am I supposed to see the buying and selling orders update on the gdax website? When I run the paper trader, I can buy and sell with they hot keys, but I cannot in the normal trade. The orders never execute.

**Comment by softwarecell** [comment]
Hi, I'm in exactly the same situation. I set live trading this morning on Gdax and it didn't execute the buy order. Zenbot reported "buying" but nothing happened using Maker trading.

I also tried manually buying ('b'), but nothing. I tried manual Taker trading ('B') and this worked and is reported on my Gdax account.

I set my min_size to 0.001 and increment to 0.001.

**Comment by softwarecell** [comment]
Hi, ok maybe it was my fault. I set the buy and sell % to 99 (from 100) and it is working again.

**Comment by hquan212** [comment]
Interesting, my buy and sell pct is set to the default 99 yet still does not execute. Ill try messing around with those parameters to see what will happen.

**Comment by softwarecell** [comment]
In the end I have the following:

min_size: 0.001
increment: 0.00001

buy %: 99
sell %: 100

**Comment by hquan212** [comment]
@johnchodgson That worked! I re downloaded the products.json and edited the min_size and increment to match your, then on the config file I set it to the same pct values and now it works when I manually buy!

Resolved!

**Comment by pete-oconnell** [comment]
@hquan212 if the issue is resolved then please close the issue
