### ISSUE TITLE
zenbot.sh always hangs

### ISSUE THREAD

**Issue by jpita** [DeviaVir/zenbot#808]
![image](https://user-images.githubusercontent.com/5482105/33688310-3d6d82a6-dadb-11e7-8219-e8bd0be888f8.png)

always hangs here.
I had to change the sim days to 1 because it was hanging in the step before.

any help?

**Comment by DeviaVir** [comment]
Is this bug still active in the latest `unstable`?

**Comment by leozzo** [comment]
This still occour

Inviato da iPhone
