### ISSUE TITLE
Simulation vs Reality

### ISSUE THREAD

**Issue by grigio** [DeviaVir/zenbot#81]
Can you share some numbers? I didn't test much because of this #9 

I mean, if in the backtesting simulation you get ROI 1.7 with 30 txs, how  much would you expect after one or two month in reality? Do you lose money in bear or flat trends?

**Comment by totomaze** [comment]
I am still trying to find a good strategy backtesting since 01/01/2016. backtesting for 3 months is really not enough.
Using gdax BTC EUR

I would like to see some number too from poloniex, which config is the best.@JFD3D

**Comment by JFD3D** [comment]
@totomaze There is no 'one-size-fits-all' configuration. If there was, everyone would be doing it and then it wouldn't work anymore. The best thing to do is to test with different settings over different time-frames and see what settings are the most accurate for a given pair. You can also try averaging smaller time-frames and try to find settings that may work for an 'overfit' strategy. Keep in mind zenbot is in active development and there is still lots to do.
