### ISSUE TITLE
REST API makes bot crash

### ISSUE THREAD

**Issue by albabosh** [DeviaVir/zenbot#814]
When I put c.output.api.port (not 0) into config zenbot crashes at startup. port=0 works ok. It seems that REST API uses 2 ports. Could you give a correct example of api config ? Thanks

**Comment by ArnaudRitti** [comment]
Hi, 
I got the same issue. It's a bug in trade.js. 
You can check my fix at [https://github.com/ArnaudRitti/zenbot/blob/API/commands/trade.js#L385](https://github.com/ArnaudRitti/zenbot/blob/API/commands/trade.js#L385)

**Comment by abduegal** [comment]
Hi, I'm going to take a look and see if I can solve this.

**Comment by abduegal** [comment]
@albabosh @ArnaudRitti what error did you get. What did you enter in the c.output.api.port?
I tested this with the following settings, and they all work:
c.output.api = {}
c.output.api.on = true
c.output.api.port = 8080 

-------------

c.output.api = {}
c.output.api.on = true
c.output.api.port = 0  

------

c.output.api = {}
c.output.api.on = true
c.output.api.port

**Comment by ArnaudRitti** [comment]
I get a Node Express error : `EADDRINUSE, Address already in use`

**Comment by albabosh** [comment]
The same I get "EADDRINUSE, Address already in use"

**Comment by abduegal** [comment]
Allright, still can't reproduce it. But @albabosh could you try the fix that @ArnaudRitti provided and see if that solves it for you. If that is the case then we should add that fix in a pull request

**Comment by ArnaudRitti** [comment]
My PR #850 integrate the fix

**Comment by albabosh** [comment]
It seems to happen only if strategy is set to 'neural'

**Comment by j0nxs** [comment]
It is not fixed - it crashed in 'neural', because it open two sockets - on random it uses difference ports, but when you use a fixed port then fail the second socket because it use the same port
