### ISSUE TITLE
Bittrex backfill

### ISSUE THREAD

**Issue by kazdimenator** [DeviaVir/zenbot#816]
Bittrex api does not support backfilling (trade/paper only).

Can not I use it?
https://bittrex.com/Api/v2.0/
( https://bittrex.com/Api/v2.0/pub/market/GetTicks?marketName=BTC-LTC&tickInterval=thirtyMin )

or

https://github.com/miti0/python-bittrex

**Comment by DeviaVir** [comment]
Pretty sure this has already been asked, so marking duplicate.

**Comment by DeviaVir** [comment]
Duplicate of https://github.com/carlos8f/zenbot/issues/499
