### ISSUE TITLE
Zenbot | Quadrigacx

### ISSUE THREAD

**Issue by ZapperZR1** [DeviaVir/zenbot#817]
Can someone help shed some light on setting this up.. I'm a bit confused on the instruction

I've tried multiple variations.. Don't get what "as a string not numbers" means

// to enable QuadrigaCX tranding, enter your API credentials:
c.quadriga = {}
c.quadriga.key = 'YOUR-API-KEY'
// this is the manual secret key entered by editing the API access
// and NOT the md5 hash you see in the summary
c.quadriga.secret = 'YOUR-SECRET'
// replace with the client id used at login, as a string, not number
c.quadriga.client_id = 'YOUR-CLIENT-ID'

**Comment by sniper7kills** [comment]
Enter the number in the quotes like:
``c.quadriga.client_id = '####'``
NOT LIKE:
``c.quadriga.client_id = ####``

**Comment by ZapperZR1** [comment]
Got it.. It wasn't the quotes 

I messed up on the secret key.. I wasn't grabbing it as I created the api key .. I was grabbing it after not noticing that it was different..

Thanks for making double check
