### ISSUE TITLE
Is Zenbot still being actively developed?

### ISSUE THREAD

**Issue by JeffUberman** [DeviaVir/zenbot#82]
Is Zenbot still being actively developed?

**Comment by carlos8f** [comment]
yes, i had some personal issues to deal with but i’ll be back in action improving zenbot as of next week.

Cheers,
Morpheus.5250

**Comment by ghostnegotiator** [comment]
I am dealing some RL issues atm, but will be available soon to help again.

**Comment by ghostnegotiator** [comment]
@Carlos is there some way to reach you trough chat?

**Comment by carlos8f** [comment]
Zenbot 4 is out, so I'm cleaning up 3.x issues. Please use and test 4, thanks!
