### ISSUE TITLE
Docker + Raspberry Pi,  'CANNOT CONNECT TO A NON RUNNING CONTAINER 

### ISSUE THREAD

**Issue by kayoshin** [DeviaVir/zenbot#821]
Hey everyone, I have been stuck on this for a while now. Does anybody understand where that error comes from, and why? I am running docker on my RPi3 - I know its a stupid Idea but I was hoping I could clear the Db in regular intervals ( not exactly sure how that would work either) 
I tried a couple of things, like reinstalling docker compose, I tried deleting and reinstalling Docker but I just cannot get it removed- I have tried so man things.

**Comment by jespertje** [comment]
I tried running Zenbot on Raspbian but it never really worked, so I installed Ubuntu Mate on my rpi3 and now it runs perfectly. So I recommend doing the same as me.

Jesper

**Comment by creatorlabpro** [comment]
@jespertje  Did you install Ubuntu Mate + Docker on RPI3 or you just run Zenbot straight on Ubuntu Mate?

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
