### ISSUE TITLE
cex.io: There was an error while placing your order: Invalid price

### ISSUE THREAD

**Issue by jellebens** [DeviaVir/zenbot#824]
using neural I get
Trade Error There was an error while placing your order: Invalid price

**Comment by yellowcandle** [comment]
Same problem here.
After searching in discord:
> bloodseeker - Today at 2:00 AM
Zombot - 12/01/2017
in case you wan't to avoid taker fee (0,16%), you can modify extensions/exchanges/cexio/products.json and reduce increment of your asset, here the one from
```
eth-usd  {
    "asset": "ETH",
    "currency": "USD",
    "min_size": "0.1",
    "max_size": "1000",
    "increment": "0.0001", <--
    "label": "ETH/USD"
  },
```
> That helped me with invalid price

**Comment by Karlheinzniebuhr** [comment]
Same issue

**Comment by jellebens** [comment]
or ju you can run the script sh script in same dir

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
