### ISSUE TITLE
The param 'device_iden' has an invalid value

### ISSUE THREAD

**Issue by sfdu** [DeviaVir/zenbot#825]
I'm running on ubuntu ./zenbot.sh trade --paper
I have this error 
 error: Push message failed, Error: The param 'device_iden' has an invalid value.
any idea ?

**Comment by tolleiv** [comment]
This means that the `c.notifiers.pushbullet.deviceID` setting is not correct. Or pushbullet is enabled even though you have not fully configured it.
You can use the sample code from https://github.com/alexwhitman/node-pushbullet-api to get the correct id or curl:
`curl --header 'Access-Token: <token>' https://api.pushbullet.com/v2/devices`

**Comment by sfdu** [comment]
ok thank, 
my deviceID was not set to my email account 

c.notifiers.pushbullet.key = 'YOUR-API-KEY'
c.notifiers.pushbullet.deviceID = 'YOUR-DEVICE-ID or EMAIL if registred via google account'
