### ISSUE TITLE
Link in description and livefeed link in readme broken.

### ISSUE THREAD

**Issue by joeswann** [DeviaVir/zenbot#83]
Livefeed link in readme also appears to have been hacked or something?

**Comment by fkadibs** [comment]
S8f.org was carlos8f's domain, but it is no longer maintained.

**Comment by joeswann** [comment]
I can do a PR to remove that line from readme?

**Comment by carlos8f** [comment]
I'm going to resurrect s8f, I shut it down temporarily

**Comment by JFD3D** [comment]
@carlos8f, Looking forward to it. Glad to see you back in action. I my self have been away for quite some time as well (due to an injury) but now that I'm back in full force I'm looking forward to the continuation and further development of this project. Best wishes
