### ISSUE TITLE
binance transactions errors

### ISSUE THREAD

**Issue by vitorego** [DeviaVir/zenbot#830]
hi guys,
I+m having thsi error when live trading on binance:

```
Error: binance POST https://api.binance.com/api/v3/order 400 Bad Request {"code":-1100,"msg":"Illegal characters found in parameter 'price'; legal range is '^([0-9]{1,20})(\\.[0-9]{1,20})?$'."} (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting)
    at binance.defaultErrorHandler (/home/vitorego/download/zenbot_master/node_modules/ccxt/js/base/Exchange.js:400:15)
    at response.text.then.text (/home/vitorego/download/zenbot_master/node_modules/ccxt/js/base/Exchange.js:413:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: ExchangeNotAvailable] }

Binance API is down! unable to call buy, retrying in 20s
[ { size: '0.00280188',
    orig_size: '0.00280188',
    remaining_size: '0.00280188',
    orig_price: '426.96',
    cancel_after: 'day',
    product_id: 'ETH-USDT',
    type: 'limit',
    side: 'buy',
    post_only: true } ]

```

Do you know if this is a bug or what?

**Comment by hquan212** [comment]
try asking binance for a new api, that worked for me on gdax.

**Comment by vitorego** [comment]
I think the issue is because binance only supports 5 decimal digits and we are sending 8.

**Comment by carolburri** [comment]
Same problem here. Couldn't fix it. Any help would be great!

**Comment by vitorego** [comment]
i just discover that this errors happens because the products.json of binance is not correct according with the real minimum allowed by their site. Fixing the file manually the issue seems to be fixed.

thanks for the support

**Comment by carolburri** [comment]
Could you show me what exactly did you chance? That would be great. Thx

**Comment by vitorego** [comment]
For ETH-USD pair i just changed to:
{
    "id": "ETHUSDT",
    "asset": "ETH",
    "currency": "USDT",
    "min_size": "0.01000",
    "max_size": "100000",
    "increment": "0.001",
    "label": "ETH/USDT"
  }

**Comment by carolburri** [comment]
Thx. I'm not able to get it work. 
Did also the increment of 0.001 but no hope. 

 {
    "id": "IOTABTC",
    "asset": "IOTA",
    "currency": "BTC",
    "min_size": "1.000000",
    "max_size": "100000",
    "increment": "0.000001",
    "label": "IOTA/BTC"
  },

If someone have a idea it would be great!

**Comment by Hochgesand** [comment]
Where do I find this file?
