### ISSUE TITLE
docker-compose error

### ISSUE THREAD

**Issue by zigzag-way** [DeviaVir/zenbot#831]
While trying to launch the bot on my Windows 10 laptop, I tried to execute command:
docker-compose --file=docker-compose-windows.yml up
and that`s the end of the output with the error:

File "site-packages\docker\transport\npipesocket.py", line 50, in connect
pywintypes.error: (2, 'WaitNamedPipe', '\xcd\xe5 \xf3\xe4\xe0\xe5\xf2\xf1\xff \xed\xe0\xe9\xf2\xe8 \xf3\xea\xe0\xe7\xe0\xed\xed\xfb\xe9 \xf4\xe0\xe9\xeb.')
Failed to execute script docker-compose

**Comment by JensvdHeydt** [comment]
Do you get the same result when you start docker-compose without any arguments?

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
