### ISSUE TITLE
Is there a way to specify a period offset?

### ISSUE THREAD

**Issue by wschultz** [DeviaVir/zenbot#837]
I've got a bot running at 30 minute intervals, so it's going at :00 and :30

Is there a way to change that to use :01 and :31, or any other pair of offsets? I don't see anything obvious.

**Comment by brucetus** [comment]
That's not a feature right now, but I was just curious why you would want that.

**Comment by wschultz** [comment]
Other trading platforms have an offset so everyone isn't always trading on :00 and :30, a random offset could put the trade intervals at :03 and :33, for example.

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
