### ISSUE TITLE
profit_stop_enable_pct doesn't seem to trigger on SAR when live trading?

### ISSUE THREAD

**Issue by paroxysm** [DeviaVir/zenbot#838]
I've only  seen this setting work on 'sim' mode, but in live mode. Never triggers. I've tried setting it to really low percentages to PROC it more often, but it doesn't seem to work. Either that, or it appears to not be calculating profits percent correctly

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
