### ISSUE TITLE
Suppress Kraken API warnings

### ISSUE THREAD

**Issue by timstoop** [DeviaVir/zenbot#843]
Hi,

Is there an option to suppress the Kraken API warnings? They're messing up my display :/

**Comment by MT00x** [comment]
No, and sincerely I think this should not be done.
Continously get some exchange API warnings / errors is a sinthom that using bot is extremely risky and could end with capital loose

**Comment by timstoop** [comment]
Having a simple option like "--ignore-warnings-at-my-own-peril" wouldn't be so bad...

**Comment by MT00x** [comment]
On your fork or local clone you can change 
`zenbot/extensions/exchanges/kraken/exchange.js`
and comment line 85

`console.warn(('\nKraken API warning - unable to call ' + method + ' (' + errorMsg + '), retrying in ' + timeout / 1000 + 's').yellow)`

**Comment by timstoop** [comment]
I noticed a bit late that the warning are sent to stderr, so simply redirecting fd 2 to /dev/null solves my issue :)
