### ISSUE TITLE
QuadrigaCX API rate limit exceeded! unable to call getBalance, aborting  QuadrigaCX API is down: (getBalance) Cannot perform request - nonce must be higher than 1513082520

### ISSUE THREAD

**Issue by zaidkazi** [DeviaVir/zenbot#845]
Keep getting this bug when i try to run on quadriga

**Comment by TCourage** [comment]
Did you ever figure out a way to fix this? I'm running into the same problem, it'll get a trade or two in before it gives me

``QuadrigaCX API is down: (cancelOrder) Cannot perform request - not found

or 

``QuadrigaCX API is down: (getBalance) Cannot perform request - nonce must be higher than 1519749656

I've tried creating new API keys, changing the period length, not really sure where to go from here

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
