### ISSUE TITLE
Start sim from certain date

### ISSUE THREAD

**Issue by pete-oconnell** [DeviaVir/zenbot#851]
Is it possible to run the sim from a certain date? For example I've been running the bot for 4 days and whilst it's done some good trades it's also done some bad. I would like to re-run those 4 days with different strategies to see if it's down to my settings or just the bot having a bad day.

**Comment by tiagosiebler** [comment]
@pete-oconnell it's all documented. Check out `zenbot sim --help` for a list of primary parameters. These start/stop params take either a unix time stamp, or a UTC formatted date (E.g `--start="2017-12-13T09:23:48.791Z"`).

**Comment by pete-oconnell** [comment]
Yes - sorry I have just seen this - thank you.
