### ISSUE TITLE
Error on docker-compose build on Rasp Pi3

### ISSUE THREAD

**Issue by ghost** [DeviaVir/zenbot#859]
I follow indications on issues 533 and .md file in doc

docker, docker-compose, nodejs are installed
mongo docker is ok

I clone the git, do the npm install.
But on docker-compose, get this error
```
mongodb-data uses an image, skipping
mongodb uses an image, skipping
Building server
Step 1/10 : FROM node:latest
latest: Pulling from library/node
ERROR: Service 'server' failed to build: no matching manifest for linux/arm in the manifest list entries
```
Any suggestions ?

**Comment by daphid4** [comment]
I ran into this error as well on PI2.  I got it to work by changing the first line in the Dockerfile to this:

FROM arm32v7/node

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
