### ISSUE TITLE
web server logs with multi-pair mode

### ISSUE THREAD

**Issue by wiscokidd** [DeviaVir/zenbot#86]
I just setup a new Digital Ocean droplet and started backfilling BTC/USD, ETH/USD and ETH/BTC when I check the localhost:3013/logs the only thing that shows up is the ETH/BTC trades. Now it says backfill complete and is no longer showing any new ticks. Is this a bug or am I doing something wrong?

**Comment by wiscokidd** [comment]
I ran each command in a different tmux instance:
`./reducer.sh`
`./server.sh`
`./run-btc-usd.sh`
`./run-eth-usd.sh`
`./run-eth-btc.sh`

**Comment by marciopuga** [comment]
@wiscokidd what was the issue?

**Comment by wiscokidd** [comment]
> 
I ran each command in a different tmux instance:
./reducer.sh
./server.sh
./run-btc-usd.sh
./run-eth-usd.sh
./run-eth-btc.sh

>
