### ISSUE TITLE
Allow strategies to trigger a SELL NOW signal, which forces zenbot to place a market order to sell asap

### ISSUE THREAD

**Issue by tiagosiebler** [DeviaVir/zenbot#865]
Some signals can be acted on delay when the strategy thinks the ideal selling/buying point is about to happen, but there may be scenarios where the only way to prevent a loss is in immediate sell (or buy) as close as possible to the currently quoted price. 

The fees may be higher, but this should allow for strategy situations where there's a high confidence that the best price will be to buy/sell at this very instant, and delaying using limit orders would miss that opportunity. Not sure how heavy this change would be in the current zenbot designs.

**Comment by slashafk** [comment]
Hello, 
if in your strategy you do something like : s.order_type='taker' you will replace the current order_type from maker to taker, you'll then have to switch back to maker once the order is validated

**Comment by DeviaVir** [comment]
This issue was moved to highvelocityspace/zenbot#83

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
