### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by osnwt** [DeviaVir/zenbot#87]
Hi!

I found the project by accident and like it a lot. Being new, I am trying to make it work with at lest some exchange. GDAX isn't available for me (not in US), Poloniex doesn't work yet AFAIK (read about issues), and only Kraken is supported somehow. Still, I have some issues with it:
- can't find a direct correlation between RSI graph and RSI values in the output. RSI crosses up/down lines but no buy/sell actions generated for those crosses;
- can't run sim on some data that not yet have 3 months (ZEC/BTC is an example);
- something else.

But I see that:
- home site is down;
- discord channel's invite is outdated (can't enter the channel);
- reddit author username is deleted.

So the question is about the future and how to contact/talk to developers and contributors. Is it going to be maintained or should I look at something else. I am interested to play with such bots, I am ok to fix something (but do not have javascript experience). And I hope the project is not dead. Can anybody explain its status?

**Comment by carlos8f** [comment]
Hi,

I am the author and I intend on improving and supporting the project. I just have been going through some personal and career bumps. As for the exchange support, it's hard to support multiple exchanges consistently (for legal and practical reasons) and I depend on contributions from the community so I apologize if your international needs are not supported.

I hope to release an overhaul in the next few months that will make the bot more organized, modular, and easier for community to contribute features.

Regards,
Carlos

**Comment by osnwt** [comment]
Thank you for your prompt feedback.

An exchange support is not an issue, I am able to add anything I need. It just may take more time than usual since I have to learn javascript in details, but that's perfectly fine.

I am happy to know that it still is in development and not abandoned. In this case I may spend efforts to study zenbot code and look at what happens when I get unexpected results like above.
