### ISSUE TITLE
Cannot read property 'vsBuyHold'

### ISSUE THREAD

**Issue by davobo** [DeviaVir/zenbot#872]
After running first generation in Darwin the following error appears:
 
**TypeError: Cannot read property 'vsBuyHold' of undefined**
       at Object.fitness [as fitnessFunction] 
   (/home/geronimo/zenbot/scripts/genetic_backtester/phenotype.js:66:40)
       at /home/geronimo/zenbot/node_modules/geneticalgorithm/index.js:135:38
       at Array.map (<anonymous>)

Have been checking out and it appears that darwin isn't storing any data in it's CSV and JSON files.
i.e.  backtesting_1513035564.csv and generation_data_1513035564_gen_2.json

After modifying line 551 in darwin.js from:
`_fs.writeFile(fileName, csv, err => {_`
to:
`_fs.writeFileSync(fileName, csv, err => {_`

it has started storing data in CSV and JSON files but the error still remains. Since it's a parallel execution I suspect that it's trying to get the variable before any data is stored in files.

Any suggestions ?

**Comment by bdfoster** [comment]
Can reproduce completely, but I unfortunately don't have a solution.

**Comment by tiagosiebler** [comment]
I'm seeing this too, this issue was introduced in one of the more recent PRs. The sim results are missing when darwin attempts to loop through results:
```
    selectedStrategies.forEach(function(v) {
      let best = pools[v]['pool'].best();
      console.log(`(${v}) VS Buy and Hold: ${best.sim.vsBuyHold} End Balance: ${best.sim.endBalance}`);
      let nextGen = pools[v]['pool'].evolve();
    });
```

best() only returns the parameters, with no sim object present. Not sure where this is supposed to be set from.

**Comment by davobo** [comment]
Hi tiagosiebler

thanks for the fix, I'm closing the bug.

BR
