### ISSUE TITLE
How can i achieve following?

### ISSUE THREAD

**Issue by dshetyo** [DeviaVir/zenbot#874]
Is it possible to do following thing with current available settings?

1. In trend_ema strategy buy only if the current price is less then amount X (this is in addition of upward trend detection). As in i dont want the risk to buy when price is very high.
2. I want to make the bot buy with with X capital when its buying at high risk. For example buy with 100 usd capital when current market rate is above USD 17K, but the bot can buy with 200 usd when the market price is beflow 17K. These values should be configurable.

**Comment by DeviaVir** [comment]
This issue was moved to highvelocityspace/zenbot#77

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
