### ISSUE TITLE
Bot keeps chasing current market rate in trend_ema.

### ISSUE THREAD

**Issue by dshetyo** [DeviaVir/zenbot#875]
The bot detected a upward trend and then it places a limit order to buy at price X. The market price goes about X+5, bot cancels old bit and places a new bid at X+4.99, market again jumps to X+10, bot cancels old order and places new order at X+9.99. 

This is risky. If there is a config that prevents bot from doing this then it would be good.

**Comment by slashafk** [comment]
Are you using some markdown_buy/markup_sell parameters ? Those are responsible to such behaviour. Default zenbot behaviour is to be on top of the order book.

**Comment by DeviaVir** [comment]
This issue was moved to highvelocityspace/zenbot#76

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
