### ISSUE TITLE
Binance order errors

### ISSUE THREAD

**Issue by confact** [DeviaVir/zenbot#876]
I get this error in almost every order:
```javascript
An error occurred { Error: binance POST https://api.binance.com/api/v3/order 400 Bad Request {"code":-2010,"msg":"Account has insufficient balance for requested action."} (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting)
    at binance.defaultErrorHandler (/home/confact/Documents/code/zenbot/node_modules/ccxt/js/base/Exchange.js:400:15)
    at response.text.then.text (/home/confact/Documents/code/zenbot/node_modules/ccxt/js/base/Exchange.js:413:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: ExchangeNotAvailable] }
```

Is this a bug?

**Comment by sfdu** [comment]
Do you have enough $ on your account because the first part of the error code is : "Account has insufficient balance for requested action."

**Comment by confact** [comment]
I have 400 USD. 

Shouldn't this trigger some rejection of order instead of an error occurred message?

**Comment by rickysahu** [comment]
i currently am encountering the same issue and have enough funds to cover the trade. i believe this is an issue with binance's api. has anyone figured out a way around it?

**Comment by DeviaVir** [comment]
This issue was moved to highvelocityspace/zenbot#75

**Comment by mkuendig** [comment]
Same here. I have set 100% of funds to buy. Now it trades but often runs into the error above. I use the neural strategy.

**Comment by benjamincburns** [comment]
It seems to be a rounding bug in zenbot in `executeSignal` when calculating the `size` of a buy order. I see this on GDAX as well, and it was reported on Bittrex over in #910. [Relevant comment from another issue](https://github.com/DeviaVir/zenbot/issues/868#issuecomment-354963455).

**Comment by rsergiuistoc** [comment]
I encountered the same error while I tried to sell on limit ... messing up hours of research , but finally solved it.Each time i wanted to sell binance took me 0.1% FEE for every transaction i made so instead of selling 324 units , binance forced me to sell 323... . Here is the formula for doing this new_quantity = int(quantity - (0.050*quantity)/100).Good luck :>.

**Comment by glennfu** [comment]
Still getting this. Using BNB for fees, of which I have plenty. Zenbot purchase 10 EOS just fine, then a bit later goes to sell it back. Every time it does, it gets "Account has insufficient balance for requested action." even though the sell order actually shows up on my Open Orders screen on Binance. Over and over it places and adjusts sell orders, always getting that error, even though they're actually going through and appearing correctly on Binance.

This issue on another project suggests we shouldn't even be looking at this error and instead should be looking at our trade history: https://github.com/taniman/profit-trailer/issues/452

**Comment by DeviaVir** [comment]
I think I'll close this in favor of #868 and #1406
