### ISSUE TITLE
Websocket on CEX.io

### ISSUE THREAD

**Issue by albabosh** [DeviaVir/zenbot#877]
Why not use Websocket API on CEX.io ? Rest API has very low rate limit.

**Comment by slashafk** [comment]
Because the websocket require a very different architecture than the one being used by all the others exchange.

Websocket could be more interesting since it's the server that calls back on new period but it require lots of changes.

**Comment by DeviaVir** [comment]
This issue was moved to highvelocityspace/zenbot#74

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
