### ISSUE TITLE
buy_pct on manual trades keeps buying

### ISSUE THREAD

**Issue by thober35** [DeviaVir/zenbot#878]
Im using zenbot as a manual trader which should buy in my case 20% of my currency balance when i press b
Zenbot executes the order, buys 20% but than buys another 20% and so on.

could there be something wrong with my code? 

my command to open the trader would be in ubuntu:
./zenbot.sh trader --manual --paper bittrex.ltc-btc 

in config = c.buy_pct = 20

thanks in advance

**Comment by daphid4** [comment]
I'm experiencing this as well, not just with manual trades but automatic trades too. This is my slack notifications for the last 5 minutes 
`Selling BITTREX: placing sell order at 671.999 USDT, 2.27894 USDT over best ask


[7:59] 
Sell BITTREX: 
sell order completed at 2017-12-15 14:58:54:

1.51848363 ETH at 671.697 USDT
total 1019.96 USDT
0.0450% slippage (orig. price 671.999 USDT)
execution: a minute


[7:59] 
Selling BITTREX: placing sell order at 672.393 USDT, 2.59328 USDT over best ask


[8:00] 
Sell BITTREX: 
sell order completed at 2017-12-15 14:59:53:

0.01518484 ETH at 672.091 USDT
total 10.2056 USDT
0.0450% slippage (orig. price 672.393 USDT)
execution: a minute


[8:00] 
Selling BITTREX: placing sell order at 673.272 USDT, 0.878673 USDT over best ask


[8:00] 
Selling BITTREX: placing sell order at 673.272 USDT, 0.878673 USDT over best ask


[8:01] 
Buying BITTREX: placing buy order at 672.000 USDT, 0.00000000 USDT under best bid


[8:01] 
Buy BITTREX: 
buy order completed at 2017-12-15 15:01:11:

0.31446376 ETH at 672.302 USDT
total 211.415 USDT
0.0450% slippage (orig. price 672.000 USDT)
execution: a few seconds


[8:01] 
Buying BITTREX: placing buy order at 672.000 USDT, 0.00000000 USDT under best bid


[8:02] 
Buy BITTREX: 
buy order completed at 2017-12-15 15:01:38:

0.25154270 ETH at 672.302 USDT
total 169.113 USDT
0.0450% slippage (orig. price 672.000 USDT)
execution: a few seconds


[8:02] 
Buying BITTREX: placing buy order at 670.520 USDT, 0.00000000 USDT under best bid


[8:02] 
Buying BITTREX: placing buy order at 670.520 USDT, 0.00000000 USDT under best bid

[8:02] 
Buy BITTREX: 
buy order completed at 2017-12-15 15:01:49:

0.20165554 ETH at 670.822 USDT
total 135.275 USDT
0.0450% slippage (orig. price 670.520 USDT)
execution: a few seconds


[8:02] 
Buying BITTREX: placing buy order at 671.500 USDT, 0.00000000 USDT under best bid


[8:03] 
Buying BITTREX: placing buy order at 673.860 USDT, 0.00000000 USDT under best bid


[8:03] 
Buy BITTREX: 
buy order completed at 2017-12-15 15:03:07:

0.16107096 ETH at 671.802 USDT
total 108.208 USDT
0.0450% slippage (orig. price 671.500 USDT)
execution: a minute


[8:03] 
Buying BITTREX: placing buy order at 673.870 USDT, 0.00000000 USDT under best bid

[8:05] 
Buy BITTREX: 
buy order completed at 2017-12-15 15:03:52:

0.12850152 ETH at 674.174 USDT
total 86.6323 USDT
0.0450% slippage (orig. price 673.870 USDT)
execution: a few seconds


[8:05] 
Buying BITTREX: placing buy order at 673.860 USDT, 0.00000000 USDT under best bid


[8:05] 
Buying BITTREX: placing buy order at 673.860 USDT, 0.00000000 USDT under best bid


[8:05] 
Buying BITTREX: placing buy order at 673.860 USDT, 0.00000000 USDT under best bid


[8:05] 
Buying BITTREX: placing buy order at 673.860 USDT, 0.00000000 USDT under best bid


[8:06] 
Buying BITTREX: placing buy order at 673.870 USDT, 0.00000000 USDT under best bid


[8:06] 
Buying BITTREX: placing buy order at 673.870 USDT, 0.00000000 USDT under best bid


[8:06] 
Buy BITTREX: 
buy order completed at 2017-12-15 15:05:56:

0.10279124 ETH at 674.163 USDT
total 69.2981 USDT
0.0450% slippage (orig. price 673.860 USDT)
execution: a minute


[8:06] 
Buying BITTREX: placing buy order at 673.870 USDT, 0.00000000 USDT under best bid


[8:07] 
Buy BITTREX: 
buy order completed at 2017-12-15 15:06:21:

0.08222279 ETH at 674.174 USDT
total 55.4324 USDT
0.0450% slippage (orig. price 673.870 USDT)
execution: a few seconds


[8:07] 
Buying BITTREX: placing buy order at 673.870 USDT, 0.00000000 USDT under best bid


[8:07] 
Buying BITTREX: placing buy order at 674.000 USDT, 0.00000000 USDT under best bid


[8:08] 
Buying BITTREX: placing buy order at 674.163 USDT, 0.00000000 USDT under best bid


[8:08] 
Buy BITTREX: 
buy order completed at 2017-12-15 15:07:13:

0.06577083 ETH at 674.174 USDT
total 44.3410 USDT
0.0450% slippage (orig. price 673.870 USDT)
execution: a few seconds


[8:08] 
Buy BITTREX: 
buy order completed at 2017-12-15 15:08:18:

0.05259044 ETH at 674.466 USDT
total 35.4705 USDT
0.0450% slippage (orig. price 674.163 USDT)
execution: a minute


[8:08] 
Buying BITTREX: placing buy order at 673.870 USDT, 0.00000000 USDT under best bid


[8:08] 
Buying BITTREX: placing buy order at 673.870 USDT, 0.00000000 USDT under best bid`

**Comment by thober35** [comment]
i tested different settings, different strategies and also trades with poloniex but always the same outcome.
the system buys 20% but doesnt stop and attempts to buy another 20%.
My guess would be that buy_pct isnt implemented correctly.

unfortunately i couldnt find any errors in engine.js, maybe someone more experienced could look into it?

**Comment by thober35** [comment]
buy order completed at 2017-12-17 14:31:08:

46838.40749415 CANN at 0.00000427 BTC
total 0.200000 BTC
0.0000% slippage (orig. price 0.00000427 BTC)
execution: a minute

2017-12-17 14:31:21  0.00000428 CANN-BTC   +0.00%     5902              bought  
2017-12-17 14:31:21  0.00000428 CANN-BTC   +0.00%     5902              bought  
2017-12-17 14:31:21  0.00000428 CANN-BTC   +0.00%     5902              **buying**  
2017-12-17 14:31:21  0.00000428 CANN-BTC   +0.00%     5902              buying  
2017-12-17 14:31:21  0.00000428 CANN-BTC   +0.00%     5902              buying 

maybe there would be a combination with ms to pull trades ...
Ill keep testing

**Comment by DeviaVir** [comment]
This issue was moved to highvelocityspace/zenbot#73

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
