### ISSUE TITLE
Orderbook

### ISSUE THREAD

**Issue by kazdimenator** [DeviaVir/zenbot#889]
I apologize for the question:) Does any of the strategy which analyze the number of orders for purchasing and saling? This information is available via API (ex. https://bittrex.com/api/v1.1/public/getorderbook?market=BTC-LTC&type=both ).   Could this information be used to determine the growth or fall in prices?

![orderbook](https://user-images.githubusercontent.com/33937361/34070590-a49a0d1e-e279-11e7-80ce-7a1c50e2eb74.JPG)

**Comment by dshetyo** [comment]
I think order graph compared with other strategy like trend ema will be killass

**Comment by DeviaVir** [comment]
This issue was moved to highvelocityspace/zenbot#50

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖

**Comment by choperlizer** [comment]
@kazdimenator I think you want to implement this as a strategy: https://github.com/H-Gomez/btc-books-depth/blob/master/ticker.js
