### ISSUE TITLE
--output switch to have custom names on simulations

### ISSUE THREAD

**Issue by rountrey** [DeviaVir/zenbot#891]
I was wondering if an --output switch for custom names could be added. I want to run a bunch of sims overnight or when at work and go through them later.

**Comment by tiagosiebler** [comment]
@rountrey Check out the filename switch, e.g:
```--filename="simulations/indicator2.html"```

If I understood correctly, that's what you're looking for.

**Comment by rountrey** [comment]
That's exactly what I needed, thanks. It doesn't seem to be in the readme

**Comment by DeviaVir** [comment]
This issue was moved to highvelocityspace/zenbot#48
