### ISSUE TITLE
Waiting on first live trade to display reports, could be a few minutes ...

### ISSUE THREAD

**Issue by RV2013** [DeviaVir/zenbot#893]
I have below command running successfully 
zenbot trade --paper 
But it never runs successfully and keep on the below line for hours and hours . No execution below this line "Waiting on first live trade to display reports, could be a few minutes ..."

Command : zenbot trade --paper  bittrex.XRP-BTC

console log : 

api running on 192.168.0.15:7117/trades
fetching pre-roll data:
please note: the bittrex api does not support backfilling (trade/paper only).
please note: make sure to set the --period=1m to make sure data for trade/paper is fetched.

bittrex.XRP-BTC saved 100 trades 1 days left

download complete!

               DATE            PRICE     DIFF            VOL         RSI                         ACTIONS                      BAL                PROFIT
---------------------------- STARTING PAPER TRADING ----------------------------
!!! Paper mode enabled. No real trades are performed until you remove --paper from the startup command.
Press  l  to list available commands.
please note: the bittrex api does not support backfilling (trade/paper only).
please note: make sure to set the --period=1m to make sure data for trade/paper is fetched.
Waiting on first live trade to display reports, could be a few minutes ...
---------- Log ends -----------

Here is
### System information
- **using Vanilla Zenbot version**:
- **OS Platform and Distribution (Mac osx 10.11.6)**:
- **Zenbot version = 4.0.5**:
- **NodeJS version = 9.2.1**: 
- **Python version = 2.7.10**:
- **Exact command to reproduce =  zenbot trade --paper  bittrex.XRP-BTC
**:

**Comment by DeviaVir** [comment]
This issue was moved to highvelocityspace/zenbot#46

**Comment by glennfu** [comment]
I'm getting this today on live trading with Binance

Today this was the result of an outage at Binance:
https://twitter.com/cz_binance/status/961429082310258688

in `trade.js`:
`exchange.getTrades(opts, function (err, trades) {`
`err == null` and `trades == []`

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
