### ISSUE TITLE
Forum to discuss about zenbot

### ISSUE THREAD

**Issue by dshetyo** [DeviaVir/zenbot#899]
We need some way to ask questions about funtionality/ features/ options/questions.

Stackoverflow is not allowing us to post such question under zenbot . See [here](https://stackoverflow.com/questions/47850962/how-to-read-simulation-output?noredirect=1#comment82668232_47850962)

**Comment by papacasper** [comment]
Not sure why this was taken out of the README but there is a [discord server](https://discord.gg/2bcBUnx)

**Comment by brucetus** [comment]
The discord link is in the readme. Read the whole thing pls.

**Comment by DeviaVir** [comment]
The discord server has been put lower in the README, as we got a lot of beginner questions of people who didn't read the README.

I'm also fairly certain we can use StackOverflow like this, as our ISSUE_TEMPLATE is almost the same as other project's like:
https://github.com/tensorflow/tensorflow/blob/master/ISSUE_TEMPLATE.md
