### ISSUE TITLE
New feature request - CCXT

### ISSUE THREAD

**Issue by LucasSymons** [DeviaVir/zenbot#913]
Hi, 

I was wondering if we could look at adding CCXT so i can have support for my preferred exchange and many others. 
Link: https://github.com/ccxt/ccxt

I can see in #621 they talk about ccxt and maybe adding it, but i can find no actual mention to including it. 

If for what ever reason you don't want to add ccxt, can I ask we look at adding BCT Markets so i can trade in AUD. Limited coins, only BCT, ETH, ETC, XRP but they support AUD. 

Website: https://www.btcmarkets.net
API: https://github.com/BTCMarkets/API
also requested in #571 

Thanking you in advance for your time,
zenbot user

**Comment by DeviaVir** [comment]
We are already using ccxt for some exchanges :-)

**Comment by DeviaVir** [comment]
See: https://github.com/carlos8f/zenbot/search?utf8=%E2%9C%93&q=ccxt&type=
