### ISSUE TITLE
Default Min Performance

### ISSUE THREAD

**Issue by snodnipper** [DeviaVir/zenbot#92]
The value of bitcoin has gone up quite substantially since Aug 2016, when the defaults were committed.  Just observing recent trade logs it would appear that many trades are aborted due to low performance scores.  For example:

`[trader] gdax.BTC-EUR aborting buy due to low perf. = -0.074`

Given these prices:
August 2016: $700
January 2017: $1050

and performance equation:
`rs.performance = rs.last_sell_price ? n(rs.last_sell_price).subtract(rs.market_price).divide(rs.last_sell_price).value() : null`

the results:
(700 - 711) / 711 ~= -0.015     -- so $11 difference
(1009-1025)/1025 ~= -0.015    -- so about $16 difference

Does ~ -0.01 make a more appropriate value these days in your opinion?

`rs.min_performance = -0.015 // abort trades with lower performance score`

https://github.com/carlos8f/zenbot/blob/47143fd8e46c0efd3939ec7ad8ea37a91edb5e4b/default_logic.js#L490

**Comment by Leandrosson** [comment]
Before making any proposition, it is a good idea to run a sim to support your point.

**Comment by carlos8f** [comment]
Zenbot 4 is out, so I'm cleaning up 3.x issues. Trades are no longer aborted like this. Please use and test 4, thanks!
