### ISSUE TITLE
Genetic_backtester "Bad output detected TypeError:"

### ISSUE THREAD

**Issue by kazdimenator** [DeviaVir/zenbot#922]
./scripts/genetic_backtester/darwin.js --selector="poloniex.EMC2-BTC" --days=7 --currency_capital=0.00322810 --use_strategies=neural

![neural](https://user-images.githubusercontent.com/33937361/34126304-2f0e2008-e44a-11e7-8e34-12499a117c76.JPG)

**Comment by DeviaVir** [comment]
Please use the issue template to submit your bug report.

**Comment by Primea1** [comment]
min_predict must be lower than min_period. Darwin.js gives a range from 1-100 0r 1-200 and if the value that the sim tried to use doesn't meet the above criteria you get this error. Darwin.js needs to ensure that it doesn't sim when the min_predict is higher than the min_period or it doesn't work for neural strategy.
