### ISSUE TITLE
Merry Christmas!

### ISSUE THREAD

**Issue by ghost** [DeviaVir/zenbot#927]
![GitHub Logo](https://i.imgur.com/WSBR2yX.png)
Nodejs8

1000 Poll_trades
Ubuntu 16.04
Strategy speed stock, 1s period.
0.3 markup.

./zenbot.sh sim --period=1s poloniex.BCN-BTC

Merry christmas!

**Comment by DeviaVir** [comment]
🎄

**Comment by DeviaVir** [comment]
This issue was moved to highvelocityspace/zenbot#38

**Comment by DeviaVir** [comment]
This issue was moved to highvelocityspace/zenbot#68
