### ISSUE TITLE
BTC-e trade

### ISSUE THREAD

**Issue by szempo** [DeviaVir/zenbot#93]
How to config Zenbot btc-e trading?BTC/USD, LTC/USD...

How can I watch btc-e charts Zenbot 3

**Comment by badsector666** [comment]
#offtopic
Hi, can you help me cz i cannot run zenbot in my fresh ubuntu.
It always says microtime error.

**Comment by szempo** [comment]
Ah no.
I am running CentOS 7
yum update
yum install epel-release git
yum install nodejs npm mongodb-org mongodb-server gcc gcc-c++

systemctl start mongod
systemct enabled mongod

git clone https://github.com/carlos8f/zenbot.git

cd zenbot
./update.sh
npm install

cp config_sample.js config.js

./run.sh

**Comment by patrickrb** [comment]
If you're having trouble configuring zenbot yourself, consider the docker setup instead.  The docker-compose setup works great so far.  The only issue I had to deal with was securing the mongodb

**Comment by badsector666** [comment]
Thanks.
Will try it soon. 👍

**Comment by szempo** [comment]
Yes docker-compose up -d nice work

**Comment by Patmacessex** [comment]
Zenbot install CentOS 7.5 1804

This is the installation procedure I followed for installing ZENBOT on Cent OS 7.5 1804
This version of Cent OS is a standard download from the centos project website clean install as basic webserver with no extra installations patches, or alternate software installations prior.

I decided to write this guide after trying and failing to get it work at least a dozen times and reinstalling / Cloning VM's for 2 days...
All the steps in here are from different installation guides I found all over the web.
I'm trying to keep it as simple and clear as possible as I know it can be frustrating if one of the steps doesn't work...

So here we go...

#Step 1 update cent os
yum update

#Step 2 Install nodejs
curl --silent --location https://rpm.nodesource.com/setup_8.x | sudo bash -
sudo yum -y install nodejs

#In my case this was already installed with the system but it is needed
sudo yum install gcc-c++ make

#Step 3 Install MongoDB I installed it like this after a standard MongoDB install did not work
#First we have to add a repo to cent os :

sudo nano/etc/yum.repos.d/mongodb-org-4.0.repo

#Then add this to the empty repo file
[mongodb-org-4.0]
name=MongoDB Repository
baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.0/x86_64/
gpgcheck=1
enabled=1
gpgkey=https://www.mongodb.org/static/pgp/server-4.0.asc
#Save the repo
ctrl + o
ctrl + x

#Install MongoDB
sudo yum install -y mongodb-org-4.0.2 mongodb-org-server-4.0.2 mongodb-org-shell-4.0.2 mongodb-org-mongos-4.0.2 mongodb-org-tools-4.0.2

#Start MongoDB
systemctl start mongod

#Step 4 Get Zenbot make sure you are in your home Directory
#You might have to install GIT again it was already included in my system installation
git clone https://github.com/carlos8f/zenbot.git

#Step 5 Configure Zenbot
cd zenbot
#Update for some reason says permission denied so you have to give it permissions
chmod +x update.sh
./update.sh
#For some reason the directory node_modules can give errors during installation (At least it did with my VMWare configuration so we delete it and when we install it will be reinstalled)
rm -rf node_modules

#Step 6 Install Zenbot
npm install

#Step 7 Test Zenbot
./zenbot.sh trade --paper

Thats it, this worked for me on a Dell Dimension E520 and on VMWare 10 Under MacOS with the same CentOS Distro...
