### ISSUE TITLE
Creating new strategy

### ISSUE THREAD

**Issue by ttrd06** [DeviaVir/zenbot#933]
Morning at all,

I am creating my own strategy and i need a little help please.
The only trouble i have is with the 'BUY' & 'BOUGHT' signals.
I want the bot buy when it begin to start and i have these functions to buy & sell:

`var trendUp = function(s, cancel){
        if (s.trend !== 'up') {
          s.acted_on_trend = false
        }
        s.trend = 'up'
        s.signal = !s.acted_on_trend ? 'buy' : null
        s.cancel_down = false
        if(cancel)
          s.cancel_down = true
      },
      trendDown = function(s){
        if (s.trend !== 'down') {
          s.acted_on_trend = false
        }
        s.trend = 'down'
        s.signal = !s.acted_on_trend ? 'sell' : null
      };`

So i call the 'BUY' function with `trendUp(s, true)` and the bot respond to 'buy' on the screen.
But the 'BOUGHT' signal appears 6 hours later... I don't want that & i don't understand why ...
Is there a tips to force the bot to buy if i ask this signal ? Or simply how to have the 'bought' signal ?
All helps will be amazing. I stuck at this time ... :-(
For informations, i only use SIM mode & not paper or live.
Thank's a lot

**Comment by defkev** [comment]
> But the 'BOUGHT' signal appears 6 hours later...

As a market maker you of course have to wait for a taker to [sic] "take" your order, which can take anywhere from a second to a couple of hours to ad infinitum.

If you don't want too wait trade as a market taker yourself.

Use `--order_type taker` or set `c.order_type = 'taker'` in conf.js

**!!! Be advised that this almost always incurs higher fees on any exchange !!!**

**Comment by DeviaVir** [comment]
This issue was moved to highvelocityspace/zenbot#34

**Comment by DeviaVir** [comment]
This issue was moved to highvelocityspace/zenbot#64

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
