### ISSUE TITLE
binance GET starting error

### ISSUE THREAD

**Issue by djsofiane22** [DeviaVir/zenbot#937]
Hello,

I have an issue when i want to start binance (for trading paper)
here is the error message
**An error occurred { Error: binance GET https://api.binance.com/api/v1/aggTrades?symbol=IOTABTC&startTime=1513625832410&endTime=1513669032410 request timed out (10000 ms)
    at timeout.catch.e (/mnt/c/zenbot/node_modules/ccxt/js/base/Exchange.js:266:27)
    at <anonymous> constructor: [Function: RequestTimeout] }**

For info i'm using bash on windows

thanks in advance for your help

**Comment by acamso** [comment]
same issue here.. URL loads in browser

**Comment by DeviaVir** [comment]
Please re-open your ticket using the issue template.

**Comment by shprink** [comment]
same here. opens in browser perfectly

```
$ docker-compose exec server zenbot trade
fetching pre-roll data:
api running on 172.17.0.2:20003/trades
An error occurred { Error: binance GET https://api.binance.com/api/v1/exchangeInfo request timed out (10000 ms)
    at timeout.catch.e (/app/node_modules/ccxt/js/base/Exchange.js:276:27)
    at <anonymous> constructor: [Function: RequestTimeout] }
An error occurred { Error: binance GET https://api.binance.com/api/v1/aggTrades?symbol=TRXBTC&startTime=1513716541092&endTime=1513759741092 request timed out (10000 ms)
    at timeout.catch.e (/app/node_modules/ccxt/js/base/Exchange.js:276:27)
    at <anonymous> constructor: [Function: RequestTimeout] }
```

**Comment by Abdelhamidhenni** [comment]
Same Here 
`api running on 172.17.0.3:20029/trades
Fri, 22 Dec 2017 02:26:57 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. at module.js:635:30
An error occurred { Error: binance GET https://api.binance.com/api/v1/aggTrades?symbol=XRPBTC&startTime=1513823217672&endTime=1513866417672 request timed out (10000 ms)
    at timeout.catch.e (/app/node_modules/ccxt/js/base/Exchange.js:280:27)
    at <anonymous> constructor: [Function: RequestTimeout] }
An error occurred { Error: binance GET https://api.binance.com/api/v1/aggTrades?symbol=XRPBTC&startTime=1513823217672&endTime=1513866417672 request timed out (10000 ms)
    at timeout.catch.e (/app/node_modules/ccxt/js/base/Exchange.js:280:27)
    at <anonymous> constructor: [Function: RequestTimeout] }`

**Comment by Abdelhamidhenni** [comment]
api running on 172.17.0.3:20029/trades
Fri, 22 Dec 2017 02:26:57 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. at module.js:635:30
An error occurred { Error: binance GET https://api.binance.com/api/v1/aggTrades?symbol=XRPBTC&startTime=1513823217672&endTime=1513866417672 request timed out (10000 ms)
    at timeout.catch.e (/app/node_modules/ccxt/js/base/Exchange.js:280:27)
    at <anonymous> constructor: [Function: RequestTimeout] }
An error occurred { Error: binance GET https://api.binance.com/api/v1/aggTrades?symbol=XRPBTC&startTime=1513823217672&endTime=1513866417672 request timed out (10000 ms)
    at timeout.catch.e (/app/node_modules/ccxt/js/base/Exchange.js:280:27)
    at <anonymous> constructor: [Function: RequestTimeout] }

**Comment by Abdelhamidhenni** [comment]
i think The bug is here but i don't know how to fix it  exchange.js
 var args = {};
      if (opts.from) {
        args.startTime = opts.from
      }
      if (opts.to) {
        args.endTime = opts.to
      }
      if (args.startTime && !args.endTime) {
        // add 12 hours
        args.endTime = args.startTime + 43200000
        
      }
      else if (args.endTime && !args.startTime) {
        // subtract 12 hours
        args.startTime = args.endTime - 43200000
      }

**Comment by shprink** [comment]
Please re open!

**Comment by shprink** [comment]
I fixed it just by setting a bigger timeout. The response body is huge therefore needs a lot of time to retreive and parse.

https://github.com/carlos8f/zenbot/blob/master/extensions/exchanges/binance/exchange.js#L14

changed to:

```js
new ccxt.binance({ 'apiKey': '', 'secret': '', timeout: 50000 })
```

I am not sure if there is a global way to fix the timeout with exchanges that use cctx.

Hope it helps
