### ISSUE TITLE
How to add strategy options into conf.js ?

### ISSUE THREAD

**Issue by albabosh** [DeviaVir/zenbot#943]
How to add strategy options into conf.js ?

This thing (neural strat) make zenbot crash:

c.period = 5s
c.neurons_1 = 5
c.depth = 3
c.min_periods = 100
c.min_predict = 10
c.momentum = 0
c.decay = 0
c.threads = 8
c.learns = 100

**Comment by DeviaVir** [comment]
This issue was moved to highvelocityspace/zenbot#29

**Comment by DeviaVir** [comment]
This issue was moved to highvelocityspace/zenbot#59

**Comment by wupeng1211** [comment]
???

**Comment by wupeng1211** [comment]
How to add strategy options into conf.js ?

**Comment by okonon** [comment]
@DeviaVir any suggestions here ?

**Comment by DeviaVir** [comment]
Just a guess, as I don't have time to test right now, try adding the params to`c.options`

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
