### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by albertolive** [DeviaVir/zenbot#95]
Hi,

Can I host it to heroku or digitalOcean droplet? Do I need something special? It is secure?

Thanks!

**Comment by danvctr** [comment]
You can host it on any server where you can run node and mongoDB. By
default the web server listens on all interfaces port 3113, but at most the
information you'd be leaking is all public besides the fact that you're
running a zenbot server and what trades you made. You could tweak the code
so it only listens on 127.0.0.1 if you wanted plug that leak.
