### ISSUE TITLE
price in strategy file

### ISSUE THREAD

**Issue by msalek** [DeviaVir/zenbot#958]
hello 
Just question, how to get placed or executed order price in strategy file ?
thank you

**Comment by DeviaVir** [comment]
This issue was moved to highvelocityspace/zenbot#22

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
