### ISSUE TITLE
Can't update binance products to add BCC-BTC

### ISSUE THREAD

**Issue by confact** [DeviaVir/zenbot#964]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian 9.3
- **Zenbot version**: 4.0.5
- **NodeJS version**:  8.9.3
- **Python version**: 2.7.13
- **Exact command to reproduce**: 
./extensions/exchanges/binance/update-products.sh
./zenbot.sh backfill binance.BCC-BTC

### Describe the problem
I tried to update the products for binance to add BCC/BTC that binance have added support for. It gets added to products.json but it cant start trade or sim or even backfill on the new product.

### Source code / logs
```bash
confact:~/zenbot# ./zenbot.sh backfill binance.BCC-BTC --days 1
An error occurred { Error: binance does not have market symbol BCC/BTC
    at binance.market (/root/zenbot/node_modules/ccxt/js/base/Exchange.js:557:15)
    at binance.fetchTrades (/root/zenbot/node_modules/ccxt/js/binance.js:395:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: ExchangeError] }
```

and products.json is containing:
```json
  {
    "id": "BCCBTC",
    "asset": "BCC",
    "currency": "BTC",
    "min_size": "0.00100000",
    "max_size": "100000",
    "increment": "0.000001",
    "label": "BCC/BTC"
  },
```

And list-selector command contains:
```
  binance.BCC-BNB   (BCC/BNB)
  binance.BCC-BTC   (BCC/BTC)
  binance.BCC-ETH   (BCC/ETH)
  binance.BCC-USDT   (BCC/USDT)
```

**Comment by defkev** [comment]
Looks like a "problem" with ccxt which returns BCC as BCH and vice versa, at least for Binance.

Fix is simple, use BCH instead of BCC, e.g.
> ./zenbot.sh backfill binance.BCH-BTC --days 1

**Comment by confact** [comment]
Oh, great. Thanks! Such a small thing can do so much. I wonder if it does similar to other currencies with multiple shorts.
