### ISSUE TITLE
unable to call getBalance

### ISSUE THREAD

**Issue by arnoldski** [DeviaVir/zenbot#968]
Hi, 

### Describe the problem
I'm can run almost every command but if I want to start a trade I always get this message:
"CEX.IO API is down! unable to call getBalance, retrying in 10s".

What can I do about it to start trading?

### System information
- No custom code.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.13.2
- **Zenbot version**: 4.0.5
- **NodeJS version**: v8.9.3
- **Python version**: 2.7.10
- **Exact command to reproduce**: zenbot trade

### Source code / logs
Debug message: "getBalance error: API key is not activated".
Although the API key is activated.

Thank you!

**Comment by nedievas** [comment]
Is it hard to get a new API key?

**Comment by defkev** [comment]
> API key is not activated

My crystal ball tells me you have 2FA enabled, causing the keys to never get activated.

Do this:
1. Disable 2FA on your account
2. Activate the API Key
3. Confirm the mail
4. Re-enable 2FA

I already have a ticket open with CEX support as this clearly is a bug on their end.

**Comment by arnoldski** [comment]
@nedievas, I created multiple API keys.
But indeed, @defkev was correct. After disabling the 2FA, I could actually activate the API key for real, so trading is possible now.

Thanks for the help!
