### ISSUE TITLE
ROI n/a with docker and EUR currency

### ISSUE THREAD

**Issue by albertolive** [DeviaVir/zenbot#97]
Hi,

Finally I have set up my config to work with EUR currency but, i see in the console log that roi is n/a. Is it normal?

`   m24741588       1 trades.                      RSI:n/a CLOSE:     €779,50 EUR gdax.BTC-EUR BAL:         n/a ROI:n/a`

How long it takes until first trade? I will see it in gdax website?

Thanks!

**Comment by carlos8f** [comment]
Zenbot 4 is out, so I'm cleaning up 3.x issues. Please use and test 4, thanks!
