### ISSUE TITLE
cexio getBalance error: Nonce must be incremented

### ISSUE THREAD

**Issue by msalek** [DeviaVir/zenbot#985]
### System information
- **OS Platform and Distribution **: Linux Ubuntu 16.04
- **Zenbot version**: 4.0.5
- **NodeJS version**: 8.9.3
- **Exact command to reproduce**: ./zenbot.sh trade cexio.BTC-USD --debug

### Describe the problem
unable to run zenbot  trade mode CEXIO !!!

![capture](https://user-images.githubusercontent.com/2995748/34338996-d1d23b1e-e966-11e7-8be5-260bff2f6155.PNG)

**Comment by defkev** [comment]
> Nonce must be incremented

The api-module for CEX (like most others) uses the timestamp for the Nonce field, as it logically continuously increments, unless you adjust the systems time backwards, which i suppose is what happened in your case.

Make sure your system time is correct (use ntpd) and replace your API key with a new one.

**Comment by msalek** [comment]
thank you @defkev
