### ISSUE TITLE
Backtest problem ('vsBuyHold' property is undefined

### ISSUE THREAD

**Issue by albabosh** [DeviaVir/zenbot#992]
Generation's Best Results
/home/tradeops/zenbot/scripts/genetic_backtester/phenotype.js:70
    var vsBuyHoldRate = (phenotype.sim.vsBuyHold / 50);
                                       ^

TypeError: Cannot read property 'vsBuyHold' of undefined

**Comment by shr00mie** [comment]
i wrote this zenbot install script to get around the above error:
`#!/bin/bash

sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install build-essential git mongodb -y

curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs

git clone https://github.com/carlos8f/zenbot.git

cd zenbot
cp conf-sample.js conf.js
npm install
cd scripts/genetic_backtester/
npm install nodejs geneticalgorithm
npm install
chmod +x phenotype.js`

throw in a file. chmod u+x. run.
