### ISSUE TITLE
Error: invalid bucket size spec: undefined

### ISSUE THREAD

**Issue by albabosh** [DeviaVir/zenbot#994]
./scripts/auto_backtester/backtester.js gdax.ETH-USD --days=10 --currency_capital=5  gives:

/home/tradeops/zenbot/node_modules/timebucket/lib/bucket-size.js:15
  if (!match) throw new Error('invalid bucket size spec: ' + spec);
              ^

Error: invalid bucket size spec: undefined
    at BucketSize.parse (/home/tradeops/zenbot/node_modules/timebucket/lib/bucket-size.js:15:21)

**Comment by haxwell** [comment]
Addressed in PR #996 .

**Comment by JensvdHeydt** [comment]
I was wondering why the parameter periodLength was introduced at all? Now we have period and periodLength. What's the benefit here?

**Comment by haxwell** [comment]
@JensvdHeydt See PR #926. I agree there should not be both 'period' and 'periodLength', but the thought was to remove 'period' slowly, a la deprecation. After the initial commit, it started becoming more apparent, it should probably just be cut quickly. 

But the tl;dr on "why?", is an effort to make the code easier to understand. Previously, 'period' was being used to describe two different concepts.

**Comment by JensvdHeydt** [comment]
Ah, I see! Thanks for explaining. I totally agree, it’s a little bit confusing to have two meanings for the term period. We‘d better clean this up soon.

**Comment by DeviaVir** [comment]
This issue was moved to highvelocityspace/zenbot#12

**Comment by kenorb** [comment]
Related: #938
