### ISSUE TITLE
Could simulation be done on a GPU ?

### ISSUE THREAD

**Issue by albabosh** [DeviaVir/zenbot#999]
This could be a usefull thing as one could run multiple simulations for a population at a reasonable time.

**Comment by Fredrik81** [comment]
I was running some heavy simulations for neural strat and noticed that only 1 CPU core was being used out of 8 on my zeon. Think it would be better to get it to use more cores as a first step so it can still be running on a headless server.

**Comment by JensvdHeydt** [comment]
All backtester scripts currently spawn multiple processes of the simulation so basically you already have that feature.

**Comment by Fredrik81** [comment]
When doing a backtester on neural strat there was one simulation that was running one core 100% and i could see the seconds slowly moving in time. With more cores active it could at least make it run more then 2x normal speed.

**Comment by JensvdHeydt** [comment]
You’re right and it’s also true for every other strategy. They all use one core only. That’s why the backtester usually starts multiple simulations at once. That’s what I was trying to say. Sorry if I didn’t explain it good enough.

**Comment by DeviaVir** [comment]
This issue was moved to highvelocityspace/zenbot#11

**Comment by albabosh** [comment]
It is practically impossible to run genetic backtester with parameters shown in the readme  (population=150, days=30, strategy=neural) on any cpu in a reasonable amount of time. Setting population & period to minimum makes no sence, as it gives bad results.

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
